@Security
Feature: Settings Permissions
	In order to set permissions for my server
	As a Warewolf user
	I want to setup a Server Permissions
	
@Security
Scenario Outline: Server Permissions 
        Given I have a server "localhost"
        And it has '<Group>' with '<Given rights>' 
        When connected as user part of '<User Group>'
        Then resources should have '<Rights>'
Examples:
        | No | Group  | Given rights                                      | User Group | Resources | Rights                                            |
        | 1  | Public | Deploy To                                         | Users      | All       | Deploy To                                         |
        | 2  | Public | Deploy From                                       | Users      | All       | Deploy From                                       |
        | 3  | Public | View                                              | Users      | All       | View                                              |
        | 4  | Public | Execute                                           | Users      | All       | Execute                                           |
        | 5  | Public | Contribute, View, Execute                         | Users      | All       | Contribute, View, Execute                         |
        | 6  | Public | Deploy To, Deploy From                            | Users      | All       | Deploy To, Deploy From                            |
        | 7  | Public | View, Execute                                     | Users      | All       | View, Execute                                     |
        | 8  | Public | View, Execute, Contribute, Deploy To, Deploy From | Users      | All       | View, Execute, Contribute, Deploy To, Deploy From |
        | 9  | Public | Deploy To, View                                   | Users      | All       | Deploy To, View                                   |
        | 10 | Public | Deploy To, Execute                                | Users      | All       | Deploy To, Execute                                |
        | 11 | Public | Deploy To, Contribute, View, Execute              | Users      | All       | Deploy To, Contribute, View, Execute              |
        | 12 | Public | Deploy From, View                                 | Users      | All       | Deploy From, View                                 |
        | 13 | Public | Deploy From, Execute                              | Users      | All       | Deploy From, Execute                              |
        | 14 | Public | Deploy From, Contribute, View, Execute            | Users      | All       | Deploy From, Contribute, View, Execute            |
        | 15 | Public | Deploy To, Deploy From, View                      | Users      | All       | Deploy To, Deploy From, View                      |
        | 16 | Public | Deploy To, Deploy From, Execute                   | Users      | All       | Deploy To, Deploy From, Execute                   |

@Security
Scenario Outline: Setting Selected Resource Permissions for users 
        Given I have a server "localhost"
        And it has '<Group>' with '<Given rights>' 
        And Resource '<Resource Name>' has rights '<Resource Rights>' for '<User Group>'
        When connected as user part of '<User Group>'
        Then '<Resource>' should have '<Permissions>'
		And resources should not have '<Rights>' 
Examples: 
        | No | Group                   | Given rights              | Resource Name                               | Resource Rights           | User Group | Resources | Rights | Resource                                    | Permissions               |
        | 1  | Warewolf Administrators | View                      | Integration Test Resources\DECISION TESTING | View                      | Users      | All       | None   | Integration Test Resources\DECISION TESTING | View                      |
        | 2  | Warewolf Administrators | Execute                   | Integration Test Resources\DECISION TESTING | View                      | Users      | All       | None   | Integration Test Resources\DECISION TESTING | View                      |
        | 3  | Warewolf Administrators | Contribute, View, Execute | Integration Test Resources\DECISION TESTING | View                      | Users      | All       | None   | Integration Test Resources\DECISION TESTING | View                      |
        | 4  | Warewolf Administrators | View, Execute             | Integration Test Resources\DECISION TESTING | View                      | Users      | All       | None   | Integration Test Resources\DECISION TESTING | View                      |
        | 5  | Warewolf Administrators | View                      | Integration Test Resources\DECISION TESTING | Execute                   | Users      | All       | None   | Integration Test Resources\DECISION TESTING | Execute                   |
        | 6  | Warewolf Administrators | Execute                   | Integration Test Resources\DECISION TESTING | Execute                   | Users      | All       | None   | Integration Test Resources\DECISION TESTING | Execute                   |
        | 7  | Warewolf Administrators | Contribute, View, Execute | Integration Test Resources\DECISION TESTING | Execute                   | Users      | All       | None   | Integration Test Resources\DECISION TESTING | Execute                   |
        | 7  | Warewolf Administrators | View, Execute             | Integration Test Resources\DECISION TESTING | Execute                   | Users      | All       | None   | Integration Test Resources\DECISION TESTING | Execute                   |
        | 8  | Warewolf Administrators | View                      | Integration Test Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | None   | Integration Test Resources\DECISION TESTING | Contribute, View, Execute |
        | 9  | Warewolf Administrators | Execute                   | Integration Test Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | None   | Integration Test Resources\DECISION TESTING | Contribute, View, Execute |
        | 10 | Warewolf Administrators | Contribute, View, Execute | Integration Test Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | None   | Integration Test Resources\DECISION TESTING | Contribute, View, Execute |
        | 11 | Warewolf Administrators | View, Execute             | Integration Test Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | None   | Integration Test Resources\DECISION TESTING | Contribute, View, Execute |
        | 12 | Warewolf Administrators | View                      | Integration Test Resources\DECISION TESTING | View, Execute             | Users      | All       | None   | Integration Test Resources\DECISION TESTING | View, Execute             |
        | 13 | Warewolf Administrators | Execute                   | Integration Test Resources\DECISION TESTING | View, Execute             | Users      | All       | None   | Integration Test Resources\DECISION TESTING | View, Execute             |
        | 14 | Warewolf Administrators | Contribute, View, Execute | Integration Test Resources\DECISION TESTING | View, Execute             | Users      | All       | None   | Integration Test Resources\DECISION TESTING | View, Execute             |
        | 15 | Warewolf Administrators | View, Execute             | Integration Test Resources\DECISION TESTING | View, Execute             | Users      | All       | None   | Integration Test Resources\DECISION TESTING | View, Execute             |

#@Security
Scenario Outline: Setting Selected Resource Permissions for users overlapping groups
        Given I have a server "localhost"
        And it has '<Group>' with '<Given rights>' 
        And Resource '<Resource Name>' has rights '<Resource Rights>' for '<User Group>'
        When connected as user part of '<User Group>'
        Then '<Resource>' should have '<Permissions>'
		And resources should have '<Rights>' 
Examples: 
        | No | Group  | Given rights                                                     | Resource Name                               | Resource Rights           | User Group | Resources | Rights                                                           | Resource                                    | Permissions               |
        | 1  | Public | View                                                             | Integration Test Resources\DECISION TESTING | View                      | Users      | All       | View                                                             | Integration Test Resources\DECISION TESTING | View                      |
        | 2  | Public | Execute                                                          | Integration Test Resources\DECISION TESTING | View                      | Users      | All       | Execute                                                          | Integration Test Resources\DECISION TESTING | View                      |
        | 3  | Public | Contribute, View, Execute                                        | Integration Test Resources\DECISION TESTING | View                      | Users      | All       | Contribute, View, Execute                                        | Integration Test Resources\DECISION TESTING | View                      |
        | 4  | Public | View, Execute                                                    | Integration Test Resources\DECISION TESTING | View                      | Users      | All       | View, Execute                                                    | Integration Test Resources\DECISION TESTING | View                      |
        | 5  | Public | View, Execute, Contribute, Deploy To, Deploy From, Administrator | Integration Test Resources\DECISION TESTING | View                      | Users      | All       | View, Execute, Contribute, Deploy To, Deploy From, Administrator | Integration Test Resources\DECISION TESTING | View                      |
        | 6  | Public | View                                                             | Integration Test Resources\DECISION TESTING | Execute                   | Users      | All       | View                                                             | Integration Test Resources\DECISION TESTING | Execute                   |
        | 7  | Public | Execute                                                          | Integration Test Resources\DECISION TESTING | Execute                   | Users      | All       | Execute                                                          | Integration Test Resources\DECISION TESTING | Execute                   |
        | 8  | Public | Contribute, View, Execute                                        | Integration Test Resources\DECISION TESTING | Execute                   | Users      | All       | Contribute, View, Execute                                        | Integration Test Resources\DECISION TESTING | Execute                   |
        | 9  | Public | View, Execute                                                    | Integration Test Resources\DECISION TESTING | Execute                   | Users      | All       | View, Execute                                                    | Integration Test Resources\DECISION TESTING | Execute                   |
        | 10 | Public | View, Execute, Contribute, Deploy To, Deploy From, Administrator | Integration Test Resources\DECISION TESTING | Execute                   | Users      | All       | View, Execute, Contribute, Deploy To, Deploy From, Administrator | Integration Test Resources\DECISION TESTING | Execute                   |
        | 11 | Public | View                                                             | Integration Test Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | View                                                             | Integration Test Resources\DECISION TESTING | Contribute, View, Execute |
        | 12 | Public | Execute                                                          | Integration Test Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Execute                                                          | Integration Test Resources\DECISION TESTING | Contribute, View, Execute |
        | 13 | Public | Contribute, View, Execute                                        | Integration Test Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Contribute, View, Execute                                        | Integration Test Resources\DECISION TESTING | Contribute, View, Execute |
        | 14 | Public | View, Execute                                                    | Integration Test Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | View, Execute                                                    | Integration Test Resources\DECISION TESTING | Contribute, View, Execute |
        | 15 | Public | View, Execute, Contribute, Deploy To, Deploy From                | Integration Test Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | View, Execute, Contribute, Deploy To, Deploy From                | Integration Test Resources\DECISION TESTING | Contribute, View, Execute |
        | 16 | Public | View                                                             | Integration Test Resources\DECISION TESTING | View, Execute             | Users      | All       | View                                                             | Integration Test Resources\DECISION TESTING | View, Execute             |
        | 17 | Public | Execute                                                          | Integration Test Resources\DECISION TESTING | View, Execute             | Users      | All       | Execute                                                          | Integration Test Resources\DECISION TESTING | View, Execute             |
        | 18 | Public | Contribute, View, Execute                                        | Integration Test Resources\DECISION TESTING | View, Execute             | Users      | All       | Contribute, View, Execute                                        | Integration Test Resources\DECISION TESTING | View, Execute             |
        | 19 | Public | View, Execute                                                    | Integration Test Resources\DECISION TESTING | View, Execute             | Users      | All       | View, Execute                                                    | Integration Test Resources\DECISION TESTING | View, Execute             |
        | 20 | Public | View, Execute, Contribute, Deploy To, Deploy From                | Integration Test Resources\DECISION TESTING | View, Execute             | Users      | All       | View, Execute, Contribute, Deploy To, Deploy From                | Integration Test Resources\DECISION TESTING | View, Execute             |
        | 21 | Public | View                                                             | Integration Test Resources\DECISION TESTING | None                      | Users      | All       | View                                                             | Integration Test Resources\DECISION TESTING | None                      |
        | 22 | Public | Execute                                                          | Integration Test Resources\DECISION TESTING | None                      | Users      | All       | Execute                                                          | Integration Test Resources\DECISION TESTING | None                      |
        | 23 | Public | Contribute, View, Execute                                        | Integration Test Resources\DECISION TESTING | None                      | Users      | All       | Contribute, View, Execute                                        | Integration Test Resources\DECISION TESTING | None                      |
        | 24 | Public | View, Execute                                                    | Integration Test Resources\DECISION TESTING | None                      | Users      | All       | View, Execute                                                    | Integration Test Resources\DECISION TESTING | None                      |
        | 25 | Public | View, Execute, Contribute, Deploy To, Deploy From, Administrator | Integration Test Resources\DECISION TESTING | None                      | Users      | All       | View, Execute, Contribute, Deploy To, Deploy From, Administrator | Integration Test Resources\DECISION TESTING | None                      |
        | 26 | Public | None                                                             | Integration Test Resources\DECISION TESTING | Contribute, View, Execute | Users      | Users     | None                                                             | Integration Test Resources\DECISION TESTING | Contribute, View, Execute |

#@Security		
#Scenario Outline: Setting Selected Resource Permissions for users conflicting permissions
#        Given I have a server "localhost"
#        And it has '<Group>' with '<Given rights>' 
#        And Resource '<Resource Name>' has rights '<Resource Rights>' for '<User Group>'
#        When connected as user part of '<User Group>'
#        Then '<Resource>' should have '<Permissions>'
#		And resources should have '<Rights>' 
#Examples: 
#        | No | Group | Given rights                                                     | Resource Name                               | Resource Rights           | User Group | Resources | Rights                                                           | Resource                                    | Permissions               |
#        | 1  | Users | Deploy To                                                        | Integration Test Resources\DECISION TESTING | View                      | Users      | All       | Deploy To                                                        | Integration Test Resources\DECISION TESTING | View                      |
#        | 2  | Users | Deploy From                                                      | Integration Test Resources\DECISION TESTING | View                      | Users      | All       | Deploy From                                                      | Integration Test Resources\DECISION TESTING | View                      |
#        | 3  | Users | View                                                             | Integration Test Resources\DECISION TESTING | View                      | Users      | All       | View                                                             | Integration Test Resources\DECISION TESTING | View                      |
#        | 4  | Users | Execute                                                          | Integration Test Resources\DECISION TESTING | View                      | Users      | All       | Execute                                                          | Integration Test Resources\DECISION TESTING | View                      |
#        | 5  | Users | Contribute, View, Execute                                        | Integration Test Resources\DECISION TESTING | View                      | Users      | All       | Contribute, View, Execute                                        | Integration Test Resources\DECISION TESTING | View                      |
#        | 6  | Users | Deploy To, Deploy From                                           | Integration Test Resources\DECISION TESTING | View                      | Users      | All       | Deploy To, Deploy From                                           | Integration Test Resources\DECISION TESTING | View                      |
#        | 7  | Users | View, Execute                                                    | Integration Test Resources\DECISION TESTING | View                      | Users      | All       | View, Execute                                                    | Integration Test Resources\DECISION TESTING | View                      |
#        | 8  | Users | View, Execute, Contribute, Deploy To, Deploy From, Administrator | Integration Test Resources\DECISION TESTING | View                      | Users      | All       | View, Execute, Contribute, Deploy To, Deploy From, Administrator | Integration Test Resources\DECISION TESTING | View                      |
#        | 9  | Users | Deploy To, View                                                  | Integration Test Resources\DECISION TESTING | View                      | Users      | All       | Deploy To, View                                                  | Integration Test Resources\DECISION TESTING | View                      |
#        | 10 | Users | Deploy To, Execute                                               | Integration Test Resources\DECISION TESTING | View                      | Users      | All       | Deploy To, Execute                                               | Integration Test Resources\DECISION TESTING | View                      |
#        | 11 | Users | Deploy To, Contribute, View, Execute                             | Integration Test Resources\DECISION TESTING | View                      | Users      | All       | Deploy To, Contribute, View, Execute                             | Integration Test Resources\DECISION TESTING | View                      |
#        | 12 | Users | Deploy From, View                                                | Integration Test Resources\DECISION TESTING | View                      | Users      | All       | Deploy From, View                                                | Integration Test Resources\DECISION TESTING | View                      |
#        | 13 | Users | Deploy From, Execute                                             | Integration Test Resources\DECISION TESTING | View                      | Users      | All       | Deploy From, Execute                                             | Integration Test Resources\DECISION TESTING | View                      |
#        | 14 | Users | Deploy From, Contribute, View, Execute                           | Integration Test Resources\DECISION TESTING | View                      | Users      | All       | Deploy From, Contribute, View, Execute                           | Integration Test Resources\DECISION TESTING | View                      |
#        | 15 | Users | Deploy To, Deploy From, View                                     | Integration Test Resources\DECISION TESTING | View                      | Users      | All       | Deploy To, Deploy From , View                                    | Integration Test Resources\DECISION TESTING | View                      |
#        | 16 | Users | Deploy To, Deploy From, Execute                                  | Integration Test Resources\DECISION TESTING | View                      | Users      | All       | Deploy To, Deploy From , Execute                                 | Integration Test Resources\DECISION TESTING | View                      |
#        | 17 | Users | Deploy To, Deploy From, Contribute, View, Execute                | Integration Test Resources\DECISION TESTING | View                      | Users      | All       | Deploy To, Deploy From , Contribute, View, Execute               | Integration Test Resources\DECISION TESTING | View                      |
#        | 18 | Users | Deploy To                                                        | Integration Test Resources\DECISION TESTING | Execute                   | Users      | All       | Deploy To                                                        | Integration Test Resources\DECISION TESTING | Execute                   |
#        | 19 | Users | Deploy From                                                      | Integration Test Resources\DECISION TESTING | Execute                   | Users      | All       | Deploy From                                                      | Integration Test Resources\DECISION TESTING | Execute                   |
#        | 20 | Users | View                                                             | Integration Test Resources\DECISION TESTING | Execute                   | Users      | All       | View                                                             | Integration Test Resources\DECISION TESTING | Execute                   |
#        | 21 | Users | Execute                                                          | Integration Test Resources\DECISION TESTING | Execute                   | Users      | All       | Execute                                                          | Integration Test Resources\DECISION TESTING | Execute                   |
#        | 22 | Users | Contribute, View, Execute                                        | Integration Test Resources\DECISION TESTING | Execute                   | Users      | All       | Contribute, View, Execute                                        | Integration Test Resources\DECISION TESTING | Execute                   |
#        | 23 | Users | Deploy To, Deploy From                                           | Integration Test Resources\DECISION TESTING | Execute                   | Users      | All       | Deploy To, Deploy From                                           | Integration Test Resources\DECISION TESTING | Execute                   |
#        | 24 | Users | View, Execute                                                    | Integration Test Resources\DECISION TESTING | Execute                   | Users      | All       | View, Execute                                                    | Integration Test Resources\DECISION TESTING | Execute                   |
#        | 25 | Users | View, Execute, Contribute, Deploy To, Deploy From, Administrator | Integration Test Resources\DECISION TESTING | Execute                   | Users      | All       | View, Execute, Contribute, Deploy To, Deploy From, Administrator | Integration Test Resources\DECISION TESTING | Execute                   |
#        | 26 | Users | Deploy To, View                                                  | Integration Test Resources\DECISION TESTING | Execute                   | Users      | All       | Deploy To, View                                                  | Integration Test Resources\DECISION TESTING | Execute                   |
#        | 27 | Users | Deploy To, Execute                                               | Integration Test Resources\DECISION TESTING | Execute                   | Users      | All       | Deploy To, Execute                                               | Integration Test Resources\DECISION TESTING | Execute                   |
#        | 28 | Users | Deploy To, Contribute, View, Execute                             | Integration Test Resources\DECISION TESTING | Execute                   | Users      | All       | Deploy To, Contribute, View, Execute                             | Integration Test Resources\DECISION TESTING | Execute                   |
#        | 29 | Users | Deploy From, View                                                | Integration Test Resources\DECISION TESTING | Execute                   | Users      | All       | Deploy From, View                                                | Integration Test Resources\DECISION TESTING | Execute                   |
#        | 30 | Users | Deploy From, Execute                                             | Integration Test Resources\DECISION TESTING | Execute                   | Users      | All       | Deploy From, Execute                                             | Integration Test Resources\DECISION TESTING | Execute                   |
#        | 31 | Users | Deploy From, Contribute, View, Execute                           | Integration Test Resources\DECISION TESTING | Execute                   | Users      | All       | Deploy From, Contribute, View, Execute                           | Integration Test Resources\DECISION TESTING | Execute                   |
#        | 32 | Users | Deploy To, Deploy From, View                                     | Integration Test Resources\DECISION TESTING | Execute                   | Users      | All       | Deploy To, Deploy From, View                                     | Integration Test Resources\DECISION TESTING | Execute                   |
#        | 33 | Users | Deploy To, Deploy From, Execute                                  | Integration Test Resources\DECISION TESTING | Execute                   | Users      | All       | Deploy To, Deploy From, Execute                                  | Integration Test Resources\DECISION TESTING | Execute                   |
#        | 34 | Users | Deploy To, Deploy From, Contribute, View, Execute                | Integration Test Resources\DECISION TESTING | Execute                   | Users      | All       | Deploy To, Deploy From, Contribute, View, Execute                | Integration Test Resources\DECISION TESTING | Execute                   |
#        | 35 | Users | Deploy To                                                        | Integration Test Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Deploy To                                                        | Integration Test Resources\DECISION TESTING | Contribute, View, Execute |
#        | 36 | Users | Deploy From                                                      | Integration Test Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Deploy From                                                      | Integration Test Resources\DECISION TESTING | Contribute, View, Execute |
#        | 37 | Users | View                                                             | Integration Test Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | View                                                             | Integration Test Resources\DECISION TESTING | Contribute, View, Execute |
#        | 38 | Users | Execute                                                          | Integration Test Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Execute                                                          | Integration Test Resources\DECISION TESTING | Contribute, View, Execute |
#        | 39 | Users | Contribute, View, Execute                                        | Integration Test Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Contribute, View, Execute                                        | Integration Test Resources\DECISION TESTING | Contribute, View, Execute |
#        | 40 | Users | Deploy To, Deploy From                                           | Integration Test Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Deploy To, Deploy From                                           | Integration Test Resources\DECISION TESTING | Contribute, View, Execute |
#        | 41 | Users | View, Execute                                                    | Integration Test Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | View, Execute                                                    | Integration Test Resources\DECISION TESTING | Contribute, View, Execute |
#        | 42 | Users | View, Execute, Contribute, Deploy To, Deploy From                | Integration Test Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | View, Execute, Contribute, Deploy To, Deploy From                | Integration Test Resources\DECISION TESTING | Contribute, View, Execute |
#        | 43 | Users | Deploy To, View                                                  | Integration Test Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Deploy To, View                                                  | Integration Test Resources\DECISION TESTING | Contribute, View, Execute |
#        | 44 | Users | Deploy To, Execute                                               | Integration Test Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Deploy To, Execute                                               | Integration Test Resources\DECISION TESTING | Contribute, View, Execute |
#        | 45 | Users | Deploy To, Contribute, View, Execute                             | Integration Test Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Deploy To, Contribute, View, Execute                             | Integration Test Resources\DECISION TESTING | Contribute, View, Execute |
#        | 46 | Users | Deploy From, View                                                | Integration Test Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Deploy From, View                                                | Integration Test Resources\DECISION TESTING | Contribute, View, Execute |
#        | 47 | Users | Deploy From, Execute                                             | Integration Test Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Deploy From, Execute                                             | Integration Test Resources\DECISION TESTING | Contribute, View, Execute |
#        | 48 | Users | Deploy From, Contribute, View, Execute                           | Integration Test Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Deploy From, Contribute, View, Execute                           | Integration Test Resources\DECISION TESTING | Contribute, View, Execute |
#        | 49 | Users | Deploy To, Deploy From, View                                     | Integration Test Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Deploy To, Deploy From, View                                     | Integration Test Resources\DECISION TESTING | Contribute, View, Execute |
#        | 50 | Users | Deploy To, Deploy From, Execute                                  | Integration Test Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Deploy To, Deploy From, Execute                                  | Integration Test Resources\DECISION TESTING | Contribute, View, Execute |
#        | 51 | Users | Deploy To, Deploy From, Contribute, View, Execute, Administrator | Integration Test Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Deploy To, Deploy From, Contribute, View, Execute, Administrator | Integration Test Resources\DECISION TESTING | Contribute, View, Execute |
#        | 52 | Users | Deploy To                                                        | Integration Test Resources\DECISION TESTING | View, Execute             | Users      | All       | Deploy To                                                        | Integration Test Resources\DECISION TESTING | View, Execute             |
#        | 53 | Users | Deploy From                                                      | Integration Test Resources\DECISION TESTING | View, Execute             | Users      | All       | Deploy From                                                      | Integration Test Resources\DECISION TESTING | View, Execute             |
#        | 54 | Users | View                                                             | Integration Test Resources\DECISION TESTING | View, Execute             | Users      | All       | View                                                             | Integration Test Resources\DECISION TESTING | View, Execute             |
#        | 55 | Users | Execute                                                          | Integration Test Resources\DECISION TESTING | View, Execute             | Users      | All       | Execute                                                          | Integration Test Resources\DECISION TESTING | View, Execute             |
#        | 56 | Users | Contribute, View, Execute                                        | Integration Test Resources\DECISION TESTING | View, Execute             | Users      | All       | Contribute, View, Execute                                        | Integration Test Resources\DECISION TESTING | View, Execute             |
#        | 57 | Users | Deploy To, Deploy From                                           | Integration Test Resources\DECISION TESTING | View, Execute             | Users      | All       | Deploy To, Deploy From                                           | Integration Test Resources\DECISION TESTING | View, Execute             |
#        | 58 | Users | View, Execute                                                    | Integration Test Resources\DECISION TESTING | View, Execute             | Users      | All       | View, Execute                                                    | Integration Test Resources\DECISION TESTING | View, Execute             |
#        | 59 | Users | View, Execute, Contribute, Deploy To, Deploy From                | Integration Test Resources\DECISION TESTING | View, Execute             | Users      | All       | View, Execute, Contribute, Deploy To, Deploy From                | Integration Test Resources\DECISION TESTING | View, Execute             |
#        | 60 | Users | Deploy To, View                                                  | Integration Test Resources\DECISION TESTING | View, Execute             | Users      | All       | Deploy To, View                                                  | Integration Test Resources\DECISION TESTING | View, Execute             |
#        | 61 | Users | Deploy To, Execute                                               | Integration Test Resources\DECISION TESTING | View, Execute             | Users      | All       | Deploy To, Execute                                               | Integration Test Resources\DECISION TESTING | View, Execute             |
#        | 62 | Users | Deploy To, Contribute, View, Execute                             | Integration Test Resources\DECISION TESTING | View, Execute             | Users      | All       | Deploy To, Contribute, View, Execute                             | Integration Test Resources\DECISION TESTING | View, Execute             |
#        | 63 | Users | Deploy From, View                                                | Integration Test Resources\DECISION TESTING | View, Execute             | Users      | All       | Deploy From, View                                                | Integration Test Resources\DECISION TESTING | View, Execute             |
#        | 64 | Users | Deploy From, Execute                                             | Integration Test Resources\DECISION TESTING | View, Execute             | Users      | All       | Deploy From, Execute                                             | Integration Test Resources\DECISION TESTING | View, Execute             |
#        | 65 | Users | Deploy From, Contribute, View, Execute                           | Integration Test Resources\DECISION TESTING | View, Execute             | Users      | All       | Deploy From, Contribute, View, Execute                           | Integration Test Resources\DECISION TESTING | View, Execute             |
#        | 66 | Users | Deploy To, Deploy From, View                                     | Integration Test Resources\DECISION TESTING | View, Execute             | Users      | All       | Deploy To, Deploy From, View                                     | Integration Test Resources\DECISION TESTING | View, Execute             |
#        | 67 | Users | Deploy To, Deploy From, Execute                                  | Integration Test Resources\DECISION TESTING | View, Execute             | Users      | All       | Deploy To, Deploy From, Execute                                  | Integration Test Resources\DECISION TESTING | View, Execute             |
#        | 68 | Users | Deploy To, Deploy From, Contribute, View, Execute, Administrator | Integration Test Resources\DECISION TESTING | View, Execute             | Users      | All       | Deploy To, Deploy From, Contribute, View, Execute, Administrator | Integration Test Resources\DECISION TESTING | View, Execute             |
#        | 69 | Users | Deploy To                                                        | Integration Test Resources\DECISION TESTING | None                      | Users      | All       | Deploy To                                                        | Integration Test Resources\DECISION TESTING | None                      |
#        | 70 | Users | Deploy From                                                      | Integration Test Resources\DECISION TESTING | None                      | Users      | All       | Deploy From                                                      | Integration Test Resources\DECISION TESTING | None                      |
#        | 71 | Users | View                                                             | Integration Test Resources\DECISION TESTING | None                      | Users      | All       | View                                                             | Integration Test Resources\DECISION TESTING | None                      |
#        | 72 | Users | Execute                                                          | Integration Test Resources\DECISION TESTING | None                      | Users      | All       | Execute                                                          | Integration Test Resources\DECISION TESTING | None                      |
#        | 73 | Users | Contribute, View, Execute                                        | Integration Test Resources\DECISION TESTING | None                      | Users      | All       | Contribute, View, Execute                                        | Integration Test Resources\DECISION TESTING | None                      |
#        | 74 | Users | Deploy To, Deploy From                                           | Integration Test Resources\DECISION TESTING | None                      | Users      | All       | Deploy To, Deploy From                                           | Integration Test Resources\DECISION TESTING | None                      |
#        | 75 | Users | View, Execute                                                    | Integration Test Resources\DECISION TESTING | None                      | Users      | All       | View, Execute                                                    | Integration Test Resources\DECISION TESTING | None                      |
#        | 76 | Users | View, Execute, Contribute, Deploy To, Deploy From, Administrator | Integration Test Resources\DECISION TESTING | None                      | Users      | All       | View, Execute, Contribute, Deploy To, Deploy From, Administrator | Integration Test Resources\DECISION TESTING | None                      |
#        | 77 | Users | Deploy To, View                                                  | Integration Test Resources\DECISION TESTING | None                      | Users      | All       | Deploy To, View                                                  | Integration Test Resources\DECISION TESTING | None                      |
#        | 78 | Users | Deploy To, Execute                                               | Integration Test Resources\DECISION TESTING | None                      | Users      | All       | Deploy To, Execute                                               | Integration Test Resources\DECISION TESTING | None                      |
#        | 79 | Users | Deploy To, Contribute, View, Execute                             | Integration Test Resources\DECISION TESTING | None                      | Users      | All       | Deploy To, Contribute, View, Execute                             | Integration Test Resources\DECISION TESTING | None                      |
#        | 80 | Users | Deploy From, View                                                | Integration Test Resources\DECISION TESTING | None                      | Users      | All       | Deploy From, View                                                | Integration Test Resources\DECISION TESTING | None                      |
#        | 81 | Users | Deploy From, Execute                                             | Integration Test Resources\DECISION TESTING | None                      | Users      | All       | Deploy From, Execute                                             | Integration Test Resources\DECISION TESTING | None                      |
#        | 82 | Users | Deploy From, Contribute, View, Execute                           | Integration Test Resources\DECISION TESTING | None                      | Users      | All       | Deploy From, Contribute, View, Execute                           | Integration Test Resources\DECISION TESTING | None                      |
#        | 83 | Users | Deploy To, Deploy From, View                                     | Integration Test Resources\DECISION TESTING | None                      | Users      | All       | Deploy To, Deploy From, View                                     | Integration Test Resources\DECISION TESTING | None                      |
#        | 84 | Users | Deploy To, Deploy From, Execute                                  | Integration Test Resources\DECISION TESTING | None                      | Users      | All       | Deploy To, Deploy From, Execute                                  | Integration Test Resources\DECISION TESTING | None                      |
#        | 85 | Users | Deploy To, Deploy From, Contribute, View, Execute, Administrator | Integration Test Resources\DECISION TESTING | None                      | Users      | All       | Deploy To, Deploy From, Contribute, View, Execute, Administrator | Integration Test Resources\DECISION TESTING | None                      |