Feature: Settings Permissions
	In order to set permissions for my server
	As a Warewolf user
	I want to setup a Server Permissions
	
Scenario Outline: Server Permissions 
        Given I have a server "localhost"
        And it has '<Group>' with '<Given rights>' 
        When connected as user part of '<User Group>'
        Then '<Resources>' resources are visible
        And resources should have '<Rights>'
Examples:
        | No | Group  | Given rights                                      | User Group | Resources | Rights                                            |
        | 1  | Public | Deploy To                                         | Users      | All       | Deploy To                                         |
        | 2  | Public | Deploy From                                       | Users      | All       | Deploy From                                       |
        | 3  | Public | View                                              | Users      | All       | View                                              |
        | 4  | Public | Execute                                           | Users      | All       | Execute                                           |
        | 5  | Public | Contribute, View, Execute                         | Users      | All       | Contribute, View, Execute                         |
        | 6  | Public | Deploy To, Deploy From                            | Users      | All       | Deploy To, Deploy From                            |
        | 7  | Public | View, Execute                                     | Users      | All       | View, Execute                                     |
        | 8  | Public | View, Execute, Contribute, Deploy To, Deploy From | Users      | All       | View, Execute, Contribute, Deploy To, Deploy From |
        | 9  | Public | Deploy To, View                                   | Users      | All       | Deploy To, View                                   |
        | 10 | Public | Deploy To, Execute                                | Users      | All       | Deploy To, Execute                                |
        | 11 | Public | Deploy To, Contribute, View, Execute              | Users      | All       | Deploy To, Contribute, View, Execute              |
        | 12 | Public | Deploy From, View                                 | Users      | All       | Deploy From, View                                 |
        | 13 | Public | Deploy From, Execute                              | Users      | All       | Deploy From, Execute                              |
        | 14 | Public | Deploy From, Contribute, View, Execute            | Users      | All       | Deploy From, Contribute, View, Execute            |
        | 15 | Public | Deploy To, Deploy From, View                      | Users      | All       | Deploy To, Deploy From, View                      |
        | 16 | Public | Deploy To, Deploy From, Execute                   | Users      | All       | Deploy To, Deploy From, Execute                   |

Scenario Outline: Setting Selected Resource Permissions for users 
        Given I have a server "localhost"
        And it has '<Group>' with '<Given rights>' 
        And Resource '<Resource Name>' has rights '<Resource Rights>' for '<User Group>'
        When connected as user part of '<User Group>'
        Then '<Resources>' resources are visible
        And '<Resource>' should have '<Permissions>'
		And resources should not have '<Rights>' 
Examples: 
        | No | Group          | Given rights              | Resource Name           | Resource Rights           | User Group | Resources | Rights | Resource                | Permissions               |
        | 1  | Administrators | View                      | BARNEY\DECISION TESTING | View                      | Users      | All       | None   | BARNEY\DECISION TESTING | View                      |
        | 2  | Administrators | Execute                   | BARNEY\DECISION TESTING | View                      | Users      | All       | None   | BARNEY\DECISION TESTING | View                      |
        | 3  | Administrators | Contribute, View, Execute | BARNEY\DECISION TESTING | View                      | Users      | All       | None   | BARNEY\DECISION TESTING | View                      |
        | 4  | Administrators | View, Execute             | BARNEY\DECISION TESTING | View                      | Users      | All       | None   | BARNEY\DECISION TESTING | View                      |
        | 5  | Administrators | View                      | BARNEY\DECISION TESTING | Execute                   | Users      | All       | None   | BARNEY\DECISION TESTING | Execute                   |
        | 6  | Administrators | Execute                   | BARNEY\DECISION TESTING | Execute                   | Users      | All       | None   | BARNEY\DECISION TESTING | Execute                   |
        | 7  | Administrators | Contribute, View, Execute | BARNEY\DECISION TESTING | Execute                   | Users      | All       | None   | BARNEY\DECISION TESTING | Execute                   |
        | 7  | Administrators | View, Execute             | BARNEY\DECISION TESTING | Execute                   | Users      | All       | None   | BARNEY\DECISION TESTING | Execute                   |
        | 8  | Administrators | View                      | BARNEY\DECISION TESTING | Contribute, View, Execute | Users      | All       | None   | BARNEY\DECISION TESTING | Contribute, View, Execute |
        | 9  | Administrators | Execute                   | BARNEY\DECISION TESTING | Contribute, View, Execute | Users      | All       | None   | BARNEY\DECISION TESTING | Contribute, View, Execute |
        | 10 | Administrators | Contribute, View, Execute | BARNEY\DECISION TESTING | Contribute, View, Execute | Users      | All       | None   | BARNEY\DECISION TESTING | Contribute, View, Execute |
        | 11 | Administrators | View, Execute             | BARNEY\DECISION TESTING | Contribute, View, Execute | Users      | All       | None   | BARNEY\DECISION TESTING | Contribute, View, Execute |
        | 12 | Administrators | View                      | BARNEY\DECISION TESTING | View, Execute             | Users      | All       | None   | BARNEY\DECISION TESTING | View, Execute             |
        | 13 | Administrators | Execute                   | BARNEY\DECISION TESTING | View, Execute             | Users      | All       | None   | BARNEY\DECISION TESTING | View, Execute             |
        | 14 | Administrators | Contribute, View, Execute | BARNEY\DECISION TESTING | View, Execute             | Users      | All       | None   | BARNEY\DECISION TESTING | View, Execute             |
        | 15 | Administrators | View, Execute             | BARNEY\DECISION TESTING | View, Execute             | Users      | All       | None   | BARNEY\DECISION TESTING | View, Execute             |
        | 16 | Administrators | View                      | BARNEY\DECISION TESTING | None                      | Users      | All       | None   | BARNEY\DECISION TESTING | None                      |
        | 17 | Administrators | Execute                   | BARNEY\DECISION TESTING | None                      | Users      | All       | None   | BARNEY\DECISION TESTING | None                      |
        | 18 | Administrators | Contribute, View, Execute | BARNEY\DECISION TESTING | None                      | Users      | All       | None   | BARNEY\DECISION TESTING | None                      |
        | 19 | Administrators | View, Execute             | BARNEY\DECISION TESTING | None                      | Users      | All       | None   | BARNEY\DECISION TESTING | None                      |

Scenario Outline: Setting Selected Resource Permissions for users overlapping groups
        Given I have a server "localhost"
        And it has '<Group>' with '<Given rights>' 
        And Resource '<Resource Name>' has rights '<Resource Rights>' for '<User Group>'
        When connected as user part of '<User Group>'
        Then '<Resources>' resources are visible
        And '<Resource>' should have '<Permissions>'
		And resources should have '<Rights>' 
Examples: 
        | No | Group  | Given rights                                                     | Resource Name           | Resource Rights           | User Group | Resources | Rights                                                           | Resource                | Permissions                                                       |
        | 1  | Public | View                                                             | BARNEY\DECISION TESTING | View                      | Users      | All       | View                                                             | BARNEY\DECISION TESTING | View                                                              |
        | 2  | Public | Execute                                                          | BARNEY\DECISION TESTING | View                      | Users      | All       | Execute                                                          | BARNEY\DECISION TESTING | View, Execute                                                     |
        | 3  | Public | Contribute, View, Execute                                        | BARNEY\DECISION TESTING | View                      | Users      | All       | Contribute, View, Execute                                        | BARNEY\DECISION TESTING | Contribute, View, Execute                                         |
        | 4  | Public | View, Execute                                                    | BARNEY\DECISION TESTING | View                      | Users      | All       | View, Execute                                                    | BARNEY\DECISION TESTING | View, Execute                                                     |
        | 5  | Public | View, Execute, Contribute, Deploy To, Deploy From, Administrator | BARNEY\DECISION TESTING | View                      | Users      | All       | View, Execute, Contribute, Deploy To, Deploy From, Administrator | BARNEY\DECISION TESTING | View, Execute, Contribute, Deploy To, Deploy From , Administrator |
        | 6  | Public | View                                                             | BARNEY\DECISION TESTING | Execute                   | Users      | All       | View                                                             | BARNEY\DECISION TESTING | View, Execute                                                     |
        | 7  | Public | Execute                                                          | BARNEY\DECISION TESTING | Execute                   | Users      | All       | Execute                                                          | BARNEY\DECISION TESTING | Execute                                                           |
        | 8  | Public | Contribute, View, Execute                                        | BARNEY\DECISION TESTING | Execute                   | Users      | All       | Contribute, View, Execute                                        | BARNEY\DECISION TESTING | Contribute, View, Execute                                         |
        | 9  | Public | View, Execute                                                    | BARNEY\DECISION TESTING | Execute                   | Users      | All       | View, Execute                                                    | BARNEY\DECISION TESTING | View, Execute                                                     |
        | 10 | Public | View, Execute, Contribute, Deploy To, Deploy From, Administrator | BARNEY\DECISION TESTING | Execute                   | Users      | All       | View, Execute, Contribute, Deploy To, Deploy From, Administrator | BARNEY\DECISION TESTING | View, Execute, Contribute, Deploy To, Deploy From, Administrator  |
        | 11 | Public | View                                                             | BARNEY\DECISION TESTING | Contribute, View, Execute | Users      | All       | View                                                             | BARNEY\DECISION TESTING | Contribute, View, Execute                                         |
        | 12 | Public | Execute                                                          | BARNEY\DECISION TESTING | Contribute, View, Execute | Users      | All       | Execute                                                          | BARNEY\DECISION TESTING | Contribute, View, Execute                                         |
        | 13 | Public | Contribute, View, Execute                                        | BARNEY\DECISION TESTING | Contribute, View, Execute | Users      | All       | Contribute, View, Execute                                        | BARNEY\DECISION TESTING | Contribute, View, Execute                                         |
        | 14 | Public | View, Execute                                                    | BARNEY\DECISION TESTING | Contribute, View, Execute | Users      | All       | View, Execute                                                    | BARNEY\DECISION TESTING | Contribute, View, Execute                                         |
        | 15 | Public | View, Execute, Contribute, Deploy To, Deploy From                | BARNEY\DECISION TESTING | Contribute, View, Execute | Users      | All       | View, Execute, Contribute, Deploy To, Deploy From                | BARNEY\DECISION TESTING | Contribute, View, Execute, Deploy To, Deploy From                 |
        | 16 | Public | View                                                             | BARNEY\DECISION TESTING | View, Execute             | Users      | All       | View                                                             | BARNEY\DECISION TESTING | View, Execute                                                     |
        | 17 | Public | Execute                                                          | BARNEY\DECISION TESTING | View, Execute             | Users      | All       | Execute                                                          | BARNEY\DECISION TESTING | View, Execute                                                     |
        | 18 | Public | Contribute, View, Execute                                        | BARNEY\DECISION TESTING | View, Execute             | Users      | All       | Contribute, View, Execute                                        | BARNEY\DECISION TESTING | Contribute, View, Execute                                         |
        | 19 | Public | View, Execute                                                    | BARNEY\DECISION TESTING | View, Execute             | Users      | All       | View, Execute                                                    | BARNEY\DECISION TESTING | View, Execute                                                     |
        | 20 | Public | View, Execute, Contribute, Deploy To, Deploy From                | BARNEY\DECISION TESTING | View, Execute             | Users      | All       | View, Execute, Contribute, Deploy To, Deploy From                | BARNEY\DECISION TESTING | View, Execute, Contribute, Deploy To, Deploy From                 |
        | 21 | Public | View                                                             | BARNEY\DECISION TESTING | None                      | Users      | All       | View                                                             | BARNEY\DECISION TESTING | View                                                              |
        | 22 | Public | Execute                                                          | BARNEY\DECISION TESTING | None                      | Users      | All       | Execute                                                          | BARNEY\DECISION TESTING | Execute                                                           |
        | 23 | Public | Contribute, View, Execute                                        | BARNEY\DECISION TESTING | None                      | Users      | All       | Contribute, View, Execute                                        | BARNEY\DECISION TESTING | Contribute, View, Execute                                         |
        | 24 | Public | View, Execute                                                    | BARNEY\DECISION TESTING | None                      | Users      | All       | View, Execute                                                    | BARNEY\DECISION TESTING | View, Execute                                                     |
        | 25 | Public | View, Execute, Contribute, Deploy To, Deploy From, Administrator | BARNEY\DECISION TESTING | None                      | Users      | All       | View, Execute, Contribute, Deploy To, Deploy From, Administrator | BARNEY\DECISION TESTING | View, Execute, Contribute, Deploy To, Deploy From, Administrator  |


#		
#Scenario Outline: Setting Selected Resource Permissions for users 
#        Given I have a server "localhost"
#        And it has ‘<Group>’ with rights '<Given rights>' 
#        And Resource ‘<Resource Name>’ has rights ‘<GivenResourceRights>’ for '<usergroup>'
#        When connected as user part of ‘<UserGroup>’ and '<Group>'
#        Then '<Resources>' resources are visible
#        And resources should have '<ResourcesRights>' rights 
#        And selected resource ‘<SelectedResource>’ should have ‘<Selectedrights>’
#Examples: 
#        | No | Group  | Given rights                                              | Resource Name           | GivenResourceRights      | UserGroup | Resources | ResourcesRights                                    | Resource                | Selectedrights                                      |
#        | 1  | Public | Deploy To                                                 | BARNEY\DECISION TESTING | View                     | User      | All       | Deploy To,                                         | BARNEY\DECISION TESTING | View, Deploy To                                     |
#        | 2  | Public | Deploy From                                               | BARNEY\DECISION TESTING | View                     | User      | All       | Deploy From                                        | BARNEY\DECISION TESTING | View, Deploy From                                   |
#        | 3  | Public | View                                                      | BARNEY\DECISION TESTING | View                     | User      | All       | View                                               | BARNEY\DECISION TESTING | View                                                |
#        | 4  | Public | Execute                                                   | BARNEY\DECISION TESTING | View                     | User      | All       | Execute                                            | BARNEY\DECISION TESTING | View, Execute                                       |
#        | 5  | Public | Contribute, View, Execute                                 | BARNEY\DECISION TESTING | View                     | User      | All       | Contribute, View, Execute                          | BARNEY\DECISION TESTING | Contribute, View, Execute                           |
#        | 6  | Public | Deploy To, Deploy From                                    | BARNEY\DECISION TESTING | View                     | User      | All       | Deploy To, Deploy From                             | BARNEY\DECISION TESTING | Deploy To, Deploy From                              |
#        | 7  | Public | View, Execute                                             | BARNEY\DECISION TESTING | View                     | User      | All       | View, Execute                                      | BARNEY\DECISION TESTING | View, Execute                                       |
#        | 8  | Public | View, Execute, Contribute, Deploy To, Deploy From , Admin | BARNEY\DECISION TESTING | View                     | User      | All       | View, Execute, Contribute, Deploy To, Deploy From  | BARNEY\DECISION TESTING | View, Execute, Contribute, Deploy To, Deploy From   |
#        | 9  | Public | Deploy To, View                                           | BARNEY\DECISION TESTING | View                     | User      | All       | Deploy To , View                                   | BARNEY\DECISION TESTING | Deploy To , View                                    |
#        | 10 | Public | Deploy To, Execute                                        | BARNEY\DECISION TESTING | View                     | User      | All       | Deploy To , Execute                                | BARNEY\DECISION TESTING | View, Deploy To , Execute                           |
#        | 11 | Public | Deploy To, Contribute, View, Execute                      | BARNEY\DECISION TESTING | View                     | User      | All       | Deploy To , Contribute, View, Execute              | BARNEY\DECISION TESTING | Deploy To , Contribute, View, Execute               |
#        | 12 | Public | Deploy From, View                                         | BARNEY\DECISION TESTING | View                     | User      | All       | Deploy From , View                                 | BARNEY\DECISION TESTING | Deploy From , View                                  |
#        | 13 | Public | Deploy From, Execute                                      | BARNEY\DECISION TESTING | View                     | User      | All       | Deploy From , Execute                              | BARNEY\DECISION TESTING | Deploy From , Execute                               |
#        | 14 | Public | Deploy From, Contribute, View, Execute                    | BARNEY\DECISION TESTING | View                     | User      | All       | Deploy From , Contribute, View, Execute            | BARNEY\DECISION TESTING | Deploy From , Contribute, View, Execute             |
#        | 15 | Public | Deploy To, Deploy From, View                              | BARNEY\DECISION TESTING | View                     | User      | All       | Deploy To, Deploy From , View                      | BARNEY\DECISION TESTING | Deploy To, Deploy From , View                       |
#        | 16 | Public | Deploy To, Deploy From, Execute                           | BARNEY\DECISION TESTING | View                     | User      | All       | Deploy To, Deploy From , Execute                   | BARNEY\DECISION TESTING | Deploy To, Deploy From , Execute                    |
#        | 17 | Public | Deploy To, Deploy From, Contribute, View, Execute         | BARNEY\DECISION TESTING | View                     | User      | All       | Deploy To, Deploy From , Contribute, View, Execute | BARNEY\DECISION TESTING | Deploy To, Deploy From , Contribute, View, Execute  |
#        | 18 | Public | Deploy To                                                 | BARNEY\DECISION TESTING | Execute                  | User      | All       | Deploy To                                          | BARNEY\DECISION TESTING | Execute, Deploy To                                  |
#        | 19 | Public | Deploy From                                               | BARNEY\DECISION TESTING | Execute                  | User      | All       | Deploy From                                        | BARNEY\DECISION TESTING | Execute, Deploy From                                |
#        | 20 | Public | View                                                      | BARNEY\DECISION TESTING | Execute                  | User      | All       | View                                               | BARNEY\DECISION TESTING | Execute, View                                       |
#        | 21 | Public | Execute                                                   | BARNEY\DECISION TESTING | Execute                  | User      | All       | Execute                                            | BARNEY\DECISION TESTING | Execute                                             |
#        | 22 | Public | Contribute, View, Execute                                 | BARNEY\DECISION TESTING | Execute                  | User      | All       | Contribute, View, Execute                          | BARNEY\DECISION TESTING | Contribute, View, Execute                           |
#        | 23 | Public | Deploy To, Deploy From                                    | BARNEY\DECISION TESTING | Execute                  | User      | All       | Deploy To, Deploy From                             | BARNEY\DECISION TESTING | Deploy To, Deploy From                              |
#        | 24 | Public | View, Execute                                             | BARNEY\DECISION TESTING | Execute                  | User      | All       | View, Execute                                      | BARNEY\DECISION TESTING | View, Execute                                       |
#        | 25 | Public | View, Execute, Contribute, Deploy To, Deploy From, Admin  | BARNEY\DECISION TESTING | Execute                  | User      | All       | View, Execute, Contribute, Deploy To, Deploy From  | BARNEY\DECISION TESTING | View, Execute, Contribute, Deploy To, Deploy Fro    |
#        | 26 | Public | Deploy To, View                                           | BARNEY\DECISION TESTING | Execute                  | User      | All       | Deploy To, View                                    | BARNEY\DECISION TESTING | Execute, Deploy To, View                            |
#        | 27 | Public | Deploy To, Execute                                        | BARNEY\DECISION TESTING | Execute                  | User      | All       | Deploy To, Execute                                 | BARNEY\DECISION TESTING | Deploy To, Execute                                  |
#        | 28 | Public | Deploy To, Contribute, View, Execute                      | BARNEY\DECISION TESTING | Execute                  | User      | All       | Deploy To, Contribute, View, Execute               | BARNEY\DECISION TESTING | Deploy To, Contribute, View, Execute                |
#        | 29 | Public | Deploy From, View                                         | BARNEY\DECISION TESTING | Execute                  | User      | All       | Deploy From, View                                  | BARNEY\DECISION TESTING | Deploy From, View                                   |
#        | 30 | Public | Deploy From, Execute                                      | BARNEY\DECISION TESTING | Execute                  | User      | All       | Deploy From, Execute                               | BARNEY\DECISION TESTING | Deploy From, Execute                                |
#        | 31 | Public | Deploy From, Contribute, View, Execute                    | BARNEY\DECISION TESTING | Execute                  | User      | All       | Deploy From, Contribute, View, Execute             | BARNEY\DECISION TESTING | Deploy From, Contribute, View, Execute              |
#        | 32 | Public | Deploy To, Deploy From, View                              | BARNEY\DECISION TESTING | Execute                  | User      | All       | Deploy To, Deploy From, View                       | BARNEY\DECISION TESTING | Execute, Deploy To, Deploy From, View               |
#        | 33 | Public | Deploy To, Deploy From, Execute                           | BARNEY\DECISION TESTING | Execute                  | User      | All       | Deploy To, Deploy From, Execute                    | BARNEY\DECISION TESTING | Deploy To, Deploy From, Execute                     |
#        | 34 | Public | Deploy To, Deploy From, Contribute, View, Execute         | BARNEY\DECISION TESTING | Execute                  | User      | All       | Deploy To, Deploy From, Contribute, View, Execute  | BARNEY\DECISION TESTING | Deploy To, Deploy From, Contribute, View, Execute   |
#        | 35 | Public | Deploy To                                                 | BARNEY\DECISION TESTING | Cotribute, View, Execute | User      | All       | Deploy To                                          | BARNEY\DECISION TESTING | Contribute, View, Execute, Deploy To                |
#        | 36 | Public | Deploy From                                               | BARNEY\DECISION TESTING | Cotribute, View, Execute | User      | All       | Deploy From                                        | BARNEY\DECISION TESTING | Contribute, View, Execute, Deploy From              |
#        | 37 | Public | View                                                      | BARNEY\DECISION TESTING | Cotribute, View, Execute | User      | All       | View                                               | BARNEY\DECISION TESTING | Contribute, View, Execute                           |
#        | 38 | Public | Execute                                                   | BARNEY\DECISION TESTING | Cotribute, View, Execute | User      | All       | Execute                                            | BARNEY\DECISION TESTING | Contribute, View, Execute                           |
#        | 39 | Public | Contribute, View, Execute                                 | BARNEY\DECISION TESTING | Cotribute, View, Execute | User      | All       | Contribute, View, Execute                          | BARNEY\DECISION TESTING | Contribute, View, Execute                           |
#        | 40 | Public | Deploy To, Deploy From                                    | BARNEY\DECISION TESTING | Cotribute, View, Execute | User      | All       | Deploy To, Deploy From                             | BARNEY\DECISION TESTING | Contribute, View, Execute, Deploy To, Deploy From   |
#        | 41 | Public | View, Execute                                             | BARNEY\DECISION TESTING | Cotribute, View, Execute | User      | All       | View, Execute                                      | BARNEY\DECISION TESTING | Contribute, View, Execute                           |
#        | 42 | Public | View, Execute, Contribute, Deploy To, Deploy From         | BARNEY\DECISION TESTING | Cotribute, View, Execute | User      | All       | View, Execute, Contribute, Deploy To, Deploy From  | BARNEY\DECISION TESTING | Contribute, View, Execute, Deploy To, Deploy From   |
#        | 43 | Public | Deploy To, View                                           | BARNEY\DECISION TESTING | Cotribute, View, Execute | User      | All       | Deploy To, View                                    | BARNEY\DECISION TESTING | Contribute, View, Execute, Deploy To                |
#        | 44 | Public | Deploy To, Execute                                        | BARNEY\DECISION TESTING | Cotribute, View, Execute | User      | All       | Deploy To, Execute                                 | BARNEY\DECISION TESTING | Contribute, View, Execute, Deploy To                |
#        | 45 | Public | Deploy To, Contribute, View, Execute                      | BARNEY\DECISION TESTING | Cotribute, View, Execute | User      | All       | Deploy To, Contribute, View, Execute               | BARNEY\DECISION TESTING | Contribute, View, Execute, Deploy To                |
#        | 46 | Public | Deploy From, View                                         | BARNEY\DECISION TESTING | Cotribute, View, Execute | User      | All       | Deploy From, View                                  | BARNEY\DECISION TESTING | Contribute, View, Execute, Deploy From              |
#        | 47 | Public | Deploy From, Execute                                      | BARNEY\DECISION TESTING | Cotribute, View, Execute | User      | All       | Deploy From, Execute                               | BARNEY\DECISION TESTING | Contribute, View, Execute, Deploy From              |
#        | 48 | Public | Deploy From, Contribute, View, Execute                    | BARNEY\DECISION TESTING | Cotribute, View, Execute | User      | All       | Deploy From, Contribute, View, Execute             | BARNEY\DECISION TESTING | Contribute, View, Execute, Deploy From              |
#        | 49 | Public | Deploy To, Deploy From, View                              | BARNEY\DECISION TESTING | Cotribute, View, Execute | User      | All       | Deploy To, Deploy From, View                       | BARNEY\DECISION TESTING | Contribute, View, Execute, Deploy To, Deploy From   |
#        | 50 | Public | Deploy To, Deploy From, Execute                           | BARNEY\DECISION TESTING | Cotribute, View, Execute | User      | All       | Deploy To, Deploy From, Execute                    | BARNEY\DECISION TESTING | Contribute, View, Execute, Deploy To, Deploy From   |
#        | 51 | Public | Deploy To, Deploy From, Contribute, View, Execute, Admin  | BARNEY\DECISION TESTING | Cotribute, View, Execute | User      | All       | Deploy To, Deploy From, Contribute, View, Execute  | BARNEY\DECISION TESTING | Deploy To, Deploy From, Contribute, View, Execute   |
#        | 52 | Public | Deploy To                                                 | BARNEY\DECISION TESTING | View, Execute            | User      | All       | Deploy To                                          | BARNEY\DECISION TESTING | View, Execute, Deploy To                            |
#        | 53 | Public | Deploy From                                               | BARNEY\DECISION TESTING | View, Execute            | User      | All       | Deploy From                                        | BARNEY\DECISION TESTING | View, Execute, Deploy From                          |
#        | 54 | Public | View                                                      | BARNEY\DECISION TESTING | View, Execute            | User      | All       | View                                               | BARNEY\DECISION TESTING | View, Execute                                       |
#        | 55 | Public | Execute                                                   | BARNEY\DECISION TESTING | View, Execute            | User      | All       | Execute                                            | BARNEY\DECISION TESTING | View, Execute                                       |
#        | 56 | Public | Contribute, View, Execute                                 | BARNEY\DECISION TESTING | View, Execute            | User      | All       | Contribute, View, Execute                          | BARNEY\DECISION TESTING | View, Execute, Contribute                           |
#        | 57 | Public | Deploy To, Deploy From                                    | BARNEY\DECISION TESTING | View, Execute            | User      | All       | Deploy To, Deploy From                             | BARNEY\DECISION TESTING | View, Execute, Deploy To, Deploy From               |
#        | 58 | Public | View, Execute                                             | BARNEY\DECISION TESTING | View, Execute            | User      | All       | View, Execute                                      | BARNEY\DECISION TESTING | View, Execute                                       |
#        | 59 | Public | View, Execute, Contribute, Deploy To, Deploy From         | BARNEY\DECISION TESTING | View, Execute            | User      | All       | View, Execute, Contribute, Deploy To, Deploy From  | BARNEY\DECISION TESTING | View, Execute, Contribute, Deploy To, Deploy From   |
#        | 60 | Public | Deploy To, View                                           | BARNEY\DECISION TESTING | View, Execute            | User      | All       | Deploy To, View                                    | BARNEY\DECISION TESTING | View, Execute, Deploy To                            |
#        | 61 | Public | Deploy To, Execute                                        | BARNEY\DECISION TESTING | View, Execute            | User      | All       | Deploy To, Execute                                 | BARNEY\DECISION TESTING | View, Execute, Deploy To                            |
#        | 62 | Public | Deploy To, Contribute, View, Execute                      | BARNEY\DECISION TESTING | View, Execute            | User      | All       | Deploy To, Contribute, View, Execute               | BARNEY\DECISION TESTING | View, Execute                                       |
#        | 63 | Public | Deploy From, View                                         | BARNEY\DECISION TESTING | View, Execute            | User      | All       | Deploy From, View                                  | BARNEY\DECISION TESTING | View, Execute, Deploy From                          |
#        | 64 | Public | Deploy From, Execute                                      | BARNEY\DECISION TESTING | View, Execute            | User      | All       | Deploy From, Execute                               | BARNEY\DECISION TESTING | View, Execute, Deploy From                          |
#        | 65 | Public | Deploy From, Contribute, View, Execute                    | BARNEY\DECISION TESTING | View, Execute            | User      | All       | Deploy From, Contribute, View, Execute             | BARNEY\DECISION TESTING | Deploy From, Contribute, View, Execute              |
#        | 66 | Public | Deploy To, Deploy From, View                              | BARNEY\DECISION TESTING | View, Execute            | User      | All       | Deploy To, Deploy From, View                       | BARNEY\DECISION TESTING | View, Execute, Deploy To, Deploy From               |
#        | 67 | Public | Deploy To, Deploy From, Execute                           | BARNEY\DECISION TESTING | View, Execute            | User      | All       | Deploy To, Deploy From, Execute                    | BARNEY\DECISION TESTING | View, Deploy To, Deploy From, Execute               |
#        | 68 | Public | Deploy To, Deploy From, Contribute, View, Execute, Admin  | BARNEY\DECISION TESTING | View, Execute            | User      | All       | Deploy To, Deploy From, Contribute, View, Execute  | BARNEY\DECISION TESTING | Deploy To, Deploy From, Contribute, View, Execute e |
#        | 69 | Public | Deploy To                                                 | BARNEY\DECISION TESTING | None                     | User      | All       | Deploy To                                          | BARNEY\DECISION TESTING | Deploy To                                           |
#        | 70 | Public | Deploy From                                               | BARNEY\DECISION TESTING | None                     | User      | All       | Deploy From                                        | BARNEY\DECISION TESTING | Deploy From                                         |
#        | 71 | Public | View                                                      | BARNEY\DECISION TESTING | None                     | User      | All       | View                                               | BARNEY\DECISION TESTING | View                                                |
#        | 72 | Public | Execute                                                   | BARNEY\DECISION TESTING | None                     | User      | All       | Execute                                            | BARNEY\DECISION TESTING | Execute                                             |
#        | 73 | Public | Contribute, View, Execute                                 | BARNEY\DECISION TESTING | None                     | User      | All       | Contribute, View, Execute                          | BARNEY\DECISION TESTING | Contribute, View, Execute                           |
#        | 74 | Public | Deploy To, Deploy From                                    | BARNEY\DECISION TESTING | None                     | User      | All       | Deploy To, Deploy From                             | BARNEY\DECISION TESTING | Deploy To, Deploy From                              |
#        | 75 | Public | View, Execute                                             | BARNEY\DECISION TESTING | None                     | User      | All       | View, Execute                                      | BARNEY\DECISION TESTING | View, Execute                                       |
#        | 76 | Public | View, Execute, Contribute, Deploy To, Deploy From, Admin  | BARNEY\DECISION TESTING | None                     | User      | All       | View, Execute, Contribute, Deploy To, Deploy From  | BARNEY\DECISION TESTING | View, Execute, Contribute, Deploy To, Deploy From   |
#        | 77 | Public | Deploy To, View                                           | BARNEY\DECISION TESTING | None                     | User      | All       | Deploy To, View                                    | BARNEY\DECISION TESTING | Deploy To, View                                     |
#        | 78 | Public | Deploy To, Execute                                        | BARNEY\DECISION TESTING | None                     | User      | All       | Deploy To, Execute                                 | BARNEY\DECISION TESTING | Deploy To, Execute                                  |
#        | 79 | Public | Deploy To, Contribute, View, Execute                      | BARNEY\DECISION TESTING | None                     | User      | All       | Deploy To, Contribute, View, Execute               | BARNEY\DECISION TESTING | Deploy To, Contribute, View, Execute                |
#        | 80 | Public | Deploy From, View                                         | BARNEY\DECISION TESTING | None                     | User      | All       | Deploy From, View                                  | BARNEY\DECISION TESTING | Deploy From, View                                   |
#        | 81 | Public | Deploy From, Execute                                      | BARNEY\DECISION TESTING | None                     | User      | All       | Deploy From, Execute                               | BARNEY\DECISION TESTING | Deploy From, Execute                                |
#        | 82 | Public | Deploy From, Contribute, View, Execute                    | BARNEY\DECISION TESTING | None                     | User      | All       | Deploy From, Contribute, View, Execute             | BARNEY\DECISION TESTING | Deploy From, Contribute, View, Execute              |
#        | 83 | Public | Deploy To, Deploy From, View                              | BARNEY\DECISION TESTING | None                     | User      | All       | Deploy To, Deploy From, View                       | BARNEY\DECISION TESTING | Deploy To, Deploy From, View                        |
#        | 84 | Public | Deploy To, Deploy From, Execute                           | BARNEY\DECISION TESTING | None                     | User      | All       | Deploy To, Deploy From, Execute                    | BARNEY\DECISION TESTING | Deploy To, Deploy From, Execute                     |
#        | 85 | Public | Deploy To, Deploy From, Contribute, View, Execute, Admin  | BARNEY\DECISION TESTING | None                     | User      | All       | Deploy To, Deploy From, Contribute, View, Execute  | BARNEY\DECISION TESTING | Deploy To, Deploy From, Contribute, View, Execute   |




