Feature: Rename
	In order to be able to Rename File or Folder 
	as a Warewolf user
	I want a tool that will rename a File or Floder at a given location

@FileRenameFromLocalWithOverwrite
@FileRenameFromLocal
Scenario Outline: Rename file at local location
	Given I have a source path "<source>" with value "<sourceLocation>" 
	And source credentials as "<username>" and "<password>"
	And I have a destination path "<destination>" with value "<destinationLocation>"
    And destination credentials as "<destUsername>" and "<destPassword>"
	And overwrite is "<selected>"
	And use private public key for source is "<sourcePrivateKeyFile>"
	And use private public key for destination is "<destinationPrivateKeyFile>"
	And result as "<resultVar>"
    When the rename file tool is executed
	Then the result variable "<resultVar>" will be "<result>"
	And the execution has "<errorOccured>" error
	And the debug inputs as
         | Source Path                 | Username   | Password | Source Private Key File |Destination Path                      | Destination Username | Destination Password |Destination Private Key File | Overwrite  |
         | <source> = <sourceLocation> | <username> | String   | <sourcePrivateKeyFile>  |<destination> = <destinationLocation> | <destUsername>       | String               |<destinationPrivateKeyFile>  | <selected> |
	And the debug output as
		|                        |
		| <resultVar> = <result> |
	Examples: 
	| No | Name            | source         | sourceLocation      | username | password | destination  | destinationLocation                                                                          | destUsername  | destPassword | selected | resultVar  | result    | errorOccured | sourcePrivateKeyFile | destinationPrivateKeyFile |
	| 1  | Local to Local  | [[sourcePath]] | C:\renamefile0.txt  | ""       | ""       | [[destPath]] | C:\renamed0.txt                                                                              | ""            | ""           | True     | [[result]] | "Success" | NO           |                      |                           |
	| 2  | Local to FTP    | [[sourcePath]] | C:\renamefile1.txt  | ""       | ""       | [[destPath]] | ftp://DEVOPSPDC.premier.local:1001/FORFILERENAMETESTING/renamed0.txt                         | ""            | ""           | True     | [[result]] | "Success" | NO           |                      |                           |
	| 3  | Local to FTPS   | [[sourcePath]] | C:\renamefile2.txt  | ""       | ""       | [[destPath]] | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed0.txt                         | Administrator | Dev2@dmin123 | True     | [[result]] | "Success" | NO           |                      |                           |
	| 4  | Local to SFTP   | [[sourcePath]] | C:\renamefile3.txt  | ""       | ""       | [[destPath]] | sftp://SVRDEV.premier.local/renamed0.txt                                                     | dev2          | Q/ulw&]      | True     | [[result]] | "Success" | NO           |                      |                           |
	| 5  | Local to UNC    | [[sourcePath]] | C:\renamefile4.txt  | ""       | ""       | [[destPath]] | \\\\SVRDEV.premier.local\FileSystemShareTestingSite\FileRenameSharedTestingSite\renamed0.txt | ""            | ""           | True     | [[result]] | "Success" | NO           |                      |                           |
	| 27 | Local to Local  | [[sourcePath]] | NULL                | ""       | ""       | [[destPath]] | C:\renamed0.txt                                                                              | ""            | ""           | True     | [[result]] | ""        | AN           |                      |                           |

@FileRenameFromUNCWithOverwrite
@FileRenameFromUNC
Scenario Outline: Rename file at UNC location
	Given I have a source path "<source>" with value "<sourceLocation>" 
	And source credentials as "<username>" and "<password>"
	And I have a destination path "<destination>" with value "<destinationLocation>"
    And destination credentials as "<destUsername>" and "<destPassword>"
	And overwrite is "<selected>"
	And use private public key for source is "<sourcePrivateKeyFile>"
	And use private public key for destination is "<destinationPrivateKeyFile>"
	And result as "<resultVar>"
    When the rename file tool is executed
	Then the result variable "<resultVar>" will be "<result>"
	And the execution has "<errorOccured>" error
	And the debug inputs as
         | Source Path                 | Username   | Password | Source Private Key File |Destination Path                      | Destination Username | Destination Password |Destination Private Key File | Overwrite  |
         | <source> = <sourceLocation> | <username> | String   | <sourcePrivateKeyFile>  |<destination> = <destinationLocation> | <destUsername>       | String               |<destinationPrivateKeyFile>  | <selected> |
	And the debug output as
		|                        |
		| <resultVar> = <result> |
	Examples: 
	| No | Name            | source         | sourceLocation                                                                                  | username      | password     | destination  | destinationLocation                                                                          | destUsername  | destPassword | selected | resultVar  | result    | errorOccured | sourcePrivateKeyFile | destinationPrivateKeyFile |
	| 6  | UNC to Local    | [[sourcePath]] | \\\\SVRDEV.premier.local\FileSystemShareTestingSite\FileRenameSharedTestingSite\renamefile0.txt | ""            | ""           | [[destPath]] | C:\renamed1.txt                                                                              | ""            | ""           | True     | [[result]] | "Success" | NO           |                      |                           |
	| 7  | UNC to FTP      | [[sourcePath]] | \\\\SVRDEV.premier.local\FileSystemShareTestingSite\FileRenameSharedTestingSite\renamefile1.txt | ""            | ""           | [[destPath]] | ftp://DEVOPSPDC.premier.local:1001/FORFILERENAMETESTING/renamed1.txt                         | ""            | ""           | True     | [[result]] | "Success" | NO           |                      |                           |
	| 8  | UNC to FTPS     | [[sourcePath]] | \\\\SVRDEV.premier.local\FileSystemShareTestingSite\FileRenameSharedTestingSite\renamefile2.txt | ""            | ""           | [[destPath]] | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed1.txt                         | Administrator | Dev2@dmin123 | True     | [[result]] | "Success" | NO           |                      |                           |
	| 9  | UNC to SFTP     | [[sourcePath]] | \\\\SVRDEV.premier.local\FileSystemShareTestingSite\FileRenameSharedTestingSite\renamefile3.txt | ""            | ""           | [[destPath]] | sftp://SVRDEV.premier.local/renamed1.txt                                                     | dev2          | Q/ulw&]      | True     | [[result]] | "Success" | NO           |                      |                           |
	| 10 | UNC to UNC      | [[sourcePath]] | \\\\SVRDEV.premier.local\FileSystemShareTestingSite\FileRenameSharedTestingSite\renamefile4.txt | ""            | ""           | [[destPath]] | \\\\SVRDEV.premier.local\FileSystemShareTestingSite\FileRenameSharedTestingSite\renamed1.txt | ""            | ""           | True     | [[result]] | "Success" | NO           |                      |                           |

@FileRenameFromFTPWithOverwrite
@FileRenameFromFTP
Scenario Outline: Rename file at FTP location
	Given I have a source path "<source>" with value "<sourceLocation>" 
	And source credentials as "<username>" and "<password>"
	And I have a destination path "<destination>" with value "<destinationLocation>"
    And destination credentials as "<destUsername>" and "<destPassword>"
	And overwrite is "<selected>"
	And use private public key for source is "<sourcePrivateKeyFile>"
	And use private public key for destination is "<destinationPrivateKeyFile>"
	And result as "<resultVar>"
    When the rename file tool is executed
	Then the result variable "<resultVar>" will be "<result>"
	And the execution has "<errorOccured>" error
	And the debug inputs as
         | Source Path                 | Username   | Password | Source Private Key File |Destination Path                      | Destination Username | Destination Password |Destination Private Key File | Overwrite  |
         | <source> = <sourceLocation> | <username> | String   | <sourcePrivateKeyFile>  |<destination> = <destinationLocation> | <destUsername>       | String               |<destinationPrivateKeyFile>  | <selected> |
	And the debug output as
		|                        |
		| <resultVar> = <result> |
	Examples: 
	| No | Name            | source         | sourceLocation                                                          | username      | password | destination  | destinationLocation                                                                          | destUsername  | destPassword | selected | resultVar  | result    | errorOccured | sourcePrivateKeyFile | destinationPrivateKeyFile |
	| 11 | FTP to Local    | [[sourcePath]] | ftp://DEVOPSPDC.premier.local:1001/FORFILERENAMETESTING/renamefile0.txt | ""            | ""       | [[destPath]] | C:\renamed2.txt                                                                              | ""            | ""           | True     | [[result]] | "Success" | NO           |                      |                           |
	| 12 | FTP to UNC      | [[sourcePath]] | ftp://DEVOPSPDC.premier.local:1001/FORFILERENAMETESTING/renamefile1.txt | ""            | ""       | [[destPath]] | \\\\SVRDEV.premier.local\FileSystemShareTestingSite\FileRenameSharedTestingSite\renamed2.txt | ""            | ""           | True     | [[result]] | "Success" | NO           |                      |                           |
	| 13 | FTP to FTPS     | [[sourcePath]] | ftp://DEVOPSPDC.premier.local:1001/FORFILERENAMETESTING/renamefile2.txt | ""            | ""       | [[destPath]] | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed2.txt                         | Administrator | Dev2@dmin123 | True     | [[result]] | "Success" | NO           |                      |                           |
	| 14 | FTP to SFTP     | [[sourcePath]] | ftp://DEVOPSPDC.premier.local:1001/FORFILERENAMETESTING/renamefile3.txt | ""            | ""       | [[destPath]] | sftp://SVRDEV.premier.local/renamed2.txt                                                     | dev2          | Q/ulw&]      | True     | [[result]] | "Success" | NO           |                      |                           |
	| 15 | FTP to FTP      | [[sourcePath]] | ftp://DEVOPSPDC.premier.local:1001/FORFILERENAMETESTING/renamefile4.txt | ""            | ""       | [[destPath]] | ftp://DEVOPSPDC.premier.local:1001/FORFILERENAMETESTING/renamed2.txt                         | ""            | ""           | True     | [[result]] | "Success" | NO           |                      |                           |

@FileRenameFromFTPSWithOverwrite
@FileRenameFromFTPS
Scenario Outline: Rename file at FTPS location
	Given I have a source path "<source>" with value "<sourceLocation>" 
	And source credentials as "<username>" and "<password>"
	And I have a destination path "<destination>" with value "<destinationLocation>"
    And destination credentials as "<destUsername>" and "<destPassword>"
	And overwrite is "<selected>"
	And use private public key for source is "<sourcePrivateKeyFile>"
	And use private public key for destination is "<destinationPrivateKeyFile>"
	And result as "<resultVar>"
    When the rename file tool is executed
	Then the result variable "<resultVar>" will be "<result>"
	And the execution has "<errorOccured>" error
	And the debug inputs as
         | Source Path                 | Username   | Password | Source Private Key File |Destination Path                      | Destination Username | Destination Password |Destination Private Key File | Overwrite  |
         | <source> = <sourceLocation> | <username> | String   | <sourcePrivateKeyFile>  |<destination> = <destinationLocation> | <destUsername>       | String               |<destinationPrivateKeyFile>  | <selected> |
	And the debug output as
		|                        |
		| <resultVar> = <result> |
	Examples: 
	| No | Name            | source         | sourceLocation                                                          | username      | password     | destination  | destinationLocation                                                                          | destUsername  | destPassword | selected | resultVar  | result    | errorOccured | sourcePrivateKeyFile | destinationPrivateKeyFile |
	| 16 | FTPS to Local   | [[sourcePath]] | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamefile0.txt | Administrator | Dev2@dmin123 | [[destPath]] | C:\renamed3.txt                                                                              | ""            | ""           | True     | [[result]] | "Success" | NO           |                      |                           |
	| 17 | FTPS to UNC     | [[sourcePath]] | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamefile1.txt | Administrator | Dev2@dmin123 | [[destPath]] | \\\\SVRDEV.premier.local\FileSystemShareTestingSite\FileRenameSharedTestingSite\renamed3.txt | ""            | ""           | True     | [[result]] | "Success" | NO           |                      |                           |
	| 18 | FTPS to FTPS    | [[sourcePath]] | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamefile2.txt | Administrator | Dev2@dmin123 | [[destPath]] | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed3.txt                         | Administrator | Dev2@dmin123 | True     | [[result]] | "Success" | NO           |                      |                           |
	| 19 | FTPS to SFTP    | [[sourcePath]] | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamefile3.txt | Administrator | Dev2@dmin123 | [[destPath]] | sftp://SVRDEV.premier.local/renamed3.txt                                                     | dev2          | Q/ulw&]      | True     | [[result]] | "Success" | NO           |                      |                           |
	| 20 | FTPS to FTP     | [[sourcePath]] | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamefile4.txt | Administrator | Dev2@dmin123 | [[destPath]] | ftp://DEVOPSPDC.premier.local:1001/FORFILERENAMETESTING/renamed3.txt                         | ""            | ""           | True     | [[result]] | "Success" | NO           |                      |                           |

@FileRenameFromSFTPWithOverwrite
@FileRenameFromSFTP
Scenario Outline: Rename file at SFTP location
	Given I have a source path "<source>" with value "<sourceLocation>" 
	And source credentials as "<username>" and "<password>"
	And I have a destination path "<destination>" with value "<destinationLocation>"
    And destination credentials as "<destUsername>" and "<destPassword>"
	And overwrite is "<selected>"
	And use private public key for source is "<sourcePrivateKeyFile>"
	And use private public key for destination is "<destinationPrivateKeyFile>"
	And result as "<resultVar>"
    When the rename file tool is executed
	Then the result variable "<resultVar>" will be "<result>"
	And the execution has "<errorOccured>" error
	And the debug inputs as
         | Source Path                 | Username   | Password | Source Private Key File |Destination Path                      | Destination Username | Destination Password |Destination Private Key File | Overwrite  |
         | <source> = <sourceLocation> | <username> | String   | <sourcePrivateKeyFile>  |<destination> = <destinationLocation> | <destUsername>       | String               |<destinationPrivateKeyFile>  | <selected> |
	And the debug output as
		|                        |
		| <resultVar> = <result> |
	Examples: 
	| No | Name            | source         | sourceLocation                               | username | password | destination  | destinationLocation                                                                          | destUsername  | destPassword | selected | resultVar  | result    | errorOccured | sourcePrivateKeyFile | destinationPrivateKeyFile |
	| 1  | SFTP to Local   | [[sourcePath]] | sftp://SVRDEV.premier.local/renamefile0.txt  | dev2     | Q/ulw&]  | [[destPath]] | C:\renamed4.txt                                                                              | ""            | ""           | True     | [[result]] | "Success" | NO           |                      |                           |
	| 2  | SFTP to UNC     | [[sourcePath]] | sftp://SVRDEV.premier.local/renamefile1.txt  | dev2     | Q/ulw&]  | [[destPath]] | \\\\SVRDEV.premier.local\FileSystemShareTestingSite\FileRenameSharedTestingSite\renamed4.txt | ""            | ""           | True     | [[result]] | "Success" | NO           |                      |                           |
	| 3  | SFTP to FTP     | [[sourcePath]] | sftp://SVRDEV.premier.local/renamefile2.txt  | dev2     | Q/ulw&]  | [[destPath]] | ftp://DEVOPSPDC.premier.local:1001/FORFILERENAMETESTING/renamed4.txt                         | ""            | ""           | True     | [[result]] | "Success" | NO           |                      |                           |
	| 4  | SFTP to FTPS    | [[sourcePath]] | sftp://SVRDEV.premier.local/renamefile3.txt  | dev2     | Q/ulw&]  | [[destPath]] | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed4.txt                         | Administrator | Dev2@dmin123 | True     | [[result]] | "Success" | NO           |                      |                           |
	| 5  | SFTP to SFTP    | [[sourcePath]] | sftp://SVRDEV.premier.local/renamefile4.txt  | dev2     | Q/ulw&]  | [[destPath]] | sftp://SVRDEV.premier.local/renamed4.txt                                                     | dev2          | Q/ulw&]      | True     | [[result]] | "Success" | NO           |                      |                           |
	| 6  | SFTP to SFTP PK | [[sourcePath]] | sftp://SVRDEV.premier.local/renamefile41.txt | dev2     | Q/ulw&]  | [[destPath]] | sftp://SVRDEV.premier.local/renamed41.txt                                                    | dev2          | Q/ulw&]      | True     | [[result]] | "Success" | NO           | C:\\Temp\\key.opk    | C:\\Temp\\key.opk         |

@FileRenameFromLocalWithoutOverwrite
@FileRenameFromLocal
Scenario Outline: Rename file at local location with overwrite disabled
	Given I have a source path "<source>" with value "<sourceLocation>" 
	And source credentials as "<username>" and "<password>"
	And I have a destination path "<destination>" with value "<destinationLocation>"
    And destination credentials as "<destUsername>" and "<destPassword>"
	And overwrite is "<selected>"
	And use private public key for source is "<sourcePrivateKeyFile>"
	And use private public key for destination is "<destinationPrivateKeyFile>"
	And result as "<resultVar>"
    When the rename file tool is executed
	Then the result variable "<resultVar>" will be "<result>"
	And the execution has "<errorOccured>" error
	And the debug inputs as
         | Source Path                 | Username   | Password | Source Private Key File |Destination Path                      | Destination Username | Destination Password |Destination Private Key File | Overwrite  |
         | <source> = <sourceLocation> | <username> | String   | <sourcePrivateKeyFile>  |<destination> = <destinationLocation> | <destUsername>       | String               |<destinationPrivateKeyFile>  | <selected> |
	And the debug output as
		|                        |
		| <resultVar> = <result> |
	Examples: 
	| No | Name           | source         | sourceLocation     | username | password | destination  | destinationLocation                                                                          | destUsername  | destPassword | selected | resultVar  | result    | errorOccured | sourcePrivateKeyFile | destinationPrivateKeyFile |
	| 1  | Local to Local | [[sourcePath]] | C:\renamefile0.txt | ""       | ""       | [[destPath]] | C:\renamed0.txt                                                                              | ""            | ""           | False    | [[result]] | "Success" | NO           |                      |                           |
	| 2  | Local to FTP   | [[sourcePath]] | C:\renamefile1.txt | ""       | ""       | [[destPath]] | ftp://DEVOPSPDC.premier.local:1001/FORFILERENAMETESTING/renamed0.txt                         | ""            | ""           | False    | [[result]] | "Success" | NO           |                      |                           |
	| 3  | Local to FTPS  | [[sourcePath]] | C:\renamefile2.txt | ""       | ""       | [[destPath]] | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed0.txt                         | Administrator | Dev2@dmin123 | False    | [[result]] | "Success" | NO           |                      |                           |
	| 4  | Local to SFTP  | [[sourcePath]] | C:\renamefile3.txt | ""       | ""       | [[destPath]] | sftp://SVRDEV.premier.local/renamed0.txt                                                     | dev2          | Q/ulw&]      | False    | [[result]] | "Success" | NO           |                      |                           |
	| 5  | Local to UNC   | [[sourcePath]] | C:\renamefile4.txt | ""       | ""       | [[destPath]] | \\\\SVRDEV.premier.local\FileSystemShareTestingSite\FileRenameSharedTestingSite\renamed0.txt | ""            | ""           | False    | [[result]] | "Success" | NO           |                      |                           |
	| 6  | Local to Local | [[sourcePath]] | NULL               | ""       | ""       | [[destPath]] | C:\renamed0.txt                                                                              | ""            | ""           | False    | [[result]] | ""        | AN           |                      |                           |

@FileRenameFromUNCWithoutOverwrite
@FileRenameFromUNC
Scenario Outline: Rename file at UNC location with overwrite disabled
	Given I have a source path "<source>" with value "<sourceLocation>" 
	And source credentials as "<username>" and "<password>"
	And I have a destination path "<destination>" with value "<destinationLocation>"
    And destination credentials as "<destUsername>" and "<destPassword>"
	And overwrite is "<selected>"
	And use private public key for source is "<sourcePrivateKeyFile>"
	And use private public key for destination is "<destinationPrivateKeyFile>"
	And result as "<resultVar>"
    When the rename file tool is executed
	Then the result variable "<resultVar>" will be "<result>"
	And the execution has "<errorOccured>" error
	And the debug inputs as
         | Source Path                 | Username   | Password | Source Private Key File |Destination Path                      | Destination Username | Destination Password |Destination Private Key File | Overwrite  |
         | <source> = <sourceLocation> | <username> | String   | <sourcePrivateKeyFile>  |<destination> = <destinationLocation> | <destUsername>       | String               |<destinationPrivateKeyFile>  | <selected> |
	And the debug output as
		|                        |
		| <resultVar> = <result> |
	Examples: 
	| No | Name         | source         | sourceLocation                                                                                  | username          | password | destination  | destinationLocation                                                                          | destUsername  | destPassword | selected | resultVar  | result    | errorOccured | sourcePrivateKeyFile | destinationPrivateKeyFile |
	| 1  | UNC to Local | [[sourcePath]] | \\\\SVRDEV.premier.local\FileSystemShareTestingSite\FileRenameSharedTestingSite\renamefile0.txt | ""                | ""       | [[destPath]] | C:\renamed1.txt                                                                              | ""            | ""           | False    | [[result]] | "Success" | NO           |                      |                           |
	| 2  | UNC to FTP   | [[sourcePath]] | \\\\SVRDEV.premier.local\FileSystemShareTestingSite\FileRenameSharedTestingSite\renamefile1.txt | ""                | ""       | [[destPath]] | ftp://DEVOPSPDC.premier.local:1001/FORFILERENAMETESTING/renamed1.txt                         | ""            | ""           | False    | [[result]] | "Success" | NO           |                      |                           |
	| 3  | UNC to FTPS  | [[sourcePath]] | \\\\SVRDEV.premier.local\FileSystemShareTestingSite\FileRenameSharedTestingSite\renamefile2.txt | ""                | ""       | [[destPath]] | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed1.txt                         | Administrator | Dev2@dmin123 | False    | [[result]] | "Success" | NO           |                      |                           |
	| 4  | UNC to SFTP  | [[sourcePath]] | \\\\SVRDEV.premier.local\FileSystemShareTestingSite\FileRenameSharedTestingSite\renamefile3.txt | ""                | ""       | [[destPath]] | sftp://SVRDEV.premier.local/renamed1.txt                                                     | dev2          | Q/ulw&]      | False    | [[result]] | "Success" | NO           |                      |                           |
	| 5  | UNC to UNC   | [[sourcePath]] | \\\\SVRDEV.premier.local\FileSystemShareTestingSite\FileRenameSharedTestingSite\renamefile4.txt | ""                | ""       | [[destPath]] | \\\\SVRDEV.premier.local\FileSystemShareTestingSite\FileRenameSharedTestingSite\renamed1.txt | ""            | ""           | False    | [[result]] | "Success" | NO           |                      |                           |

@FileRenameFromFTPWithoutOverwrite
@FileRenameFromFTP
Scenario Outline: Rename file at FTP location with overwrite disabled
	Given I have a source path "<source>" with value "<sourceLocation>" 
	And source credentials as "<username>" and "<password>"
	And I have a destination path "<destination>" with value "<destinationLocation>"
    And destination credentials as "<destUsername>" and "<destPassword>"
	And overwrite is "<selected>"
	And use private public key for source is "<sourcePrivateKeyFile>"
	And use private public key for destination is "<destinationPrivateKeyFile>"
	And result as "<resultVar>"
    When the rename file tool is executed
	Then the result variable "<resultVar>" will be "<result>"
	And the execution has "<errorOccured>" error
	And the debug inputs as
         | Source Path                 | Username   | Password | Source Private Key File |Destination Path                      | Destination Username | Destination Password |Destination Private Key File | Overwrite  |
         | <source> = <sourceLocation> | <username> | String   | <sourcePrivateKeyFile>  |<destination> = <destinationLocation> | <destUsername>       | String               |<destinationPrivateKeyFile>  | <selected> |
	And the debug output as
		|                        |
		| <resultVar> = <result> |
	Examples: 
	| No | Name         | source         | sourceLocation                                                          | username | password | destination  | destinationLocation                                                                          | destUsername  | destPassword | selected | resultVar  | result    | errorOccured | sourcePrivateKeyFile | destinationPrivateKeyFile |
	| 1  | FTP to Local | [[sourcePath]] | ftp://DEVOPSPDC.premier.local:1001/FORFILERENAMETESTING/renamefile0.txt | ""       | ""       | [[destPath]] | C:\renamed2.txt                                                                              | ""            | ""           | False    | [[result]] | "Success" | NO           |                      |                           |
	| 2  | FTP to UNC   | [[sourcePath]] | ftp://DEVOPSPDC.premier.local:1001/FORFILERENAMETESTING/renamefile1.txt | ""       | ""       | [[destPath]] | \\\\SVRDEV.premier.local\FileSystemShareTestingSite\FileRenameSharedTestingSite\renamed2.txt | ""            | ""           | False    | [[result]] | "Success" | NO           |                      |                           |
	| 3  | FTP to FTPS  | [[sourcePath]] | ftp://DEVOPSPDC.premier.local:1001/FORFILERENAMETESTING/renamefile2.txt | ""       | ""       | [[destPath]] | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed2.txt                         | Administrator | Dev2@dmin123 | False    | [[result]] | "Success" | NO           |                      |                           |
	| 4  | FTP to SFTP  | [[sourcePath]] | ftp://DEVOPSPDC.premier.local:1001/FORFILERENAMETESTING/renamefile3.txt | ""       | ""       | [[destPath]] | sftp://SVRDEV.premier.local/renamed2.txt                                                     | dev2          | Q/ulw&]      | False    | [[result]] | "Success" | NO           |                      |                           |
	| 5  | FTP to FTP   | [[sourcePath]] | ftp://DEVOPSPDC.premier.local:1001/FORFILERENAMETESTING/renamefile4.txt | ""       |          | [[destPath]] | ftp://DEVOPSPDC.premier.local:1001/FORFILERENAMETESTING/renamed2.txt                         | ""            | ""           | False    | [[result]] | "Success" | NO           |                      |                           |

@FileRenameFromFTPSWithoutOverwrite
@FileRenameFromFTPS
Scenario Outline: Rename file at FTPS location with overwrite disabled
	Given I have a source path "<source>" with value "<sourceLocation>" 
	And source credentials as "<username>" and "<password>"
	And I have a destination path "<destination>" with value "<destinationLocation>"
    And destination credentials as "<destUsername>" and "<destPassword>"
	And overwrite is "<selected>"
	And use private public key for source is "<sourcePrivateKeyFile>"
	And use private public key for destination is "<destinationPrivateKeyFile>"
	And result as "<resultVar>"
    When the rename file tool is executed
	Then the result variable "<resultVar>" will be "<result>"
	And the execution has "<errorOccured>" error
	And the debug inputs as
         | Source Path                 | Username   | Password | Source Private Key File |Destination Path                      | Destination Username | Destination Password |Destination Private Key File | Overwrite  |
         | <source> = <sourceLocation> | <username> | String   | <sourcePrivateKeyFile>  |<destination> = <destinationLocation> | <destUsername>       | String               |<destinationPrivateKeyFile>  | <selected> |
	And the debug output as
		|                        |
		| <resultVar> = <result> |
	Examples: 
	| No | Name          | source         | sourceLocation                                                          | username          | password | destination  | destinationLocation                                                                          | destUsername  | destPassword | selected | resultVar  | result    | errorOccured | sourcePrivateKeyFile | destinationPrivateKeyFile |
	| 1  | FTPS to Local | [[sourcePath]] | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamefile0.txt | Administrator | Dev2@dmin123 | [[destPath]] | C:\renamed3.txt                                                                              | ""            | ""           | False    | [[result]] | "Success" | NO           |                      |                           |
	| 2  | FTPS to UNC   | [[sourcePath]] | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamefile1.txt | Administrator | Dev2@dmin123 | [[destPath]] | \\\\SVRDEV.premier.local\FileSystemShareTestingSite\FileRenameSharedTestingSite\renamed3.txt | ""            | ""           | False    | [[result]] | "Success" | NO           |                      |                           |
	| 3  | FTPS to FTPS  | [[sourcePath]] | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamefile2.txt | Administrator | Dev2@dmin123 | [[destPath]] | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed3.txt                         | Administrator | Dev2@dmin123 | False    | [[result]] | "Success" | NO           |                      |                           |
	| 4  | FTPS to SFTP  | [[sourcePath]] | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamefile3.txt | Administrator | Dev2@dmin123 | [[destPath]] | sftp://SVRDEV.premier.local/renamed3.txt                                                     | dev2          | Q/ulw&]      | False    | [[result]] | "Success" | NO           |                      |                           |
	| 5  | FTPS to FTP   | [[sourcePath]] | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamefile4.txt | Administrator | Dev2@dmin123 | [[destPath]] | ftp://DEVOPSPDC.premier.local:1001/FORFILERENAMETESTING/renamed3.txt                         | ""            | ""           | False    | [[result]] | "Success" | NO           |                      |                           |

@FileRenameFromSFTPWithoutOverwrite
@FileRenameFromSFTP
Scenario Outline: Rename file at SFTP location with overwrite disabled
	Given I have a source path "<source>" with value "<sourceLocation>" 
	And source credentials as "<username>" and "<password>"
	And I have a destination path "<destination>" with value "<destinationLocation>"
    And destination credentials as "<destUsername>" and "<destPassword>"
	And overwrite is "<selected>"
	And use private public key for source is "<sourcePrivateKeyFile>"
	And use private public key for destination is "<destinationPrivateKeyFile>"
	And result as "<resultVar>"
    When the rename file tool is executed
	Then the result variable "<resultVar>" will be "<result>"
	And the execution has "<errorOccured>" error
	And the debug inputs as
         | Source Path                 | Username   | Password | Source Private Key File |Destination Path                      | Destination Username | Destination Password |Destination Private Key File | Overwrite  |
         | <source> = <sourceLocation> | <username> | String   | <sourcePrivateKeyFile>  |<destination> = <destinationLocation> | <destUsername>       | String               |<destinationPrivateKeyFile>  | <selected> |
	And the debug output as
		|                        |
		| <resultVar> = <result> |
	Examples: 
	| No | Name            | source         | sourceLocation                               | username | password | destination  | destinationLocation                                                                          | destUsername  | destPassword | selected | resultVar  | result    | errorOccured | sourcePrivateKeyFile | destinationPrivateKeyFile |
	| 1  | SFTP to Local   | [[sourcePath]] | sftp://SVRDEV.premier.local/renamefile0.txt  | dev2     | Q/ulw&]  | [[destPath]] | C:\renamed4.txt                                                                              | ""            | ""           | False    | [[result]] | "Success" | NO           |                      |                           |
	| 2  | SFTP to UNC     | [[sourcePath]] | sftp://SVRDEV.premier.local/renamefile1.txt  | dev2     | Q/ulw&]  | [[destPath]] | \\\\SVRDEV.premier.local\FileSystemShareTestingSite\FileRenameSharedTestingSite\renamed4.txt | ""            | ""           | False    | [[result]] | "Success" | NO           |                      |                           |
	| 3  | SFTP to FTP     | [[sourcePath]] | sftp://SVRDEV.premier.local/renamefile2.txt  | dev2     | Q/ulw&]  | [[destPath]] | ftp://DEVOPSPDC.premier.local:1001/FORFILERENAMETESTING/renamed4.txt                         | ""            | ""           | False    | [[result]] | "Success" | NO           |                      |                           |
	| 4  | SFTP to FTPS    | [[sourcePath]] | sftp://SVRDEV.premier.local/renamefile3.txt  | dev2     | Q/ulw&]  | [[destPath]] | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed4.txt                         | Administrator | Dev2@dmin123 | False    | [[result]] | "Success" | NO           |                      |                           |
	| 5  | SFTP to SFTP    | [[sourcePath]] | sftp://SVRDEV.premier.local/renamefile4.txt  | dev2     | Q/ulw&]  | [[destPath]] | sftp://SVRDEV.premier.local/renamed4.txt                                                     | dev2          | Q/ulw&]      | False    | [[result]] | "Success" | NO           |                      |                           |
	| 6  | SFTP to SFTP PK | [[sourcePath]] | sftp://SVRDEV.premier.local/renamefile41.txt | dev2     | Q/ulw&]  | [[destPath]] | sftp://SVRDEV.premier.local/renamed41.txt                                                    | dev2          | Q/ulw&]      | False    | [[result]] | "Success" | NO           | C:\\Temp\\key.opk    | C:\\Temp\\key.opk         |

@FileAndFolderRename
Scenario Outline: Rename file validation
    Given I have a variable "[[a]]" with a value "<Val1>"
	Given I have a variable "[[b]]" with a value "<Val2>"
	Given I have a variable "[[rec(1).a]]" with a value "<Val1>"
	Given I have a variable "[[rec(2).a]]" with a value "<Val2>"
	Given I have a variable "[[index]]" with a value "1"
	Given I have a source path "<File or Folder>" with value "<sourceLocation>" 
	And source credentials as "<username>" and "<password>"
	And use private public key for source is "C:\\Temp\\key.opk"
	And use private public key for destination is "C:\\Temp\\key.opk"
	And I have a destination path "<destination>" with value "<destinationLocation>"
    And destination credentials as "<destUsername>" and "<destPassword>"
	And overwrite is "<selected>"
	And result as "<resultVar>"
	When validating the rename tool
	Then validation is "<ValidationResult>"
	And validation message is "<DesignValidation>"
    When the rename file tool is executed
	Then the result variable "<resultVar>" will be "<result>"
	And the execution has "<errorOccured>" error	
	Examples: 
		| No | File or Folder                 | Val1                                                          | Val2                                    | sourceLocation      | username              | password | destination                                                | destinationLocation                                                                   | destUsername      | destPassword | selected | resultVar              | result    | errorOccured | ValidationResult | DesignValidation                                                                          | OutputError                                                                           |
		| No | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile5.txt  | ""                    | ""       | [[destPath]]                                               | C:\renamed6.txt                                                                       | ""                | ""           | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 4  | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile6.txt  | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1001/FORFILERENAMETESTING/renamed7.txt                             | ""                | ""           | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 5  | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile7.txt  | ""                    | ""       | [[destPath]]                                               | C:\renamed6.txt                                                                       | ""                | ""           | Truee    | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 1  | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile8.txt  | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1001/FORFILERENAMETESTING/renamed8.txt                             | ""                | ""           | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 2  | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile9.txt  | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed9.txt                             | Administrator | Dev2@dmin123     | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 3  | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile10.txt | ""                    | ""       | [[destPath]]                                               | C:\renamed6.txt                                                                       | ""                | ""           | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 6  | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile11.txt | ""                    | ""       | [[destPath]]                                               | C:\renamed6.txt                                                                       | ""                | ""           | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 7  | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile12.txt | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1001/FORFILERENAMETESTING/renamed10.txt                            | ""                | ""           | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 8  | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile13.txt | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed11.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 9  | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile14.txt | ""                    | ""       | [[destPath]]                                               | sftp://SVRDEV.premier.local/renamed12.txt                                                | dev2              | Q/ulw&]      | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 10 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile15.txt | ""                    | ""       | [[destPath]]                                               | C:\renamed8.txt                                                                       | ""                | ""           | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 11 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile16.txt | ""                    | ""       | [[destPath]]                                               | \\\\SVRDEV.premier.local\FileSystemShareTestingSite\FileRenameSharedTestingSite\renamed13.txt | ""                | ""           | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 12 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile17.txt | ""                    | ""       | [[destPath]]                                               | C:\renamed9.txt                                                                       | ""                | ""           | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 13 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile18.txt | ""                    | ""       | [[destPath]]                                               | \\\\SVRDEV.premier.local\FileSystemShareTestingSite\FileRenameSharedTestingSite\renamed14.txt | ""                | ""           | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 14 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile19.txt | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed11.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 15 | [[a]][[b]]                     | c:\rename                                                     | file20.txt                              | C:\renamefile20.txt | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed12.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 16 | [[a]]\[[b]]                    | c:                                                            | renamefile21.txt                        | C:\renamefile21.txt | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed13.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 17 | [[a]][[b]].txt                 | c:\rename                                                     | file22                                  | C:\renamefile22.txt | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed14.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 18 | [[a]]:[[b]]                    | c                                                             | \renamefile23.txt                       | C:\renamefile23.txt | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed15.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 19 | C:[[a]][[b]].txt               | \rename                                                       | file24                                  | C:\renamefile24.txt | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed16.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 20 | [[rec(1).a]][[rec(2).a]]       | c:\rename                                                     | file25.txt                              | C:\renamefile25.txt | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed17.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 21 | [[rec(1).a]]\[[rec(2).a]]      | c:                                                            | renamefile26.txt                        | C:\renamefile26.txt | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed18.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 22 | [[rec(1).a]][[rec(2).a]].txt   | c:\rename                                                     | file27                                  | C:\renamefile27.txt | ""                    | ""       | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed19.txt | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed19.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 23 | [[rec(1).a]]:[[rec(2).a]]      | c                                                             | \renamefile28.txt                       | C:\renamefile28.txt | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed20.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 24 | C:[[rec(1).a]][[rec(2).a]].txt | \rename                                                       | file29                                  | C:\renamefile29.txt | ""                    | ""       | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed21.txt | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed21.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 25 | [[a]]                          | C:\copyfile0.txt                                              | ""                                      | C:\renamefile30.txt | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed22.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 26 | [[rec([[index]]).a]]           | c:\renamefile31.txt                                           | ""                                      | C:\renamefile31.txt | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed23.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 27 | [[a]]                          | C:\copyfile0.txt                                              | ""                                      | C:\renamefile32.txt | ""                    | ""       | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed24.txt | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed24.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 28 | [[sourcePath]]                 | ftp://DEVOPSPDC.premier.local:1002                                       | /FORFILERENAMETESTING/renamed25.txt     | C:\renamefile33.txt | ""                    | ""       | [[a]][[b]]                                                 | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed25.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 29 | [[sourcePath]]                 | ftp://DEVOPSPDC.premier.local:1002/FORRENAMETESTING                      | FORTESTING/renamed26.txt                | C:\renamefile34.txt | ""                    | ""       | [[a]]/[[b]]                                                | ftp://DEVOPSPDC.premier.local:1002/FORRENAMETESTING/renamed26.txt                                | Administrator | Dev2@dmin123     | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 30 | [[sourcePath]]                 | ftp://DEVOPSPDC.premier.local:1002/                                      | /FORFILERENAMETESTING/renamed27.txt     | C:\renamefile35.txt | ""                    | ""       | [[a]][[b]].txt                                             | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed27.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 31 | [[sourcePath]]                 | ftp://DEVOPSPDC.premier.local                                            | 1002/FORFILERENAMETESTING/renamed28.txt | C:\renamefile36.txt | ""                    | ""       | [[a]]:[[b]]                                                | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed28.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 32 | [[sourcePath]]                 | //DEVOPSPDC.premier.local:1002/                                          | FORTESTING/renamed29.txt                | C:\renamefile37.txt | ""                    | ""       | ftp:[[a]][[b]].txt                                         | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed29.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 33 | [[sourcePath]]                 | ftp://DEVOPSPDC.premier.local:1002/                                      | FORTESTING/renamed30.txt                | C:\renamefile38.txt | ""                    | ""       | [[rec(1).a]][[rec(2).a]]                                   | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed30.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 34 | [[sourcePath]]                 | ftp://DEVOPSPDC.premier.local:1002/FORRENAMETESTING                      | /renamed31.txt                          | C:\renamefile39.txt | ""                    | ""       | [[rec(1).a]]/[[rec(2).a]]                                  | ftp://DEVOPSPDC.premier.local:1002/FORRENAMETESTING/renamed31.txt                                | Administrator | Dev2@dmin123     | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 35 | [[sourcePath]]                 | ftp://DEVOPSPDC.premier.local:1002                                       | /FORFILERENAMETESTING/renamed32         | C:\renamefile40.txt | ""                    | ""       | [[rec(1).a]][[rec(2).a]].txt                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed32.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 36 | [[sourcePath]]                 | ftp://DEVOPSPDC.premier.local:1002/FORRENAMETESTING/                     | renamed33.txt                           | C:\renamefile41.txt | ""                    | ""       | ftp://DEVOPSPDC.premier.local:1002/FORRENAMETESTING/renamed33.txt     | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed33.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 37 | [[sourcePath]]                 | //DEVOPSPDC.premier.local:1002/                                          | FORTESTING/renamed34                    | C:\renamefile42.txt | ""                    | ""       | ftp:[[rec(1).a]][[rec(2).a]].txt                           | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed34.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 38 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile43.txt | ""                    | ""       | C:\copyfile0.txt                                           | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed35.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | ""        | AN           | False            | Failed to authenticate with user [ Administrator ] for resource [ C:\\copyfile0.txt ] | ""                                                                                    |
		| 39 | [[sourcePath]]                 | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed36.txt    | ""                                      | C:\renamefile44.txt | ""                    | ""       | [[rec([[index]]).a]]                                       | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed36.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 40 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile45.txt | ""                    | ""       | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed37.txt | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed37.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | "Success" | NO           | False            | ""                                                                                        | ""                                                                                    |
		| 41 | [[a&]]                         | ""                                                            | ""                                      | C                   | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed38.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | ""        | AN           | True             | File or Folder - Variable name [[a&]] contains invalid character(s)                       | 1.File or Folder - Variable name [[a&]] contains invalid character(s)                 |
		| 42 | [[rec(**).a]]                  | ""                                                            | ""                                      | C                   | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed39.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | ""        | AN           | True             | File or Folder - Recordset index (**) contains invalid character(s)                       | 1.File or Folder - Recordset index (**) contains invalid character(s)                 |
		| 43 | [[a]                           | ""                                                            | ""                                      | C                   | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed40.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | ""        | AN           | True             | File or Folder - Invalid expression: opening and closing brackets don"t match             | 1.File or Folder - Invalid expression: opening and closing brackets don"t match       |
		| 44 | [[rec(a]]                      | ""                                                            | ""                                      | C                   | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed41.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | ""        | AN           | True             | File or Folder - Recordset name [[rec(a]] contains invalid character(s)                   | 1.File or Folder - Recordset name [[rec(a]] contains invalid character(s)             |
		| 45 | c(*()                          | ""                                                            | ""                                      | C                   | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed42.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | ""        | AN           | True             | Please supply a valid File or Folder                                                      | 1.Please supply a valid File or Folder                                                |
		| 46 | [[rec([[inde$x]]).a]]          | ""                                                            | ""                                      | C                   | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed43.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | ""        | AN           | True             | File or Folder - Variable name [[inde$x]]  contains invalid character(s)                  | 1.File or Folder - Variable name [[inde$x]]  contains invalid character(s)            |
		| 47 | ghjghj                         | ""                                                            | ""                                      | C                   | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed44.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | ""        | AN           | True             | Please supply a valid File or Folder                                                      | 1.Please supply a valid File or Folder                                                |
		| 48 | ""                             | ""                                                            | ""                                      | C                   | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed45.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | ""        | AN           | True             | File or Folder cannot be empty or only white space                                        | 1.File or Folder cannot be empty or only white space                                  |
		| 49 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile46.txt | ""                    | ""       | [[a&]]                                                     | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed46.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | ""        | AN           | True             | Destination - Variable name [[a&]] contains invalid character(s)                          | 1.Destination - Variable name [[a&]] contains invalid character(s)                    |
		| 50 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile47.txt | ""                    | ""       | [[rec(**).a]]                                              | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed47.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | ""        | AN           | True             | Destination - Recordset index (**) contains invalid character(s)                          | 1.Destination - Recordset index (**) contains invalid character(s)                    |
		| 51 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile48.txt | ""                    | ""       | [[a]                                                       | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed48.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | ""        | AN           | True             | Destination - Invalid expression: opening and closing brackets don"t match                | 1.Destination - Invalid expression: opening and closing brackets don"t match          |
		| 52 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile49.txt | ""                    | ""       | [[rec(a]]                                                  | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed49.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | ""        | AN           | True             | Destination - Recordset name [[rec(a]] contains invalid character(s)                      | 1.Destination - Recordset name [[rec(a]] contains invalid character(s)                |
		| 53 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile50.txt | ""                    | ""       | c(*()                                                      | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed50.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | ""        | AN           | True             | Please supply a valid File or Folder                                                      | 1.Please supply a valid File or Folder                                                |
		| 54 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile51.txt | ""                    | ""       | [[rec([[inde$x]]).a]]                                      | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed51.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | ""        | AN           | True             | Destination - Variable name [[inde$x]]  contains invalid character(s)                     | 1.Destination - Variable name [[inde$x]]  contains invalid character(s)               |
		| 55 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile52.txt | ""                    | ""       | ghjghj                                                     | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed52.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | ""        | AN           | True             | Please supply a valid File or Folder                                                      | 1.Please supply a valid File or Folder                                                |
		| 56 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile53.txt | ""                    | ""       | ""                                                         | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed53.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | ""        | AN           | True             | Destination cannot be empty or only white space                                           | 1.Destination cannot be empty or only white space                                     |
		| 57 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile54.txt | [[a&]]                | String   | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed54.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | ""        | AN           | True             | Username - Variable name [[a&]] contains invalid character(s)                             | 1.Username - Variable name [[a&]] contains invalid character(s)                       |
		| 58 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile55.txt | [[rec(**).a]]         | String   | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed55.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | ""        | AN           | True             | Username - Recordset index (**) contains invalid character(s)                             | 1.Username - Recordset index (**) contains invalid character(s)                       |
		| 59 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile56.txt | [[a]                  | String   | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed56.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | ""        | AN           | True             | Username - Invalid expression: opening and closing brackets don"t match                   | 1.Username - Invalid expression: opening and closing brackets don"t match             |
		| 60 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile57.txt | [[rec(a]]             | String   | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed57.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | ""        | AN           | True             | Username - Recordset name [[rec(a]] contains invalid character(s)                         | 1.Username - Recordset name [[rec(a]] contains invalid character(s)                   |
		| 61 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile58.txt | [[rec([[inde$x]]).a]] | String   | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed58.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | ""        | AN           | True             | Username - Variable name [[inde$x]]  contains invalid character(s)                        | 1.Username - Variable name [[inde$x]]  contains invalid character(s)                  |
		| 62 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile59.txt |                       | String   | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed59.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | ""        | AN           | True             | Username cannot be empty or only white space                                              | 1.Username cannot be empty or only white space                                        |
		| 63 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile50.txt | [[a&]]                | String   | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed60.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | ""        | AN           | True             | Username - Variable name [[a&]] contains invalid character(s)                             | 1.Destination Username - Variable name [[a&]] contains invalid character(s)           |
		| 64 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile61.txt | [[rec(**).a]]         | String   | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed61.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | ""        | AN           | True             | Username - Recordset index (**) contains invalid character(s)                             | 1.Destination Username - Recordset index (**) contains invalid character(s)           |
		| 65 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile62.txt | [[a]                  | String   | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed62.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | ""        | AN           | True             | Username - Invalid expression: opening and closing brackets don"t match                   | 1.Destination Username - Invalid expression: opening and closing brackets don"t match |
		| 66 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile63.txt | [[rec(a]]             | String   | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed63.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | ""        | AN           | True             | Username - Recordset name [[rec(a]] contains invalid character(s)                         | 1.Destination Username - Recordset name [[rec(a]] contains invalid character(s)       |
		| 67 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile64.txt | [[rec([[inde$x]]).a]] | String   | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed64.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | ""        | AN           | True             | Username - Variable name [[inde$x]]  contains invalid character(s)                        | 1.Destination Username - Variable name [[inde$x]]  contains invalid character(s)      |
		| 68 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile65.txt | ""                    | String   | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed65.txt                            | Administrator | Dev2@dmin123     | True     | [[result]]             | ""        | AN           | True             | Username cannot be empty or only white space                                              | 1.Destination Username cannot be empty or only white space                            |
		| 69 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile66.txt | [[a&]]                | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed66.txt                            | Administrator | Dev2@dmin123     | True     | [[result]][[a]]        | ""        | AN           | True             | The result field only allows a single result                                              | 1.The result field only allows a single result                                        |
		| 70 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile67.txt | [[a]]*]]              | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed67.txt                            | Administrator | Dev2@dmin123     | True     | [[a]]*]]               | ""        | AN           | True             | Result - Invalid expression: opening and closing brackets don"t match                     | 1.Result - Invalid expression: opening and closing brackets don"t match               |
		| 71 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile68.txt | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed68.txt                            | Administrator | Dev2@dmin123     | True     | [[var@]]               | ""        | AN           | True             | Result - Variable name [[var@]] contains invalid character(s)                             | 1.Result - Variable name [[var@]] contains invalid character(s)                       |
		| 72 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile69.txt | [[var]]00]]           | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed69.txt                            | Administrator | Dev2@dmin123     | True     | [[var]]00]]            | ""        | AN           | True             | Result - Invalid expression: opening and closing brackets don"t match                     | 1.Result - Invalid expression: opening and closing brackets don"t match               |
		| 73 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile70.txt | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed70.txt                            | Administrator | Dev2@dmin123     | True     | [[var@]]               | ""        | AN           | True             | Result - Variable name [[1var]] contains invalid character(s)                             | 1.Result - Variable name [[1var]] contains invalid character(s)                       |
		| 74 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile71.txt | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed71.txt                            | Administrator | Dev2@dmin123     | True     | [[var[[a]]]]           | ""        | AN           | True             | Result - Invalid Region [[var[[a]]]]                                                      | 1.Result - Invalid Region [[var[[a]]]]                                                |
		| 75 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile72.txt | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed72.txt                            | Administrator | Dev2@dmin123     | True     | [[var.a]]              | ""        | AN           | True             | Result - Variable name [[var.a]]contains invalid character(s)                             | 1.Result - Variable name [[var.a]] contains invalid character(s)                      |
		| 76 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile73.txt | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed73.txt                            | Administrator | Dev2@dmin123     | True     | [[#var]]               | ""        | AN           | True             | Result - Variable name [[@var]] contains invalid character(s)                             | 1.Result - Variable name [[@var]] contains invalid character(s)                       |
		| 77 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile74.txt | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed74.txt                            | Administrator | Dev2@dmin123     | True     | [[var 1]]              | ""        | AN           | True             | Result - Variable name [[var 1]] contains invalid character(s)                            | 1.Result - Variable name [[var 1]] contains invalid character(s)                      |
		| 78 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile75.txt | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed75.txt                            | Administrator | Dev2@dmin123     | True     | [[rec(1).[[rec().1]]]] | ""        | AN           | True             | Result - Invalid Region [[rec(1).[[rec().1]]]]                                            | 1.Result - Invalid Region [[rec(1).[[rec().1]]]]                                      |
		| 79 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile76.txt | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed76.txt                            | Administrator | Dev2@dmin123     | True     | [[rec(@).a]]           | ""        | AN           | True             | Result - Recordset index [[@]] contains invalid character(s)                              | 1.Result - Recordset index [[@]] contains invalid character(s)                        |
		| 80 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile77.txt | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed77.txt                            | Administrator | Dev2@dmin123     | True     | [[rec"()".a]]          | ""        | AN           | True             | Result - Recordset name [[rec"()"]] contains invalid character(s)                         | 1.Result - Recordset name [[rec"()"]] contains invalid character(s)                   |
		| 81 | [[sourcePath]]                 | ""                                                            | ""                                      | C:\renamefile78.txt | ""                    | ""       | [[destPath]]                                               | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed78.txt                            | Administrator | Dev2@dmin123     | True     | [[rec([[[[b]]]]).a]]   | ""        | AN           | True             | Result - Invalid Region [[rec([[[[b]]]]).a]]                                              | 1.Result - Invalid Region [[rec([[[[b]]]]).a]]                                        |
	
@FileAndFolderRename
Scenario Outline: Rename file at location with invalid directories
	Given I have a source path "<source>" with value "<sourceLocation>" 
	And source credentials as "<username>" and "<password>"
	And I have a destination path "<destination>" with value "<destinationLocation>"
    And destination credentials as "<destUsername>" and "<destPassword>"
	And overwrite is "<selected>"
	And result as "<resultVar>"
    When the rename file tool is executed
	Then the result variable "<resultVar>" will be "<result>"
	And the execution has "AN" error
	And the debug inputs as
         | Source Path                 | Username   | Password | Destination Path                      | Destination Username | Destination Password | Overwrite  |
         | <source> = <sourceLocation> | <username> | String   | <destination> = <destinationLocation> | <destUsername>       | String               | <selected> |
	And the debug output as
		|                        |
		| <resultVar> = <result> |
	Examples: 
	| No | Name           | source       | sourceLocation | username | password | destination  | destinationLocation                                       | destUsername      | destPassword | selected | resultVar  | result | 
	| 1  | Local to Local | [[var]]      | ""             | ""       | ""       | [[destPath]] | C:\renamed0.txt                                           | ""                | ""           | True     | [[result]] |        | 
	| 2  | Local to FTP   | [[variable]] |                | ""       | ""       | [[destPath]] | ftp://DEVOPSPDC.premier.local:1001/FORFILERENAMETESTING/renamed0.txt | ""                | ""           | True     | [[result]] |        | 
	| 3  | Local to FTPS  | 445544       | 445544         | ""       | ""       | [[destPath]] | ftp://DEVOPSPDC.premier.local:1002/FORFILERENAMETESTING/renamed0.txt | Administrator | Dev2@dmin123     | True     | [[result]] |        | 
	| 4  | Local to Local | [[var]]      | E:\tr.txt      | ""       | ""       | [[local]]    |                                                           | ""                | ""           | True     | [[result]] |        | 
	| 5  | Local to FTP   | [[variable]] | E:\tr.txt      | ""       | ""       | [[v]]        | ""                                                        | ""                | ""           | True     | [[result]] |        | 
	| 6  | Local to FTPS  | [[path]]     | E:\test.txt    | ""       | ""       | 5453         | 5453                                                      | Administrator | Dev2@dmin123     | True     | [[result]] |        | 


















