@fileFeature
Feature: Unzip
	In order to be able to Unzip File or Folder 
	as a Warewolf user
	I want a tool that will Unzip File(s) or Folder(s) at a given location
	
Scenario Outline: Unzip file at location
	Given I have a source path '<source>' with value '<sourceLocation>'
	And zip credentials as '<username>' and '<password>'
	And I have a destination path '<destination>' with value '<destinationLocation>'
	And destination credentials as '<destUsername>' and '<destPassword>'
	And overwrite is '<selected>'
	And result as '<resultVar>'	
	And Archive Password as '<archivepassword>'
    When the Unzip file tool is executed
	Then the result variable '<resultVar>' will be '<result>'
	And the execution has "<errorOccured>" error
	And the debug inputs as
         | Source Path                 | Username   | Password | Destination Path                      | Destination Username | Destination Password | Overwrite  | Archive Password |
         | <source> = <sourceLocation> | <username> | String   | <destination> = <destinationLocation> | <destUsername>       | String               | <selected> | String           |         
	And the debug output as
		|                        |
		| <resultVar> = <result> |
	Examples: 
	| No | Name           | source   | sourceLocation                                           | username          | password | destination | destinationLocation                                 | destUsername      | destPassword | selected | archivepassword | resultVar  | result  | errorOccured |
	| 1  | Local to Local | [[path]] | c:\test0.zip                                             | ""                | ""       | [[path1]]   | c:\ZIP0                                             | ""                | ""           | True     | ""              | [[result]] | Success | NO           |
	| 2  | UNC to Local   | [[path]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\test0.zip | ""                | ""       | [[path1]]   | c:\ZIP1                                             | ""                | ""           | True     | ""              | [[result]] | Success | NO           |
	| 3  | FTP to Local   | [[path]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/test0.zip          | ""                | ""       | [[path1]]   | c:\ZIP2                                             | ""                | ""           | True     | ""              | [[result]] | Success | NO           |
	| 4  | FTPS to Local  | [[path]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/test0.zip          | integrationtester | I73573r0 | [[path1]]   | c:\ZIP3                                             | ""                | ""           | True     | ""              | [[result]] | Success | NO           |
	| 5  | SFTP to Local  | [[path]] | sftp://localhost/test0.zip                               | dev2              | Q/ulw&]  | [[path1]]   | c:\ZIP4                                             | ""                | ""           | True     | ""              | [[result]] | Success | NO           |
	| 6  | Local to UNC   | [[path]] | c:\test1.zip                                             | ""                | ""       | [[path1]]   | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\ZIP0 | ""                | ""           | True     | ""              | [[result]] | Success | NO           |
	| 7  | UNC to UNC     | [[path]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\test1.zip | ""                | ""       | [[path1]]   | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\ZIP1 | ""                | ""           | True     | ""              | [[result]] | Success | NO           |
	| 8  | FTP to UNC     | [[path]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/test1.zip          | ""                | ""       | [[path1]]   | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\ZIP2 | ""                | ""           | True     | ""              | [[result]] | Success | NO           |
	| 9  | FTPS to UNC    | [[path]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/test1.zip          | integrationtester | I73573r0 | [[path1]]   | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\ZIP3 | ""                | ""           | True     | ""              | [[result]] | Success | NO           |
	| 10 | SFTP to UNC    | [[path]] | sftp://localhost/test1.zip                               | dev2              | Q/ulw&]  | [[path1]]   | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\ZIP4 | ""                | ""           | True     | ""              | [[result]] | Success | NO           |
	| 11 | Local to FTP   | [[path]] | c:\test2.zip                                             | ""                | ""       | [[path1]]   | ftp://rsaklfsvrsbspdc:1001/FORTESTING/ZIP0          | ""                | ""           | True     | ""              | [[result]] | Success | NO           |
	| 12 | UNC to FTP     | [[path]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\test2.zip | ""                | ""       | [[path1]]   | ftp://rsaklfsvrsbspdc:1001/FORTESTING/ZIP1          | ""                | ""           | True     | ""              | [[result]] | Success | NO           |
	| 13 | FTP to FTP     | [[path]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/test2.zip          | ""                | ""       | [[path1]]   | ftp://rsaklfsvrsbspdc:1001/FORTESTING/ZIP2          | ""                | ""           | True     | ""              | [[result]] | Success | NO           |
	| 14 | FTPS to FTP    | [[path]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/test2.zip          | integrationtester | I73573r0 | [[path1]]   | ftp://rsaklfsvrsbspdc:1001/FORTESTING/ZIP3          | ""                | ""           | True     | ""              | [[result]] | Success | NO           |
	| 15 | SFTP to FTP    | [[path]] | sftp://localhost/test2.zip                               | dev2              | Q/ulw&]  | [[path1]]   | ftp://rsaklfsvrsbspdc:1001/FORTESTING/ZIP4          | ""                | ""           | True     | ""              | [[result]] | Success | NO           |
	| 16 | Local to FTPS  | [[path]] | c:\test3.zip                                             | ""                | ""       | [[path1]]   | ftp://rsaklfsvrsbspdc:1002/FORTESTING/ZIP0          | integrationtester | I73573r0     | True     | ""              | [[result]] | Success | NO           |
	| 17 | UNC to FTPS    | [[path]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\test3.zip | ""                | ""       | [[path1]]   | ftp://rsaklfsvrsbspdc:1002/FORTESTING/ZIP1          | integrationtester | I73573r0     | True     | ""              | [[result]] | Success | NO           |
	| 18 | FTP tp FTPS    | [[path]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/test3.zip          | ""                | ""       | [[path1]]   | ftp://rsaklfsvrsbspdc:1002/FORTESTING/ZIP2          | integrationtester | I73573r0     | True     | ""              | [[result]] | Success | NO           |
	| 19 | FTPS to FTPS   | [[path]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/test3.zip          | integrationtester | I73573r0 | [[path1]]   | ftp://rsaklfsvrsbspdc:1002/FORTESTING/ZIP3          | integrationtester | I73573r0     | True     | ""              | [[result]] | Success | NO           |
	| 20 | SFTP to FTPS   | [[path]] | sftp://localhost/test3.zip                               | dev2              | Q/ulw&]  | [[path1]]   | ftp://rsaklfsvrsbspdc:1002/FORTESTING/ZIP4          | integrationtester | I73573r0     | True     | ""              | [[result]] | Success | NO           |
	| 21 | Local to SFTP  | [[path]] | c:\test4.zip                                             | ""                | ""       | [[path1]]   | sftp://localhost/ZIP0                               | dev2              | Q/ulw&]      | True     | ""              | [[result]] | Success | NO           |
	| 22 | UNC to SFTP    | [[path]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\test4.zip | ""                | ""       | [[path1]]   | sftp://localhost/ZIP1                               | dev2              | Q/ulw&]      | True     | ""              | [[result]] | Success | NO           |
	| 23 | FTP to SFTP    | [[path]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/test4.zip          | ""                | ""       | [[path1]]   | sftp://localhost/ZIP2                               | dev2              | Q/ulw&]      | True     | ""              | [[result]] | Success | NO           |
	| 24 | FTPS to SFTP   | [[path]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/test4.zip          | integrationtester | I73573r0 | [[path1]]   | sftp://localhost/ZIP3                               | dev2              | Q/ulw&]      | True     | ""              | [[result]] | Success | NO           |
	| 25 | SFTP to SFTP   | [[path]] | sftp://localhost/test5.zip                               | dev2              | Q/ulw&]  | [[path1]]   | sftp://localhost/ZIP6                                | dev2              | Q/ulw&]      | True     | ""              | [[result]] | Success | NO           |



#Scenario Outline: Unzip file at location1
#	Given I have a source path '<File or Folder>' with value '<sourceLocation>' 
#	And zip credentials as '<username>' and '<password>'
#	And I have a destination path '<destination>' with value '<destinationLocation>'
#    And destination credentials as '<destUsername>' and '<destPassword>'
#	And overwrite is '<selected>'
#	And result as '<resultVar>'
#	And Archive Password as '<archivepassword>'
#	When validating the tool
#	Then validation is '<ValidationResult>'
#	And validation message is '<DesignValidation>'
#    When the Unzip file tool is executed
#	Then the result variable '<resultVar>' will be '<result>'
#	And the execution has "<errorOccured>" error
#	And execution error message will be '<DesignValidation>'
#	And the debug inputs as
#        | Source Path                         | Username   | Password | Destination Path                      | Destination Username | Destination Password | Overwrite  |
#        | <File or FOlder> = <sourceLocation> | <username> | String   | <destination> = <destinationLocation> | <destUsername>       | String               | <selected> |
#	And the debug output as
#		|                        |
#		| <resultVar> = <result> |
#	Examples: 
#		| No | File or Folder                  | sourceLocation    | username              | password | destination                     | destinationLocation | destUsername      | destPassword | selected | resultVar              | archivepassword | result  | errorOccured | ValidationResult | DesignValidation                                                              | OutputError                                                                           |
#		| No | [[sourcePath]]                  | c:\test7.zip      | ""                    | ""       | [[destPath]]                    | c:\ZIP9             | dev2              | Q/ulw&]      | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 4  | [[sourcePath]]                  | c:\test10.zip     | ""                    | ""       | [[destPath]]                    | c:\ZIP10            | ""                | ""           | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 5  | [[sourcePath]]                  | c:\test11.zip     | ""                    | ""       | [[destPath]]                    | c:\ZIP11            | ""                | ""           | Truee    | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 1  | [[sourcePath]]                  | c:\test12.zip     | ""                    | ""       | [[destPath]]                    | c:\ZIP12            | ""                | ""           | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 2  | [[sourcePath]]                  | c:\test13.zip     | ""                    | ""       | [[destPath]]                    | c:\ZIP13            | integrationtester | I73573r0     | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 3  | [[sourcePath]]                  | c:\test14.zip     | ""                    | ""       | [[destPath]]                    | c:\ZIP14            | ""                | ""           | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 6  | [[sourcePath]]                  | c:\test15.zip     | ""                    | ""       | [[destPath]]                    | c:\ZIP15            | ""                | ""           | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 7  | [[sourcePath]]                  | c:\test16.zip     | ""                    | ""       | [[destPath]]                    | c:\ZIP16            | ""                | ""           | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 8  | [[sourcePath]]                  | c:\test17.zip     | ""                    | ""       | [[destPath]]                    | c:\ZIP17            | integrationtester | I73573r0     | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 9  | [[sourcePath]]                  | c:\test18.zip     | ""                    | ""       | [[destPath]]                    | c:\ZIP18            | dev2              | Q/ulw&]      | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 10 | [[sourcePath]]                  | c:\test19.zip     | ""                    | ""       | [[destPath]]                    | c:\ZIP19            | ""                | ""           | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 11 | [[sourcePath]]                  | c:\test20.zip     | ""                    | ""       | [[destPath]]                    | c:\ZIP20            | ""                | ""           | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 12 | [[sourcePath]]                  | c:\test21.zip     | ""                    | ""       | [[destPath]]                    | c:\ZIP21            | ""                | ""           | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 13 | [[sourcePath]]                  | c:\test22.zip     | ""                    | ""       | [[destPath]]                    | c:\ZIP22            | ""                | ""           | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 14 | [[sourcePath]]                  | c:\test23.zip     | ""                    | ""       | [[destPath]]                    | c:\ZIP23            | integrationtester | I73573r0     | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 15 | [[a]][[b]]                      | c:\test24.zip     | ""                    | ""       | [[destPath]]                    | c:\ZIP24            | integrationtester | I73573r0     | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 16 | [[a]]\[[b]]                     | c:\test25.zip     | ""                    | ""       | [[destPath]]                    | c:\ZIP25            | integrationtester | I73573r0     | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 17 | [[a]][[b]].txt                  | c:\test26.zip     | ""                    | ""       | [[destPath]]                    | c:\ZIP26            | integrationtester | I73573r0     | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 18 | [[a]]:[[b]]                     | c:\test27.zip     | ""                    | ""       | [[destPath]]                    | c:\ZIP27            | integrationtester | I73573r0     | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 19 | C:[[a]][[b]].txt                | c:\test28.zip     | ""                    | ""       | [[destPath]]                    | c:\ZIP28            | integrationtester | I73573r0     | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 20 | [[rec(1).a]][[rec(2).a]]        | c:\test29.zip     | ""                    | ""       | [[destPath]]                    | c:\ZIP29            | integrationtester | I73573r0     | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 21 | [[rec(1).a]]\[[rec(2).a]]       | c:\test30.zip     | ""                    | ""       | [[destPath]]                    | c:\ZIP30            | integrationtester | I73573r0     | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 22 | [[rec(1).a]][[rec(2).a]] .txt   | c:\test31.zip     | ""                    | ""       | [[destPath]]                    | c:\ZIP31            | integrationtester | I73573r0     | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 23 | [[rec(1).a]]:[[rec(2).a]]       | c:\test32.zip     | ""                    | ""       | [[destPath]]                    | c:\ZIP32            | integrationtester | I73573r0     | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 24 | C:[[rec(1).a]][[rec(2).a]] .txt | c:\test33.zip     | ""                    | ""       | [[destPath]]                    | c:\ZIP33            | integrationtester | I73573r0     | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 25 | c:\copyfile0.txt                | c:\test34.zip     | ""                    | ""       | [[destPath]]                    | c:\ZIP34            | integrationtester | I73573r0     | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 26 | [[rec([[index]]).a]]            | c:\test35.zip     | ""                    | ""       | [[destPath]]                    | c:\ZIP35            | integrationtester | I73573r0     | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 27 | c:\copyfile0.txt                | c:\test36.zip     | ""                    | ""       | [[destPath]]                    | c:\ZIP36            | integrationtester | I73573r0     | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 28 | [[sourcePath]]                  | c:\test37.zip     | ""                    | ""       | [[a]][[b]]                      | c:\ZIP37            | integrationtester | I73573r0     | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 29 | [[sourcePath]]                  | c:\test38.zip     | ""                    | ""       | [[a]]\[[b]]                     | c:\ZIP38            | integrationtester | I73573r0     | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 30 | [[sourcePath]]                  | c:\test39.zip     | ""                    | ""       | [[a]][[b]].txt                  | c:\ZIP39            | integrationtester | I73573r0     | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 31 | [[sourcePath]]                  | c:\test40.zip     | ""                    | ""       | [[a]]:[[b]]                     | c:\ZIP40            | integrationtester | I73573r0     | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 32 | [[sourcePath]]                  | c:\test41.zip     | ""                    | ""       | C:[[a]][[b]].txt                | c:\ZIP41            | integrationtester | I73573r0     | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 33 | [[sourcePath]]                  | c:\test42.zip     | ""                    | ""       | [[rec(1).a]][[rec(2).a]]        | c:\ZIP42            | integrationtester | I73573r0     | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 34 | [[sourcePath]]                  | c:\test43.zip     | ""                    | ""       | [[rec(1).a]]\[[rec(2).a]]       | c:\ZIP43            | integrationtester | I73573r0     | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 35 | [[sourcePath]]                  | c:\test44.zip     | ""                    | ""       | [[rec(1).a]][[rec(2).a]] .txt   | c:\ZIP44            | integrationtester | I73573r0     | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 36 | [[sourcePath]]                  | c:\test45.zip     | ""                    | ""       | [[rec(1).a]]:[[rec(2).a]]       | c:\ZIP45            | integrationtester | I73573r0     | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 37 | [[sourcePath]]                  | c:\test46.zip     | ""                    | ""       | C:[[rec(1).a]][[rec(2).a]] .txt | c:\ZIP46            | integrationtester | I73573r0     | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 38 | [[sourcePath]]                  | c:\test47.zip     | ""                    | ""       | c:\copyfile0.txt                | c:\ZIP47            | integrationtester | I73573r0     | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 39 | [[sourcePath]]                  | c:\test48.zip     | ""                    | ""       | [[rec([[index]]).a]]            | c:\ZIP48            | integrationtester | I73573r0     | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 40 | [[sourcePath]]                  | c:\test49.zip     | ""                    | ""       | c:\copyfile0.txt                | c:\ZIP49            | integrationtester | I73573r0     | True     | [[result]]             | ""              | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 41 | [[a&]]                          |                   | ""                    | ""       | [[destPath]]                    | c:\ZIP50            | integrationtester | I73573r0     | True     | [[result]]             | ""              | ""      | AN           | True             | File or Folder - Variable name [[a&]] contains invalid character(s)           | 1.File or Folder - Variable name [[a&]] contains invalid character(s)                 |
#		| 42 | [[rec(**).a]]                   |                   | ""                    | ""       | [[destPath]]                    | c:\ZIP51            | integrationtester | I73573r0     | True     | [[result]]             | ""              | ""      | AN           | True             | File or Folder - Recordset index (**) contains invalid character(s)           | 1.File or Folder - Recordset index (**) contains invalid character(s)                 |
#		| 43 | [[a]                            |                   | ""                    | ""       | [[destPath]]                    | c:\ZIP52            | integrationtester | I73573r0     | True     | [[result]]             | ""              | ""      | AN           | True             | File or Folder - Invalid expression: opening and closing brackets don't match | 1.File or Folder - Invalid expression: opening and closing brackets don't match       |
#		| 44 | [[rec(a]]                       |                   | ""                    | ""       | [[destPath]]                    | c:\ZIP53            | integrationtester | I73573r0     | True     | [[result]]             | ""              | ""      | AN           | True             | File or Folder - Recordset name [[rec(a]] contains invalid character(s)       | 1.File or Folder - Recordset name [[rec(a]] contains invalid character(s)             |
#		| 45 | c(*()                           |                   | ""                    | ""       | [[destPath]]                    | c:\ZIP54            | integrationtester | I73573r0     | True     | [[result]]             | ""              | ""      | AN           | True             | Please supply a valid File or Folder                                          | 1.Please supply a valid File or Folder                                                |
#		| 46 | [[rec([[inde$x]]).a]]           |                   | ""                    | ""       | [[destPath]]                    | c:\ZIP55            | integrationtester | I73573r0     | True     | [[result]]             | ""              | ""      | AN           | True             | File or Folder - Variable name [[inde$x]]  contains invalid character(s)      | 1.File or Folder - Variable name [[inde$x]]  contains invalid character(s)            |
#		| 47 | ghjghj                          |                   | ""                    | ""       | [[destPath]]                    | c:\ZIP56            | integrationtester | I73573r0     | True     | [[result]]             | ""              | ""      | AN           | True             | Please supply a valid File or Folder                                          | 1.Please supply a valid File or Folder                                                |
#		| 48 | ""                              |                   | ""                    | ""       | [[destPath]]                    | c:\ZIP57            | integrationtester | I73573r0     | True     | [[result]]             | ""              | ""      | AN           | True             | File or Folder cannot be empty or only white space                            | 1.File or Folder cannot be empty or only white space                                  |
#		| 49 | [[sourcePath]]                  | c:\copyfile50.txt | ""                    | ""       | [[a&]]                          | c:\ZIP58            | integrationtester | I73573r0     | True     | [[result]]             | ""              | ""      | AN           | True             | Destination - Variable name [[a&]] contains invalid character(s)              | 1.Destination - Variable name [[a&]] contains invalid character(s)                    |
#		| 50 | [[sourcePath]]                  | c:\copyfile51.txt | ""                    | ""       | [[rec(**).a]]                   | c:\ZIP59            | integrationtester | I73573r0     | True     | [[result]]             | ""              | ""      | AN           | True             | Destination - Recordset index (**) contains invalid character(s)              | 1.Destination - Recordset index (**) contains invalid character(s)                    |
#		| 51 | [[sourcePath]]                  | c:\copyfile52.txt | ""                    | ""       | [[a]                            | c:\ZIP60            | integrationtester | I73573r0     | True     | [[result]]             | ""              | ""      | AN           | True             | Destination - Invalid expression: opening and closing brackets don't match    | 1.Destination - Invalid expression: opening and closing brackets don't match          |
#		| 52 | [[sourcePath]]                  | c:\copyfile53.txt | ""                    | ""       | [[rec(a]]                       | c:\ZIP61            | integrationtester | I73573r0     | True     | [[result]]             | ""              | ""      | AN           | True             | Destination - Recordset name [[rec(a]] contains invalid character(s)          | 1.Destination - Recordset name [[rec(a]] contains invalid character(s)                |
#		| 53 | [[sourcePath]]                  | c:\copyfile54.txt | ""                    | ""       | c(*()                           | c:\ZIP62            | integrationtester | I73573r0     | True     | [[result]]             | ""              | ""      | AN           | True             | Please supply a valid File or Folder                                          | 1.Please supply a valid File or Folder                                                |
#		| 54 | [[sourcePath]]                  | c:\copyfile55.txt | ""                    | ""       | [[rec([[inde$x]]).a]]           | c:\ZIP63            | integrationtester | I73573r0     | True     | [[result]]             | ""              | ""      | AN           | True             | Destination - Variable name [[inde$x]]  contains invalid character(s)         | 1.Destination - Variable name [[inde$x]]  contains invalid character(s)               |
#		| 55 | [[sourcePath]]                  | c:\copyfile56.txt | ""                    | ""       | ghjghj                          | c:\ZIP64            | integrationtester | I73573r0     | True     | [[result]]             | ""              | ""      | AN           | True             | Please supply a valid File or Folder                                          | 1.Please supply a valid File or Folder                                                |
#		| 56 | [[sourcePath]]                  | c:\copyfile57.txt | ""                    | ""       | ""                              | c:\ZIP65            | integrationtester | I73573r0     | True     | [[result]]             | ""              | ""      | AN           | True             | Destination cannot be empty or only white space                               | 1.Destination cannot be empty or only white space                                     |
#		| 57 | [[sourcePath]]                  | c:\copyfile58.txt | [[a&]]                | String   | [[destPath]]                    | c:\ZIP66            | integrationtester | I73573r0     | True     | [[result]]             | ""              | ""      | AN           | True             | Username - Variable name [[a&]] contains invalid character(s)                 | 1.Username - Variable name [[a&]] contains invalid character(s)                       |
#		| 58 | [[sourcePath]]                  | c:\copyfile59.txt | [[rec(**).a]]         | String   | [[destPath]]                    | c:\ZIP67            | integrationtester | I73573r0     | True     | [[result]]             | ""              | ""      | AN           | True             | Username - Recordset index (**) contains invalid character(s)                 | 1.Username - Recordset index (**) contains invalid character(s)                       |
#		| 59 | [[sourcePath]]                  | c:\copyfile60.txt | [[a]                  | String   | [[destPath]]                    | c:\ZIP68            | integrationtester | I73573r0     | True     | [[result]]             | ""              | ""      | AN           | True             | Username - Invalid expression: opening and closing brackets don't match       | 1.Username - Invalid expression: opening and closing brackets don't match             |
#		| 60 | [[sourcePath]]                  | c:\copyfile61.txt | [[rec(a]]             | String   | [[destPath]]                    | c:\ZIP69            | integrationtester | I73573r0     | True     | [[result]]             | ""              | ""      | AN           | True             | Username - Recordset name [[rec(a]] contains invalid character(s)             | 1.Username - Recordset name [[rec(a]] contains invalid character(s)                   |
#		| 61 | [[sourcePath]]                  | c:\copyfile62.txt | [[rec([[inde$x]]).a]] | String   | [[destPath]]                    | c:\ZIP70            | integrationtester | I73573r0     | True     | [[result]]             | ""              | ""      | AN           | True             | Username - Variable name [[inde$x]]  contains invalid character(s)            | 1.Username - Variable name [[inde$x]]  contains invalid character(s)                  |
#		| 62 | [[sourcePath]]                  | c:\copyfile63.txt |                       | String   | [[destPath]]                    | c:\ZIP71            | integrationtester | I73573r0     | True     | [[result]]             | ""              | ""      | AN           | True             | Username cannot be empty or only white space                                  | 1.Username cannot be empty or only white space                                        |
#		| 63 | [[sourcePath]]                  | c:\copyfile64.txt | [[a&]]                | String   | [[destPath]]                    | c:\ZIP72            | integrationtester | I73573r0     | True     | [[result]]             | ""              | ""      | AN           | True             | Username - Variable name [[a&]] contains invalid character(s)                 | 1.Destination Username - Variable name [[a&]] contains invalid character(s)           |
#		| 64 | [[sourcePath]]                  | c:\copyfile65.txt | [[rec(**).a]]         | String   | [[destPath]]                    | c:\ZIP73            | integrationtester | I73573r0     | True     | [[result]]             | ""              | ""      | AN           | True             | Username - Recordset index (**) contains invalid character(s)                 | 1.Destination Username - Recordset index (**) contains invalid character(s)           |
#		| 65 | [[sourcePath]]                  | c:\copyfile66.txt | [[a]                  | String   | [[destPath]]                    | c:\ZIP74            | integrationtester | I73573r0     | True     | [[result]]             | ""              | ""      | AN           | True             | Username - Invalid expression: opening and closing brackets don't match       | 1.Destination Username - Invalid expression: opening and closing brackets don't match |
#		| 66 | [[sourcePath]]                  | c:\copyfile67.txt | [[rec(a]]             | String   | [[destPath]]                    | c:\ZIP75            | integrationtester | I73573r0     | True     | [[result]]             | ""              | ""      | AN           | True             | Username - Recordset name [[rec(a]] contains invalid character(s)             | 1.Destination Username - Recordset name [[rec(a]] contains invalid character(s)       |
#		| 67 | [[sourcePath]]                  | c:\copyfile68.txt | [[rec([[inde$x]]).a]] | String   | [[destPath]]                    | c:\ZIP76            | integrationtester | I73573r0     | True     | [[result]]             | ""              | ""      | AN           | True             | Username - Variable name [[inde$x]]  contains invalid character(s)            | 1.Destination Username - Variable name [[inde$x]]  contains invalid character(s)      |
#		| 68 | [[sourcePath]]                  | c:\copyfile69.txt | ""                    | String   | [[destPath]]                    | c:\ZIP77            | integrationtester | I73573r0     | True     | [[result]]             | ""              | ""      | AN           | True             | Username cannot be empty or only white space                                  | 1.Destination Username cannot be empty or only white space                            |
#		| 69 | [[sourcePath]]                  | c:\copyfile70.txt | ""                    | ""       | [[destPath]]                    | c:\ZIP78            | integrationtester | I73573r0     | True     | [[result]][[a]]        | ""              | ""      | AN           | True             | The result field only allows a single result                                  | 1.The result field only allows a single result                                        |
#		| 70 | [[sourcePath]]                  | c:\copyfile71.txt | ""                    | ""       | [[destPath]]                    | c:\ZIP79            | integrationtester | I73573r0     | True     | [[a]]*]]               | ""              | ""      | AN           | True             | Result - Invalid expression: opening and closing brackets don't match         | 1.Result - Invalid expression: opening and closing brackets don't match               |
#		| 71 | [[sourcePath]]                  | c:\copyfile72.txt | ""                    | ""       | [[destPath]]                    | c:\ZIP80            | integrationtester | I73573r0     | True     | [[var@]]               | ""              | ""      | AN           | True             | Result - Variable name [[var@]] contains invalid character(s)                 | 1.Result - Variable name [[var@]] contains invalid character(s)                       |
#		| 72 | [[sourcePath]]                  | c:\copyfile73.txt | ""                    | ""       | [[destPath]]                    | c:\ZIP81            | integrationtester | I73573r0     | True     | [[var]]00]]            | ""              | ""      | AN           | True             | Result - Invalid expression: opening and closing brackets don't match         | 1.Result - Invalid expression: opening and closing brackets don't match               |
#		| 73 | [[sourcePath]]                  | c:\copyfile74.txt | ""                    | ""       | [[destPath]]                    | c:\ZIP82            | integrationtester | I73573r0     | True     | [[(1var)]]             | ""              | ""      | AN           | True             | Result - Variable name [[1var]] contains invalid character(s)                 | 1.Result - Variable name [[1var]] contains invalid character(s)                       |
#		| 74 | [[sourcePath]]                  | c:\copyfile75.txt | ""                    | ""       | [[destPath]]                    | c:\ZIP83            | integrationtester | I73573r0     | True     | [[var[[a]]]]           | ""              | ""      | AN           | True             | Result - Invalid Region [[var[[a]]]]                                          | 1.Result - Invalid Region [[var[[a]]]]                                                |
#		| 75 | [[sourcePath]]                  | c:\copyfile76.txt | ""                    | ""       | [[destPath]]                    | c:\ZIP84            | integrationtester | I73573r0     | True     | [[var.a]]              | ""              | ""      | AN           | True             | Result - Variable name [[var.a]]contains invalid character(s)                 | 1.Result - Variable name [[var.a]] contains invalid character(s)                      |
#		| 76 | [[sourcePath]]                  | c:\copyfile77.txt | ""                    | ""       | [[destPath]]                    | c:\ZIP85            | integrationtester | I73573r0     | True     | [[@var]]               | ""              | ""      | AN           | True             | Result - Variable name [[@var]] contains invalid character(s)                 | 1.Result - Variable name [[@var]] contains invalid character(s)                       |
#		| 77 | [[sourcePath]]                  | c:\copyfile78.txt | ""                    | ""       | [[destPath]]                    | c:\ZIP86            | integrationtester | I73573r0     | True     | [[var 1]]              | ""              | ""      | AN           | True             | Result - Variable name [[var 1]] contains invalid character(s)                | 1.Result - Variable name [[var 1]] contains invalid character(s)                      |
#		| 78 | [[sourcePath]]                  | c:\copyfile79.txt | ""                    | ""       | [[destPath]]                    | c:\ZIP87            | integrationtester | I73573r0     | True     | [[rec(1).[[rec().1]]]] | ""              | ""      | AN           | True             | Result - Invalid Region [[rec(1).[[rec().1]]]]                                | 1.Result - Invalid Region [[rec(1).[[rec().1]]]]                                      |
#		| 79 | [[sourcePath]]                  | c:\copyfile80.txt | ""                    | ""       | [[destPath]]                    | c:\ZIP88            | integrationtester | I73573r0     | True     | [[rec(@).a]]           | ""              | ""      | AN           | True             | Result - Recordset index [[@]] contains invalid character(s)                  | 1.Result - Recordset index [[@]] contains invalid character(s)                        |
#		| 80 | [[sourcePath]]                  | c:\copyfile81.txt | ""                    | ""       | [[destPath]]                    | c:\ZIP89            | integrationtester | I73573r0     | True     | [[rec"()".a]]          | ""              | ""      | AN           | True             | Result - Recordset name [[rec"()"]] contains invalid character(s)             | 1.Result - Recordset name [[rec"()"]] contains invalid character(s)                   |
#		| 81 | [[sourcePath]]                  | c:\copyfile82.txt | ""                    | ""       | [[destPath]]                    | c:\ZIP90            | integrationtester | I73573r0     | True     | [[rec([[[[b]]]]).a]]   | ""              | ""      | AN           | True             | Result - Invalid Region [[rec([[[[b]]]]).a]]                                  | 1.Result - Invalid Region [[rec([[[[b]]]]).a]]                                        |
															
			  	  										