using System;
using System.Collections.Generic;

namespace Bashley
{
    class Job_Definitions
    {
        public static Dictionary<string, Tuple<string, string>> GetJobDefinitions()
        {
            return new Dictionary<string, Tuple<string, string>>
            {
                ["Other Unit Tests"] = new Tuple<string, string>("Dev2.*.Tests, Warewolf.*.Tests", null),
                ["Server Proxy Layer Tests"] = new Tuple<string, string>("Warewolf.Studio.ServerProxyLayer.Tests", null),
                ["Infrastructure Unit Tests"] = new Tuple<string, string>("Dev2.Infrastructure.Tests", null),
                ["Runtime Unit Tests"] = new Tuple<string, string>("Dev2.Runtime.Tests", null),
                ["Core Unit Tests"] = new Tuple<string, string>("Dev2.Core.Tests", null),
                ["Data Unit Tests"] = new Tuple<string, string>("Dev2.Data.Tests", null),
                ["Parsing Unit Tests"] = new Tuple<string, string>("Warewolf.Parsing.Tests", null),
                ["Storage Unit Tests"] = new Tuple<string, string>("Warewolf.Storage.Tests", null),
                ["Studio Core Unit Tests"] = new Tuple<string, string>("Dev2.Studio.Core.Tests", null),
                ["COMIPC Unit Tests"] = new Tuple<string, string>("Warewolf.COMIPC.Tests", null),
                ["Studio View Models Unit Tests"] = new Tuple<string, string>("Warewolf.Studio.ViewModels.Tests", null),
                ["Activity Designers Unit Tests"] = new Tuple<string, string>("Dev2.Activities.Designers.Tests", null),
                ["Activities Unit Tests"] = new Tuple<string, string>("Dev2.Activities.Tests", null),
                ["Other Tools Specs"] = new Tuple<string, string>("Warewolf.Tools.Specs", null),
                ["Scripting Tools Specs"] = new Tuple<string, string>("Warewolf.Tools.Specs", "Scripting"),
                ["Storage Tools Specs"] = new Tuple<string, string>("Warewolf.Tools.Specs", "Storage"),
                ["Utility Tools Specs"] = new Tuple<string, string>("Warewolf.Tools.Specs", "Utility"),
                ["Control Flow Tools Specs"] = new Tuple<string, string>("Warewolf.Tools.Specs", "ControlFlow"),
                ["Data Tools Specs"] = new Tuple<string, string>("Warewolf.Tools.Specs", "Data"),
                ["Database Tools Specs"] = new Tuple<string, string>("Warewolf.Tools.Specs", "Database"),
                ["Email Tools Specs"] = new Tuple<string, string>("Warewolf.Tools.Specs", "Email"),
                ["File And Folder Copy Tool Specs"] = new Tuple<string, string>("Warewolf.Tools.Specs", "FileAndFolderCopy"),
                ["File And Folder Create Tool Specs"] = new Tuple<string, string>("Warewolf.Tools.Specs", "FileAndFolderCreate"),
                ["File And Folder Delete Tool Specs"] = new Tuple<string, string>("Warewolf.Tools.Specs", "FileAndFolderDelete"),
                ["File And Folder Move Tool Specs"] = new Tuple<string, string>("Warewolf.Tools.Specs", "FileAndFolderMove"),
                ["Folder Read Tool Specs"] = new Tuple<string, string>("Warewolf.Tools.Specs", "ReadFolder"),
                ["File Read Tool Specs"] = new Tuple<string, string>("Warewolf.Tools.Specs", "ReadFile"),
                ["File And Folder Rename Tool Specs"] = new Tuple<string, string>("Warewolf.Tools.Specs", "FileAndFolderRename"),
                ["Unzip Tool Specs"] = new Tuple<string, string>("Warewolf.Tools.Specs", "Unzip"),
                ["Write File Tool Specs"] = new Tuple<string, string>("Warewolf.Tools.Specs", "WriteFile"),
                ["Zip Tool Specs"] = new Tuple<string, string>("Warewolf.Tools.Specs", "Zip"),
                ["Loop Construct Tools Specs"] = new Tuple<string, string>("Warewolf.Tools.Specs", "LoopConstructs"),
                ["Recordset Tools Specs"] = new Tuple<string, string>("Warewolf.Tools.Specs", "Recordset"),
                ["Resource Tools Specs"] = new Tuple<string, string>("Warewolf.Tools.Specs", "Resources"),
                ["UI Binding Tests"] = new Tuple<string, string>("Warewolf.UIBindingTests.*", null),
                //Server Tests
                ["Integration Tests"] = new Tuple<string, string>("Dev2.IntegrationTests", null),
                ["Load Tests"] = new Tuple<string, string>("Dev2.IntegrationTests", "Load Tests"),
                ["Other Specs"] = new Tuple<string, string>("Dev2.*.Specs,Warewolf.*.Specs", null),
                ["Other Activities Specs"] = new Tuple<string, string>("Dev2.Activities.Specs", null),
                ["Example Workflow Execution Specs"] = new Tuple<string, string>("Dev2.Activities.Specs", "ExampleWorkflowExecution"),
                ["Subworkflow Execution Specs"] = new Tuple<string, string>("Dev2.Activities.Specs", "SubworkflowExecution"),
                ["Workflow Execution Specs"] = new Tuple<string, string>("Dev2.Activities.Specs", "WorkflowExecution"),
                ["Studio Test Framework Specs"] = new Tuple<string, string>("Dev2.Activities.Specs", "StudioTestFramework"),
                ["Studio Test Framework With Data Tools Specs"] = new Tuple<string, string>("Dev2.Activities.Specs", "StudioTestFrameworkWithDataTools"),
                ["Studio Test Framework With Database Tools Specs"] = new Tuple<string, string>("Dev2.Activities.Specs", "StudioTestFrameworkWithDatabaseTools"),
                ["Studio Test Framework With Deleted Resources Specs"] = new Tuple<string, string>("Dev2.Activities.Specs", "StudioTestFrameworkWithDeletedResources"),
                ["Studio Test Framework With Dropbox Tools Specs"] = new Tuple<string, string>("Dev2.Activities.Specs", "StudioTestFrameworkWithDropboxTools"),
                ["Studio Test Framework With File And Folder Tools Specs"] = new Tuple<string, string>("Dev2.Activities.Specs", "StudioTestFrameworkWithFileAndFolderTools"),
                ["Studio Test Framework With Hello World Workflow Specs"] = new Tuple<string, string>("Dev2.Activities.Specs", "StudioTestFrameworkWithHelloWorldWorkflow"),
                ["Studio Test Framework With HTTP Web Tools Specs"] = new Tuple<string, string>("Dev2.Activities.Specs", "StudioTestFrameworkWithHTTPWebTools"),
                ["Studio Test Framework With Scripting Tools Specs"] = new Tuple<string, string>("Dev2.Activities.Specs", "StudioTestFrameworkWithScriptingTools"),
                ["Studio Test Framework With Subworkflow Specs"] = new Tuple<string, string>("Dev2.Activities.Specs", "StudioTestFrameworkWithSubworkflow"),
                ["Studio Test Framework With Utility Tools Specs"] = new Tuple<string, string>("Dev2.Activities.Specs", "StudioTestFrameworkWithUtilityTools"),
                ["Other Security Specs"] = new Tuple<string, string>("Warewolf.Security.Specs", null),
                ["Conflicting Contribute View And Execute Permissions Security Specs"] = new Tuple<string, string>("Warewolf.Security.Specs", "ConflictingContributeViewExecutePermissionsSecurity"),
                ["Conflicting Execute Permissions Security Specs"] = new Tuple<string, string>("Warewolf.Security.Specs", "ConflictingExecutePermissionsSecurity"),
                ["Conflicting View And Execute Permissions Security Specs"] = new Tuple<string, string>("Warewolf.Security.Specs", "ConflictingViewExecutePermissionsSecurity"),
                ["Conflicting View Permissions Security Specs"] = new Tuple<string, string>("Warewolf.Security.Specs", "ConflictingViewPermissionsSecurity"),
                ["No Conflicting Permissions Security Specs"] = new Tuple<string, string>("Warewolf.Security.Specs", "NoConflictingPermissionsSecurity"),
                ["Overlapping User Groups Permissions Security Specs"] = new Tuple<string, string>("Warewolf.Security.Specs", "OverlappingUserGroupsPermissionsSecurity"),
                ["Resource Permissions Security Specs"] = new Tuple<string, string>("Warewolf.Security.Specs", "ResourcePermissionsSecurity"),
                ["Server Permissions Security Specs"] = new Tuple<string, string>("Warewolf.Security.Specs", "ServerPermissionsSecurity"),
                //Web UI Tests
                ["Other Web UI Tests"] = new Tuple<string, string>("Warewolf.Web.UI.Tests", null),
                ["Execution Logging Web UI Tests"] = new Tuple<string, string>("Warewolf.Web.UI.Tests", "ExecutionLogging"),
                ["No Warewolf Server Web UI Tests"] = new Tuple<string, string>("Warewolf.Web.UI.Tests", "NoWarewolfServer"),
                //Desktop UI Tests
                ["Other UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", null),
                ["Other UI Specs"] = new Tuple<string, string>("Warewolf.UI.Specs", null),
                ["Assign Tool UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Assign Tool"),
                ["Control Flow Tools UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Control Flow Tools"),
                ["Database Sources UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Database Sources"),
                ["Database Tools UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Database Tools"),
                ["Data Tools UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Data Tools"),
                ["DB Connector UI Specs"] = new Tuple<string, string>("Warewolf.UI.Specs", "DBConnector"),
                ["Debug Input UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Debug Input"),
                ["Default Layout UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Default Layout"),
                ["Studio Shutdown UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Studio Shutdown"),
                ["Dependency Graph UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Dependency Graph"),
                ["Deploy UI Specs"] = new Tuple<string, string>("Warewolf.UI.Specs", "Deploy"),
                ["Deploy Security UI Specs"] = new Tuple<string, string>("Warewolf.UI.Specs", "DeploySecurity"),
                ["Deploy UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Deploy"),
                ["Deploy from Explorer UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Deploy from Explorer"),
                ["Deploy from Remote UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Deploy from Remote"),
                ["Deploy Filtering UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Deploy Filtering"),
                ["Deploy Hello World UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Deploy Hello World"),
                ["Deploy Select Dependencies UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Deploy Select Dependencies"),
                ["DotNet Connector Mocking UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "DotNet Connector Mocking Tests"),
                ["DotNet Connector Tool UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "DotNet Connector Tool"),
                ["Dropbox Tools UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Dropbox Tools"),
                ["Email Tools UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Email Tools"),
                ["Explorer UI Specs"] = new Tuple<string, string>("Warewolf.UI.Specs", "Explorer"),
                ["Explorer UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Explorer"),
                ["File Tools UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "File Tools"),
                ["Hello World Mocking UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Hello World Mocking Tests"),
                ["HTTP Tools UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "HTTP Tools"),
                ["Plugin Sources UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Plugin Sources"),
                ["Recordset Tools UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Recordset Tools"),
                ["Resource Tools UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Resource Tools"),
                ["Save Dialog UI Specs"] = new Tuple<string, string>("Warewolf.UI.Specs", "SaveDialog"),
                ["Save Dialog UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Save Dialog"),
                ["Server Sources UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Server Sources"),
                ["Settings UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Settings"),
                ["Sharepoint Tools UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Sharepoint Tools"),
                ["Shortcut Keys UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Shortcut Keys"),
                ["Source Wizards UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Source Wizards"),
                ["Tabs And Panes UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Tabs and Panes"),
                ["Tools UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Tools"),
                ["Utility Tools UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Utility Tools"),
                ["Variables UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Variables"),
                ["Web Connector UI Specs"] = new Tuple<string, string>("Warewolf.UI.Specs", "WebConnector"),
                ["Web Sources UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Web Sources"),
                ["Workflow Mocking Tests UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Workflow Mocking Tests"),
                ["Workflow Testing UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Workflow Testing"),
                ["Workflow Merging UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Merge"),
                ["Search UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Search"),
                ["Input Search UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Input Search"),
                ["Output Search UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Output Search"),
                ["Test Name Search UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Test Name Search"),
                ["Scalar Search UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Scalar Search"),
                ["Recordset Search UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Recordset Search"),
                ["Object Search UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Object Search"),
                ["Service Search UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Service Search"),
                ["Title Search UI Tests"] = new Tuple<string, string>("Warewolf.UI.Tests", "Title Search"),
                //UI Load Spec
                ["UI Load Specs"] = new Tuple<string, string>("Warewolf.UI.Load.Specs", null),
                ["Load Tests"] = new Tuple<string, string>("Dev2.Integration.Tests", "Load Tests")
            };
        }
    }
}
