#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.5.{build}

# branches to build
branches:
  only:
    - development

# Including commits with particular message
only_commits:
  message: /WOLF-/                # Start a new build if message contains 'WOLF-'

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\Builds\Warewolf

# build cache to preserve files/folders between builds
cache:
  - Dev\packages -> **\packages.config  # preserve "packages" directory in the 'Dev' folder but will reset it if packages.config is modified
  - '%LocalAppData%\NuGet\Cache'

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  parallel: true                  # enable MSBuild parallel builds
  project: Dev\Server.sln.sln     # path to Visual Studio solution or project
  verbosity: normal

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  # pushing a single file with environment variable in path and "Deployment name" specified
  - path: Dev2.Server\bin\$(configuration)
    name: Warewolf Server $(version)