# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  name: Default

jobs:

- job: build
  displayName: 'Compile AcceptanceTesting.sln'

  steps:
  - script: "powershell -NoProfile -NoLogo -ExecutionPolicy Bypass -NoExit -File \"$(Agent.BuildDirectory)\\s\\Compile.ps1\" -AcceptanceTesting"
    displayName: 'Compile AcceptanceTesting.sln'

- job: Zip_Tool_Specs
  displayName: 'Run Zip Tool Specs'
  dependsOn: build

  steps:
  - script: "\"$(Agent.BuildDirectory)\\s\\Dev\\.run\\Job Shortcuts\\Container\\Zip Tool Specs.bat\""
    displayName: 'Run Zip Tool Specs'

  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
      failTaskOnFailedTests: true

- job: Auditing_Unit_Tests
  displayName: 'Run Auditing Unit Tests'
  dependsOn: build

  steps:
  - script: "\"$(Agent.BuildDirectory)\\s\\Dev\\.run\\Job Shortcuts\\Container\\Auditing Unit Tests.bat\""
    displayName: 'Run Auditing Unit Tests'

  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
      failTaskOnFailedTests: true