<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net48</TargetFramework>
		<ImplicitUsings>false</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="System.ServiceProcess" />
		<Reference Include="System" />
		<Reference Include="System.Core" />
		<Reference Include="System.Diagnostics" />
	</ItemGroup>

</Project>
