using System.Reflection;
using System.Runtime.CompilerServices;
[assembly: AssemblyCompany("Warewolf")]
[assembly: AssemblyProduct("Warewolf")]
[assembly: AssemblyCopyright("Copyright Warewolf 2019")]
[assembly: AssemblyVersion("2.2.0.75")]
[assembly: AssemblyInformationalVersion("02/08/2019 13:15:43 83e577c0122e05837368754f19b1da8c2d63d432 4442_Special_Version_Installers")]
[assembly: InternalsVisibleTo("Dev2.Activities.Tests")]
[assembly: InternalsVisibleTo("Dev2.Activities.Designers.Tests")]
[assembly: InternalsVisibleTo("Warewolf.Studio.ViewModels.Tests")]
[assembly: InternalsVisibleTo("Dev2.Activities.Specs")]
[assembly: InternalsVisibleTo("Dev2.Runtime.Tests")]
[assembly: InternalsVisibleTo("Dev2.Studio.Core.Tests")]
[assembly: InternalsVisibleTo("Dev2.Core.Tests")]
[assembly: InternalsVisibleTo("Dev2.Integration.Tests")]
[assembly: InternalsVisibleTo("Dev2.TaskScheduler.Wrappers")]
[assembly: InternalsVisibleTo("Dev2.Infrastructure.Tests")]
[assembly: InternalsVisibleTo("Warewolf.UIBindingTests.ComDll")]
[assembly: InternalsVisibleTo("Warewolf.Studio.ViewModels.Tests")]
[assembly: InternalsVisibleTo("Dev2.Data.Tests")]
[assembly: InternalsVisibleTo("Warewolf.Tools.Specs")]
[assembly: InternalsVisibleTo("Warewolf.UIBindingTests.PluginSource")]
