@fileFeature
Feature: Move
	In order to be able to Move a File or Folder 
	as a Warewolf user
	I want a tool that will Move File(s) or Folder(s) from a given location to another location
	
Scenario Outline: Move file at location
	Given I have a source path '<source>' with value '<sourceLocation>' 
	And source credentials as '<username>' and '<password>'
	And I have a destination path '<destination>' with value '<destinationLocation>'
    And destination credentials as '<destUsername>' and '<destPassword>'
	And overwrite is '<selected>'
	And result as '<resultVar>'
    When the Move file tool is executed
	Then the result variable '<resultVar>' will be '<result>'
	And the execution has "<errorOccured>" error
	And the debug inputs as
         | Source Path                 | Username   | Password | Destination Path                      | Destination Username | Destination Password | Overwrite  |
         | <source> = <sourceLocation> | <username> | String   | <destination> = <destinationLocation> | <destUsername>       | String               | <selected> |       
	And the debug output as
		|                        |
		| <resultVar> = <result> |
	Examples: 
	   | No | Name           | source         | sourceLocation                                               | username          | password | destination  | destinationLocation                                       | destUsername      | destPassword | selected | resultVar              | result  | errorOccured |
	   | 1  | Local to Local | [[sourcePath]] | c:\movefile0.txt                                             | ""                | ""       | [[destPath]] | C:\moved0.txt                                             | ""                | ""           | True     | [[result]]             | Success | NO           |
	   | 2  | Local to FTP   | [[sourcePath]] | c:\movefile1.txt                                             | ""                | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/moved0.txt          | ""                | ""           | True     | [[result]]             | Success | NO           |
	   | 3  | Local to FTPS  | [[sourcePath]] | c:\movefile2.txt                                             | ""                | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/moved0.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           |
	   | 4  | Local to SFTP  | [[sourcePath]] | c:\movefile3.txt                                             | ""                | ""       | [[destPath]] | sftp://localhost/moved0.txt                               | dev2              | Q/ulw&]      | True     | [[result]]             | Success | NO           |
	   | 5  | Local to UNC   | [[sourcePath]] | c:\movefile4.txt                                             | ""                | ""       | [[destPath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\moved0.txt | ""                | ""           | True     | [[result]]             | Success | NO           |
	   | 6  | UNC to Local   | [[sourcePath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\movefile0.txt | ""                | ""       | [[destPath]] | C:\moved1.txt                                             | ""                | ""           | True     | [[result]]             | Success | NO           |
	   | 7  | UNC to FTP     | [[sourcePath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\movefile1.txt | ""                | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/moved1.txt          | ""                | ""           | True     | [[result]]             | Success | NO           |
	   | 8  | UNC to FTPS    | [[sourcePath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\movefile2.txt | ""                | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/moved1.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           |
	   | 9  | UNC to SFTP    | [[sourcePath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\movefile3.txt | ""                | ""       | [[destPath]] | sftp://localhost/moved1.txt                               | dev2              | Q/ulw&]      | True     | [[result]]             | Success | NO           |
	   | 10 | UNC TO UNC     | [[sourcePath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\movefile4.txt | ""                | ""       | [[destPath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\moved1.txt | ""                | ""           | True     | [[result]]             | Success | NO           |
	   | 11 | FTP to Local   | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/movefile0.txt          | ""                | ""       | [[destPath]] | C:\moved2.txt                                             | ""                | ""           | True     | [[result]]             | Success | NO           |
	   | 12 | FTP to UNC     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/movefile1.txt          | ""                | ""       | [[destPath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\moved2.txt | ""                | ""           | True     | [[result]]             | Success | NO           |
	   | 13 | FTP to FTPS    | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/movefile2.txt          | ""                | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/moved2.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           |
	   | 14 | FTP to SFTP    | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/movefile3.txt          | ""                | ""       | [[destPath]] | sftp://localhost/moved2.txt                               | dev2              | Q/ulw&]      | True     | [[result]]             | Success | NO           |
	   | 15 | FTP to FTP     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/movefile4.txt          | ""                | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/moved2.txt          | ""                | ""           | True     | [[result]]             | Success | NO           |
	   | 16 | FTPS to Local  | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/movefile0.txt          | integrationtester | I73573r0 | [[destPath]] | C:\moved3.txt                                             | ""                | ""           | True     | [[result]]             | Success | NO           |
	   | 17 | FTPS to UNC    | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/movefile1.txt          | integrationtester | I73573r0 | [[destPath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\moved3.txt | ""                | ""           | True     | [[result]]             | Success | NO           |
	   | 18 | FTPS to FTPS   | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/movefile2.txt          | integrationtester | I73573r0 | [[destPath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/moved3.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           |
	   | 19 | FTPS to SFTP   | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/movefile3.txt          | integrationtester | I73573r0 | [[destPath]] | sftp://localhost/moved3.txt                               | dev2              | Q/ulw&]      | True     | [[result]]             | Success | NO           |
	   | 20 | FTPS to FTP    | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/movefile4.txt          | integrationtester | I73573r0 | [[destPath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/moved3.txt          | ""                | ""           | True     | [[result]]             | Success | NO           |
	   | 21 | SFTP to Local  | [[sourcePath]] | sftp://localhost/movefile0.txt                               | dev2              | Q/ulw&]  | [[destPath]] | C:\moved4.txt                                             | ""                | ""           | True     | [[result]]             | Success | NO           |
	   | 22 | SFTP to UNC    | [[sourcePath]] | sftp://localhost/movefile1.txt                               | dev2              | Q/ulw&]  | [[destPath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\moved4.txt | ""                | ""           | True     | [[result]]             | Success | NO           |
	   | 23 | SFTP to FTP    | [[sourcePath]] | sftp://localhost/movefile2.txt                               | dev2              | Q/ulw&]  | [[destPath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/moved4.txt          | ""                | ""           | True     | [[result]]             | Success | NO           |
	   | 24 | SFTP to FTPS   | [[sourcePath]] | sftp://localhost/movefile3.txt                               | dev2              | Q/ulw&]  | [[destPath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/moved4.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           |
	   | 25 | SFTP to SFTP   | [[sourcePath]] | sftp://localhost/movefile4.txt                               | dev2              | Q/ulw&]  | [[destPath]] | sftp://localhost/moved4.txt                               | dev2              | Q/ulw&]      | True     | [[result]]             | Success | NO           |


	 


 #Scenario Outline: Move file at location1
#	Given I have a source path '<File or Folder>' with value '<sourceLocation>' 
#	And source credentials as '<username>' and '<password>'
#	And I have a destination path '<destination>' with value '<destinationLocation>'
#    And destination credentials as '<destUsername>' and '<destPassword>'
#	And overwrite is '<selected>'
#	And result as '<resultVar>'
#	When validating the tool
#	Then validation is '<ValidationResult>'
#	And validation message is '<DesignValidation>'
#    When the Move file tool is executed
#	Then the result variable '<resultVar>' will be '<result>'
#	And the execution has "<errorOccured>" error
#	And execution error message will be '<DesignValidation>'
#	And the debug inputs as
#        | Source Path                         | Username   | Password | Destination Path                      | Destination Username | Destination Password | Overwrite  |
#        | <File or FOlder> = <sourceLocation> | <username> | String   | <destination> = <destinationLocation> | <destUsername>       | String               | <selected> |
#	And the debug output as
#		|                        |
#		| <resultVar> = <result> |
#	Examples: 
#		| No | File or Folder                  | sourceLocation                     | username              | password | destination                     | destinationLocation   | destUsername      | destPassword | selected | resultVar  | result  | errorOccured | ValidationResult | DesignValidation                                                              | OutputError                                                                     |
#		| 4  | [[sourcePath]]                  | c:\movefile57.txt                  | ""                    | ""       | [[destPath]]                    | C:\moved0.txt         | dev2              | Q/ulw&]      | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 5  | [[sourcePath]]                  | c:\movefile58.txt                  | ""                    | ""       | [[destPath]]                    | C:\moved0.txt         | ""                | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 1  | [[sourcePath]]                  | c:\movefile59.txt                  | ""                    | ""       | [[destPath]]                    | C:\moved0.txt         | ""                | ""           | Truee    | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 2  | [[sourcePath]]                  | c:\movefile60.txt                  | ""                    | ""       | [[destPath]]                    | C:\moved0.txt         | ""                | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 3  | [[sourcePath]]                  | c:\movefile61.txt c:\copyfile2.txt | ""                    | ""       | [[destPath]]                    | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 6  | [[sourcePath]]                  | c:\movefile5.txt                   | ""                    | ""       | [[destPath]]                    | C:\moved0.txt         | ""                | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 7  | [[sourcePath]]                  | c:\movefile6.txt                   | ""                    | ""       | [[destPath]]                    | C:\moved0.txt         | ""                | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 8  | [[sourcePath]]                  | c:\movefile7.txt                   | ""                    | ""       | [[destPath]]                    | C:\moved0.txt         | ""                | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 9  | [[sourcePath]]                  | c:\movefile8.txt                   | ""                    | ""       | [[destPath]]                    | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 10 | [[sourcePath]]                  | c:\movefile9.txt                   | ""                    | ""       | [[destPath]]                    | C:\moved0.txt         | dev2              | Q/ulw&]      | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 11 | [[sourcePath]]                  | c:\movefile10.txt                  | ""                    | ""       | [[destPath]]                    | C:\moved0.txt         | ""                | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 12 | [[sourcePath]]                  | c:\movefile11.txt                  | ""                    | ""       | [[destPath]]                    | C:\moved0.txt         | ""                | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 13 | [[sourcePath]]                  | c:\movefile12.txt                  | ""                    | ""       | [[destPath]]                    | C:\moved0.txt         | ""                | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 14 | [[sourcePath]]                  | c:\movefile13.txt                  | ""                    | ""       | [[destPath]]                    | C:\moved0.txt         | ""                | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 15 | [[sourcePath]]                  | c:\movefile14.txt                  | ""                    | ""       | [[destPath]]                    | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 16 | [[a]][[b]]                      | c:\movefile15.txt                  | ""                    | ""       | [[destPath]]                    | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 17 | [[a]]\[[b]]                     | c:\movefile16.txt                  | ""                    | ""       | [[destPath]]                    | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 18 | [[a]][[b]].txt                  | c:\movefile17.txt                  | ""                    | ""       | [[destPath]]                    | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 19 | [[a]]:[[b]]                     | c:\movefile18.txt                  | ""                    | ""       | [[destPath]]                    | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 20 | C:[[a]][[b]].txt                | c:\movefile19.txt                  | ""                    | ""       | [[destPath]]                    | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 21 | [[rec(1).a]][[rec(2).a]]        | c:\movefile20.txt                  | ""                    | ""       | [[destPath]]                    | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 22 | [[rec(1).a]]\[[rec(2).a]]       | c:\movefile21.txt                  | ""                    | ""       | [[destPath]]                    | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 23 | [[rec(1).a]][[rec(2).a]] .txt   | c:\movefile22.txt                  | ""                    | ""       | [[destPath]]                    | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 24 | [[rec(1).a]]:[[rec(2).a]]       | c:\movefile23.txt                  | ""                    | ""       | [[destPath]]                    | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 25 | C:[[rec(1).a]][[rec(2).a]] .txt | c:\movefile24.txt                  | ""                    | ""       | [[destPath]]                    | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 26 | c:\copyfile0.txt                | c:\movefile25.txt                  | ""                    | ""       | [[destPath]]                    | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 27 | [[rec([[index]]).a]]            | c:\movefile26.txt                  | ""                    | ""       | [[destPath]]                    | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 28 | c:\copyfile0.txt                | c:\movefile27.txt                  | ""                    | ""       | [[destPath]]                    | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 29 | [[sourcePath]]                  | c:\movefile28.txt                  | ""                    | ""       | [[a]][[b]]                      | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 30 | [[sourcePath]]                  | c:\movefile29.txt                  | ""                    | ""       | [[a]]\[[b]]                     | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 31 | [[sourcePath]]                  | c:\movefile30.txt                  | ""                    | ""       | [[a]][[b]].txt                  | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 32 | [[sourcePath]]                  | c:\movefile31.txt                  | ""                    | ""       | [[a]]:[[b]]                     | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 33 | [[sourcePath]]                  | c:\movefile32.txt                  | ""                    | ""       | C:[[a]][[b]].txt                | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 34 | [[sourcePath]]                  | c:\movefile33.txt                  | ""                    | ""       | [[rec(1).a]][[rec(2).a]]        | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 35 | [[sourcePath]]                  | c:\movefile34.txt                  | ""                    | ""       | [[rec(1).a]]\[[rec(2).a]]       | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 36 | [[sourcePath]]                  | c:\movefile35.txt                  | ""                    | ""       | [[rec(1).a]][[rec(2).a]] .txt   | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 37 | [[sourcePath]]                  | c:\movefile36.txt                  | ""                    | ""       | [[rec(1).a]]:[[rec(2).a]]       | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 38 | [[sourcePath]]                  | c:\movefile37.txt                  | ""                    | ""       | C:[[rec(1).a]][[rec(2).a]] .txt | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 39 | [[sourcePath]]                  | c:\movefile38.txt                  | ""                    | ""       | c:\copyfile0.txt                | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 40 | [[sourcePath]]                  | c:\movefile39.txt                  | ""                    | ""       | [[rec([[index]]).a]]            | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 41 | [[sourcePath]]                  | c:\movefile40.txt                  | ""                    | ""       | c:\copyfile0.txt                | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |
#		| 42 | [[a&]]                          |                                    | ""                    | ""       | [[destPath]]                    | fC:\moved0.txt        | integrationtester | I73573r0     | True     | [[result]] | ""      | AN           | True             | File or Folder - Variable name [[a&]] contains invalid character(s)           | 1.File or Folder - Variable name [[a&]] contains invalid character(s)           |
#		| 43 | [[rec(**).a]]                   |                                    | ""                    | ""       | [[destPath]]                    | fC:\moved0.txt        | integrationtester | I73573r0     | True     | [[result]] | ""      | AN           | True             | File or Folder - Recordset index (**) contains invalid character(s)           | 1.File or Folder - Recordset index (**) contains invalid character(s)           |
#		| 44 | [[a]                            |                                    | ""                    | ""       | [[destPath]]                    | fC:\moved0.txt        | integrationtester | I73573r0     | True     | [[result]] | ""      | AN           | True             | File or Folder - Invalid expression: opening and closing brackets don't match | 1.File or Folder - Invalid expression: opening and closing brackets don't match |
#		| 45 | [[rec(a]]                       |                                    | ""                    | ""       | [[destPath]]                    | fC:\moved0.txt        | integrationtester | I73573r0     | True     | [[result]] | ""      | AN           | True             | File or Folder - Recordset name [[rec(a]] contains invalid character(s)       | 1.File or Folder - Recordset name [[rec(a]] contains invalid character(s)       |
#		| 46 | c(*()                           |                                    | ""                    | ""       | [[destPath]]                    | fC:\moved0.txt        | integrationtester | I73573r0     | True     | [[result]] | ""      | AN           | True             | Please supply a valid File or Folder                                          | 1.Please supply a valid File or Folder                                          |
#		| 47 | [[rec([[inde$x]]).a]]           |                                    | ""                    | ""       | [[destPath]]                    | fC:\moved0.txt        | integrationtester | I73573r0     | True     | [[result]] | ""      | AN           | True             | File or Folder - Variable name [[inde$x]]  contains invalid character(s)      | 1.File or Folder - Variable name [[inde$x]]  contains invalid character(s)      |
#		| 48 | ghjghj                          |                                    | ""                    | ""       | [[destPath]]                    | fC:\moved0.txt        | integrationtester | I73573r0     | True     | [[result]] | ""      | AN           | True             | Please supply a valid File or Folder                                          | 1.Please supply a valid File or Folder                                          |
#		| 49 | ""                              |                                    | ""                    | ""       | [[destPath]]                    | fC:\moved0.txt        | integrationtester | I73573r0     | True     | [[result]] | ""      | AN           | True             | File or Folder cannot be empty or only white space                            | 1.File or Folder cannot be empty or only white space                            |
#		| 50 | [[sourcePath]]                  | c:\copyfile41.txt                  | ""                    | ""       | [[a&]]                          | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | ""      | AN           | True             | Destination - Variable name [[a&]] contains invalid character(s)              | 1.Destination - Variable name [[a&]] contains invalid character(s)              |
#		| 51 | [[sourcePath]]                  | c:\copyfile42.txt                  | ""                    | ""       | [[rec(**).a]]                   | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | ""      | AN           | True             | Destination - Recordset index (**) contains invalid character(s)              | 1.Destination - Recordset index (**) contains invalid character(s)              |
#		| 52 | [[sourcePath]]                  | c:\copyfile43.txt                  | ""                    | ""       | [[a]                            | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | ""      | AN           | True             | Destination - Invalid expression: opening and closing brackets don't match    | 1.Destination - Invalid expression: opening and closing brackets don't match    |
#		| 53 | [[sourcePath]]                  | c:\copyfile44.txt                  | ""                    | ""       | [[rec(a]]                       | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | ""      | AN           | True             | Destination - Recordset name [[rec(a]] contains invalid character(s)          | 1.Destination - Recordset name [[rec(a]] contains invalid character(s)          |
#		| 54 | [[sourcePath]]                  | c:\copyfile45.txt                  | ""                    | ""       | c(*()                           | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | ""      | AN           | True             | Please supply a valid File or Folder                                          | 1.Please supply a valid File or Folder                                          |
#		| 55 | [[sourcePath]]                  | c:\copyfile46.txt                  | ""                    | ""       | [[rec([[inde$x]]).a]]           | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | ""      | AN           | True             | Destination - Variable name [[inde$x]]  contains invalid character(s)         | 1.Destination - Variable name [[inde$x]]  contains invalid character(s)         |
#		| 56 | [[sourcePath]]                  | c:\copyfile47.txt                  | ""                    | ""       | ghjghj                          | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | ""      | AN           | True             | Please supply a valid File or Folder                                          | 1.Please supply a valid File or Folder                                          |
#		| 57 | [[sourcePath]]                  | c:\copyfile48.txt                  | ""                    | ""       | ""                              | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | ""      | AN           | True             | Destination cannot be empty or only white space                               | 1.Destination cannot be empty or only white space                               |
#		| 58 | [[sourcePath]]                  | c:\copyfile49.txt                  | [[a&]]                | String   | [[destPath]]                    | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | ""      | AN           | True             | Username - Variable name [[a&]] contains invalid character(s)                 | 1.Username - Variable name [[a&]] contains invalid character(s)                 |
#		| 59 | [[sourcePath]]                  | c:\copyfile50.txt                  | [[rec(**).a]]         | String   | [[destPath]]                    | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | ""      | AN           | True             | Username - Recordset index (**) contains invalid character(s)                 | 1.Username - Recordset index (**) contains invalid character(s)                 |
#		| 60 | [[sourcePath]]                  | c:\copyfile51.txt                  | [[a]                  | String   | [[destPath]]                    | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | ""      | AN           | True             | Username - Invalid expression: opening and closing brackets don't match       | 1.Username - Invalid expression: opening and closing brackets don't match       |
#		| 61 | [[sourcePath]]                  | c:\copyfile52.txt                  | [[rec(a]]             | String   | [[destPath]]                    | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | ""      | AN           | True             | Username - Recordset name [[rec(a]] contains invalid character(s)             | 1.Username - Recordset name [[rec(a]] contains invalid character(s)             |
#		| 62 | [[sourcePath]]                  | c:\copyfile53.txt                  | [[rec([[inde$x]]).a]] | String   | [[destPath]]                    | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | ""      | AN           | True             | Username - Variable name [[inde$x]]  contains invalid character(s)            | 1.Username - Variable name [[inde$x]]  contains invalid character(s)            |
#		| 63 | [[sourcePath]]                  | c:\copyfile54.txt                  |                       | String   | [[destPath]]                    | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | ""      | AN           | True             | Username cannot be empty or only white space                                  | 1.Username cannot be empty or only white space                                  |
#		| 64 | [[sourcePath]]                  | c:\copyfile55.txt                  | [[a&]]                | String   | [[destPath]]                    | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | ""      | AN           | True             | Username - Variable name [[a&]] contains invalid character(s)                 | 1.Destination Username - Variable name [[a&]] contains invalid character(s)     |
#		| 65 | [[sourcePath]]                  | c:\copyfile56.txt                  | [[rec(**).a]]         | String   | [[destPath]]                    | C:\moved0.txt         | integrationtester | I73573r0     | True     | [[result]] | ""      | AN           | True             | Username - Recordset index (**) contains invalid character(s)                 | 1.Destination Username - Recordset index (**) contains invalid character(s)     |
	