<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>10.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dev2.Common.Interfaces\Dev2.Common.Interfaces.csproj" />
    <ProjectReference Include="..\Dev2.Common\Dev2.Common.csproj" />
    <ProjectReference Include="..\Dev2.Diagnostics\Dev2.Diagnostics.csproj" />
    <ProjectReference Include="..\Warewolf.Interfaces\Warewolf.Interfaces.csproj" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
  </ItemGroup>

</Project>
