# For more information on GitHub Actions, refer to https://github.com/features/actions

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Compile
      run: &.\Compile.ps1 -AcceptanceTesting
      
    - name: Zip
      run: &'C:/Builds/7Zip/7za.exe' u -up0q3r2x2y2z1w2 ${{ env.Wap_Project_Directory }}\AcceptanceTesting.zip .\Bin\AcceptanceTesting\*

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: AcceptanceTesting.zip
        path: ${{ env.Wap_Project_Directory }}\AcceptanceTesting.zip
