@fileFeature
Feature: Copy
	In order to be able to Copy File or Folder 
	as a Warewolf user
	I want a tool that Copy File or Folder from a given location to another location

Scenario Outline: Copy file at location
	Given I have a source path '<source>' with value '<sourceLocation>' 
	And source credentials as '<username>' and '<password>'
	And I have a destination path '<destination>' with value '<destinationLocation>'
    And destination credentials as '<destUsername>' and '<destPassword>'
	And overwrite is '<selected>'
	And result as '<resultVar>'
    When the copy file tool is executed
	Then the result variable '<resultVar>' will be '<result>'
	And the execution has "<errorOccured>" error
	And the debug inputs as
         | Source Path                 | Username   | Password | Destination Path                      | Destination Username | Destination Password | Overwrite  |
         | <source> = <sourceLocation> | <username> | String   | <destination> = <destinationLocation> | <destUsername>       | String               | <selected> |
	And the debug output as
		|                        |
		| <resultVar> = <result> |
	Examples: 
		 | No     | source         | sourceLocation                                               | username                       | password | destination  | destinationLocation                                        | destUsername                 | destPassword | selected | resultVar  | result     | errorOccured |
		 | 1      | [[sourcePath]] | c:\copyfile0.txt                                             | ""                             | ""       | [[destPath]] | C:\copied00.txt                                            | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 2      | [[sourcePath]] | c:\copyfile1.txt                                             | ""                             | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/copied0.txt          | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 3      | [[sourcePath]] | c:\copyfile2.txt                                             | ""                             | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied0.txt          | integrationtester            | I73573r0     | True     | [[result]] | Success    | NO           |
		 | 4      | [[sourcePath]] | c:\copyfile3.txt                                             | ""                             | ""       | [[destPath]] | sftp://localhost/copied0.txt                               | dev2                         | Q/ulw&]      | True     | [[result]] | Success    | NO           |
		 | 5      | [[sourcePath]] | c:\copyfile4.txt                                             | ""                             | ""       | [[destPath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copied0.txt | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 6      | [[sourcePath]] | c:\copyfile5.txt                                             | ""                             | ""       | [[destPath]] | C:\copied01.txt                                            | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 7      | [[sourcePath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copyfile0.txt | ""                             | ""       | [[destPath]] | C:\copied10.txt                                            | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 8      | [[sourcePath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copyfile1.txt | ""                             | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/copied1.txt          | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 9      | [[sourcePath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copyfile2.txt | ""                             | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied1.txt          | integrationtester            | I73573r0     | True     | [[result]] | Success    | NO           |
		 | 10     | [[sourcePath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copyfile3.txt | ""                             | ""       | [[destPath]] | sftp://localhost/copied1.txt                               | dev2                         | Q/ulw&]      | True     | [[result]] | Success    | NO           |
		 | 11     | [[sourcePath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copyfile4.txt | ""                             | ""       | [[destPath]] | C:\copied11.txt                                            | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 12     | [[sourcePath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copyfile5.txt | ""                             | ""       | [[destPath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copied1.txt | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 13     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/copyfile0.txt          | ""                             | ""       | [[destPath]] | C:\copied20.txt                                            | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 14     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/copyfile1.txt          | ""                             | ""       | [[destPath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copied2.txt | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 15     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/copyfile2.txt          | ""                             | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester            | I73573r0     | True     | [[result]] | Success    | NO           |
		 | 16     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/copyfile3.txt          | ""                             | ""       | [[destPath]] | sftp://localhost/copied2.txt                               | dev2                         | Q/ulw&]      | True     | [[result]] | Success    | NO           |
		 | 17     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/copyfile4.txt          | ""                             | ""       | [[destPath]] | C:\copied21.txt                                            | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 18     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/copyfile5.txt          | ""                             | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/copied2.txt          | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 19     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copyfile0.txt          | integrationtester              | I73573r0 | [[destPath]] | C:\copied30.txt                                            | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 20     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copyfile1.txt          | integrationtester              | I73573r0 | [[destPath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copied3.txt | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 21     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copyfile2.txt          | integrationtester              | I73573r0 | [[destPath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/copied3.txt          | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 22     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copyfile3.txt          | integrationtester              | I73573r0 | [[destPath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied3.txt          | integrationtester            | I73573r0     | True     | [[result]] | Success    | NO           |
		 | 23     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copyfile4.txt          | integrationtester              | I73573r0 | [[destPath]] | C:\copied31.txt                                            | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 24     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copyfile5.txt          | integrationtester              | I73573r0 | [[destPath]] | C:\copied32.txt                                            | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 25     | [[sourcePath]] | sftp://localhost/copyfile0.txt                               | dev2                           | Q/ulw&]  | [[destPath]] | C:\copied40.txt                                            | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 26     | [[sourcePath]] | sftp://localhost/copyfile1.txt                               | dev2                           | Q/ulw&]  | [[destPath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copied4.txt | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 27     | [[sourcePath]] | sftp://localhost/copyfile2.txt                               | dev2                           | Q/ulw&]  | [[destPath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/copied4.txt          | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 28     | [[sourcePath]] | sftp://localhost/copyfile3.txt                               | dev2                           | Q/ulw&]  | [[destPath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied4.txt          | integrationtester            | I73573r0     | True     | [[result]] | Success    | NO           |
		 | 29     | [[sourcePath]] | sftp://localhost/copyfile4.txt                               | dev2                           | Q/ulw&]  | [[destPath]] | C:\copied41.txt                                            | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 30     | [[sourcePath]] | sftp://localhost/copyfile5.txt                               | dev2                           | Q/ulw&]  | [[destPath]] | sftp://localhost/copied4.txt                               | dev2                         | Q/ulw&]      | True     | [[result]] | Success    | NO           |
  #12050 | 31             | [[sourcePath]]                                               | [[a]]                          | dev2     | Q/ulw&]      | [[destPath]]                                               | sftp://localhost/copied4.txt | dev2         | Q/ulw&]  | True       | [[result]] |              | AN |
  #      | 30             | [[sourcePath]]                                               | sftp://localhost/copyfile5.txt | [[a]]    | Q/ulw&]      | [[destPath]]                                               | sftp://localhost/copied4.txt | dev2         | Q/ulw&]  | True       | [[result]] |              | AN |
  #      | 30             | [[sourcePath]]                                               | sftp://localhost/copyfile5.txt | dev2     | [[a]]        | [[destPath]]                                               | sftp://localhost/copied4.txt | dev2         | Q/ulw&]  | True       | [[result]] |              | AN |
#
#

#BUG12180 #| [[sourcePath]] | c:\copyfile0.txt                                             | ""                | ""       | [[destPath]] | C:\copied00.txt                                            | ""                | ""           | True     | [[result]][[a]]        | Failure | AN           |
		  #| [[sourcePath]] | c:\copyfile0.txt                                             | ""                | ""       | [[destPath]] | C:\copied00.txt                                            | ""                | ""           | True     | [[a]]*]]               | Failure | AN           |
          #| [[sourcePath]] | c:\copyfile0.txt                                             | ""                | ""       | [[destPath]] | C:\copied00.txt                                            | ""                | ""           | True     | [[var@]]               | Failure | AN           |
          #| [[sourcePath]] | c:\copyfile0.txt                                             | ""                | ""       | [[destPath]] | C:\copied00.txt                                            | ""                | ""           | True     | [[var]]00]]            | Failure | AN           |
          #| [[sourcePath]] | c:\copyfile0.txt                                             | ""                | ""       | [[destPath]] | C:\copied00.txt                                            | ""                | ""           | True     | [[(1var)]]             | Failure | AN           |
          #| [[sourcePath]] | c:\copyfile0.txt                                             | ""                | ""       | [[destPath]] | C:\copied00.txt                                            | ""                | ""           | True     | [[var[[a]]]]           | Failure | AN           |
          #| [[sourcePath]] | c:\copyfile0.txt                                             | ""                | ""       | [[destPath]] | C:\copied00.txt                                            | ""                | ""           | True     | [[var.a]]              | Failure | AN           |
          #| [[sourcePath]] | c:\copyfile0.txt                                             | ""                | ""       | [[destPath]] | C:\copied00.txt                                            | ""                | ""           | True     | [[@var]]               | Failure | AN           |
          #| [[sourcePath]] | c:\copyfile0.txt                                             | ""                | ""       | [[destPath]] | C:\copied00.txt                                            | ""                | ""           | True     | [[var 1]]              | Failure | AN           |
          #| [[sourcePath]] | c:\copyfile0.txt                                             | ""                | ""       | [[destPath]] | C:\copied00.txt                                            | ""                | ""           | True     | [[rec(1).[[rec().1]]]] | Failure | AN           |
          #| [[sourcePath]] | c:\copyfile0.txt                                             | ""                | ""       | [[destPath]] | C:\copied00.txt                                            | ""                | ""           | True     | [[rec(@).a]]           | Failure | AN           |
          #| [[sourcePath]] | c:\copyfile0.txt                                             | ""                | ""       | [[destPath]] | C:\copied00.txt                                            | ""                | ""           | True     | [[rec"()".a]]          | Failure | AN           |
		  #| [[sourcePath]] | c:\copyfile0.txt                                             | ""                | ""       | [[destPath]] | C:\copied00.txt                                            | ""                | ""           | True     | [[rec([[[[b]]]]).a]]   | Failure | AN           |
																																																													 
	
##Hugs to scalfold
#Scenario Outline: Copy file at location1
#	Given I have a source path '<File or FOlder>' with value '<sourceLocation>' 
#	And source credentials as '<username>' and '<password>'
#	And I have a destination path '<destination>' with value '<destinationLocation>'
#   And destination credentials as '<destUsername>' and '<destPassword>'
#	And overwrite is '<selected>'
#	And result as '<resultVar>'
#	When validating the tool
#	Then validation is '<ValidationResult>'
#	And validation message is '<DesignValidation>'
#   When the copy file tool is executed
#	Then the result variable '<resultVar>' will be '<result>'
#	And the execution has "<errorOccured>" error
#	And the error message will be '<OutputError>'
#	And the debug inputs as
#        | Source Path                         | Username   | Password | Destination Path                      | Destination Username | Destination Password | Overwrite  |
#        | <File or FOlder> = <sourceLocation> | <username> | String   | <destination> = <destinationLocation> | <destUsername>       | String               | <selected> |
#	And the debug output as
#		|                        |
#		| <resultVar> = <result> |
#	Examples: 
#| No | File or FOlder                  | sourceLocation                                               | username | password | destination                     | destinationLocation                                        | destUsername          | destPassword | selected | resultVar  | result  | errorOccured | ValidationResult | DesignValidation                                                                                                                                                                                                      | OutputError                                                                                                                                                                                                           |
#| 1  | [[sourcePath]]                  | c:\copyfile0.txt                                             | ""       | ""       | [[destPath]]                    | C:\copied00.txt                                            | ""                    | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 2  | [[sourcePath]]                  | c:\copyfile1.txt                                             | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1001/FORTESTING/copied0.txt          | ""                    | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 3  | [[sourcePath]]                  | c:\copyfile2.txt                                             | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied0.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 4  | [[sourcePath]]                  | c:\copyfile3.txt                                             | ""       | ""       | [[destPath]]                    | sftp://localhost/copied0.txt                               | dev2                  | Q/ulw&]      | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 5  | [[sourcePath]]                  | c:\copyfile4.txt                                             | ""       | ""       | [[destPath]]                    | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copied0.txt | ""                    | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 6  | [[sourcePath]]                  | c:\copyfile5.txt                                             | ""       | ""       | [[destPath]]                    | C:\copied01.txt                                            | ""                    | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 7  | [[sourcePath]]                  | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copyfile0.txt | ""       | ""       | [[destPath]]                    | C:\copied10.txt                                            | ""                    | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 8  | [[sourcePath]]                  | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copyfile1.txt | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1001/FORTESTING/copied1.txt          | ""                    | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 9  | [[sourcePath]]                  | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copyfile2.txt | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied1.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 10 | [[sourcePath]]                  | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copyfile3.txt | ""       | ""       | [[destPath]]                    | sftp://localhost/copied1.txt                               | dev2                  | Q/ulw&]      | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 11 | [[sourcePath]]                  | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copyfile4.txt | ""       | ""       | [[destPath]]                    | C:\copied11.txt                                            | ""                    | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 12 | [[sourcePath]]                  | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copyfile5.txt | ""       | ""       | [[destPath]]                    | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copied1.txt | ""                    | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 13 | [[sourcePath]]                  | ftp://rsaklfsvrsbspdc:1001/FORTESTING/copyfile0.txt          | ""       | ""       | [[destPath]]                    | C:\copied20.txt                                            | ""                    | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 14 | [[sourcePath]]                  | ftp://rsaklfsvrsbspdc:1001/FORTESTING/copyfile1.txt          | ""       | ""       | [[destPath]]                    | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copied2.txt | ""                    | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 15 | [[sourcePath]]                  | ftp://rsaklfsvrsbspdc:1001/FORTESTING/copyfile2.txt          | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 16 | [[a]][[b]]                      | c:\copyfile0.txt                                             | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 17 | [[a]]\[[b]]                     | c:\copyfile0.txt                                             | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 18 | [[a]][[b]].txt                  | c:\copyfile0.txt                                             | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 19 | [[a]]:[[b]]                     | c:\copyfile0.txt                                             | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 20 | C:[[a]][[b]].txt                | c:\copyfile0.txt                                             | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 21 | [[rec(1).a]][[rec(2).a]]        | c:\copyfile0.txt                                             | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 22 | [[rec(1).a]]\[[rec(2).a]]       | c:\copyfile0.txt                                             | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 23 | [[rec(1).a]][[rec(2).a]] .txt   | c:\copyfile0.txt                                             | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 24 | [[rec(1).a]]:[[rec(2).a]]       | c:\copyfile0.txt                                             | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 25 | C:[[rec(1).a]][[rec(2).a]] .txt | c:\copyfile0.txt                                             | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 26 | c:\copyfile0.txt                | c:\copyfile0.txt                                             | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 27 | [[rec([[index]]).a]]            | c:\copyfile0.txt                                             | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 28 | c:\copyfile0.txt                | c:\copyfile0.txt                                             | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 29 | [[sourcePath]]                  | c:\copyfile0.txt                                             | ""       | ""       | [[a]][[b]]                      | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 31 | [[sourcePath]]                  | c:\copyfile0.txt                                             | ""       | ""       | [[a]]\[[b]]                     | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 32 | [[sourcePath]]                  | c:\copyfile0.txt                                             | ""       | ""       | [[a]][[b]].txt                  | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 33 | [[sourcePath]]                  | c:\copyfile0.txt                                             | ""       | ""       | [[a]]:[[b]]                     | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 34 | [[sourcePath]]                  | c:\copyfile0.txt                                             | ""       | ""       | C:[[a]][[b]].txt                | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 35 | [[sourcePath]]                  | c:\copyfile0.txt                                             | ""       | ""       | [[rec(1).a]][[rec(2).a]]        | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 36 | [[sourcePath]]                  | c:\copyfile0.txt                                             | ""       | ""       | [[rec(1).a]]\[[rec(2).a]]       | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 37 | [[sourcePath]]                  | c:\copyfile0.txt                                             | ""       | ""       | [[rec(1).a]][[rec(2).a]] .txt   | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 38 | [[sourcePath]]                  | c:\copyfile0.txt                                             | ""       | ""       | [[rec(1).a]]:[[rec(2).a]]       | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 39 | [[sourcePath]]                  | c:\copyfile0.txt                                             | ""       | ""       | C:[[rec(1).a]][[rec(2).a]] .txt | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 40 | [[sourcePath]]                  | c:\copyfile0.txt                                             | ""       | ""       | c:\copyfile0.txt                | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    |                                                                                                                                                                                                                       |
#| 41 | [[sourcePath]]                  | c:\copyfile0.txt                                             | ""       | ""       | [[rec([[index]]).a]]            | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    |                                                                                                                                                                                                                       |
#| 42 | [[sourcePath]]                  | c:\copyfile0.txt                                             | ""       | ""       | [[a]]&[[b]]                     | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 43 | [[sourcePath]]                  | c:\copyfile0.txt                                             | ""       | ""       | c:\copyfile0.txt                | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Success | NO           | False            | ""                                                                                                                                                                                                                    | ""                                                                                                                                                                                                                    |
#| 44 | [[a&]]                          |                                                              | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Failure | AN           | True             | File or Folder - Variable name [[a&]] contains invalid character(s)                                                                                                                                                   | 1.File or Folder - Variable name [[a&]] contains invalid character(s)                                                                                                                                                 |
#| 45 | [[rec(**).a]]                   |                                                              | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Failure | AN           | True             | File or Folder - Variable name [[rec(**).a]]  contains invalid character(s)                                                                                                                                           | 1."File or Folder - Variable name [[rec(**).a]]  contains invalid character(s)                                                                                                                                        |
#| 46 | [[a]][b]]                       |                                                              | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Failure | AN           | True             | File or Folder - Variable name [[a]]&[[b]]  contains invalid character(s)                                                                                                                                             | 1.File or Folder - Variable name [[a]]&[[b]]  contains invalid character(s)                                                                                                                                           |
#| 47 | c(*()                           |                                                              | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Failure | AN           | True             |                                                                                                                                                                                                                       | 1."Please supply a valid File or Folder"                                                                                                                                                                              |
#| 48 | C:\\\\\gvh                      |                                                              | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Failure | AN           | True             | Please supply a valid File or Folder                                                                                                                                                                                  | 1.Directory not found [ C:\\\\\gvh** ] 2. Problems Evaluating Expression [ ]                                                                                                                                          |
#| 49 | [[rec(**).a]]                   |                                                              | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Failure | AN           | True             | File or Folder - Variable name [[rec(**).a]]  contains invalid character(s)                                                                                                                                           | 1."File or Folder - Variable name [[rec(**).a]]  contains invalid character(s)                                                                                                                                        |
#| 50 | [[a]]&[[b]]                     |                                                              | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Failure | AN           | True             | File or Folder - Variable name [[a]]&[[b]]  contains invalid character(s)                                                                                                                                             | 1.File or Folder - Variable name [[a]]&[[b]]  contains invalid character(s)                                                                                                                                           |
#| 51 | [[a]][b]]                       |                                                              | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Failure | AN           | True             | File or Folder - Variable name [[a]]&[[b]]  contains invalid character(s)                                                                                                                                             | 1.File or Folder - Variable name [[a]]&[[b]]  contains invalid character(s)                                                                                                                                           |
#| 52 | c(*()                           |                                                              | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Failure | AN           | True             | Please supply a valid File or Folder"                                                                                                                                                                                 | 1."Please supply a valid File or Folder"                                                                                                                                                                              |
#| 53 | [[rec([[inde$x]]).a]]           |                                                              | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester     | I73573r0     | True     | [[result]] | Failure | AN           | True             | File or Folder - Variable name [[index$x]]  contains invalid character(s)                                                                                                                                             | 1.File or Folder - Variable name [[index$x]]  contains invalid character(s)                                                                                                                                           |
#| 54 | [[sourcePath]]                  | c:\copyfile0.txt                                             | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | [[rec([[inde$x]]).a]] | I73573r0     | True     | [[result]] | Failure | AN           | True             | Destination Username - Variable name [[rec(**).a]]  contains invalid character(s)                                                                                                                                     | 1.Destination Username - Variable name [[rec(**).a]]  contains invalid character(s)                                                                                                                                   |
#| 55 | [[sourcePath]]                  | c:\copyfile0.txt                                             | ""       | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | [[s3*]]               | I73573r0     | True     | [[result]] | Failure | AN           | True             | Destination Username - Variable name [[s3*]]   contains invalid character(s)                                                                                                                                          | 1.Destination Username - Variable name [[s3*]]  contains invalid character(s)                                                                                                                                         |
#| 56 | [[rec(**).a]]                   |                                                              | ""       | ""       | [[rec(**).a]]                   |                                                            | [[s3*]]               | I73573r0     | True     | [[result]] | Failure | AN           | True             | 1.File or Folder - Variable name (**) contains invalid character(s) 2.Destination - Recordset index (**) contains invalid character(s) 3.Destination Username - Variable name [[s3*]]   contains invalid character(s) | 1.File or Folder - Variable name (**) contains invalid character(s) 2.Destination - Recordset index (**) contains invalid character(s) 3.Destination Username - Variable name [[s3*]]   contains invalid character(s) |
		 
		 
		 
		 	 
		 
		 
		 
		 
		 
		 
		 
	




























