@fileFeature
Feature: Copy
	In order to be able to Copy File or Folder 
	as a Warewolf user
	I want a tool that Copy File or Folder from a given location to another location

Scenario Outline: Copy file at location
	Given I have a source path '<source>' with value '<sourceLocation>' 
	And source credentials as '<username>' and '<password>'
	And I have a destination path '<destination>' with value '<destinationLocation>'
    And destination credentials as '<destUsername>' and '<destPassword>'
	And overwrite is '<selected>'
	And result as '<resultVar>'
    When the copy file tool is executed
	Then the result variable '<resultVar>' will be '<result>'
	And the execution has "<errorOccured>" error
	And the debug inputs as
         | Source Path                 | Username   | Password | Destination Path                      | Destination Username | Destination Password | Overwrite  |
         | <source> = <sourceLocation> | <username> | String   | <destination> = <destinationLocation> | <destUsername>       | String               | <selected> |
	And the debug output as
		|                        |
		| <resultVar> = <result> |
	Examples: 
		 | No     | source         | sourceLocation                                               | username                       | password | destination  | destinationLocation                                        | destUsername                 | destPassword | selected | resultVar  | result     | errorOccured |
		 | 1      | [[sourcePath]] | c:\copyfile0.txt                                             | ""                             | ""       | [[destPath]] | C:\copied00.txt                                            | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 2      | [[sourcePath]] | c:\copyfile1.txt                                             | ""                             | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/copied0.txt          | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 3      | [[sourcePath]] | c:\copyfile2.txt                                             | ""                             | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied0.txt          | integrationtester            | I73573r0     | True     | [[result]] | Success    | NO           |
		 | 4      | [[sourcePath]] | c:\copyfile3.txt                                             | ""                             | ""       | [[destPath]] | sftp://localhost/copied0.txt                               | dev2                         | Q/ulw&]      | True     | [[result]] | Success    | NO           |
		 | 5      | [[sourcePath]] | c:\copyfile4.txt                                             | ""                             | ""       | [[destPath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copied0.txt | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 6      | [[sourcePath]] | c:\copyfile5.txt                                             | ""                             | ""       | [[destPath]] | C:\copied01.txt                                            | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 7      | [[sourcePath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copyfile0.txt | ""                             | ""       | [[destPath]] | C:\copied10.txt                                            | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 8      | [[sourcePath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copyfile1.txt | ""                             | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/copied1.txt          | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 9      | [[sourcePath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copyfile2.txt | ""                             | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied1.txt          | integrationtester            | I73573r0     | True     | [[result]] | Success    | NO           |
		 | 10     | [[sourcePath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copyfile3.txt | ""                             | ""       | [[destPath]] | sftp://localhost/copied1.txt                               | dev2                         | Q/ulw&]      | True     | [[result]] | Success    | NO           |
		 | 11     | [[sourcePath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copyfile4.txt | ""                             | ""       | [[destPath]] | C:\copied11.txt                                            | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 12     | [[sourcePath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copyfile5.txt | ""                             | ""       | [[destPath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copied1.txt | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 13     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/copyfile0.txt          | ""                             | ""       | [[destPath]] | C:\copied20.txt                                            | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 14     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/copyfile1.txt          | ""                             | ""       | [[destPath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copied2.txt | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 15     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/copyfile2.txt          | ""                             | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester            | I73573r0     | True     | [[result]] | Success    | NO           |
		 | 16     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/copyfile3.txt          | ""                             | ""       | [[destPath]] | sftp://localhost/copied2.txt                               | dev2                         | Q/ulw&]      | True     | [[result]] | Success    | NO           |
		 | 17     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/copyfile4.txt          | ""                             | ""       | [[destPath]] | C:\copied21.txt                                            | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 18     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/copyfile5.txt          | ""                             | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/copied2.txt          | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 19     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copyfile0.txt          | integrationtester              | I73573r0 | [[destPath]] | C:\copied30.txt                                            | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 20     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copyfile1.txt          | integrationtester              | I73573r0 | [[destPath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copied3.txt | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 21     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copyfile2.txt          | integrationtester              | I73573r0 | [[destPath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/copied3.txt          | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 22     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copyfile3.txt          | integrationtester              | I73573r0 | [[destPath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied3.txt          | integrationtester            | I73573r0     | True     | [[result]] | Success    | NO           |
		 | 23     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copyfile4.txt          | integrationtester              | I73573r0 | [[destPath]] | C:\copied31.txt                                            | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 24     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copyfile5.txt          | integrationtester              | I73573r0 | [[destPath]] | C:\copied32.txt                                            | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 25     | [[sourcePath]] | sftp://localhost/copyfile0.txt                               | dev2                           | Q/ulw&]  | [[destPath]] | C:\copied40.txt                                            | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 26     | [[sourcePath]] | sftp://localhost/copyfile1.txt                               | dev2                           | Q/ulw&]  | [[destPath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copied4.txt | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 27     | [[sourcePath]] | sftp://localhost/copyfile2.txt                               | dev2                           | Q/ulw&]  | [[destPath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/copied4.txt          | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 28     | [[sourcePath]] | sftp://localhost/copyfile3.txt                               | dev2                           | Q/ulw&]  | [[destPath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied4.txt          | integrationtester            | I73573r0     | True     | [[result]] | Success    | NO           |
		 | 29     | [[sourcePath]] | sftp://localhost/copyfile4.txt                               | dev2                           | Q/ulw&]  | [[destPath]] | C:\copied41.txt                                            | ""                           | ""           | True     | [[result]] | Success    | NO           |
		 | 30     | [[sourcePath]] | sftp://localhost/copyfile5.txt                               | dev2                           | Q/ulw&]  | [[destPath]] | sftp://localhost/copied4.txt                               | dev2                         | Q/ulw&]      | True     | [[result]] | Success    | NO           |
  #12050 | 31             | [[sourcePath]]                                               | [[a]]                          | dev2     | Q/ulw&]      | [[destPath]]                                               | sftp://localhost/copied4.txt | dev2         | Q/ulw&]  | True       | [[result]] |              | AN |
  #      | 30             | [[sourcePath]]                                               | sftp://localhost/copyfile5.txt | [[a]]    | Q/ulw&]      | [[destPath]]                                               | sftp://localhost/copied4.txt | dev2         | Q/ulw&]  | True       | [[result]] |              | AN |
  #      | 30             | [[sourcePath]]                                               | sftp://localhost/copyfile5.txt | dev2     | [[a]]        | [[destPath]]                                               | sftp://localhost/copied4.txt | dev2         | Q/ulw&]  | True       | [[result]] |              | AN |
#
#

#BUG12180 #| [[sourcePath]] | c:\copyfile0.txt                                             | ""                | ""       | [[destPath]] | C:\copied00.txt                                            | ""                | ""           | True     | [[result]][[a]]        | Failure | AN           |
		  #| [[sourcePath]] | c:\copyfile0.txt                                             | ""                | ""       | [[destPath]] | C:\copied00.txt                                            | ""                | ""           | True     | [[a]]*]]               | Failure | AN           |
          #| [[sourcePath]] | c:\copyfile0.txt                                             | ""                | ""       | [[destPath]] | C:\copied00.txt                                            | ""                | ""           | True     | [[var@]]               | Failure | AN           |
          #| [[sourcePath]] | c:\copyfile0.txt                                             | ""                | ""       | [[destPath]] | C:\copied00.txt                                            | ""                | ""           | True     | [[var]]00]]            | Failure | AN           |
          #| [[sourcePath]] | c:\copyfile0.txt                                             | ""                | ""       | [[destPath]] | C:\copied00.txt                                            | ""                | ""           | True     | [[(1var)]]             | Failure | AN           |
          #| [[sourcePath]] | c:\copyfile0.txt                                             | ""                | ""       | [[destPath]] | C:\copied00.txt                                            | ""                | ""           | True     | [[var[[a]]]]           | Failure | AN           |
          #| [[sourcePath]] | c:\copyfile0.txt                                             | ""                | ""       | [[destPath]] | C:\copied00.txt                                            | ""                | ""           | True     | [[var.a]]              | Failure | AN           |
          #| [[sourcePath]] | c:\copyfile0.txt                                             | ""                | ""       | [[destPath]] | C:\copied00.txt                                            | ""                | ""           | True     | [[@var]]               | Failure | AN           |
          #| [[sourcePath]] | c:\copyfile0.txt                                             | ""                | ""       | [[destPath]] | C:\copied00.txt                                            | ""                | ""           | True     | [[var 1]]              | Failure | AN           |
          #| [[sourcePath]] | c:\copyfile0.txt                                             | ""                | ""       | [[destPath]] | C:\copied00.txt                                            | ""                | ""           | True     | [[rec(1).[[rec().1]]]] | Failure | AN           |
          #| [[sourcePath]] | c:\copyfile0.txt                                             | ""                | ""       | [[destPath]] | C:\copied00.txt                                            | ""                | ""           | True     | [[rec(@).a]]           | Failure | AN           |
          #| [[sourcePath]] | c:\copyfile0.txt                                             | ""                | ""       | [[destPath]] | C:\copied00.txt                                            | ""                | ""           | True     | [[rec"()".a]]          | Failure | AN           |
		  #| [[sourcePath]] | c:\copyfile0.txt                                             | ""                | ""       | [[destPath]] | C:\copied00.txt                                            | ""                | ""           | True     | [[rec([[[[b]]]]).a]]   | Failure | AN           |
																																																													 
	
##Hugs to scalfold
#Scenario Outline: Copy file at location1
#	Given I have a source path '<File or Folder>' with value '<sourceLocation>' 
#	And source credentials as '<username>' and '<password>'
#	And I have a destination path '<destination>' with value '<destinationLocation>'
#    And destination credentials as '<destUsername>' and '<destPassword>'
#	And overwrite is '<selected>'
#	And result as '<resultVar>'
#	When validating the tool
#	Then validation is '<ValidationResult>'
#	And validation message is '<DesignValidation>'
#    When the copy file tool is executed
#	Then the result variable '<resultVar>' will be '<result>'
#	And the execution has "<errorOccured>" error
#	And execution error message will be '<DesignValidation>'
#	And the debug inputs as
#        | Source Path                         | Username   | Password | Destination Path                      | Destination Username | Destination Password | Overwrite  |
#        | <File or FOlder> = <sourceLocation> | <username> | String   | <destination> = <destinationLocation> | <destUsername>       | String               | <selected> |
#	And the debug output as
#		|                        |
#		| <resultVar> = <result> |
#	Examples: 
#		| No | File or Folder                  | sourceLocation   | username              | password | destination                     | destinationLocation                                        | destUsername      | destPassword | selected | resultVar              | result  | errorOccured | ValidationResult | DesignValidation                                                              | OutputError                                                                           |
#		| No | [[sourcePath]]                  | c:\copyfile3.txt | ""                    | ""       | [[destPath]]                    | sftp://localhost/copied0.txt                               | dev2              | Q/ulw&]      | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 4  | [[sourcePath]]                  | c:\copyfile4.txt | ""                    | ""       | [[destPath]]                    | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copied0.txt | ""                | ""           | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 5  | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | [[destPath]]                    | C:\copied00.txt                                            | ""                | ""           | Truee    | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 1  | [[sourcePath]]                  | c:\copyfile1.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1001/FORTESTING/copied0.txt          | ""                | ""           | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 2  | [[sourcePath]]                  | c:\copyfile2.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied0.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 3  | [[sourcePath]]                  | c:\copyfile5.txt | ""                    | ""       | [[destPath]]                    | C:\copied01.txt                                            | ""                | ""           | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 6  | [[sourcePath]]                  | c:\copyfile3.txt | ""                    | ""       | [[destPath]]                    | C:\copied10.txt                                            | ""                | ""           | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 7  | [[sourcePath]]                  | c:\copyfile3.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1001/FORTESTING/copied1.txt          | ""                | ""           | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 8  | [[sourcePath]]                  | c:\copyfile3.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied1.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 9  | [[sourcePath]]                  | c:\copyfile3.txt | ""                    | ""       | [[destPath]]                    | sftp://localhost/copied1.txt                               | dev2              | Q/ulw&]      | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 10 | [[sourcePath]]                  | c:\copyfile3.txt | ""                    | ""       | [[destPath]]                    | C:\copied11.txt                                            | ""                | ""           | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 11 | [[sourcePath]]                  | c:\copyfile3.txt | ""                    | ""       | [[destPath]]                    | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copied1.txt | ""                | ""           | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 12 | [[sourcePath]]                  | c:\copyfile3.txt | ""                    | ""       | [[destPath]]                    | C:\copied20.txt                                            | ""                | ""           | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 13 | [[sourcePath]]                  | c:\copyfile3.txt | ""                    | ""       | [[destPath]]                    | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\copied2.txt | ""                | ""           | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 14 | [[sourcePath]]                  | c:\copyfile3.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 15 | [[a]][[b]]                      | c:\copyfile0.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 16 | [[a]]\[[b]]                     | c:\copyfile0.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 17 | [[a]][[b]].txt                  | c:\copyfile0.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 18 | [[a]]:[[b]]                     | c:\copyfile0.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 19 | C:[[a]][[b]].txt                | c:\copyfile0.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 20 | [[rec(1).a]][[rec(2).a]]        | c:\copyfile0.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 21 | [[rec(1).a]]\[[rec(2).a]]       | c:\copyfile0.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 22 | [[rec(1).a]][[rec(2).a]] .txt   | c:\copyfile0.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 23 | [[rec(1).a]]:[[rec(2).a]]       | c:\copyfile0.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 24 | C:[[rec(1).a]][[rec(2).a]] .txt | c:\copyfile0.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 25 | c:\copyfile0.txt                | c:\copyfile0.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 26 | [[rec([[index]]).a]]            | c:\copyfile0.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 27 | c:\copyfile0.txt                | c:\copyfile0.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 28 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | [[a]][[b]]                      | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 29 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | [[a]]\[[b]]                     | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 30 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | [[a]][[b]].txt                  | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 31 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | [[a]]:[[b]]                     | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 32 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | C:[[a]][[b]].txt                | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 33 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | [[rec(1).a]][[rec(2).a]]        | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 34 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | [[rec(1).a]]\[[rec(2).a]]       | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 35 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | [[rec(1).a]][[rec(2).a]] .txt   | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 36 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | [[rec(1).a]]:[[rec(2).a]]       | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 37 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | C:[[rec(1).a]][[rec(2).a]] .txt | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 38 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | c:\copyfile0.txt                | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 39 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | [[rec([[index]]).a]]            | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 40 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | c:\copyfile0.txt                | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 41 | [[a&]]                          |                  | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | File or Folder - Variable name [[a&]] contains invalid character(s)           | 1.File or Folder - Variable name [[a&]] contains invalid character(s)                 |
#		| 42 | [[rec(**).a]]                   |                  | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | File or Folder - Recordset index (**) contains invalid character(s)           | 1.File or Folder - Recordset index (**) contains invalid character(s)                 |
#		| 43 | [[a]                            |                  | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | File or Folder - Invalid expression: opening and closing brackets don't match | 1.File or Folder - Invalid expression: opening and closing brackets don't match       |
#		| 44 | [[rec(a]]                       |                  | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | File or Folder - Recordset name [[rec(a]] contains invalid character(s)       | 1.File or Folder - Recordset name [[rec(a]] contains invalid character(s)             |
#		| 45 | c(*()                           |                  | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Please supply a valid File or Folder                                          | 1.Please supply a valid File or Folder                                                |
#		| 46 | [[rec([[inde$x]]).a]]           |                  | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | File or Folder - Variable name [[inde$x]]  contains invalid character(s)      | 1.File or Folder - Variable name [[inde$x]]  contains invalid character(s)            |
#		| 47 | ghjghj                          |                  | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Please supply a valid File or Folder                                          | 1.Please supply a valid File or Folder                                                |
#		| 48 | ""                              |                  | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | File or Folder cannot be empty or only white space                            | 1.File or Folder cannot be empty or only white space                                  |
#		| 49 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | [[a&]]                          | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Destination - Variable name [[a&]] contains invalid character(s)              | 1.Destination - Variable name [[a&]] contains invalid character(s)                    |
#		| 50 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | [[rec(**).a]]                   | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Destination - Recordset index (**) contains invalid character(s)              | 1.Destination - Recordset index (**) contains invalid character(s)                    |
#		| 51 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | [[a]                            | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Destination - Invalid expression: opening and closing brackets don't match    | 1.Destination - Invalid expression: opening and closing brackets don't match          |
#		| 52 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | [[rec(a]]                       | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Destination - Recordset name [[rec(a]] contains invalid character(s)          | 1.Destination - Recordset name [[rec(a]] contains invalid character(s)                |
#		| 53 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | c(*()                           | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Please supply a valid File or Folder                                          | 1.Please supply a valid File or Folder                                                |
#		| 54 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | [[rec([[inde$x]]).a]]           | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Destination - Variable name [[inde$x]]  contains invalid character(s)         | 1.Destination - Variable name [[inde$x]]  contains invalid character(s)               |
#		| 55 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | ghjghj                          | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Please supply a valid File or Folder                                          | 1.Please supply a valid File or Folder                                                |
#		| 56 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | ""                              | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Destination cannot be empty or only white space                               | 1.Destination cannot be empty or only white space                                     |
#		| 57 | [[sourcePath]]                  | c:\copyfile0.txt | [[a&]]                | String   | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Username - Variable name [[a&]] contains invalid character(s)                 | 1.Username - Variable name [[a&]] contains invalid character(s)                       |
#		| 58 | [[sourcePath]]                  | c:\copyfile0.txt | [[rec(**).a]]         | String   | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Username - Recordset index (**) contains invalid character(s)                 | 1.Username - Recordset index (**) contains invalid character(s)                       |
#		| 59 | [[sourcePath]]                  | c:\copyfile0.txt | [[a]                  | String   | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Username - Invalid expression: opening and closing brackets don't match       | 1.Username - Invalid expression: opening and closing brackets don't match             |
#		| 60 | [[sourcePath]]                  | c:\copyfile0.txt | [[rec(a]]             | String   | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Username - Recordset name [[rec(a]] contains invalid character(s)             | 1.Username - Recordset name [[rec(a]] contains invalid character(s)                   |
#		| 61 | [[sourcePath]]                  | c:\copyfile0.txt | [[rec([[inde$x]]).a]] | String   | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Username - Variable name [[inde$x]]  contains invalid character(s)            | 1.Username - Variable name [[inde$x]]  contains invalid character(s)                  |
#		| 62 | [[sourcePath]]                  | c:\copyfile0.txt |                       | String   | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Username cannot be empty or only white space                                  | 1.Username cannot be empty or only white space                                        |
#		| 63 | [[sourcePath]]                  | c:\copyfile0.txt | [[a&]]                | String   | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Username - Variable name [[a&]] contains invalid character(s)                 | 1.Destination Username - Variable name [[a&]] contains invalid character(s)           |
#		| 64 | [[sourcePath]]                  | c:\copyfile0.txt | [[rec(**).a]]         | String   | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Username - Recordset index (**) contains invalid character(s)                 | 1.Destination Username - Recordset index (**) contains invalid character(s)           |
#		| 65 | [[sourcePath]]                  | c:\copyfile0.txt | [[a]                  | String   | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Username - Invalid expression: opening and closing brackets don't match       | 1.Destination Username - Invalid expression: opening and closing brackets don't match |
#		| 66 | [[sourcePath]]                  | c:\copyfile0.txt | [[rec(a]]             | String   | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Username - Recordset name [[rec(a]] contains invalid character(s)             | 1.Destination Username - Recordset name [[rec(a]] contains invalid character(s)       |
#		| 67 | [[sourcePath]]                  | c:\copyfile0.txt | [[rec([[inde$x]]).a]] | String   | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Username - Variable name [[inde$x]]  contains invalid character(s)            | 1.Destination Username - Variable name [[inde$x]]  contains invalid character(s)      |
#		| 68 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | String   | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Username cannot be empty or only white space                                  | 1.Destination Username cannot be empty or only white space                            |
#		| 69 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[result]][[a]]        | ""      | AN           | True             | The result field only allows a single result                                  | 1.The result field only allows a single result                                        |
#		| 70 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[a]]*]]               | ""      | AN           | True             | Result - Invalid expression: opening and closing brackets don't match         | 1.Result - Invalid expression: opening and closing brackets don't match               |
#		| 71 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[var@]]               | ""      | AN           | True             | Result - Variable name [[var@]] contains invalid character(s)                 | 1.Result - Variable name [[var@]] contains invalid character(s)                       |
#		| 72 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[var]]00]]            | ""      | AN           | True             | Result - Invalid expression: opening and closing brackets don't match         | 1.Result - Invalid expression: opening and closing brackets don't match               |
#		| 73 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[(1var)]]             | ""      | AN           | True             | Result - Variable name [[1var]] contains invalid character(s)                 | 1.Result - Variable name [[1var]] contains invalid character(s)                       |
#		| 74 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[var[[a]]]]           | ""      | AN           | True             | Result - Invalid Region [[var[[a]]]]                                          | 1.Result - Invalid Region [[var[[a]]]]                                                |
#		| 75 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[var.a]]              | ""      | AN           | True             | Result - Variable name [[var.a]]contains invalid character(s)                 | 1.Result - Variable name [[var.a]] contains invalid character(s)                      |
#		| 76 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[@var]]               | ""      | AN           | True             | Result - Variable name [[@var]] contains invalid character(s)                 | 1.Result - Variable name [[@var]] contains invalid character(s)                       |
#		| 77 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[var 1]]              | ""      | AN           | True             | Result - Variable name [[var 1]] contains invalid character(s)                | 1.Result - Variable name [[var 1]] contains invalid character(s)                      |
#		| 78 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[rec(1).[[rec().1]]]] | ""      | AN           | True             | Result - Invalid Region [[rec(1).[[rec().1]]]]                                | 1.Result - Invalid Region [[rec(1).[[rec().1]]]]                                      |
#		| 79 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[rec(@).a]]           | ""      | AN           | True             | Result - Recordset index [[@]] contains invalid character(s)                  | 1.Result - Recordset index [[@]] contains invalid character(s)                        |
#		| 80 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[rec"()".a]]          | ""      | AN           | True             | Result - Recordset name [[rec"()"]] contains invalid character(s)             | 1.Result - Recordset name [[rec"()"]] contains invalid character(s)                   |
#		| 81 | [[sourcePath]]                  | c:\copyfile0.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/copied2.txt          | integrationtester | I73573r0     | True     | [[rec([[[[b]]]]).a]]   | ""      | AN           | True             | Result - Invalid Region [[rec([[[[b]]]]).a]]                                  | 1.Result - Invalid Region [[rec([[[[b]]]]).a]]                                        |
		
			  	  																																																																				 

		
	
		
		
		
		
		
		
		
		
		
		
		
		
		 	 
		 
		 
		 
		 
		 
		 
		 
	




























