@fileFeature
Feature: Zip
	In order to be able to Zip File or Folder 
	as a Warewolf user
	I want a tool that Zip File or Folder at a given location

Scenario Outline: Zip file at location
	Given I have a source path '<source>' with value '<sourceLocation>'
	And source credentials as '<username>' and '<password>'
	And I have a destination path '<destination>' with value '<destinationLocation>'
	And destination credentials as '<destUsername>' and '<destPassword>'
	And overwrite is '<selected>'
	And result as '<resultVar>'	
	And Archive Password as '<archivepassword>'
	And the Compression as '<compression>'
    When the Zip file tool is executed
	Then the result variable '<resultVar>' will be '<result>'
	And the execution has "<errorOccured>" error
	And the debug inputs as
         | Source Path                 | Username   | Password | Destination Path                      | Destination Username | Destination Password | Overwrite  | Archive Password  | Compression Ratio |
         | <source> = <sourceLocation> | <username> | String   | <destination> = <destinationLocation> | <destUsername>       | String               | <selected> | <archivepassword> | <compression>     |
	And the debug output as
		|                        |
		| <resultVar> = <result> |
	Examples: 
		| No | Name           | source   | sourceLocation                                                | username          | password | destination | destinationLocation                                           | destUsername      | destPassword | selected | archivepassword | compression     | resultVar  | result  | errorOccured |
		| 1  | Local to Local | [[path]] | c:\filetozip0.txt                                             | ""                | ""       | [[path1]]   | c:\My New0.zip                                                | ""                | ""           | True     |                 | NoCompression   | [[result]] | Success | NO           |
		| 2  | UNC to Local   | [[path]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\filetozip0.txt | ""                | ""       | [[path1]]   | c:\My New1.zip                                                | ""                | ""           | True     |                 | BestSpeed       | [[result]] | Success | NO           |
		| 3  | FTP to Local   | [[path]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/filetozip0.txt          | ""                | ""       | [[path1]]   | c:\My New2.zip                                                | ""                | ""           | True     |                 | Default         | [[result]] | Success | NO           |
		| 4  | FTPS to Local  | [[path]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/filetozip0.txt          | integrationtester | I73573r0 | [[path1]]   | c:\My New3.zip                                                | ""                | ""           | True     |                 | BestCompression | [[result]] | Success | NO           |
		| 5  | SFTP to Local  | [[path]] | sftp://localhost/filetozip0.txt                               | dev2              | Q/ulw&]  | [[path1]]   | c:\My New4.zip                                                | ""                | ""           | True     |                 | NoCompression   | [[result]] | Success | NO           |
		| 6  | Local to UNC   | [[path]] | c:\filetozip1.txt                                             | ""                | ""       | [[path1]]   | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\filetozip10.txt | ""                | ""           | True     |                 | BestSpeed       | [[result]] | Success | NO           |
		| 7  | UNC to UNC     | [[path]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\filetozip1.txt | ""                | ""       | [[path1]]   | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\filetozip11.txt | ""                | ""           | True     |                 | Default         | [[result]] | Success | NO           |
		| 8  | FTP to UNC     | [[path]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/filetozip1.txt          | ""                | ""       | [[path1]]   | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\filetozip12.txt | ""                | ""           | True     |                 | BestCompression | [[result]] | Success | NO           |
		| 9  | FTPS to UNC    | [[path]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/filetozip1.txt          | integrationtester | I73573r0 | [[path1]]   | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\filetozip13.txt | ""                | ""           | True     |                 | NoCompression   | [[result]] | Success | NO           |
		| 10 | SFTP to UNC    | [[path]] | sftp://localhost/filetozip1.txt                               | dev2              | Q/ulw&]  | [[path1]]   | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\filetozip14.txt | ""                | ""           | True     |                 | BestSpeed       | [[result]] | Success | NO           |
		| 11 | Local to FTP   | [[path]] | c:\filetozip2.txt                                             | ""                | ""       | [[path1]]   | ftp://rsaklfsvrsbspdc:1001/FORTESTING/filetozip10.txt          | ""                | ""           | True     |                 | Default         | [[result]] | Success | NO           |
		| 12 | UNC to FTP     | [[path]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\filetozip2.txt | ""                | ""       | [[path1]]   | ftp://rsaklfsvrsbspdc:1001/FORTESTING/filetozip11.txt          | ""                | ""           | True     |                 | BestCompression | [[result]] | Success | NO           |
		| 13 | FTP to FTP     | [[path]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/filetozip2.txt          | ""                | ""       | [[path1]]   | ftp://rsaklfsvrsbspdc:1001/FORTESTING/filetozip12.txt          | ""                | ""           | True     |                 | NoCompression   | [[result]] | Success | NO           |
		| 14 | FTPS to FTP    | [[path]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/filetozip2.txt          | integrationtester | I73573r0 | [[path1]]   | ftp://rsaklfsvrsbspdc:1001/FORTESTING/filetozip13.txt          | ""                | ""           | True     |                 | BestSpeed       | [[result]] | Success | NO           |
		| 15 | SFTP to FTP    | [[path]] | sftp://localhost/filetozip2.txt                               | dev2              | Q/ulw&]  | [[path1]]   | ftp://rsaklfsvrsbspdc:1001/FORTESTING/filetozip14.txt          | ""                | ""           | True     |                 | Default         | [[result]] | Success | NO           |
		| 16 | Local to FTPS  | [[path]] | c:\filetozip3.txt                                             | ""                | ""       | [[path1]]   | ftp://rsaklfsvrsbspdc:1002/FORTESTING/filetozip20.txt          | integrationtester | I73573r0     | True     |                 | BestCompression | [[result]] | Success | NO           |
		| 17 | UNC to FTPS    | [[path]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\filetozip3.txt | ""                | ""       | [[path1]]   | ftp://rsaklfsvrsbspdc:1002/FORTESTING/filetozip21.txt          | integrationtester | I73573r0     | True     |                 | NoCompression   | [[result]] | Success | NO           |
		| 18 | FTP to FTPS    | [[path]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/filetozip3.txt          | ""                | ""       | [[path1]]   | ftp://rsaklfsvrsbspdc:1002/FORTESTING/filetozip22.txt          | integrationtester | I73573r0     | True     |                 | BestSpeed       | [[result]] | Success | NO           |
		| 19 | FTPS to FTPS   | [[path]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/filetozip3.txt          | integrationtester | I73573r0 | [[path1]]   | ftp://rsaklfsvrsbspdc:1002/FORTESTING/filetozip23.txt          | integrationtester | I73573r0     | True     |                 | Default         | [[result]] | Success | NO           |
		| 20 | SFTP to FTPS   | [[path]] | sftp://localhost/filetozip3.txt                               | dev2              | Q/ulw&]  | [[path1]]   | ftp://rsaklfsvrsbspdc:1002/FORTESTING/filetozip24.txt          | integrationtester | I73573r0     | True     |                 | BestCompression | [[result]] | Success | NO           |
		| 21 | Local to SFTP  | [[path]] | c:\filetozip4.txt                                             | ""                | ""       | [[path1]]   | sftp://localhost/filetozip10.txt                               | dev2              | Q/ulw&]      | True     |                 | NoCompression   | [[result]] | Success | NO           |
		| 22 | UNC to SFTP    | [[path]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\filetozip4.txt | ""                | ""       | [[path1]]   | sftp://localhost/filetozip11.txt                               | dev2              | Q/ulw&]      | True     |                 | BestSpeed       | [[result]] | Success | NO           |
		| 23 | FTP to SFTP    | [[path]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/filetozip4.txt          | ""                | ""       | [[path1]]   | sftp://localhost/filetozip12.txt                               | dev2              | Q/ulw&]      | True     |                 | Default         | [[result]] | Success | NO           |
		| 24 | FTPS to SFTP   | [[path]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/filetozip4.txt          | integrationtester | I73573r0 | [[path1]]   | sftp://localhost/filetozip13.txt                               | dev2              | Q/ulw&]      | True     |                 | BestCompression | [[result]] | Success | NO           |
		| 25 | SFTP to SFTP   | [[path]] | sftp://localhost/filetozip4.txt                               | dev2              | Q/ulw&]  | [[path1]]   | sftp://localhost/filetozip14.txt                               | dev2              | Q/ulw&]      | True     |                 | NoCompression   | [[result]] | Success | NO           |




#Scenario Outline: Zip file at location1
#    Given I have a variable "[[a]]" with a value '<Val1>'
#	Given I have a variable "[[b]]" with a value '<Val2>'
#	Given I have a variable "[[rec(1).a]]" with a value '<Val1>'
#	Given I have a variable "[[rec(2).a]]" with a value '<Val2>'
#	Given I have a variable "[[index]]" with a value "1"
#	Given I have a source path '<File or Folder>' with value '<sourceLocation>' 
#	And source credentials as '<username>' and '<password>'
#	And I have a destination path '<destination>' with value '<destinationLocation>'
#    And destination credentials as '<destUsername>' and '<destPassword>'
#	And overwrite is '<selected>'
#	And result as '<resultVar>'
#	And Archive Password as '<archivepassword>'
#	And the Compression as '<compression>'
#	When validating the tool
#	Then validation is '<ValidationResult>'
#	And validation message is '<DesignValidation>'
#    When the Unzip file tool is executed
#	Then the result variable '<resultVar>' will be '<result>'
#	And the execution has "<errorOccured>" error
#	And execution error message will be '<DesignValidation>'
#	And the debug inputs as
#        | Source Path                         | Username   | Password | Destination Path                      | Destination Username | Destination Password | Overwrite  |
#        | <File or FOlder> = <sourceLocation> | <username> | String   | <destination> = <destinationLocation> | <destUsername>       | String               | <selected> |
#	And the debug output as
#		|                        |
#		| <resultVar> = <result> |
#	Examples: 
#		| No | File or Folder                 |                 |                  | sourceLocation     | username              | password | destination                    | destinationLocation | destUsername      | destPassword | selected | resultVar              | archivepassword | compression   | result  | errorOccured | ValidationResult | DesignValidation                                                              | OutputError                                                                           |
#		| No | [[sourcePath]]                 | ""              | ""               | c:\filetozip7.txt  | ""                    | ""       | [[destPath]]                   | c:\My New9.zip      | dev2              | Q/ulw&]      | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 4  | [[sourcePath]]                 | ""              | ""               | c:\filetozip10.zip | ""                    | ""       | [[destPath]]                   | c:\My New10.zip     | ""                | ""           | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 5  | [[sourcePath]]                 | ""              | ""               | c:\filetozip11.zip | ""                    | ""       | [[destPath]]                   | c:\My New11.zip     | ""                | ""           | Truee    | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 1  | [[sourcePath]]                 | ""              | ""               | c:\filetozip12.zip | ""                    | ""       | [[destPath]]                   | c:\My New12.zip     | ""                | ""           | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 2  | [[sourcePath]]                 | ""              | ""               | c:\filetozip13.zip | ""                    | ""       | [[destPath]]                   | c:\My New13.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 3  | [[sourcePath]]                 | ""              | ""               | c:\filetozip14.zip | ""                    | ""       | [[destPath]]                   | c:\My New14.zip     | ""                | ""           | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 6  | [[sourcePath]]                 | ""              | ""               | c:\filetozip15.zip | ""                    | ""       | [[destPath]]                   | c:\My New15.zip     | ""                | ""           | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 7  | [[sourcePath]]                 | ""              | ""               | c:\filetozip16.zip | ""                    | ""       | [[destPath]]                   | c:\My New16.zip     | ""                | ""           | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 8  | [[sourcePath]]                 | ""              | ""               | c:\filetozip17.zip | ""                    | ""       | [[destPath]]                   | c:\My New17.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 9  | [[sourcePath]]                 | ""              | ""               | c:\filetozip18.zip | ""                    | ""       | [[destPath]]                   | c:\My New18.zip     | dev2              | Q/ulw&]      | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 10 | [[sourcePath]]                 | ""              | ""               | c:\filetozip19.zip | ""                    | ""       | [[destPath]]                   | c:\My New19.zip     | ""                | ""           | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 11 | [[sourcePath]]                 | ""              | ""               | c:\filetozip20.zip | ""                    | ""       | [[destPath]]                   | c:\My New20.zip     | ""                | ""           | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 12 | [[sourcePath]]                 | ""              | ""               | c:\filetozip21.zip | ""                    | ""       | [[destPath]]                   | c:\My New21.zip     | ""                | ""           | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 13 | [[sourcePath]]                 | ""              | ""               | c:\filetozip22.zip | ""                    | ""       | [[destPath]]                   | c:\My New22.zip     | ""                | ""           | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 14 | [[sourcePath]]                 | ""              | ""               | c:\filetozip23.zip | ""                    | ""       | [[destPath]]                   | c:\My New23.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 15 | [[a]][[b]]                     | c:\fileto       | zip24.zip        | c:\filetozip24.zip | ""                    | ""       | [[destPath]]                   | c:\My New24.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 16 | [[a]]\[[b]]                    | c:              | filetozip25.zip  | c:\filetozip25.zip | ""                    | ""       | [[destPath]]                   | c:\My New25.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 17 | [[a]][[b]].zip                 | c:\file         | tozip26          | c:\filetozip26.zip | ""                    | ""       | [[destPath]]                   | c:\My New26.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 18 | [[a]]:[[b]]                    | c               | \filetozip27.zip | c:\filetozip27.zip | ""                    | ""       | [[destPath]]                   | c:\My New27.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 19 | C:[[a]][[b]].zip               | \fileto         | zip28            | c:\filetozip28.zip | ""                    | ""       | [[destPath]]                   | c:\My New28.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 20 | [[rec(1).a]][[rec(2).a]]       | c:\fileto       | zip29.zip        | c:\filetozip29.zip | ""                    | ""       | [[destPath]]                   | c:\My New29.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 21 | [[rec(1).a]]\[[rec(2).a]]      | c:              | filetozip30.zip  | c:\filetozip30.zip | ""                    | ""       | [[destPath]]                   | c:\My New30.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 22 | [[rec(1).a]][[rec(2).a]].zip   | c:\file         | tozip31          | c:\filetozip31.zip | ""                    | ""       | [[destPath]]                   | c:\My New31.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 23 | [[rec(1).a]]:[[rec(2).a]]      | c               | \filetozip32.zip | c:\filetozip32.zip | ""                    | ""       | [[destPath]]                   | c:\My New32.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 24 | C:[[rec(1).a]][[rec(2).a]].zip | \file           | tozip33          | c:\filetozip33.zip | ""                    | ""       | [[destPath]]                   | c:\My New33.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 25 | c:\filetozip0.txt              | ""              | ""               | c:\filetozip34.zip | ""                    | ""       | [[destPath]]                   | c:\My New34.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 26 | [[rec([[index]]).a]]           | ""              | ""               | c:\filetozip35.zip | ""                    | ""       | [[destPath]]                   | c:\My New35.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 27 | c:\filetozip36.zip             | ""              | ""               | c:\filetozip36.zip | ""                    | ""       | [[destPath]]                   | c:\My New36.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 28 | [[sourcePath]]                 | c:\My New37     | .zip             | c:\filetozip37.zip | ""                    | ""       | [[a]][[b]]                     | c:\My New37.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 29 | [[sourcePath]]                 | c:              | My New38.zip     | c:\filetozip38.zip | ""                    | ""       | [[a]]/[[b]]                    | c:\My New38.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 30 | [[sourcePath]]                 | c:\My New       | 39               | c:\filetozip39.zip | ""                    | ""       | [[a]][[b]].zip                 | c:\My New39.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 31 | [[sourcePath]]                 | c               | \My New40.zip    | c:\filetozip40.zip | ""                    | ""       | [[a]]:[[b]]                    | c:\My New40.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 32 | [[sourcePath]]                 | \My New         | 41               | c:\filetozip41.zip | ""                    | ""       | C:[[a]][[b]].zip               | c:\My New41.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 33 | [[sourcePath]]                 | c:\My New42     | .zip             | c:\filetozip42.zip | ""                    | ""       | [[rec(1).a]][[rec(2).a]]       | c:\My New42.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 34 | [[sourcePath]]                 | c:              | My New43.zip     | c:\filetozip43.zip | ""                    | ""       | [[rec(1).a]]\[[rec(2).a]]      | c:\My New43.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 35 | [[sourcePath]]                 | :\My            | New44            | c:\filetozip44.zip | ""                    | ""       | [[rec(1).a]][[rec(2).a]].zip   | c:\My New44.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 36 | [[sourcePath]]                 | c               | \My New45.zip    | c:\filetozip45.zip | ""                    | ""       | [[rec(1).a]]:[[rec(2).a]]      | c:\My New45.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 37 | [[sourcePath]]                 | \My New         | 46               | c:\filetozip46.zip | ""                    | ""       | C:[[rec(1).a]][[rec(2).a]].zip | c:\My New46.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 38 | [[sourcePath]]                 | ""              | ""               | c:\filetozip47.zip | ""                    | ""       | c:\filetozip0.txt              | c:\My New47.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 39 | [[sourcePath]]                 | c:\My New48.zip | ""               | c:\filetozip48.zip | ""                    | ""       | [[rec([[index]]).a]]           | c:\My New48.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 40 | [[sourcePath]]                 | ""              | ""               | c:\filetozip49.zip | ""                    | ""       | c:\filetozip0.txt              | c:\My New49.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 41 | [[a&]]                         | ""              | ""               |                    | ""                    | ""       | [[destPath]]                   | c:\My New50.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | ""      | AN           | True             | File or Folder - Variable name [[a&]] contains invalid character(s)           | 1.File or Folder - Variable name [[a&]] contains invalid character(s)                 |
#		| 42 | [[rec(**).a]]                  | ""              | ""               |                    | ""                    | ""       | [[destPath]]                   | c:\My New51.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | ""      | AN           | True             | File or Folder - Recordset index (**) contains invalid character(s)           | 1.File or Folder - Recordset index (**) contains invalid character(s)                 |
#		| 43 | [[a]                           | ""              | ""               |                    | ""                    | ""       | [[destPath]]                   | c:\My New52.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | ""      | AN           | True             | File or Folder - Invalid expression: opening and closing brackets don't match | 1.File or Folder - Invalid expression: opening and closing brackets don't match       |
#		| 44 | [[rec(a]]                      | ""              | ""               |                    | ""                    | ""       | [[destPath]]                   | c:\My New53.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | ""      | AN           | True             | File or Folder - Recordset name [[rec(a]] contains invalid character(s)       | 1.File or Folder - Recordset name [[rec(a]] contains invalid character(s)             |
#		| 45 | c(*()                          | ""              | ""               |                    | ""                    | ""       | [[destPath]]                   | c:\My New54.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | ""      | AN           | True             | Please supply a valid File or Folder                                          | 1.Please supply a valid File or Folder                                                |
#		| 46 | [[rec([[inde$x]]).a]]          | ""              | ""               |                    | ""                    | ""       | [[destPath]]                   | c:\My New55.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | ""      | AN           | True             | File or Folder - Variable name [[inde$x]]  contains invalid character(s)      | 1.File or Folder - Variable name [[inde$x]]  contains invalid character(s)            |
#		| 47 | ghjghj                         | ""              | ""               |                    | ""                    | ""       | [[destPath]]                   | c:\My New56.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | ""      | AN           | True             | Please supply a valid File or Folder                                          | 1.Please supply a valid File or Folder                                                |
#		| 48 | ""                             | ""              | ""               |                    | ""                    | ""       | [[destPath]]                   | c:\My New57.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | ""      | AN           | True             | File or Folder cannot be empty or only white space                            | 1.File or Folder cannot be empty or only white space                                  |
#		| 49 | [[sourcePath]]                 | ""              | ""               | c:\filetozip50.txt | ""                    | ""       | [[a&]]                         | c:\My New58.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | ""      | AN           | True             | Destination - Variable name [[a&]] contains invalid character(s)              | 1.Destination - Variable name [[a&]] contains invalid character(s)                    |
#		| 50 | [[sourcePath]]                 | ""              | ""               | c:\filetozip51.txt | ""                    | ""       | [[rec(**).a]]                  | c:\My New59.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | ""      | AN           | True             | Destination - Recordset index (**) contains invalid character(s)              | 1.Destination - Recordset index (**) contains invalid character(s)                    |
#		| 51 | [[sourcePath]]                 | ""              | ""               | c:\filetozip52.txt | ""                    | ""       | [[a]                           | c:\My New60.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | ""      | AN           | True             | Destination - Invalid expression: opening and closing brackets don't match    | 1.Destination - Invalid expression: opening and closing brackets don't match          |
#		| 52 | [[sourcePath]]                 | ""              | ""               | c:\filetozip53.txt | ""                    | ""       | [[rec(a]]                      | c:\My New61.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | ""      | AN           | True             | Destination - Recordset name [[rec(a]] contains invalid character(s)          | 1.Destination - Recordset name [[rec(a]] contains invalid character(s)                |
#		| 53 | [[sourcePath]]                 | ""              | ""               | c:\filetozip54.txt | ""                    | ""       | c(*()                          | c:\My New62.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | ""      | AN           | True             | Please supply a valid File or Folder                                          | 1.Please supply a valid File or Folder                                                |
#		| 54 | [[sourcePath]]                 | ""              | ""               | c:\filetozip55.txt | ""                    | ""       | [[rec([[inde$x]]).a]]          | c:\My New63.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | ""      | AN           | True             | Destination - Variable name [[inde$x]]  contains invalid character(s)         | 1.Destination - Variable name [[inde$x]]  contains invalid character(s)               |
#		| 55 | [[sourcePath]]                 | ""              | ""               | c:\filetozip56.txt | ""                    | ""       | ghjghj                         | c:\My New64.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | ""      | AN           | True             | Please supply a valid File or Folder                                          | 1.Please supply a valid File or Folder                                                |
#		| 56 | [[sourcePath]]                 | ""              | ""               | c:\filetozip57.txt | ""                    | ""       | ""                             | c:\My New65.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | ""      | AN           | True             | Destination cannot be empty or only white space                               | 1.Destination cannot be empty or only white space                                     |
#		| 57 | [[sourcePath]]                 | ""              | ""               | c:\filetozip58.txt | [[a&]]                | String   | [[destPath]]                   | c:\My New66.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | ""      | AN           | True             | Username - Variable name [[a&]] contains invalid character(s)                 | 1.Username - Variable name [[a&]] contains invalid character(s)                       |
#		| 58 | [[sourcePath]]                 | ""              | ""               | c:\filetozip59.txt | [[rec(**).a]]         | String   | [[destPath]]                   | c:\My New67.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | ""      | AN           | True             | Username - Recordset index (**) contains invalid character(s)                 | 1.Username - Recordset index (**) contains invalid character(s)                       |
#		| 59 | [[sourcePath]]                 | ""              | ""               | c:\filetozip60.txt | [[a]                  | String   | [[destPath]]                   | c:\My New68.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | ""      | AN           | True             | Username - Invalid expression: opening and closing brackets don't match       | 1.Username - Invalid expression: opening and closing brackets don't match             |
#		| 60 | [[sourcePath]]                 | ""              | ""               | c:\filetozip61.txt | [[rec(a]]             | String   | [[destPath]]                   | c:\My New69.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | ""      | AN           | True             | Username - Recordset name [[rec(a]] contains invalid character(s)             | 1.Username - Recordset name [[rec(a]] contains invalid character(s)                   |
#		| 61 | [[sourcePath]]                 | ""              | ""               | c:\filetozip62.txt | [[rec([[inde$x]]).a]] | String   | [[destPath]]                   | c:\My New70.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | ""      | AN           | True             | Username - Variable name [[inde$x]]  contains invalid character(s)            | 1.Username - Variable name [[inde$x]]  contains invalid character(s)                  |
#		| 62 | [[sourcePath]]                 | ""              | ""               | c:\filetozip63.txt |                       | String   | [[destPath]]                   | c:\My New71.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | ""      | AN           | True             | Username cannot be empty or only white space                                  | 1.Username cannot be empty or only white space                                        |
#		| 63 | [[sourcePath]]                 | ""              | ""               | c:\filetozip64.txt | [[a&]]                | String   | [[destPath]]                   | c:\My New72.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | ""      | AN           | True             | Username - Variable name [[a&]] contains invalid character(s)                 | 1.Destination Username - Variable name [[a&]] contains invalid character(s)           |
#		| 64 | [[sourcePath]]                 | ""              | ""               | c:\filetozip65.txt | [[rec(**).a]]         | String   | [[destPath]]                   | c:\My New73.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | ""      | AN           | True             | Username - Recordset index (**) contains invalid character(s)                 | 1.Destination Username - Recordset index (**) contains invalid character(s)           |
#		| 65 | [[sourcePath]]                 | ""              | ""               | c:\filetozip66.txt | [[a]                  | String   | [[destPath]]                   | c:\My New74.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | ""      | AN           | True             | Username - Invalid expression: opening and closing brackets don't match       | 1.Destination Username - Invalid expression: opening and closing brackets don't match |
#		| 66 | [[sourcePath]]                 | ""              | ""               | c:\filetozip67.txt | [[rec(a]]             | String   | [[destPath]]                   | c:\My New75.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | ""      | AN           | True             | Username - Recordset name [[rec(a]] contains invalid character(s)             | 1.Destination Username - Recordset name [[rec(a]] contains invalid character(s)       |
#		| 67 | [[sourcePath]]                 | ""              | ""               | c:\filetozip68.txt | [[rec([[inde$x]]).a]] | String   | [[destPath]]                   | c:\My New76.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | ""      | AN           | True             | Username - Variable name [[inde$x]]  contains invalid character(s)            | 1.Destination Username - Variable name [[inde$x]]  contains invalid character(s)      |
#		| 68 | [[sourcePath]]                 | ""              | ""               | c:\filetozip69.txt | ""                    | String   | [[destPath]]                   | c:\My New77.zip     | integrationtester | I73573r0     | True     | [[result]]             | ""              | NoCompression | ""      | AN           | True             | Username cannot be empty or only white space                                  | 1.Destination Username cannot be empty or only white space                            |
#		| 69 | [[sourcePath]]                 | ""              | ""               | c:\filetozip70.txt | ""                    | ""       | [[destPath]]                   | c:\My New78.zip     | integrationtester | I73573r0     | True     | [[result]][[a]]        | ""              | NoCompression | ""      | AN           | True             | The result field only allows a single result                                  | 1.The result field only allows a single result                                        |
#		| 70 | [[sourcePath]]                 | ""              | ""               | c:\filetozip71.txt | ""                    | ""       | [[destPath]]                   | c:\My New79.zip     | integrationtester | I73573r0     | True     | [[a]]*]]               | ""              | NoCompression | ""      | AN           | True             | Result - Invalid expression: opening and closing brackets don't match         | 1.Result - Invalid expression: opening and closing brackets don't match               |
#		| 71 | [[sourcePath]]                 | ""              | ""               | c:\filetozip72.txt | ""                    | ""       | [[destPath]]                   | c:\My New80.zip     | integrationtester | I73573r0     | True     | [[var@]]               | ""              | NoCompression | ""      | AN           | True             | Result - Variable name [[var@]] contains invalid character(s)                 | 1.Result - Variable name [[var@]] contains invalid character(s)                       |
#		| 72 | [[sourcePath]]                 | ""              | ""               | c:\filetozip73.txt | ""                    | ""       | [[destPath]]                   | c:\My New81.zip     | integrationtester | I73573r0     | True     | [[var]]00]]            | ""              | NoCompression | ""      | AN           | True             | Result - Invalid expression: opening and closing brackets don't match         | 1.Result - Invalid expression: opening and closing brackets don't match               |
#		| 73 | [[sourcePath]]                 | ""              | ""               | c:\filetozip74.txt | ""                    | ""       | [[destPath]]                   | c:\My New82.zip     | integrationtester | I73573r0     | True     | [[(1var)]]             | ""              | NoCompression | ""      | AN           | True             | Result - Variable name [[1var]] contains invalid character(s)                 | 1.Result - Variable name [[1var]] contains invalid character(s)                       |
#		| 74 | [[sourcePath]]                 | ""              | ""               | c:\filetozip75.txt | ""                    | ""       | [[destPath]]                   | c:\My New83.zip     | integrationtester | I73573r0     | True     | [[var[[a]]]]           | ""              | NoCompression | ""      | AN           | True             | Result - Invalid Region [[var[[a]]]]                                          | 1.Result - Invalid Region [[var[[a]]]]                                                |
#		| 75 | [[sourcePath]]                 | ""              | ""               | c:\filetozip76.txt | ""                    | ""       | [[destPath]]                   | c:\My New84.zip     | integrationtester | I73573r0     | True     | [[var.a]]              | ""              | NoCompression | ""      | AN           | True             | Result - Variable name [[var.a]]contains invalid character(s)                 | 1.Result - Variable name [[var.a]] contains invalid character(s)                      |
#		| 76 | [[sourcePath]]                 | ""              | ""               | c:\filetozip77.txt | ""                    | ""       | [[destPath]]                   | c:\My New85.zip     | integrationtester | I73573r0     | True     | [[@var]]               | ""              | NoCompression | ""      | AN           | True             | Result - Variable name [[@var]] contains invalid character(s)                 | 1.Result - Variable name [[@var]] contains invalid character(s)                       |
#		| 77 | [[sourcePath]]                 | ""              | ""               | c:\filetozip78.txt | ""                    | ""       | [[destPath]]                   | c:\My New86.zip     | integrationtester | I73573r0     | True     | [[var 1]]              | ""              | NoCompression | ""      | AN           | True             | Result - Variable name [[var 1]] contains invalid character(s)                | 1.Result - Variable name [[var 1]] contains invalid character(s)                      |
#		| 78 | [[sourcePath]]                 | ""              | ""               | c:\filetozip79.txt | ""                    | ""       | [[destPath]]                   | c:\My New87.zip     | integrationtester | I73573r0     | True     | [[rec(1).[[rec().1]]]] | ""              | NoCompression | ""      | AN           | True             | Result - Invalid Region [[rec(1).[[rec().1]]]]                                | 1.Result - Invalid Region [[rec(1).[[rec().1]]]]                                      |
#		| 79 | [[sourcePath]]                 | ""              | ""               | c:\filetozip80.txt | ""                    | ""       | [[destPath]]                   | c:\My New88.zip     | integrationtester | I73573r0     | True     | [[rec(@).a]]           | ""              | NoCompression | ""      | AN           | True             | Result - Recordset index [[@]] contains invalid character(s)                  | 1.Result - Recordset index [[@]] contains invalid character(s)                        |
#		| 80 | [[sourcePath]]                 | ""              | ""               | c:\filetozip81.txt | ""                    | ""       | [[destPath]]                   | c:\My New89.zip     | integrationtester | I73573r0     | True     | [[rec"()".a]]          | ""              | NoCompression | ""      | AN           | True             | Result - Recordset name [[rec"()"]] contains invalid character(s)             | 1.Result - Recordset name [[rec"()"]] contains invalid character(s)                   |
#		| 81 | [[sourcePath]]                 | ""              | ""               | c:\filetozip82.txt | ""                    | ""       | [[destPath]]                   | c:\My New90.zip     | integrationtester | I73573r0     | True     | [[rec([[[[b]]]]).a]]   | ""              | NoCompression | ""      | AN           | True             | Result - Invalid Region [[rec([[[[b]]]]).a]]                                  | 1.Result - Invalid Region [[rec([[[[b]]]]).a]]                                        |
															
			  	  										                               