@Security
Feature: Settings Permissions
	In order to set permissions for my server
	As a Warewolf user
	I want to setup a Server Permissions

	Background: Initialize Feature Level settings
	
@ServerPermissionsSecurity
Scenario Outline: Server Permissions 
        Given I have Public with "<Given rights>" 
        Then resources should have "<Rights>"
Examples:
        | No |  Given rights                                      |  Rights                                            |
        | 1  |  Deploy To                                         |  Deploy To                                         |
        | 2  |  Deploy From                                       |  Deploy From                                       |
        | 3  |  View                                              |  View                                              |
        | 4  |  Execute                                           |  Execute                                           |
        | 5  |  Contribute, View, Execute                         |  Contribute, View, Execute                         |
        | 6  |  Deploy To, Deploy From                            |  Deploy To, Deploy From                            |
        | 7  |  View, Execute                                     |  View, Execute                                     |
        | 8  |  View, Execute, Contribute, Deploy To, Deploy From |  View, Execute, Contribute, Deploy To, Deploy From |
        | 9  |  Deploy To, View                                   |  Deploy To, View                                   |
        | 10 |  Deploy To, Execute                                |  Deploy To, Execute                                |
        | 11 |  Deploy To, Contribute, View, Execute              |  Deploy To, Contribute, View, Execute              |
        | 12 |  Deploy From, View                                 |  Deploy From, View                                 |
        | 13 |  Deploy From, Execute                              |  Deploy From, Execute                              |
        | 14 |  Deploy From, Contribute, View, Execute            |  Deploy From, Contribute, View, Execute            |
        | 15 |  Deploy To, Deploy From, View                      |  Deploy To, Deploy From, View                      |
        | 16 |  Deploy To, Deploy From, Execute                   |  Deploy To, Deploy From, Execute                   |

@ResourcePermissionsSecurity
Scenario Outline: Setting Selected Resource Permissions for users 
        Given I have a server "localhost"
        And it has "<Group>" with "<Given rights>" 
        And Resource "<Resource Name>" has rights "<Resource Rights>" for "<User Group>"
        When connected as user part of "<User Group>"
        Then "<Resource>" should have "<Permissions>"
		And resources should not have "<Rights>" 
Examples: 
        | No | Group                   | Given rights              | Resource Name                                 | Resource Rights           | User Group | Resources | Rights | Resource                                      | Permissions               |
        | 1  | Warewolf Administrators | Contribute, View, Execute | Acceptance Testing Resources\DECISION TESTING | View                      | Users      | All       | None   | Acceptance Testing Resources\DECISION TESTING | View                      |
        | 2  | Warewolf Administrators | Contribute, View, Execute | Acceptance Testing Resources\DECISION TESTING | View                      | Users      | All       | None   | Acceptance Testing Resources\DECISION TESTING | View                      |
        | 3  | Warewolf Administrators | Contribute, View, Execute | Acceptance Testing Resources\DECISION TESTING | View                      | Users      | All       | None   | Acceptance Testing Resources\DECISION TESTING | View                      |
        | 4  | Warewolf Administrators | Contribute, View, Execute | Acceptance Testing Resources\DECISION TESTING | View                      | Users      | All       | None   | Acceptance Testing Resources\DECISION TESTING | View                      |
        | 5  | Warewolf Administrators | Contribute, View, Execute | Acceptance Testing Resources\DECISION TESTING | Execute                   | Users      | All       | None   | Acceptance Testing Resources\DECISION TESTING | Execute                   |
        | 6  | Warewolf Administrators | Contribute, View, Execute | Acceptance Testing Resources\DECISION TESTING | Execute                   | Users      | All       | None   | Acceptance Testing Resources\DECISION TESTING | Execute                   |
        | 7  | Warewolf Administrators | Contribute, View, Execute | Acceptance Testing Resources\DECISION TESTING | Execute                   | Users      | All       | None   | Acceptance Testing Resources\DECISION TESTING | Execute                   |
        | 7  | Warewolf Administrators | Contribute, View, Execute | Acceptance Testing Resources\DECISION TESTING | Execute                   | Users      | All       | None   | Acceptance Testing Resources\DECISION TESTING | Execute                   |
        | 8  | Warewolf Administrators | Contribute, View, Execute | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | None   | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute |
        | 9  | Warewolf Administrators | Contribute, View, Execute | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | None   | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute |
        | 10 | Warewolf Administrators | Contribute, View, Execute | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | None   | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute |
        | 11 | Warewolf Administrators | Contribute, View, Execute | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | None   | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute |
        | 12 | Warewolf Administrators | Contribute, View, Execute | Acceptance Testing Resources\DECISION TESTING | View, Execute             | Users      | All       | None   | Acceptance Testing Resources\DECISION TESTING | View, Execute             |
        | 13 | Warewolf Administrators | Contribute, View, Execute | Acceptance Testing Resources\DECISION TESTING | View, Execute             | Users      | All       | None   | Acceptance Testing Resources\DECISION TESTING | View, Execute             |
        | 14 | Warewolf Administrators | Contribute, View, Execute | Acceptance Testing Resources\DECISION TESTING | View, Execute             | Users      | All       | None   | Acceptance Testing Resources\DECISION TESTING | View, Execute             |
        | 15 | Warewolf Administrators | Contribute, View, Execute | Acceptance Testing Resources\DECISION TESTING | View, Execute             | Users      | All       | None   | Acceptance Testing Resources\DECISION TESTING | View, Execute             |

@OverlappingUserGroupsPermissionsSecurity
Scenario Outline: Setting Selected Resource Permissions for users overlapping groups
        Given I have a server "localhost"
        And it has "<Group>" with "<Given rights>" 
        And Resource "<Resource Name>" has rights "<Resource Rights>" for "<User Group>"
        When connected as user part of "<User Group>"
        Then "<Resource>" should have "<Permissions>"
		And resources should have "<Rights>" 
Examples: 
        | No | Group  | Given rights                                                     | Resource Name                                 | Resource Rights           | User Group | Resources | Rights                                                           | Resource                                      | Permissions               |
        | 1  | Public | View                                                             | Acceptance Testing Resources\DECISION TESTING | View                      | Users      | All       | View                                                             | Acceptance Testing Resources\DECISION TESTING | View                      |
        | 2  | Public | Execute                                                          | Acceptance Testing Resources\DECISION TESTING | View                      | Users      | All       | Execute                                                          | Acceptance Testing Resources\DECISION TESTING | View                      |
        | 3  | Public | Contribute, View, Execute                                        | Acceptance Testing Resources\DECISION TESTING | View                      | Users      | All       | Contribute, View, Execute                                        | Acceptance Testing Resources\DECISION TESTING | View                      |
        | 4  | Public | View, Execute                                                    | Acceptance Testing Resources\DECISION TESTING | View                      | Users      | All       | View, Execute                                                    | Acceptance Testing Resources\DECISION TESTING | View                      |
        | 5  | Public | View, Execute, Contribute, Deploy To, Deploy From, Administrator | Acceptance Testing Resources\DECISION TESTING | View                      | Users      | All       | View, Execute, Contribute, Deploy To, Deploy From, Administrator | Acceptance Testing Resources\DECISION TESTING | View                      |
        | 6  | Public | View                                                             | Acceptance Testing Resources\DECISION TESTING | Execute                   | Users      | All       | View                                                             | Acceptance Testing Resources\DECISION TESTING | Execute                   |
        | 7  | Public | Execute                                                          | Acceptance Testing Resources\DECISION TESTING | Execute                   | Users      | All       | Execute                                                          | Acceptance Testing Resources\DECISION TESTING | Execute                   |
        | 8  | Public | Contribute, View, Execute                                        | Acceptance Testing Resources\DECISION TESTING | Execute                   | Users      | All       | Contribute, View, Execute                                        | Acceptance Testing Resources\DECISION TESTING | Execute                   |
        | 9  | Public | View, Execute                                                    | Acceptance Testing Resources\DECISION TESTING | Execute                   | Users      | All       | View, Execute                                                    | Acceptance Testing Resources\DECISION TESTING | Execute                   |
        | 10 | Public | View, Execute, Contribute, Deploy To, Deploy From, Administrator | Acceptance Testing Resources\DECISION TESTING | Execute                   | Users      | All       | View, Execute, Contribute, Deploy To, Deploy From, Administrator | Acceptance Testing Resources\DECISION TESTING | Execute                   |
        | 11 | Public | View                                                             | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | View                                                             | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute |
        | 12 | Public | Execute                                                          | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Execute                                                          | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute |
        | 13 | Public | Contribute, View, Execute                                        | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Contribute, View, Execute                                        | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute |
        | 14 | Public | View, Execute                                                    | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | View, Execute                                                    | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute |
        | 15 | Public | View, Execute, Contribute, Deploy To, Deploy From                | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | View, Execute, Contribute, Deploy To, Deploy From                | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute |
        | 16 | Public | View                                                             | Acceptance Testing Resources\DECISION TESTING | View, Execute             | Users      | All       | View                                                             | Acceptance Testing Resources\DECISION TESTING | View, Execute             |
        | 17 | Public | Execute                                                          | Acceptance Testing Resources\DECISION TESTING | View, Execute             | Users      | All       | Execute                                                          | Acceptance Testing Resources\DECISION TESTING | View, Execute             |
        | 18 | Public | Contribute, View, Execute                                        | Acceptance Testing Resources\DECISION TESTING | View, Execute             | Users      | All       | Contribute, View, Execute                                        | Acceptance Testing Resources\DECISION TESTING | View, Execute             |
        | 19 | Public | View, Execute                                                    | Acceptance Testing Resources\DECISION TESTING | View, Execute             | Users      | All       | View, Execute                                                    | Acceptance Testing Resources\DECISION TESTING | View, Execute             |
        | 20 | Public | View, Execute, Contribute, Deploy To, Deploy From                | Acceptance Testing Resources\DECISION TESTING | View, Execute             | Users      | All       | View, Execute, Contribute, Deploy To, Deploy From                | Acceptance Testing Resources\DECISION TESTING | View, Execute             |
        | 21 | Public | View                                                             | Acceptance Testing Resources\DECISION TESTING | None                      | Users      | All       | View                                                             | Acceptance Testing Resources\DECISION TESTING | None                      |
        | 22 | Public | Execute                                                          | Acceptance Testing Resources\DECISION TESTING | None                      | Users      | All       | Execute                                                          | Acceptance Testing Resources\DECISION TESTING | None                      |
        | 23 | Public | Contribute, View, Execute                                        | Acceptance Testing Resources\DECISION TESTING | None                      | Users      | All       | Contribute, View, Execute                                        | Acceptance Testing Resources\DECISION TESTING | None                      |
        | 24 | Public | View, Execute                                                    | Acceptance Testing Resources\DECISION TESTING | None                      | Users      | All       | View, Execute                                                    | Acceptance Testing Resources\DECISION TESTING | None                      |
        | 25 | Public | View, Execute, Contribute, Deploy To, Deploy From, Administrator | Acceptance Testing Resources\DECISION TESTING | None                      | Users      | All       | View, Execute, Contribute, Deploy To, Deploy From, Administrator | Acceptance Testing Resources\DECISION TESTING | None                      |
        | 26 | Public | None                                                             | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute | Users      | Users     | None                                                             | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute |

@ConflictingViewPermissionsSecurity		
Scenario Outline: Setting Selected Resource Permissions for users conflicting with View permissions
        Given I have a server "localhost"
        And it has "<Group>" with "<Given rights>" 
        And Resource "<Resource Name>" has rights "<Resource Rights>" for "<User Group>"
        When connected as user part of "<User Group>"
        Then "<Resource>" should have "<Permissions>"
		And resources should have "<Rights>" 
Examples: 
        | No | Group | Given rights                                                     | Resource Name                                 | Resource Rights           | User Group | Resources | Rights                                                           | Resource                                      | Permissions               |
        | 1  | Users | Deploy To                                                        | Acceptance Testing Resources\DECISION TESTING | View                      | Users      | All       | Deploy To                                                        | Acceptance Testing Resources\DECISION TESTING | View                      |
        | 2  | Users | Deploy From                                                      | Acceptance Testing Resources\DECISION TESTING | View                      | Users      | All       | Deploy From                                                      | Acceptance Testing Resources\DECISION TESTING | View                      |
        | 3  | Users | View                                                             | Acceptance Testing Resources\DECISION TESTING | View                      | Users      | All       | View                                                             | Acceptance Testing Resources\DECISION TESTING | View                      |
        | 4  | Users | Execute                                                          | Acceptance Testing Resources\DECISION TESTING | View                      | Users      | All       | Execute                                                          | Acceptance Testing Resources\DECISION TESTING | View                      |
        | 5  | Users | Contribute, View, Execute                                        | Acceptance Testing Resources\DECISION TESTING | View                      | Users      | All       | Contribute, View, Execute                                        | Acceptance Testing Resources\DECISION TESTING | View                      |
        | 6  | Users | Deploy To, Deploy From                                           | Acceptance Testing Resources\DECISION TESTING | View                      | Users      | All       | Deploy To, Deploy From                                           | Acceptance Testing Resources\DECISION TESTING | View                      |
        | 7  | Users | View, Execute                                                    | Acceptance Testing Resources\DECISION TESTING | View                      | Users      | All       | View, Execute                                                    | Acceptance Testing Resources\DECISION TESTING | View                      |
        | 8  | Users | View, Execute, Contribute, Deploy To, Deploy From, Administrator | Acceptance Testing Resources\DECISION TESTING | View                      | Users      | All       | View, Execute, Contribute, Deploy To, Deploy From, Administrator | Acceptance Testing Resources\DECISION TESTING | View                      |
        | 9  | Users | Deploy To, View                                                  | Acceptance Testing Resources\DECISION TESTING | View                      | Users      | All       | Deploy To, View                                                  | Acceptance Testing Resources\DECISION TESTING | View                      |
        | 10 | Users | Deploy To, Execute                                               | Acceptance Testing Resources\DECISION TESTING | View                      | Users      | All       | Deploy To, Execute                                               | Acceptance Testing Resources\DECISION TESTING | View                      |
        | 11 | Users | Deploy To, Contribute, View, Execute                             | Acceptance Testing Resources\DECISION TESTING | View                      | Users      | All       | Deploy To, Contribute, View, Execute                             | Acceptance Testing Resources\DECISION TESTING | View                      |
        | 12 | Users | Deploy From, View                                                | Acceptance Testing Resources\DECISION TESTING | View                      | Users      | All       | Deploy From, View                                                | Acceptance Testing Resources\DECISION TESTING | View                      |
        | 13 | Users | Deploy From, Execute                                             | Acceptance Testing Resources\DECISION TESTING | View                      | Users      | All       | Deploy From, Execute                                             | Acceptance Testing Resources\DECISION TESTING | View                      |
        | 14 | Users | Deploy From, Contribute, View, Execute                           | Acceptance Testing Resources\DECISION TESTING | View                      | Users      | All       | Deploy From, Contribute, View, Execute                           | Acceptance Testing Resources\DECISION TESTING | View                      |
        | 15 | Users | Deploy To, Deploy From, View                                     | Acceptance Testing Resources\DECISION TESTING | View                      | Users      | All       | Deploy To, Deploy From , View                                    | Acceptance Testing Resources\DECISION TESTING | View                      |
        | 16 | Users | Deploy To, Deploy From, Execute                                  | Acceptance Testing Resources\DECISION TESTING | View                      | Users      | All       | Deploy To, Deploy From , Execute                                 | Acceptance Testing Resources\DECISION TESTING | View                      |
        | 17 | Users | Deploy To, Deploy From, Contribute, View, Execute                | Acceptance Testing Resources\DECISION TESTING | View                      | Users      | All       | Deploy To, Deploy From , Contribute, View, Execute               | Acceptance Testing Resources\DECISION TESTING | View                      |

@ConflictingExecutePermissionsSecurity		
Scenario Outline: Setting Selected Resource Permissions for users and conflicting with Execute permissions
        Given I have a server "localhost"
        And it has "<Group>" with "<Given rights>" 
        And Resource "<Resource Name>" has rights "<Resource Rights>" for "<User Group>"
        When connected as user part of "<User Group>"
        Then "<Resource>" should have "<Permissions>"
		And resources should have "<Rights>" 
Examples: 
        | No | Group | Given rights                                                     | Resource Name                                 | Resource Rights           | User Group | Resources | Rights                                                           | Resource                                      | Permissions               |
        | 1  | Users | Deploy To                                                        | Acceptance Testing Resources\DECISION TESTING | Execute                   | Users      | All       | Deploy To                                                        | Acceptance Testing Resources\DECISION TESTING | Execute                   |
        | 2  | Users | Deploy From                                                      | Acceptance Testing Resources\DECISION TESTING | Execute                   | Users      | All       | Deploy From                                                      | Acceptance Testing Resources\DECISION TESTING | Execute                   |
        | 3  | Users | View                                                             | Acceptance Testing Resources\DECISION TESTING | Execute                   | Users      | All       | View                                                             | Acceptance Testing Resources\DECISION TESTING | Execute                   |
        | 4  | Users | Execute                                                          | Acceptance Testing Resources\DECISION TESTING | Execute                   | Users      | All       | Execute                                                          | Acceptance Testing Resources\DECISION TESTING | Execute                   |
        | 5  | Users | Contribute, View, Execute                                        | Acceptance Testing Resources\DECISION TESTING | Execute                   | Users      | All       | Contribute, View, Execute                                        | Acceptance Testing Resources\DECISION TESTING | Execute                   |
        | 6  | Users | Deploy To, Deploy From                                           | Acceptance Testing Resources\DECISION TESTING | Execute                   | Users      | All       | Deploy To, Deploy From                                           | Acceptance Testing Resources\DECISION TESTING | Execute                   |
        | 7  | Users | View, Execute                                                    | Acceptance Testing Resources\DECISION TESTING | Execute                   | Users      | All       | View, Execute                                                    | Acceptance Testing Resources\DECISION TESTING | Execute                   |
        | 8  | Users | View, Execute, Contribute, Deploy To, Deploy From, Administrator | Acceptance Testing Resources\DECISION TESTING | Execute                   | Users      | All       | View, Execute, Contribute, Deploy To, Deploy From, Administrator | Acceptance Testing Resources\DECISION TESTING | Execute                   |
        | 9  | Users | Deploy To, View                                                  | Acceptance Testing Resources\DECISION TESTING | Execute                   | Users      | All       | Deploy To, View                                                  | Acceptance Testing Resources\DECISION TESTING | Execute                   |
        | 10 | Users | Deploy To, Execute                                               | Acceptance Testing Resources\DECISION TESTING | Execute                   | Users      | All       | Deploy To, Execute                                               | Acceptance Testing Resources\DECISION TESTING | Execute                   |
        | 11 | Users | Deploy To, Contribute, View, Execute                             | Acceptance Testing Resources\DECISION TESTING | Execute                   | Users      | All       | Deploy To, Contribute, View, Execute                             | Acceptance Testing Resources\DECISION TESTING | Execute                   |
        | 12 | Users | Deploy From, View                                                | Acceptance Testing Resources\DECISION TESTING | Execute                   | Users      | All       | Deploy From, View                                                | Acceptance Testing Resources\DECISION TESTING | Execute                   |
        | 13 | Users | Deploy From, Execute                                             | Acceptance Testing Resources\DECISION TESTING | Execute                   | Users      | All       | Deploy From, Execute                                             | Acceptance Testing Resources\DECISION TESTING | Execute                   |
        | 14 | Users | Deploy From, Contribute, View, Execute                           | Acceptance Testing Resources\DECISION TESTING | Execute                   | Users      | All       | Deploy From, Contribute, View, Execute                           | Acceptance Testing Resources\DECISION TESTING | Execute                   |
        | 15 | Users | Deploy To, Deploy From, View                                     | Acceptance Testing Resources\DECISION TESTING | Execute                   | Users      | All       | Deploy To, Deploy From, View                                     | Acceptance Testing Resources\DECISION TESTING | Execute                   |
        | 16 | Users | Deploy To, Deploy From, Execute                                  | Acceptance Testing Resources\DECISION TESTING | Execute                   | Users      | All       | Deploy To, Deploy From, Execute                                  | Acceptance Testing Resources\DECISION TESTING | Execute                   |
        | 17 | Users | Deploy To, Deploy From, Contribute, View, Execute                | Acceptance Testing Resources\DECISION TESTING | Execute                   | Users      | All       | Deploy To, Deploy From, Contribute, View, Execute                | Acceptance Testing Resources\DECISION TESTING | Execute                   |

@ConflictingContributeViewExecutePermissionsSecurity		
Scenario Outline: Setting Selected Resource Permissions for users and conflicting with Contribute, View and Execute permissions
        Given I have a server "localhost"
        And it has "<Group>" with "<Given rights>" 
        And Resource "<Resource Name>" has rights "<Resource Rights>" for "<User Group>"
        When connected as user part of "<User Group>"
        Then "<Resource>" should have "<Permissions>"
		And resources should have "<Rights>" 
Examples: 
        | No | Group | Given rights                                                     | Resource Name                                 | Resource Rights           | User Group | Resources | Rights                                                           | Resource                                      | Permissions               |
        | 1  | Users | Deploy To                                                        | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Deploy To                                                        | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute |
        | 2  | Users | Deploy From                                                      | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Deploy From                                                      | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute |
        | 3  | Users | View                                                             | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | View                                                             | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute |
        | 4  | Users | Execute                                                          | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Execute                                                          | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute |
        | 5  | Users | Contribute, View, Execute                                        | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Contribute, View, Execute                                        | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute |
        | 6  | Users | Deploy To, Deploy From                                           | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Deploy To, Deploy From                                           | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute |
        | 7  | Users | View, Execute                                                    | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | View, Execute                                                    | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute |
        | 8  | Users | View, Execute, Contribute, Deploy To, Deploy From                | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | View, Execute, Contribute, Deploy To, Deploy From                | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute |
        | 9  | Users | Deploy To, View                                                  | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Deploy To, View                                                  | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute |
        | 10 | Users | Deploy To, Execute                                               | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Deploy To, Execute                                               | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute |
        | 11 | Users | Deploy To, Contribute, View, Execute                             | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Deploy To, Contribute, View, Execute                             | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute |
        | 12 | Users | Deploy From, View                                                | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Deploy From, View                                                | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute |
        | 13 | Users | Deploy From, Execute                                             | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Deploy From, Execute                                             | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute |
        | 14 | Users | Deploy From, Contribute, View, Execute                           | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Deploy From, Contribute, View, Execute                           | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute |
        | 15 | Users | Deploy To, Deploy From, View                                     | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Deploy To, Deploy From, View                                     | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute |
        | 16 | Users | Deploy To, Deploy From, Execute                                  | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Deploy To, Deploy From, Execute                                  | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute |
        | 17 | Users | Deploy To, Deploy From, Contribute, View, Execute, Administrator | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute | Users      | All       | Deploy To, Deploy From, Contribute, View, Execute, Administrator | Acceptance Testing Resources\DECISION TESTING | Contribute, View, Execute |

@ConflictingViewExecutePermissionsSecurity		
Scenario Outline: Setting Selected Resource Permissions for users and conflicting with View and Execute permissions
        Given I have a server "localhost"
        And it has "<Group>" with "<Given rights>" 
        And Resource "<Resource Name>" has rights "<Resource Rights>" for "<User Group>"
        When connected as user part of "<User Group>"
        Then "<Resource>" should have "<Permissions>"
		And resources should have "<Rights>" 
Examples: 
        | No | Group | Given rights                                                     | Resource Name                                 | Resource Rights           | User Group | Resources | Rights                                                           | Resource                                      | Permissions               |
        | 1  | Users | Deploy To                                                        | Acceptance Testing Resources\DECISION TESTING | View, Execute             | Users      | All       | Deploy To                                                        | Acceptance Testing Resources\DECISION TESTING | View, Execute             |
        | 2  | Users | Deploy From                                                      | Acceptance Testing Resources\DECISION TESTING | View, Execute             | Users      | All       | Deploy From                                                      | Acceptance Testing Resources\DECISION TESTING | View, Execute             |
        | 3  | Users | View                                                             | Acceptance Testing Resources\DECISION TESTING | View, Execute             | Users      | All       | View                                                             | Acceptance Testing Resources\DECISION TESTING | View, Execute             |
        | 4  | Users | Contribute, View, Execute                                        | Acceptance Testing Resources\DECISION TESTING | View, Execute             | Users      | All       | Contribute, View, Execute                                        | Acceptance Testing Resources\DECISION TESTING | View, Execute             |
        | 5  | Users | Deploy To, Deploy From                                           | Acceptance Testing Resources\DECISION TESTING | View, Execute             | Users      | All       | Deploy To, Deploy From                                           | Acceptance Testing Resources\DECISION TESTING | View, Execute             |
        | 6  | Users | View, Execute                                                    | Acceptance Testing Resources\DECISION TESTING | View, Execute             | Users      | All       | View, Execute                                                    | Acceptance Testing Resources\DECISION TESTING | View, Execute             |
        | 7  | Users | View, Execute, Contribute, Deploy To, Deploy From                | Acceptance Testing Resources\DECISION TESTING | View, Execute             | Users      | All       | View, Execute, Contribute, Deploy To, Deploy From                | Acceptance Testing Resources\DECISION TESTING | View, Execute             |
        | 8  | Users | Deploy To, View                                                  | Acceptance Testing Resources\DECISION TESTING | View, Execute             | Users      | All       | Deploy To, View                                                  | Acceptance Testing Resources\DECISION TESTING | View, Execute             |
        | 9  | Users | Deploy To, Execute                                               | Acceptance Testing Resources\DECISION TESTING | View, Execute             | Users      | All       | Deploy To, Execute                                               | Acceptance Testing Resources\DECISION TESTING | View, Execute             |
        | 10 | Users | Deploy To, Contribute, View, Execute                             | Acceptance Testing Resources\DECISION TESTING | View, Execute             | Users      | All       | Deploy To, Contribute, View, Execute                             | Acceptance Testing Resources\DECISION TESTING | View, Execute             |
        | 11 | Users | Deploy From, View                                                | Acceptance Testing Resources\DECISION TESTING | View, Execute             | Users      | All       | Deploy From, View                                                | Acceptance Testing Resources\DECISION TESTING | View, Execute             |
        | 12 | Users | Deploy From, Execute                                             | Acceptance Testing Resources\DECISION TESTING | View, Execute             | Users      | All       | Deploy From, Execute                                             | Acceptance Testing Resources\DECISION TESTING | View, Execute             |
        | 13 | Users | Deploy From, Contribute, View, Execute                           | Acceptance Testing Resources\DECISION TESTING | View, Execute             | Users      | All       | Deploy From, Contribute, View, Execute                           | Acceptance Testing Resources\DECISION TESTING | View, Execute             |
        | 14 | Users | Deploy To, Deploy From, View                                     | Acceptance Testing Resources\DECISION TESTING | View, Execute             | Users      | All       | Deploy To, Deploy From, View                                     | Acceptance Testing Resources\DECISION TESTING | View, Execute             |
        | 15 | Users | Deploy To, Deploy From, Execute                                  | Acceptance Testing Resources\DECISION TESTING | View, Execute             | Users      | All       | Deploy To, Deploy From, Execute                                  | Acceptance Testing Resources\DECISION TESTING | View, Execute             |
        | 16 | Users | Deploy To, Deploy From, Contribute, View, Execute, Administrator | Acceptance Testing Resources\DECISION TESTING | View, Execute             | Users      | All       | Deploy To, Deploy From, Contribute, View, Execute, Administrator | Acceptance Testing Resources\DECISION TESTING | View, Execute             |

@NoConflictingPermissionsSecurity		
Scenario Outline: Setting Selected Resource Permissions for users and no conflicting permissions
        Given I have a server "localhost"
        And it has "<Group>" with "<Given rights>" 
        And Resource "<Resource Name>" has rights "<Resource Rights>" for "<User Group>"
        When connected as user part of "<User Group>"
        Then "<Resource>" should have "<Permissions>"
		And resources should have "<Rights>" 
Examples: 
        | No | Group | Given rights                                                     | Resource Name                                 | Resource Rights           | User Group | Resources | Rights                                                           | Resource                                      | Permissions               |
        | 1  | Users | Deploy To                                                        | Acceptance Testing Resources\DECISION TESTING | None                      | Users      | All       | Deploy To                                                        | Acceptance Testing Resources\DECISION TESTING | None                      |
        | 2  | Users | Deploy From                                                      | Acceptance Testing Resources\DECISION TESTING | None                      | Users      | All       | Deploy From                                                      | Acceptance Testing Resources\DECISION TESTING | None                      |
        | 3  | Users | View                                                             | Acceptance Testing Resources\DECISION TESTING | None                      | Users      | All       | View                                                             | Acceptance Testing Resources\DECISION TESTING | None                      |
        | 4  | Users | Execute                                                          | Acceptance Testing Resources\DECISION TESTING | None                      | Users      | All       | Execute                                                          | Acceptance Testing Resources\DECISION TESTING | None                      |
        | 5  | Users | Contribute, View, Execute                                        | Acceptance Testing Resources\DECISION TESTING | None                      | Users      | All       | Contribute, View, Execute                                        | Acceptance Testing Resources\DECISION TESTING | None                      |
        | 6  | Users | Deploy To, Deploy From                                           | Acceptance Testing Resources\DECISION TESTING | None                      | Users      | All       | Deploy To, Deploy From                                           | Acceptance Testing Resources\DECISION TESTING | None                      |
        | 7  | Users | View, Execute                                                    | Acceptance Testing Resources\DECISION TESTING | None                      | Users      | All       | View, Execute                                                    | Acceptance Testing Resources\DECISION TESTING | None                      |
        | 8  | Users | View, Execute, Contribute, Deploy To, Deploy From, Administrator | Acceptance Testing Resources\DECISION TESTING | None                      | Users      | All       | View, Execute, Contribute, Deploy To, Deploy From, Administrator | Acceptance Testing Resources\DECISION TESTING | None                      |
        | 9  | Users | Deploy To, View                                                  | Acceptance Testing Resources\DECISION TESTING | None                      | Users      | All       | Deploy To, View                                                  | Acceptance Testing Resources\DECISION TESTING | None                      |
        | 10 | Users | Deploy To, Execute                                               | Acceptance Testing Resources\DECISION TESTING | None                      | Users      | All       | Deploy To, Execute                                               | Acceptance Testing Resources\DECISION TESTING | None                      |
        | 11 | Users | Deploy To, Contribute, View, Execute                             | Acceptance Testing Resources\DECISION TESTING | None                      | Users      | All       | Deploy To, Contribute, View, Execute                             | Acceptance Testing Resources\DECISION TESTING | None                      |
        | 12 | Users | Deploy From, View                                                | Acceptance Testing Resources\DECISION TESTING | None                      | Users      | All       | Deploy From, View                                                | Acceptance Testing Resources\DECISION TESTING | None                      |
        | 13 | Users | Deploy From, Execute                                             | Acceptance Testing Resources\DECISION TESTING | None                      | Users      | All       | Deploy From, Execute                                             | Acceptance Testing Resources\DECISION TESTING | None                      |
        | 14 | Users | Deploy From, Contribute, View, Execute                           | Acceptance Testing Resources\DECISION TESTING | None                      | Users      | All       | Deploy From, Contribute, View, Execute                           | Acceptance Testing Resources\DECISION TESTING | None                      |
        | 15 | Users | Deploy To, Deploy From, View                                     | Acceptance Testing Resources\DECISION TESTING | None                      | Users      | All       | Deploy To, Deploy From, View                                     | Acceptance Testing Resources\DECISION TESTING | None                      |
        | 16 | Users | Deploy To, Deploy From, Execute                                  | Acceptance Testing Resources\DECISION TESTING | None                      | Users      | All       | Deploy To, Deploy From, Execute                                  | Acceptance Testing Resources\DECISION TESTING | None                      |
        | 17 | Users | Deploy To, Deploy From, Contribute, View, Execute, Administrator | Acceptance Testing Resources\DECISION TESTING | None                      | Users      | All       | Deploy To, Deploy From, Contribute, View, Execute, Administrator | Acceptance Testing Resources\DECISION TESTING | None                      |
