Feature: Language Parser
	In order to get validation errors
	As a Warewolf user
	I want proper validation messages for incorrect inputs in all the tools



Scenario Outline: Parse text input
	Given I have text '<variable>' as input
    When I validate
	Then has error will be '<error>'.
	And the error message will be '<message>'
Examples: 	
	| Name | variable                                  | error | message                                                                                                                                                                                                                                                 |
	| 1    | [[var]]                                   | false |                                                                                                                                                                                                                                                         |
	| 2    | [[var1]]                                  | false |                                                                                                                                                                                                                                                         |
	| 3    | [[var1]]asdf<[[var]]                      | false |                                                                                                                                                                                                                                                         |
	| 4    | [[var@]]                                  | true  | Variable name [[var@]] contains invalid character(s)                                                                                                                                                                                                    |
	| 5    | [[var#]]                                  | true  | Variable name [[var#]] contains invalid character(s)                                                                                                                                                                                                    |
	| 6    | [[var$]]                                  | true  | Variable name [[var$]] contains invalid character(s)                                                                                                                                                                                                    |
	| 7    | [[var%]]                                  | true  | Variable name [[var%]] contains invalid character(s)                                                                                                                                                                                                    |
	| 8    | [[var^]]                                  | true  | Variable name [[var^]] contains invalid character(s)                                                                                                                                                                                                    |
	| 9    | [[var&]]                                  | true  | Variable name [[var&]] contains invalid character(s)                                                                                                                                                                                                    |
	| 10   | [[var]]00]]                               | true  | Invalid region detected: A close ]] without a related open [[                                                                                                                                                                                           |
	| 11   | [[var]]@]]                                | true  | Invalid region detected: A close ]] without a related open [[                                                                                                                                                                                           |
	| 12   | [[var]]]]                                 | true  | Invalid region detected: A close ]] without a related open [[                                                                                                                                                                                           |
	| 13   | [[[[var]]                                 | true  | Invalid region detected: An open [[ without a related close ]]                                                                                                                                                                                          |
	| 14   | [[(1var)]]                                | true  | Variable name [[(1var)]] contains invalid character(s)                                                                                                                                                                                                  |
	| 15   | [[1var)]]                                 | true  | Variable name [[1var)]] begins with a number                                                                                                                                                                                                            |
	| 16   | [[var.()]]                                | true  | Variable name [[var.()]] contains invalid character(s)                                                                                                                                                                                                  |
	| 17   | [[]]                                      | true  | Variable [[]] is missing a name                                                                                                                                                                                                                         |
	| 18   | [[()]]                                    | true  | Variable name [[()]] contains invalid character(s)                                                                                                                                                                                                      |
	| 19   | [[(1)]]                                   | true  | Variable name [[(1)]] contains invalid character(s)                                                                                                                                                                                                     |
	| 20   | [[var  ]]                                 | true  | Variable name [[var  ]] contains invalid character(s)                                                                                                                                                                                                   |
	| 21   | [[var~]]                                  | true  | Variable name [[var~]] contains invalid character(s)                                                                                                                                                                                                    |
	| 22   | [[var+]]                                  | true  | Variable name [[var+]] contains invalid character(s)                                                                                                                                                                                                    |
	| 23   | [[var]a]]                                 | true  | Variable name [[var]a]] contains invalid character(s)                                                                                                                                                                                                   |
	| 24   | [[var[a]]                                 | true  | Variable name [[var[a]] contains invalid character(s)                                                                                                                                                                                                   |
	| 25   | [[var[[a]]]]                              | false |                                                                                                                                                                                                                                                         |
	| 26   | [[var[[]]                                 | true  | Invalid region detected: An open [[ without a related close ]]                                                                                                                                                                                          |
	| 27   | [[var[[1]]]]                              | true  | Variable name [[1]] begins with a number                                                                                                                                                                                                                |
	| 28   | [[var.a]]                                 | true  | Variable name [[var.a]] contains invalid character(s)                                                                                                                                                                                                   |
	| 29   | [[var1.a]]                                | true  | Variable name [[var1.a]] contains invalid character(s)                                                                                                                                                                                                  |
	| 30   | [[var]][[var]]                            | false |                                                                                                                                                                                                                                                         |
	| 31   | [[a]].[[b]]                               | false |                                                                                                                                                                                                                                                         |
	| 32   | [[[[a]].[[b]]]]                           | false |                                                                                                                                                                                                                                                         |
	| 33   | [[[[a]].[[b]]]]cd]]                       | true  | Invalid region detected: A close ]] without a related open [[                                                                                                                                                                                           |
	| 34   | [[var*]]                                  | true  | Variable name [[var*]] contains invalid character(s)                                                                                                                                                                                                    |
	| 35   | [[1var]]                                  | true  | Variable name [[1var]] begins with a number                                                                                                                                                                                                             |
	| 36   | [[@var]]                                  | true  | Variable name [[@var]] contains invalid character(s)                                                                                                                                                                                                    |
	| 37   | [[#var]]                                  | true  | Variable name [[#var]] contains invalid character(s)                                                                                                                                                                                                    |
	| 38   | [[$var]]                                  | true  | Variable name [[$var]] contains invalid character(s)                                                                                                                                                                                                    |
	| 39   | [[%var]]                                  | true  | Variable name [[%var]] contains invalid character(s)                                                                                                                                                                                                    |
	| 40   | [[^var]]                                  | true  | Variable name [[^var]] contains invalid character(s)                                                                                                                                                                                                    |
	| 41   | [[&var]]                                  | true  | Variable name [[&var]] contains invalid character(s)                                                                                                                                                                                                    |
	| 42   | [[*var]]                                  | true  | Variable name [[*var]] contains invalid character(s)                                                                                                                                                                                                    |
	| 43   | [[(var]]                                  | true  | Variable name [[(var]] contains invalid character(s)                                                                                                                                                                                                    |
	| 44   | [[var]](var)]]                            | true  | Invalid region detected: A close ]] without a related open [[                                                                                                                                                                                           |
	| 45   | [[var,]]                                  | true  | Variable name [[var,]] contains invalid character(s)                                                                                                                                                                                                    |
	| 46   | [[var/]]                                  | true  | Variable name [[var/]] contains invalid character(s)                                                                                                                                                                                                    |
	| 47   | [[var:]]                                  | true  | Variable name [[var:]] contains invalid character(s)                                                                                                                                                                                                    |
	| 48   | [[var"]]                                  | true  | Variable name [[var"]] contains invalid character(s)                                                                                                                                                                                                    |
	| 49   | [[var']]                                  | true  | Variable name [[var']] contains invalid character(s)                                                                                                                                                                                                    |
	| 50   | [[var;]]                                  | true  | Variable name [[var;]] contains invalid character(s)                                                                                                                                                                                                    |
	| 51   | [[var?]]                                  | true  | Variable name [[var?]] contains invalid character(s)                                                                                                                                                                                                    |
	| 52   | [[var 1]]                                 | true  | Variable name [[var 1]] contains invalid character(s)                                                                                                                                                                                                   |
	| 53   | [[:var 1]]                                | true  | Variable name [[:var 1]] contains invalid character(s)                                                                                                                                                                                                  |
	| 54   | [[,var]]                                  | true  | Variable name [[,var]] contains invalid character(s)                                                                                                                                                                                                    |
	| 55   | [[test,var]]                              | true  | Variable name [[test,var]] contains invalid character(s)                                                                                                                                                                                                |
	| 56   | [[test. var]]                             | true  | Variable name [[test. var]] contains invalid character(s)                                                                                                                                                                                               |
	| 57   | [[test.var]]                              | true  | Variable name [[test.var]] contains invalid character(s)                                                                                                                                                                                                |
	| 58   | [[test. 1]]                               | true  | Variable name [[test. 1]] contains invalid character(s)                                                                                                                                                                                                 |
	| 59   | [[rec().a]]                               | false |                                                                                                                                                                                                                                                         |
	| 60   | [[rec(1).a]]                              | false |                                                                                                                                                                                                                                                         |
	| 61   | [[rec(*).a]]                              | false |                                                                                                                                                                                                                                                         |
	| 62   | [[rec(*).&]]                              | true  | Recordset field name & contains invalid character(s)                                                                                                                                                                                                    |
	| 63   | [[rec(),a]]                               | true  | Recordset name [[rec(),a]] contains invalid character(s)                                                                                                                                                                                                |
	| 64   | [[rec()*a]]                               | true  | Recordset name [[rec()*a]] contains invalid character(s)                                                                                                                                                                                                |
	| 65   | [[rec()&a]]                               | true  | Recordset name [[rec()&a]] contains invalid character(s)                                                                                                                                                                                                |
	| 66   | [[rec()!a]]                               | true  | Recordset name [[rec()!a]] contains invalid character(s)                                                                                                                                                                                                |
	| 67   | [[rec()@a]]                               | true  | Recordset name [[rec()@a]] contains invalid character(s)                                                                                                                                                                                                |
	| 68   | [[rec()(a]]                               | true  | Recordset name [[rec()(a]] contains invalid character(s)                                                                                                                                                                                                |
	| 69   | [[rec()%`a]]                              | true  | Recordset name [[rec()%`a]] contains invalid character(s)                                                                                                                                                                                               |
	| 70   | [[rec()         a]]                       | true  | Recordset name [[rec()         a]] contains invalid character(s)                                                                                                                                                                                        |
	| 71   | [[rec(1)]]                                | false |                                                                                                                                                                                                                                                         |
	| 72   | [[rec(1).[[rec().1]]]]                    | true  | Recordset field name 1 begins with a number                                                                                                                                                                                                             |
	| 73   | [[rec(a).[[rec().a]]]]                    | true  | Recordset index (a) contains invalid character(s)                                                                                                                                                                                                       |
	| 74   | [[rec().[[rec().a]]]]                     | false |                                                                                                                                                                                                                                                         |
	| 75   | [[rec().[[b]]]]                           | false |                                                                                                                                                                                                                                                         |
	| 76   | [[{{rec(_).a}}]]]                         | true  | Recordset name [[{{rec]] contains invalid character(s)                                                                                                                                                                                                  |
	| 77   | [[*[{{rec(_).a}}]]]                       | true  | Recordset name [[*[{{rec]] contains invalid character(s)                                                                                                                                                                                                |
	| 78   | [[rec(23).[[var}]]]]                      | true  | Variable name [[var}]] contains invalid character(s)                                                                                                                                                                                                    |
	| 79   | [[rec(23).[[var*]]]]                      | true  | Variable name [[var*]] contains invalid character(s)                                                                                                                                                                                                    |
	| 80   | [[rec(23).[[var%^&%]]]]                   | true  | Variable name [[var%^&%]] contains invalid character(s)                                                                                                                                                                                                 |
	| 81   | [[rec().a]]234234]]                       | true  | Invalid region detected: A close ]] without a related open [[                                                                                                                                                                                           |
	| 82   | [[rec().a]]=]]                            | true  | Invalid region detected: A close ]] without a related open [[                                                                                                                                                                                           |
	| 83   | [[rec()..]]                               | true  | Recordset name [[rec()..]] contains invalid character(s)                                                                                                                                                                                                |
	| 84   | [[rec().a.b]]                             | true  | Invalid Notation - Extra dots detected                                                                                                                                                                                                                  |
	| 85   | [[rec().a]].a]]                           | true  | Invalid region detected: A close ]] without a related open [[                                                                                                                                                                                           |
	| 86   | [[rec()]]                                 | false |                                                                                                                                                                                                                                                         |
	| 87   | [[rec(@).a]]                              | true  | Recordset index (@) contains invalid character(s)                                                                                                                                                                                                       |
	| 88   | [[rec(#).a]]                              | true  | Recordset index (#) contains invalid character(s)                                                                                                                                                                                                       |
	| 89   | [[rec($).a]]                              | true  | Recordset index ($) contains invalid character(s)                                                                                                                                                                                                       |
	| 90   | [[rec(%).a]]                              | true  | Recordset index (%) contains invalid character(s)                                                                                                                                                                                                       |
	| 91   | [[rec(^).a]]                              | true  | Recordset index (^) contains invalid character(s)                                                                                                                                                                                                       |
	| 92   | [[rec(&).a]]                              | true  | Recordset index (&) contains invalid character(s)                                                                                                                                                                                                       |
	| 93   | [[rec(*).a]]                              | false |                                                                                                                                                                                                                                                         |
	| 94   | [[rec(().a]]                              | true  | Recordset index (() contains invalid character(s)                                                                                                                                                                                                       |
	| 95   | [[rec()).a]]                              | true  | Recordset index ()) contains invalid character(s)                                                                                                                                                                                                       |
	| 96   | [[rec(+).a]]                              | true  | Recordset index (+) contains invalid character(s)                                                                                                                                                                                                       |
	| 97   | [[rec(-).a]]                              | true  | Recordset index (-) contains invalid character(s)                                                                                                                                                                                                       |
	| 98   | [[rec(!).a]]                              | true  | Recordset index (!) contains invalid character(s)                                                                                                                                                                                                       |
	| 99   | [[rec(q).a]]                              | true  | Recordset index (q) contains invalid character(s)                                                                                                                                                                                                       |
	| 100  | [[rec(w).a]]                              | true  | Recordset index (w) contains invalid character(s)                                                                                                                                                                                                       |
	| 101  | [[rec(e).a]]                              | true  | Recordset index (e) contains invalid character(s)                                                                                                                                                                                                       |
	| 102  | [[rec(r).a]]                              | true  | Recordset index (r) contains invalid character(s)                                                                                                                                                                                                       |
	| 103  | [[rec(t).a]]                              | true  | Recordset index (t) contains invalid character(s)                                                                                                                                                                                                       |
	| 104  | [[rec(y).a]]                              | true  | Recordset index (y) contains invalid character(s)                                                                                                                                                                                                       |
	| 105  | [[rec(u).a]]                              | true  | Recordset index (u) contains invalid character(s)                                                                                                                                                                                                       |
	| 106  | [[rec(d).a]]                              | true  | Recordset index (d) contains invalid character(s)                                                                                                                                                                                                       |
	| 107  | [[rec(b).a]]                              | true  | Recordset index (b) contains invalid character(s)                                                                                                                                                                                                       |
	| 108  | [[rec(.).a]]                              | true  | Invalid Notation - Extra dots detected                                                                                                                                                                                                                  |
	| 109  | [[rec(:).a]]                              | true  | Recordset index (:) contains invalid character(s)                                                                                                                                                                                                       |
	| 110  | [[rec(,).a]]                              | true  | Recordset index (,) contains invalid character(s)                                                                                                                                                                                                       |
	| 111  | [[rec"()".a]]                             | true  | Recordset name [[rec"()"]] contains invalid character(s)                                                                                                                                                                                                |
	| 112  | [[rec'()'.a]]                             | true  | Recordset name [[rec'()']] contains invalid character(s)                                                                                                                                                                                                |
	| 113  | [[rec").a]]                               | true  | Variable name [[rec").a]] contains invalid character(s)                                                                                                                                                                                                 |
	| 114  | [[rec{a]]                                 | true  | Variable name [[rec{a]] contains invalid character(s)                                                                                                                                                                                                   |
	| 115  | [[rec{a}]]                                | true  | Variable name [[rec{a}]] contains invalid character(s)                                                                                                                                                                                                  |
	| 116  | [[rec()*.a]]                              | true  | Recordset name [[rec()*]] contains invalid character(s)                                                                                                                                                                                                 |
	| 117  | [[rec().a[[a]]                            | true  | Invalid region detected: An open [[ without a related close ]]                                                                                                                                                                                          |
	| 118  | [[rec().a]][[a]]                          | false |                                                                                                                                                                                                                                                         |
	| 119  | [[rec().a]].[[a]]                         | false |                                                                                                                                                                                                                                                         |
	| 120  | asdf[[rec().a]]*[[a]]asdf                 | false |                                                                                                                                                                                                                                                         |
	| 121  | [[v]],[[a]][[rec().a]]@[[a]]              | false |                                                                                                                                                                                                                                                         |
	| 122  | [[v]],[[a]][[rec(*).a]]@[[a]]             | false |                                                                                                                                                                                                                                                         |
	| 123  | [[rec([[a]]).a]]                          | false |                                                                                                                                                                                                                                                         |
	| 124  | [[rec([[rec(*).a]]).a]]                   | false |                                                                                                                                                                                                                                                         |
	| 125  | [[rec().a]]%[[a]]                         | false |                                                                                                                                                                                                                                                         |
	| 126  | a[[rec([[[[b]]]]).a]]@                    | false |                                                                                                                                                                                                                                                         |
	| 127  | [[rec().a]]&[[a]]                         | false |                                                                                                                                                                                                                                                         |
	| 128  | [[r(q).a]][[r()..]][[r"]][[r()]][[]][[1]] | true  | Recordset index (q) contains invalid character(s)  /n  Recordset name [[r()..]] contains invalid character(s)  /n  Variable name [[r"]] contains invalid character(s)  /n Variable [[]] is missing a name  /n  Variable name [[1]] begins with a number |
	| 129  | [[[[[[[[[[[[[[[[[[[[y]]]]]]]]]]]]]]]]]]]] | false |                                                                                                                                                                                                                                                         |