using System.ComponentModel;

namespace Dev2.Studio.UI.Tests.Enums
{
    public enum ToolType
    {
        [Description("FlowDecision")]
        Decision,
        [Description("FlowSwitch")]
        Switch,
        [Description("DsfForEachActivity")]
        ForEach,
        [Description("DsfCountRecordsetActivity")]
        Count,
        [Description("DsfDeleteRecordActivity")]
        Delete,
        [Description("DsfFindRecordsMultipleActivity")]
        Find,
        [Description("DsfSortRecordsActivity")]
        Sort,
        [Description("DsfUniqueActivity")]
        Unique,
        [Description("DsfSqlBulkInsertActivity")]
        SqlBulkInsert,
        [Description("DsfMultiAssignActivity")]
        Assign,
        [Description("DsfBaseConvertActivity")]
        BaseConvert,
        [Description("DsfCaseConvertActivity")]
        CaseConvert,
        [Description("DsfDataMergeActivity")]
        DataMerge,
        [Description("DsfDataSplitActivity")]
        DataSplit,
        [Description("DsfIndexActivity")]
        FindIndex,
        [Description("DsfReplaceActivity")]
        Replace,
        [Description("DsfWorkflowActivity")]
        Workflow,
        [Description("DsfServiceActivity")]
        Service,
        [Description("DsfCalculateActivity")]
        Calculate,
        [Description("DsfNumberFormatActivity")]
        FormatNumber,
        [Description("DsfRandomActivity")]
        Random,
        [Description("DsfDateTimeActivity")]
        DateAndTime,
        [Description("DsfDateTimeDifferenceActivity")]
        DateAndTimeDifference,
        [Description("DsfSendEmailActivity")]
        Email,
        [Description("DsfGatherSystemInformationActivity")]
        SystemInformation,
        [Description("DsfXPathActivity")]
        XPath,
        [Description("DsfCommentActivity")]
        Comment,
        [Description("DsfWebGetRequestActivity")]
        WebRequest,
        [Description("DsfPathCreate")]
        Create,
        [Description("DsfPathCopy")]
        Copy,
        [Description("DsfPathMove")]
        Move,
        [Description("DsfPathDelete")]
        DeleteFile,
        [Description("DsfPathFileRead")]
        ReadFile,
        [Description("DsfPathFileWrite")]
        WriteFile,
        [Description("DsfPathFolderRead")]
        ReadFolder,
        [Description("DsfPathRename")]
        Rename,
        [Description("DsfUnZip")]
        Unzip,
        [Description("DsfZip")]
        Zip,
        [Description("DsfExecuteCommandLineActivity")]
        CMDLine,
        [Description("DsfScriptingActivity")]
        Script
    }
}
