using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;
using System.Security;
using IronRuby.Builtins;
using IronRuby.Runtime;
using IronRuby.StandardLibrary.BigDecimal;
using IronRuby.StandardLibrary.Digest;
using IronRuby.StandardLibrary.Enumerator;
using IronRuby.StandardLibrary.FileControl;
using IronRuby.StandardLibrary.FunctionControl;
using IronRuby.StandardLibrary.Iconv;
using IronRuby.StandardLibrary.Open3;
using IronRuby.StandardLibrary.OpenSsl;
using IronRuby.StandardLibrary.ParseTree;
using IronRuby.StandardLibrary.Sockets;
using IronRuby.StandardLibrary.StringIO;
using IronRuby.StandardLibrary.StringScanner;
using IronRuby.StandardLibrary.Threading;
using IronRuby.StandardLibrary.Win32API;
using IronRuby.StandardLibrary.Zlib;

[assembly: AllowPartiallyTrustedCallers]
[assembly: SecurityTransparent]
[assembly: RubyLibrary(typeof(FunctionControlLibraryInitializer))]
[assembly: Guid("ca75230d-3011-485d-b1db-dfe924b6c434")]
[assembly: AssemblyFileVersion("1.1.3.0")]
[assembly: RubyLibrary(typeof(BuiltinsLibraryInitializer))]
[assembly: RubyLibrary(typeof(ThreadingLibraryInitializer))]
[assembly: RubyLibrary(typeof(SocketsLibraryInitializer))]
[assembly: RubyLibrary(typeof(OpenSslLibraryInitializer))]
[assembly: RubyLibrary(typeof(DigestLibraryInitializer))]
[assembly: RubyLibrary(typeof(ZlibLibraryInitializer))]
[assembly: RubyLibrary(typeof(StringIOLibraryInitializer))]
[assembly: RubyLibrary(typeof(StringScannerLibraryInitializer))]
[assembly: RubyLibrary(typeof(EnumeratorLibraryInitializer))]
[assembly: SecurityRules(SecurityRuleSet.Level1)]
[assembly: RubyLibrary(typeof(FileControlLibraryInitializer))]
[assembly: RubyLibrary(typeof(BigDecimalLibraryInitializer))]
[assembly: RubyLibrary(typeof(IconvLibraryInitializer))]
[assembly: RubyLibrary(typeof(ParseTreeLibraryInitializer))]
[assembly: RubyLibrary(typeof(Open3LibraryInitializer))]
[assembly: RubyLibrary(typeof(Win32APILibraryInitializer))]
[assembly: AssemblyTitle("Ruby Libraries")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Microsoft")]
[assembly: AssemblyProduct("Ruby")]
[assembly: AssemblyCopyright("© Microsoft Corporation.  All rights reserved.")]
[assembly: AssemblyTrademark("")]
[assembly: ComVisible(false)]
[assembly: AssemblyVersion("1.1.3.0")]
