@fileFeature
Feature: Write File
	In order to be able to Write File
	as a Warewolf user
	I want a tool that writes a file at a given location

Scenario Outline: Write file at location
	Given I have a source path "<source>" with value "<sourceLocation>" 
	And source credentials as "<username>" and "<password>"	
	And Method is "<method>"
	And input contents as "<content>"    
	And use private public key for source is "<sourcePrivateKeyFile>" 
	And result as "<resultVar>"
    When the write file tool is executed
	Then the result variable "<resultVar>" will be "<result>"
	And the execution has "<errorOccured>" error
	And the debug inputs as
         | Output Path                 | Method   | Username   | Password | Private Key File       |File Contents |
         | <source> = <sourceLocation> | <method> | <username> | String   | <sourcePrivateKeyFile> |<content>     |
	And the debug output as
		|                        |
		| <resultVar> = <result> |
		Examples: 
		| Name                       | source   | sourceLocation                                               | method        | content        | username          | password | resultVar  | result  | errorOccured | sourcePrivateKeyFile |
		| Local with Overwrite       | [[path]] | c:\Temp\filetowrite0.txt                                     | Overwrite     | warewolf rules | ""                | ""       | [[result]] | Success | NO           |                      |
		| UNC with Overwrite         | [[path]] | \\\\RSAKLFSVRPDC\FileSystemShareTestingSite\filetowrite0.txt | Overwrite     | warewolf rules | ""                | ""       | [[result]] | Success | NO           |                      |
		| FTP with Overwrite         | [[path]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/filetowrite0.txt          | Overwrite     | warewolf rules | ""                | ""       | [[result]] | Success | NO           |                      |
		| FTPS with Overwrite        | [[path]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/filetowrite0.txt          | Overwrite     | warewolf rules | integrationtester | I73573r0 | [[result]] | Success | NO           |                      |
		| SFTP with Overwrite        | [[path]] | sftp://rsaklfsvrgendev/filetowrite0.txt                      | Overwrite     | warewolf rules | dev2              | Q/ulw&]  | [[result]] | Success | NO           |                      |
		| Local with Append Top      | [[path]] | c:\Temp\filetowrite1.txt                                     | Append Top    | warewolf rules | ""                | ""       | [[result]] | Success | NO           |                      |
		| UNC with Append Top        | [[path]] | \\\\RSAKLFSVRPDC\FileSystemShareTestingSite\filetowrite1.txt | Append Top    | warewolf rules | ""                | ""       | [[result]] | Success | NO           |                      |
		| FTP with Append Top        | [[path]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/filetowrite1.txt          | Append Top    | warewolf rules | ""                | ""       | [[result]] | Success | NO           |                      |
		| FTPS with Append Top       | [[path]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/filetowrite1.txt          | Append Top    | warewolf rules | integrationtester | I73573r0 | [[result]] | Success | NO           |                      |
		| SFTP with Append Top       | [[path]] | sftp://rsaklfsvrgendev/filetowrite1.txt                      | Append Top    | warewolf rules | dev2              | Q/ulw&]  | [[result]] | Success | NO           |                      |
		| Local with Append Bottom   | [[path]] | c:\Temp\filetowrite2.txt                                     | Append Bottom | warewolf rules | ""                | ""       | [[result]] | Success | NO           |                      |
		| UNC with Append Bottom     | [[path]] | \\\\RSAKLFSVRPDC\FileSystemShareTestingSite\filetowrite2.txt | Append Bottom | warewolf rules | ""                | ""       | [[result]] | Success | NO           |                      |
		| FTP with Append Bottom     | [[path]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/filetowrite2.txt          | Append Bottom | warewolf rules | ""                | ""       | [[result]] | Success | NO           |                      |
		| FTPS with Append Bottom    | [[path]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/filetowrite2.txt          | Append Bottom | warewolf rules | integrationtester | I73573r0 | [[result]] | Success | NO           |                      |
		| SFTP with Append Bottom    | [[path]] | sftp://rsaklfsvrgendev/filetowrite2.txt                      | Append Bottom | warewolf rules | dev2              | Q/ulw&]  | [[result]] | Success | NO           |                      |
		| SFTP with Append Bottom PK | [[path]] | sftp://rsaklfsvrgendev/filetowrite21.txt                     | Append Bottom | warewolf rules | dev2              | Q/ulw&]  | [[result]] | Success | NO           | C:\\Temp\\key.opk    |
		| Local with Overwrite       | [[path]] |                                                              | Overwrite     | warewolf rules | ""                | ""       | [[result]] |         | AN           |                      |


Scenario Outline: Write file at location Null
	Given I have a source path "<source>" with value "<sourceLocation>" 
	And source credentials as "<username>" and "<password>"	
	And Method is "<method>"
	And input contents as "<content>"    
	And use private public key for source is "<sourcePrivateKeyFile>" 
	And result as "<resultVar>"
    When the write file tool is executed
	Then the execution has "<errorOccured>" error
		Examples: 
		| Name                 | source   | sourceLocation | method    | content        | username | password | resultVar  | result | errorOccured | sourcePrivateKeyFile |
		| Local with Overwrite | [[path]] | NULL           | Overwrite | warewolf rules | ""       | ""       | [[result]] |        | AN           |                      |
	
Scenario Outline: Write file validation
    Given I have a variable "[[a]]" with a value "<Val1>"
	Given I have a variable "[[b]]" with a value "<Val2>"
	Given I have a variable "[[rec(1).a]]" with a value "<Val1>"
	Given I have a variable "[[rec(2).a]]" with a value "<Val2>"
	Given I have a variable "[[index]]" with a value "1"
	Given I have a source path "<File or Folder>" with value "<sourceLocation>" 
	And source credentials as "<username>" and "<password>"	
	And use private public key for source is "<sourcePrivateKeyFile>" 
	And Method is "<method>"
	And input contents as "<content>"   
	And result as "<resultVar>"
	Then validation is "<ValidationResult>"
	And validation message is "<DesignValidation>"
    When the write file tool is executed	
	Then the result variable "<resultVar>" will be "<result>"
	And the execution has "<errorOccured>" error
	And the debug inputs as
         | Username   | Password | File Contents | Output Path                 | Method   | 
         | <username> | String   | <content>     | <source> = <sourceLocation> | <method> |
	And the debug output as
		|                        |
		| <resultVar> = <result> |
	Examples: 
		| No | Name                 | File or Folder                 | Val1              | Val2            | sourceLocation    | method        | content                  | username              | password | resultVar              | result  | errorOccured | ValidationResult | DesignValidation                                                                                                                                                                                                          | OutputError                                                                                                                                                                                                                    | sourcePrivateKeyFile |
		| 1  | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | C:\filetoread.txt | Overwrite     | warewolf rules           | ""                    | ""       | [[result]]             | String  | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |                      |
		| 2  | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | C:\filetoread.txt | Overwrite     | warewolf rules           | ""                    | ""       | [[result]]             | String  | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |                      |
		| 3  | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | C:\filetoread.txt | Overwrite     | warewolf rules           | ""                    | ""       | [[result]]             | String  | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |                      |
		| 4  | Local with Overwrite | [[a]].txt                      | c:\file           | toread          | C:\filetoread.txt | Overwrite     | warewolf rules           | ""                    | ""       | [[result]]             | String  | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |                      |
		| 5  | Local with Overwrite | [[a]][[b]].txt                 | c:\fileto         | read            | C:\filetoread.txt | Overwrite     | warewolf rules           | ""                    | ""       | [[result]]             | String  | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |                      |
		| 6  | Local with Overwrite | [[rec([[index]]).a]]           | c:\filetoread.txt | ""              | C:\filetoread.txt | Append Top    | warewolf rules           | ""                    | ""       | [[result]]             | String  | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |                      |
		| 7  | Local with Overwrite | [[a]][[b]]                     | c:\file           | toread.txt      | C:\filetoread.txt | Append Top    | warewolf rules           | ""                    | ""       | [[result]]             | String  | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |                      |
		| 8  | Local with Overwrite | [[a]]\[[b]]                    | c:                | filetoread.txt  | C:\filetoread.txt | Append Top    | warewolf rules           | ""                    | ""       | [[result]]             | String  | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |                      |
		| 9  | Local with Overwrite | [[a]]:[[b]]                    | c                 | \filetoread.txt | C:\filetoread.txt | Append Top    | warewolf rules           | ""                    | ""       | [[result]]             | String  | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |                      |
		| 10 | Local with Overwrite | C:[[a]][[b]].txt               | \fileto           | read            | C:\filetoread.txt | Append Top    | warewolf rules           | ""                    | ""       | [[result]]             | String  | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |                      |
		| 11 | Local with Overwrite | [[rec(1).a]][[rec(2).a]]       | c:\fileto         | read.txt        | C:\filetoread.txt | Append Bottom | warewolf rules           | ""                    | ""       | [[result]]             | String  | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |                      |
		| 12 | Local with Overwrite | [[rec(1).a]]\[[rec(2).a]]      | c:                | filetoread.txt  | C:\filetoread.txt | Append Bottom | warewolf rules           | ""                    | ""       | [[result]]             | String  | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |                      |
		| 13 | Local with Overwrite | [[rec(1).a]][[rec(2).a]].txt   | c:\file           | toread          | C:\filetoread.txt | Append Bottom | warewolf rules           | ""                    | ""       | [[result]]             | String  | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |                      |
		| 14 | Local with Overwrite | [[rec(1).a]]:[[rec(2).a]]      | c                 | \filetoread.txt | C:\filetoread.txt | Append Bottom | warewolf rules           | ""                    | ""       | [[result]]             | String  | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |                      |
		| 15 | Local with Overwrite | C:[[rec(1).a]][[rec(2).a]].txt | fileto            | read            | C:\filetoread.txt | Append Bottom | warewolf rules           | ""                    | ""       | [[result]]             | String  | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |                      |
		| 16 | Local with Overwrite | c:\copyfile0.txt               | ""                | ""              |                   | method        | content                  | ""                    | ""       | [[result]]             | String  | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |                      |
		| 17 | Local with Overwrite | [[rec([[index]]).a]]           | c:\filetoread.txt | ""              | c:\filetoread.txt | Overwrite     | warewolf rules           | ""                    | ""       | [[result]]             | String  | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |                      |
		| 18 | Local with Overwrite | [[a&]]                         | ""                | ""              |                   | Overwrite     | warewolf rules           | ""                    | ""       | [[result]]             | ""      | AN           | True             | File Name - Variable name [[a&]] contains invalid character(s)                                                                                                                                                            | 1.File Name - Variable name [[a&]] contains invalid character(s)                                                                                                                                                               |                      |
		| 19 | Local with Overwrite | [[rec(**).a]]                  | ""                | ""              |                   | Overwrite     | warewolf rules           | ""                    | ""       | [[result]]             | ""      | AN           | True             | File Name - Recordset index (**) contains invalid character(s)                                                                                                                                                            | 1.File Name - Recordset index (**) contains invalid character(s)                                                                                                                                                               |                      |
		| 20 | Local with Overwrite | c(*()                          | ""                | ""              |                   | Overwrite     | warewolf rules           | ""                    | ""       | [[result]]             | ""      | AN           | True             | Please supply a valid File or Folder                                                                                                                                                                                      | 1.Please supply a valid File or Folder                                                                                                                                                                                         |                      |
		| 21 | Local with Overwrite | C:\\\\\gvh                     | ""                | ""              |                   | Overwrite     | warewolf rules           | ""                    | ""       | [[result]]             | ""      | AN           | False            | ""                                                                                                                                                                                                                        | 1.File Name not found [ C:\\\\\gvh ]                                                                                                                                                                                           |                      |
		| 22 | Local with Overwrite | [[rec([[inde$x]]).a]]          | ""                | ""              |                   | Append Top    | warewolf rules           | ""                    | ""       | [[result]]             | ""      | AN           | True             | File Name - Variable name [[index$x]] contains invalid character(s)                                                                                                                                                       | 1.File Name - Variable name [[index$x]] contains invalid character(s)                                                                                                                                                          |                      |
		| 23 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              |                   | Append Top    | warewolf rules           | ""                    | ""       | [[result]]             | ""      | AN           | False            | ""                                                                                                                                                                                                                        | 1.No Value assigned for [[a]]                                                                                                                                                                                                  |                      |
		| 24 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | C:\filetoread.txt | Append Top    | warewolf rules           | [[$#]]                | String   | [[result]]             | ""      | AN           | True             | Username - Variable name [[$#]] contains invalid character(s)                                                                                                                                                             | 1.Username - Variable name [[$#]] contains invalid character(s)                                                                                                                                                                |                      |
		| 25 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | C:\filetoread.txt | Append Top    | warewolf rules           | [[a]]\[[b]]           | String   | [[result]]             | ""      | AN           | False            | ""                                                                                                                                                                                                                        | 1.No Value assigned for [[a]] 2.1.No Value assigned for [[b]]                                                                                                                                                                  |                      |
		| 26 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | C:\filetoread.txt | Append Top    | warewolf rules           | [[rec([[index]]).a]]  | String   | [[result]]             | ""      | AN           | False            | ""                                                                                                                                                                                                                        | 1.No Value assigned for [[index]]                                                                                                                                                                                              |                      |
		| 27 | Local with Overwrite | [[sourcePath]].txt             | ""                | ""              | C:\filetoread.txt | Append Bottom | warewolf rules           | [[rec([[index&]]).a]] | String   | [[result]]             | ""      | AN           | True             | Username - Recordset name [[indexx&]] contains invalid character(s)                                                                                                                                                       | Username - Recordset name [[indexx&]] contains invalid character(s)                                                                                                                                                            |                      |
		| 29 | Local with Overwrite | [[sourcePath]].txt             | ""                | ""              | C:\filetoread.txt | Append Bottom | warewolf rules           | [[a]]*]]              | String   | [[result]]             | ""      | AN           | True             | Username - Invalid expression: opening and closing brackets don't match                                                                                                                                                   | 1.Username - Invalid expression: opening and closing brackets don't match                                                                                                                                                      |                      |
		| 30 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | C:\filetoread.txt | Append Bottom | warewolf rules           | ""                    | ""       | [[var@]]               | ""      | AN           | True             | Result - Variable name [[var@]] contains invalid character(s)                                                                                                                                                             | 1.Result - Variable name [[var@]] contains invalid character(s)                                                                                                                                                                |                      |
		| 31 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | C:\filetoread.txt | Overwrite     | warewolf rules           | ""                    | ""       | [[var@]]               | ""      | AN           | True             | Result - Variable name [[var@]] contains invalid character(s)                                                                                                                                                             | 1.Result - Variable name [[var@]] contains invalid character(s)                                                                                                                                                                |                      |
		| 32 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | C:\filetoread.txt | Overwrite     | warewolf rules           | ""                    | ""       | [[var[[a]]]]           | ""      | AN           | True             | Result - Invalid Region [[var[[a]]]]                                                                                                                                                                                      | 1.Result - Invalid Region [[var[[a]]]]                                                                                                                                                                                         |                      |
		| 33 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | C:\filetoread.txt | Overwrite     | warewolf rules           | ""                    | ""       | [[var.a]]              | ""      | AN           | True             | Result - Variable name [[var.a]]contains invalid character(s)                                                                                                                                                             | 1.Result - Variable name [[var.a]] contains invalid character(s)                                                                                                                                                               |                      |
		| 34 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | C:\filetoread.txt | Overwrite     | warewolf rules           | ""                    | ""       | [[@var]]               | ""      | AN           | True             | Result - Variable name [[@var]] contains invalid character(s)                                                                                                                                                             | 1.Result - Variable name [[@var]] contains invalid character(s)                                                                                                                                                                |                      |
		| 35 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | C:\filetoread.txt | Overwrite     | warewolf rules           | ""                    | ""       | [[var 1]]              | ""      | AN           | True             | Result - Variable name [[var 1]] contains invalid character(s)                                                                                                                                                            | 1.Result - Variable name [[var 1]] contains invalid character(s)                                                                                                                                                               |                      |
		| 36 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | C:\filetoread.txt | Append Top    | warewolf rules           | ""                    | ""       | [[rec(1).[[rec().1]]]] | ""      | AN           | True             | Result - Invalid Region [[var[[a]]]]                                                                                                                                                                                      | 1.Result - Invalid Region [[var[[a]]]]                                                                                                                                                                                         |                      |
		| 37 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | C:\filetoread.txt | Append Top    | warewolf rules           | ""                    | ""       | [[rec(@).a]]           | ""      | AN           | True             | Result - Recordset index [[@]] contains invalid character(s)                                                                                                                                                              | 1.Result - Recordset index [[@]] contains invalid character(s)                                                                                                                                                                 |                      |
		| 38 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | C:\filetoread.txt | Append Top    | warewolf rules           | ""                    | ""       | [[rec"()".a]]          | ""      | AN           | True             | Result - Recordset name [[rec"()"]] contains invalid character(s)                                                                                                                                                         | 1.Result - Recordset name [[rec"()"]] contains invalid character(s)                                                                                                                                                            |                      |
		| 39 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | C:\filetoread.txt | Append Top    | warewolf rules           | ""                    | ""       | [[rec([[[[b]]]]).a]]   | ""      | AN           | True             | Result - Invalid Region [[rec([[[[b]]]]).a]]                                                                                                                                                                              | 1.Result - Invalid Region [[rec([[[[b]]]]).a]]                                                                                                                                                                                 |                      |
		| 40 | Local with Overwrite | [[a]                           | ""                | ""              |                   | Append Top    | warewolf rules           | ""                    | ""       | [[result]]             | ""      | AN           | True             | File Name - Invalid expression: opening and closing brackets don't match                                                                                                                                                  | 1.File Name - Invalid expression: opening and closing brackets don't match                                                                                                                                                     |                      |
		| 41 | Local with Overwrite | [[rec]]                        | ""                | ""              |                   | Append Bottom | warewolf rules           | ""                    | ""       | [[result]]             | ""      | AN           | True             | File Name - [[rec]] does not exist in your variable list                                                                                                                                                                  | 1.File Name - [[rec]] does not exist in your variable list                                                                                                                                                                     |                      |
		| 42 | Local with Overwrite | [[rec]                         | ""                | ""              |                   | Append Bottom | warewolf rules           | ""                    | ""       | [[result]]             | ""      | AN           | True             | File Name - Recordset name [[rec(]] contains invalid character(s)                                                                                                                                                         | 1.File Name - Recordset name [[rec(]] contains invalid character(s)                                                                                                                                                            |                      |
		| 43 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | C:\filetoread.txt | Append Bottom | warewolf rules           | Test                  | ""       | [[result]]             | ""      | AN           | True             | Password cannot be empty or only white space                                                                                                                                                                              | 1.Password cannot be empty or only white space                                                                                                                                                                                 |                      |
		| 44 | Local with Overwrite | A                              | ""                | ""              | ""                | Append Bottom | warewolf rules           | Test                  | ""       | [[result]]             | ""      | AN           | True             | Please supply valid File Name                                                                                                                                                                                             | 1.Please supply valid File Name                                                                                                                                                                                                |                      |
		| 45 | Local with Overwrite | [[var@]]                       | ""                | ""              |                   | Append Bottom | warewolf rules           | [[var@]]              | ""       | [[var@]]               | ""      | AN           | True             | Username - Variable name [[$#]] contains invalid character(s)   Result - Variable name [[var@]] contains invalid character(s)                                                                                             | 1.Username - Variable name [[$#]] contains invalid character(s)  2.Result - Variable name [[var@]] contains invalid character(s)                                                                                               |                      |
		| 46 | Local with Overwrite | C#$%#$]]                       | ""                | ""              |                   | Append Bottom | warewolf rules           | C#$%#$]]              | ""       | C#$%#$]]               | ""      | AN           | True             | File Name - Invalid expression: opening and closing brackets don't match  Username - Invalid expression: opening and closing brackets don't match   Result - Invalid expression: opening and closing brackets don't match | 1.File Name - Invalid expression: opening and closing brackets don't match 2.Username - Invalid expression: opening and closing brackets don't match   3.Result - Invalid expression: opening and closing brackets don't match |                      |
		| 47 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | C:\filetoread.txt | Append Bottom | [[rec(]]                 | ""                    | ""       | [[result]]             | ""      | AN           | True             | Contents - Recordset name [[indexx&]] contains invalid character(s)                                                                                                                                                       | 1.Contents - Recordset name [[indexx&]] contains invalid character(s)                                                                                                                                                          |                      |
		| 48 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | C:\filetoread.txt | Append Bottom | [[var$]]                 | ""                    | ""       | [[result]]             | Success | AN           | True             | Contents - Variable name [[var$]]  contains invalid character(s)                                                                                                                                                          | 1.Contents - Variable name [[var$]]  contains invalid character(s)                                                                                                                                                             |                      |
		| 49 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | C:\filetoread.txt | Append Bottom | [[rec(**).a]] rules      | ""                    | ""       | [[result]]             | ""      | AN           | True             | Contents - Recordset index (**) contains invalid character(s)                                                                                                                                                             | 1.Contents - Recordset index (**) contains invalid character(s)                                                                                                                                                                |                      |
		| 50 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | C:\filetoread.txt | Append Bottom | [[rec(**).a              | ""                    | ""       | [[result]]             | ""      | AN           | True             | Contents - Invalid expression: Opening and closing brackets don't match                                                                                                                                                   | 1.Contents - Invalid expression: Opening and closing brackets don't match                                                                                                                                                      |                      |
		| 51 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | C:\filetoread.txt | Append Bottom | [[rec().a]] rules        | ""                    | ""       | [[result]]             | Success | NO           | False            |                                                                                                                                                                                                                           | 1.Contents - No Value assigned for : [[rec().a]]                                                                                                                                                                               |                      |
		| 52 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | C:\filetoread.txt | Append Bottom | [[rec([[a]]).a]] rules   | ""                    | ""       | [[result]]             | ""      | AN           | False            |                                                                                                                                                                                                                           | 1.Contents - No Value assigned for : [[a]]                                                                                                                                                                                     |                      |
		| 53 | Local with Overwrite | [[variable]]                   | c:\Tempfile.txt   | ""              | C:\filetoread.txt | Overwrite     | [[var]] variable is null | ""                    | ""       | [[result]]             | ""      | NO           | False            |                                                                                                                                                                                                                           | ""                                                                                                                                                                                                                             |                      |
  