@fileFeature
Feature: Unzip
	In order to be able to Unzip File or Folder 
	as a Warewolf user
	I want a tool that will Unzip File(s) or Folder(s) at a given location
	
Scenario Outline: Unzip file at location
	Given I have a source path "<source>" with value "<sourceLocation>"
	And zip credentials as "<username>" and "<password>"
	And I have a destination path "<destination>" with value "<destinationLocation>"
	And destination credentials as "<destUsername>" and "<destPassword>"
	And overwrite is "<selected>"
	And use private public key for source is "<sourcePrivateKeyFile>"
	And use private public key for destination is "<destinationPrivateKeyFile>"	
	And result as "<resultVar>"	
	And Archive Password as "<archivepassword>"	
    When the Unzip file tool is executed
	Then the result variable "<resultVar>" will be "<result>"
	And the execution has "<errorOccured>" error
	And the debug inputs as
         | Source Path                 | Username   | Password | Source Private Key File |Destination Path                      | Destination Username | Destination Password |Destination Private Key File | Overwrite  | Archive Password |
         | <source> = <sourceLocation> | <username> | String   | <sourcePrivateKeyFile>  |<destination> = <destinationLocation> | <destUsername>       | String               |<destinationPrivateKeyFile>  | <selected> | String           |         
	And the debug output as
		|                        |
		| <resultVar> = <result> |
	Examples: 
	| No | Name            | source   | sourceLocation                                           | username          | password | destination | destinationLocation                                 | destUsername      | destPassword | selected | archivepassword | resultVar  | result  | errorOccured | sourcePrivateKeyFile | destinationPrivateKeyFile |
	| 1  | Local to Local  | [[path]] | C:\test0.zip                                             | ""                | ""       | [[path1]]   | C:\ZIP0                                             | ""                | ""           | True     | ""              | [[result]] | Success | NO           |                      |                           |
	| 2  | UNC to Local    | [[path]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\test0.zip | ""                | ""       | [[path1]]   | C:\ZIP1                                             | ""                | ""           | True     | ""              | [[result]] | Success | NO           |                      |                           |
	| 3  | FTP to Local    | [[path]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/test0.zip          | ""                | ""       | [[path1]]   | C:\ZIP2                                             | ""                | ""           | True     | ""              | [[result]] | Success | NO           |                      |                           |
	| 4  | FTPS to Local   | [[path]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/test0.zip          | integrationtester | I73573r0 | [[path1]]   | C:\ZIP3                                             | ""                | ""           | True     | ""              | [[result]] | Success | NO           |                      |                           |
	| 5  | SFTP to Local   | [[path]] | sftp://localhost/test0.zip                               | dev2              | Q/ulw&]  | [[path1]]   | C:\ZIP4                                             | ""                | ""           | True     | ""              | [[result]] | Success | NO           |                      |                           |
	| 6  | Local to UNC    | [[path]] | C:\test1.zip                                             | ""                | ""       | [[path1]]   | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\ZIP0 | ""                | ""           | True     | ""              | [[result]] | Success | NO           |                      |                           |
	| 7  | UNC to UNC      | [[path]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\test1.zip | ""                | ""       | [[path1]]   | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\ZIP1 | ""                | ""           | True     | ""              | [[result]] | Success | NO           |                      |                           |
	| 8  | FTP to UNC      | [[path]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/test1.zip          | ""                | ""       | [[path1]]   | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\ZIP2 | ""                | ""           | True     | ""              | [[result]] | Success | NO           |                      |                           |
	| 9  | FTPS to UNC     | [[path]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/test1.zip          | integrationtester | I73573r0 | [[path1]]   | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\ZIP3 | ""                | ""           | True     | ""              | [[result]] | Success | NO           |                      |                           |
	| 10 | SFTP to UNC     | [[path]] | sftp://localhost/test1.zip                               | dev2              | Q/ulw&]  | [[path1]]   | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\ZIP4 | ""                | ""           | True     | ""              | [[result]] | Success | NO           |                      |                           |
	| 11 | Local to FTP    | [[path]] | C:\test2.zip                                             | ""                | ""       | [[path1]]   | ftp://rsaklfsvrsbspdc:1001/FORTESTING/ZIP0          | ""                | ""           | True     | ""              | [[result]] | Success | NO           |                      |                           |
	| 12 | UNC to FTP      | [[path]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\test2.zip | ""                | ""       | [[path1]]   | ftp://rsaklfsvrsbspdc:1001/FORTESTING/ZIP1          | ""                | ""           | True     | ""              | [[result]] | Success | NO           |                      |                           |
	| 13 | FTP to FTP      | [[path]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/test2.zip          | ""                | ""       | [[path1]]   | ftp://rsaklfsvrsbspdc:1001/FORTESTING/ZIP2          | ""                | ""           | True     | ""              | [[result]] | Success | NO           |                      |                           |
	| 14 | FTPS to FTP     | [[path]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/test2.zip          | integrationtester | I73573r0 | [[path1]]   | ftp://rsaklfsvrsbspdc:1001/FORTESTING/ZIP3          | ""                | ""           | True     | ""              | [[result]] | Success | NO           |                      |                           |
	| 15 | SFTP to FTP     | [[path]] | sftp://localhost/test2.zip                               | dev2              | Q/ulw&]  | [[path1]]   | ftp://rsaklfsvrsbspdc:1001/FORTESTING/ZIP4          | ""                | ""           | True     | ""              | [[result]] | Success | NO           |                      |                           |
	| 16 | Local to FTPS   | [[path]] | C:\test3.zip                                             | ""                | ""       | [[path1]]   | ftp://rsaklfsvrsbspdc:1002/FORTESTING/ZIP0          | integrationtester | I73573r0     | True     | ""              | [[result]] | Success | NO           |                      |                           |
	| 17 | UNC to FTPS     | [[path]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\test3.zip | ""                | ""       | [[path1]]   | ftp://rsaklfsvrsbspdc:1002/FORTESTING/ZIP1          | integrationtester | I73573r0     | True     | ""              | [[result]] | Success | NO           |                      |                           |
	| 18 | FTP tp FTPS     | [[path]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/test3.zip          | ""                | ""       | [[path1]]   | ftp://rsaklfsvrsbspdc:1002/FORTESTING/ZIP2          | integrationtester | I73573r0     | True     | ""              | [[result]] | Success | NO           |                      |                           |
	| 19 | FTPS to FTPS    | [[path]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/test3.zip          | integrationtester | I73573r0 | [[path1]]   | ftp://rsaklfsvrsbspdc:1002/FORTESTING/ZIP3          | integrationtester | I73573r0     | True     | ""              | [[result]] | Success | NO           |                      |                           |
	| 20 | SFTP to FTPS    | [[path]] | sftp://localhost/test3.zip                               | dev2              | Q/ulw&]  | [[path1]]   | ftp://rsaklfsvrsbspdc:1002/FORTESTING/ZIP4          | integrationtester | I73573r0     | True     | ""              | [[result]] | Success | NO           |                      |                           |
	| 21 | Local to SFTP   | [[path]] | C:\test4.zip                                             | ""                | ""       | [[path1]]   | sftp://localhost/ZIP0                               | dev2              | Q/ulw&]      | True     | ""              | [[result]] | Success | NO           |                      |                           |
	| 22 | UNC to SFTP     | [[path]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\test4.zip | ""                | ""       | [[path1]]   | sftp://localhost/ZIP1                               | dev2              | Q/ulw&]      | True     | ""              | [[result]] | Success | NO           |                      |                           |
	| 23 | FTP to SFTP     | [[path]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/test4.zip          | ""                | ""       | [[path1]]   | sftp://localhost/ZIP2                               | dev2              | Q/ulw&]      | True     | ""              | [[result]] | Success | NO           |                      |                           |
	| 24 | FTPS to SFTP    | [[path]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/test4.zip          | integrationtester | I73573r0 | [[path1]]   | sftp://localhost/ZIP3                               | dev2              | Q/ulw&]      | True     | ""              | [[result]] | Success | NO           |                      |                           |
	| 25 | SFTP to SFTP    | [[path]] | sftp://localhost/test5.zip                               | dev2              | Q/ulw&]  | [[path1]]   | sftp://localhost/ZIP6                               | dev2              | Q/ulw&]      | True     | ""              | [[result]] | Success | NO           |                      |                           |
	| 26 | SFTP to SFTP PK | [[path]] | sftp://localhost/test51.zip                              | dev2              | Q/ulw&]  | [[path1]]   | sftp://localhost/ZIP61                              | dev2              | Q/ulw&]      | True     | ""              | [[result]] | Success | NO           | C:\\Temp\\key.opk    | C:\\Temp\\key.opk         |



Scenario Outline: Unzip file validation
    Given I have a variable "[[a]]" with a value "<Val1>"
	Given I have a variable "[[b]]" with a value "<Val2>"
	Given I have a variable "[[rec(1).a]]" with a value "<Val1>"
	Given I have a variable "[[rec(2).a]]" with a value "<Val2>"
	Given I have a variable "[[index]]" with a value "1"
	Given I have a source path "<File or Folder>" with value "<sourceLocation>" 
	And zip credentials as "<username>" and "<password>"
	And I have a destination path "<destination>" with value "<destinationLocation>"
    And destination credentials as "<destUsername>" and "<destPassword>"
	And use private public key for source is "<sourcePrivateKeyFile>"
	And use private public key for destination is "<destinationPrivateKeyFile>"	
	And overwrite is "<selected>"
	And result as "<resultVar>"
	And Archive Password as "<Archive Password>"
	When validating the unzip tool
	Then validation is "<ValidationResult>"
	And validation message is "<DesignValidation>"
    When the Unzip file tool is executed
	Then the result variable "<resultVar>" will be "<result>"
	And the execution has "<errorOccured>" error	
	And the debug inputs as
        | Source Path                         | Username   | Password | Destination Path                      | Destination Username | Destination Password | Overwrite  | Archive Password | Destination Private Key File | Source Private Key File |
        | <File or Folder> = <sourceLocation> | <username> | String   | <destination> = <destinationLocation> | <destUsername>       | String               | <selected> | String           | <destinationPrivateKeyFile>  | <sourcePrivateKeyFile>  |
	
	Examples: 
		| No | File or Folder              | Val1          | Val2        | sourceLocation    | username              | password | destination                  | destinationLocation | destUsername      | destPassword | selected | resultVar              | Archive Password | result  | errorOccured | ValidationResult | DesignValidation                                                                                                         | OutputError                                                                           |
		| No | [[sourcePath]]              | ""            | ""          | C:\test7.zip      | ""                    | ""       | [[destPath]]                 | C:\ZIP9             | dev2              | Q/ulw&]      | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 1  | [[sourcePath]]              | ""            | ""          | C:\test12.zip     | ""                    | ""       | [[destPath]]                 | C:\ZIP12            | ""                | ""           | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 2  | [[sourcePath]]              | ""            | ""          | C:\test13.zip     | ""                    | ""       | [[destPath]]                 | C:\ZIP13            | integrationtester | I73573r0     | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 3  | [[sourcePath]]              | ""            | ""          | C:\test14.zip     | ""                    | ""       | [[destPath]]                 | C:\ZIP14            | ""                | ""           | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 4  | [[sourcePath]]              | ""            | ""          | C:\test10.zip     | ""                    | ""       | [[destPath]]                 | C:\ZIP10            | ""                | ""           | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 5  | [[sourcePath]]              | ""            | ""          | C:\test11.zip     | ""                    | ""       | [[destPath]]                 | C:\ZIP11            | ""                | ""           | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 6  | [[sourcePath]]              | ""            | ""          | C:\test15.zip     | ""                    | ""       | [[destPath]]                 | C:\ZIP15            | ""                | ""           | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 7  | [[sourcePath]]              | ""            | ""          | C:\test16.zip     | ""                    | ""       | [[destPath]]                 | C:\ZIP16            | ""                | ""           | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 8  | [[sourcePath]]              | ""            | ""          | C:\test17.zip     | ""                    | ""       | [[destPath]]                 | C:\ZIP17            | integrationtester | I73573r0     | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 9  | [[sourcePath]]              | ""            | ""          | C:\test18.zip     | ""                    | ""       | [[destPath]]                 | C:\ZIP18            | dev2              | Q/ulw&]      | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 10 | [[sourcePath]]              | ""            | ""          | C:\test19.zip     | ""                    | ""       | [[destPath]]                 | C:\ZIP19            | ""                | ""           | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 11 | [[sourcePath]]              | ""            | ""          | C:\test20.zip     | ""                    | ""       | [[destPath]]                 | C:\ZIP20            | ""                | ""           | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 12 | [[sourcePath]]              | ""            | ""          | C:\test21.zip     | ""                    | ""       | [[destPath]]                 | C:\ZIP21            | ""                | ""           | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 13 | [[sourcePath]]              | ""            | ""          | C:\test22.zip     | ""                    | ""       | [[destPath]]                 | C:\ZIP22            | ""                | ""           | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 14 | [[sourcePath]]              | ""            | ""          | C:\test23.zip     | ""                    | ""       | [[destPath]]                 | C:\ZIP23            | integrationtester | I73573r0     | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 15 | [[a]][[b]]                  | C:\test24     | .zip        | C:\test24.zip     | ""                    | ""       | [[destPath]]                 | C:\ZIP24            | integrationtester | I73573r0     | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 16 | [[a]]\[[b]]                 | C:            | test25.zip  | C:\test25.zip     | ""                    | ""       | [[destPath]]                 | C:\ZIP25            | integrationtester | I73573r0     | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 17 | [[a]][[b]].zip              | C:\test       | 26          | C:\test26.zip     | ""                    | ""       | [[destPath]]                 | C:\ZIP26            | integrationtester | I73573r0     | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 18 | [[a]]:[[b]]                 | C             | \test27.zip | C:\test27.zip     | ""                    | ""       | [[destPath]]                 | C:\ZIP27            | integrationtester | I73573r0     | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 19 | C:[[a]][[b]]                | \test         | 28.zip      | C:\test28.zip     | ""                    | ""       | [[destPath]]                 | C:\ZIP28            | integrationtester | I73573r0     | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 20 | [[rec(1).a]][[rec(2).a]]    | C:\test       | 29.zip      | C:\test29.zip     | ""                    | ""       | [[destPath]]                 | C:\ZIP29            | integrationtester | I73573r0     | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 21 | [[rec(1).a]]\[[rec(2).a]]   | C:            | test30.zip  | C:\test30.zip     | ""                    | ""       | [[destPath]]                 | C:\ZIP30            | integrationtester | I73573r0     | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 22 | [[rec(1).a]][[rec(2).a]]    | C:\test       | 31.zip      | C:\test31.zip     | ""                    | ""       | [[destPath]]                 | C:\ZIP31            | integrationtester | I73573r0     | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 23 | [[rec(1).a]]:[[rec(2).a]]   | C             | \test32.zip | C:\test32.zip     | ""                    | ""       | [[destPath]]                 | C:\ZIP32            | integrationtester | I73573r0     | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 24 | C:\[[rec(1).a]][[rec(2).a]] | test          | 33.zip      | C:\test33.zip     | ""                    | ""       | [[destPath]]                 | C:\ZIP33            | integrationtester | I73573r0     | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 25 | [[rec(1).a]]                |               |             | C:\test34.zip     | ""                    | ""       | [[destPath]]                 | C:\ZIP34            | integrationtester | I73573r0     | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 26 | [[rec(1).a]]                | C:\test35.zip | ""          | C:\test35.zip     | ""                    | ""       | [[destPath]]                 | C:\ZIP35            | integrationtester | I73573r0     | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 27 | [[rec(1).a]]                |               |             | C:\test36.zip     | ""                    | ""       | [[destPath]]                 | C:\ZIP36            | integrationtester | I73573r0     | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 28 | [[sourcePath]]              | C:            | \ZIP37      | C:\test37.zip     | ""                    | ""       | [[a]][[b]]                   | C:\ZIP37            | integrationtester | I73573r0     | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 29 | [[sourcePath]]              | C:            | ZIP38       | C:\test38.zip     | ""                    | ""       | [[a]]\[[b]]                  | C:\ZIP38            | integrationtester | I73573r0     | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 30 | [[sourcePath]]              | C:\           | ZIP         | C:\test39.zip     | ""                    | ""       | [[a]][[b]]39                 | C:\ZIP39            | integrationtester | I73573r0     | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 31 | [[sourcePath]]              | C             | ZIP40       | C:\test40.zip     | ""                    | ""       | [[a]]:\[[b]]                 | C:\ZIP40            | integrationtester | I73573r0     | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 32 | [[sourcePath]]              | \ZIP          | 41          | C:\test41.zip     | ""                    | ""       | C:[[a]][[b]]                 | C:\ZIP41            | integrationtester | I73573r0     | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 33 | [[sourcePath]]              | C:\           | ZIP42       | C:\test42.zip     | ""                    | ""       | [[rec(1).a]][[rec(2).a]]     | C:\ZIP42            | integrationtester | I73573r0     | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 34 | [[sourcePath]]              | C:            | ZIP43       | C:\test43.zip     | ""                    | ""       | [[rec(1).a]]\[[rec(2).a]]    | C:\ZIP43            | integrationtester | I73573r0     | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 35 | [[sourcePath]]              | C:\           | ZIP44       | C:\test44.zip     | ""                    | ""       | [[rec(1).a]][[rec(2).a]]     | C:\ZIP44            | integrationtester | I73573r0     | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 36 | [[sourcePath]]              | C             | \ZIP45      | C:\test45.zip     | ""                    | ""       | [[rec(1).a]]:[[rec(2).a]]    | C:\ZIP45            | integrationtester | I73573r0     | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 37 | [[sourcePath]]              | \             | ZIP         | C:\test46.zip     | ""                    | ""       | C:[[rec(1).a]][[rec(2).a]]46 | C:\ZIP46            | integrationtester | I73573r0     | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 38 | [[sourcePath]]              | ""            | ""          | C:\test47.zip     | ""                    | ""       |                              | C:\ZIP47            | integrationtester | I73573r0     | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 39 | [[sourcePath]]              | C:\ZIP48      | ""          | C:\test48.zip     | ""                    | ""       | [[rec(1).a]]                 | C:\ZIP48            | integrationtester | I73573r0     | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 40 | [[sourcePath]]              | ""            | ""          | C:\test49.zip     | ""                    | ""       |                              | C:\ZIP49            | integrationtester | I73573r0     | True     | [[result]]             | ""               | Success | NO           | False            | ""                                                                                                                       | ""                                                                                    |
		| 41 | [[a&]]                      | ""            | ""          |                   | ""                    | ""       | [[destPath]]                 | C:\ZIP50            | integrationtester | I73573r0     | True     | [[result]]             | ""               | ""      | AN           | True             | Invalid Path. Please ensure that the path provided is an absolute path, if you intended to access the local file system. | 1.File or Folder - Variable name [[a&]] contains invalid character(s)                 |
		| 42 | [[rec(**).a]]               | ""            | ""          |                   | ""                    | ""       | [[destPath]]                 | C:\ZIP51            | integrationtester | I73573r0     | True     | [[result]]             | ""               | ""      | AN           | True             | Invalid Path. Please ensure that the path provided is an absolute path, if you intended to access the local file system. | 1.File or Folder - Recordset index (**) contains invalid character(s)                 |
		| 43 | [[a]                        | ""            | ""          |                   | ""                    | ""       | [[destPath]]                 | C:\ZIP52            | integrationtester | I73573r0     | True     | [[result]]             | ""               | ""      | AN           | True             | Invalid Path. Please ensure that the path provided is an absolute path, if you intended to access the local file system. | 1.File or Folder - Invalid expression: opening and closing brackets don't match       |
		| 44 | [[rec(a]]                   | ""            | ""          |                   | ""                    | ""       | [[destPath]]                 | C:\ZIP53            | integrationtester | I73573r0     | True     | [[result]]             | ""               | ""      | AN           | True             | Invalid Path. Please ensure that the path provided is an absolute path, if you intended to access the local file system. | 1.File or Folder - Recordset name [[rec(a]] contains invalid character(s)             |
		| 45 | c(*()                       | ""            | ""          |                   | ""                    | ""       | [[destPath]]                 | C:\ZIP54            | integrationtester | I73573r0     | True     | [[result]]             | ""               | ""      | AN           | True             | Invalid Path. Please ensure that the path provided is an absolute path, if you intended to access the local file system. | 1.Please supply a valid File or Folder                                                |
		| 46 | [[rec([[inde$x]]).a]]       | ""            | ""          |                   | ""                    | ""       | [[destPath]]                 | C:\ZIP55            | integrationtester | I73573r0     | True     | [[result]]             | ""               | ""      | AN           | True             | Invalid Path. Please ensure that the path provided is an absolute path, if you intended to access the local file system. | 1.File or Folder - Variable name [[inde$x]]  contains invalid character(s)            |
		| 47 | ghjghj                      | ""            | ""          |                   | ""                    | ""       | [[destPath]]                 | C:\ZIP56            | integrationtester | I73573r0     | True     | [[result]]             | ""               | ""      | AN           | True             | Invalid Path. Please ensure that the path provided is an absolute path, if you intended to access the local file system. | 1.Please supply a valid File or Folder                                                |
		| 48 | ""                          | ""            | ""          |                   | ""                    | ""       | [[destPath]]                 | C:\ZIP57            | integrationtester | I73573r0     | True     | [[result]]             | ""               | ""      | AN           | True             | Invalid Path. Please ensure that the path provided is an absolute path, if you intended to access the local file system. | 1.File or Folder cannot be empty or only white space                                  |
		| 49 | [[sourcePath]]              | ""            | ""          | C:\copyfile50.txt | ""                    | ""       | [[a&]]                       | C:\ZIP58            | integrationtester | I73573r0     | True     | [[result]]             | ""               | ""      | AN           | True             | Invalid Path. Please ensure that the path provided is an absolute path, if you intended to access the local file system. | 1.Destination - Variable name [[a&]] contains invalid character(s)                    |
		| 50 | [[sourcePath]]              | ""            | ""          | C:\copyfile51.txt | ""                    | ""       | [[rec(**).a]]                | C:\ZIP59            | integrationtester | I73573r0     | True     | [[result]]             | ""               | ""      | AN           | True             | Invalid Path. Please ensure that the path provided is an absolute path, if you intended to access the local file system. | 1.Destination - Recordset index (**) contains invalid character(s)                    |
		| 51 | [[sourcePath]]              | ""            | ""          | C:\copyfile52.txt | ""                    | ""       | [[a]                         | C:\ZIP60            | integrationtester | I73573r0     | True     | [[result]]             | ""               | ""      | AN           | True             | Invalid Path. Please ensure that the path provided is an absolute path, if you intended to access the local file system. | 1.Destination - Invalid expression: opening and closing brackets don't match          |
		| 52 | [[sourcePath]]              | ""            | ""          | C:\copyfile53.txt | ""                    | ""       | [[rec(a]]                    | C:\ZIP61            | integrationtester | I73573r0     | True     | [[result]]             | ""               | ""      | AN           | True             | Invalid Path. Please ensure that the path provided is an absolute path, if you intended to access the local file system. | 1.Destination - Recordset name [[rec(a]] contains invalid character(s)                |
		| 53 | [[sourcePath]]              | ""            | ""          | c(*()             | ""                    | ""       | C:\copyfile54.txt            | C:\ZIP62            | integrationtester | I73573r0     | True     | [[result]]             | ""               | ""      | AN           | True             | Invalid Path. Please ensure that the path provided is an absolute path, if you intended to access the local file system. | 1.Please supply a valid File or Folder                                                |
		| 54 | [[sourcePath]]              | ""            | ""          | C:\copyfile55.txt | ""                    | ""       | [[rec([[inde$x]]).a]]        | C:\ZIP63            | integrationtester | I73573r0     | True     | [[result]]             | ""               | ""      | AN           | True             | Invalid Path. Please ensure that the path provided is an absolute path, if you intended to access the local file system. | 1.Destination - Variable name [[inde$x]]  contains invalid character(s)               |
		| 55 | [[sourcePath]]              | ""            | ""          | C:\copyfile56.txt | ""                    | ""       | ghjghj                       | C:\ZIP64            | integrationtester | I73573r0     | True     | [[result]]             | ""               | ""      | AN           | True             | Invalid Path. Please ensure that the path provided is an absolute path, if you intended to access the local file system. | 1.Please supply a valid File or Folder                                                |
		| 56 | [[sourcePath]]              | ""            | ""          | C:\copyfile57.txt | ""                    | ""       | ""                           | C:\ZIP65            | integrationtester | I73573r0     | True     | [[result]]             | ""               | ""      | AN           | True             | Invalid Path. Please ensure that the path provided is an absolute path, if you intended to access the local file system. | 1.Destination cannot be empty or only white space                                     |
		| 57 | [[sourcePath]]              | ""            | ""          | C:\copyfile58.txt | [[a&]]                | String   | [[destPath]]                 | C:\ZIP66            | integrationtester | I73573r0     | True     | [[result]]             | ""               | ""      | AN           | True             | Failed to authenticate with user [ [[a&]] ] for resource [ C:\copyfile58.txt ]                                           | 1.Username - Variable name [[a&]] contains invalid character(s)                       |
		| 58 | [[sourcePath]]              | ""            | ""          | C:\copyfile59.txt | [[rec(**).a]]         | String   | [[destPath]]                 | C:\ZIP67            | integrationtester | I73573r0     | True     | [[result]]             | ""               | ""      | AN           | True             | Failed to authenticate with user [ [[rec(**).a]] ] for resource [ C:\copyfile59.txt ]                                    | 1.Username - Recordset index (**) contains invalid character(s)                       |
		| 59 | [[sourcePath]]              | ""            | ""          | C:\copyfile60.txt | [[a]                  | String   | [[destPath]]                 | C:\ZIP68            | integrationtester | I73573r0     | True     | [[result]]             | ""               | ""      | AN           | True             | Failed to authenticate with user [ [[a] ] for resource [ C:\copyfile60.txt ]                                             | 1.Username - Invalid expression: opening and closing brackets don't match             |
		| 60 | [[sourcePath]]              | ""            | ""          | C:\copyfile61.txt | [[rec(a]]             | String   | [[destPath]]                 | C:\ZIP69            | integrationtester | I73573r0     | True     | [[result]]             | ""               | ""      | AN           | True             | Failed to authenticate with user [ [[rec(a]] ] for resource [ C:\copyfile61.txt ]                                        | 1.Username - Recordset name [[rec(a]] contains invalid character(s)                   |
		| 61 | [[sourcePath]]              | ""            | ""          | C:\copyfile62.txt | [[rec([[inde$x]]).a]] | String   | [[destPath]]                 | C:\ZIP70            | integrationtester | I73573r0     | True     | [[result]]             | ""               | ""      | AN           | True             | Failed to authenticate with user [ [[rec([[inde$x]]).a]] ] for resource [ C:\copyfile62.txt ]                            | 1.Username - Variable name [[inde$x]]  contains invalid character(s)                  |
		| 62 | [[sourcePath]]              | ""            | ""          | C:\copyfile63.txt | [[a]]                 | String   | [[destPath]]                 | C:\ZIP71            | integrationtester | I73573r0     | True     | [[result]]             | ""               | ""      | AN           | True             | Failed to authenticate with user [ [[a]] ] for resource [ C:\copyfile63.txt ]                                            | 1.Failed to authenticate with user [ [[a]] ] for resource [ C:\copyfile63.txt ]       |
		| 63 | [[sourcePath]]              | ""            | ""          | C:\copyfile64.txt | [[a&]]                | String   | [[destPath]]                 | C:\ZIP72            | integrationtester | I73573r0     | True     | [[result]]             | ""               | ""      | AN           | True             | Failed to authenticate with user [ [[a&]] ] for resource [ C:\copyfile64.txt ]                                           | 1.Destination Username - Variable name [[a&]] contains invalid character(s)           |
		| 64 | [[sourcePath]]              | ""            | ""          | C:\copyfile65.txt | [[rec(**).a]]         | String   | [[destPath]]                 | C:\ZIP73            | integrationtester | I73573r0     | True     | [[result]]             | ""               | ""      | AN           | True             | Failed to authenticate with user [ [[rec(**).a]] ] for resource [ C:\copyfile65.txt ]                                    | 1.Destination Username - Recordset index (**) contains invalid character(s)           |
		| 65 | [[sourcePath]]              | ""            | ""          | C:\copyfile66.txt | [[a]                  | String   | [[destPath]]                 | C:\ZIP74            | integrationtester | I73573r0     | True     | [[result]]             | ""               | ""      | AN           | True             | Failed to authenticate with user [ [[a] ] for resource [ C:\copyfile66.txt ]                                             | 1.Destination Username - Invalid expression: opening and closing brackets don't match |
		| 66 | [[sourcePath]]              | ""            | ""          | C:\copyfile67.txt | [[rec(a]]             | String   | [[destPath]]                 | C:\ZIP75            | integrationtester | I73573r0     | True     | [[result]]             | ""               | ""      | AN           | True             | Failed to authenticate with user [ [[rec(a]] ] for resource [ C:\copyfile67.txt ]                                        | 1.Destination Username - Recordset name [[rec(a]] contains invalid character(s)       |
		| 67 | [[sourcePath]]              | ""            | ""          | C:\copyfile68.txt | [[rec([[inde$x]]).a]] | String   | [[destPath]]                 | C:\ZIP76            | integrationtester | I73573r0     | True     | [[result]]             | ""               | ""      | AN           | True             | Failed to authenticate with user [ [[rec([[inde$x]]).a]] ] for resource [ C:\copyfile68.txt ]                            | 1.Destination Username - Variable name [[inde$x]]  contains invalid character(s)      |
		| 68 | [[sourcePath]]              | ""            | ""          | C:\copyfile70.txt | ""                    | ""       | [[destPath]]                 | C:\ZIP78            | integrationtester | I73573r0     | True     | [[result]][[a]]        | ""               | ""      | AN           | True             | The result field only allows a single result                                                                             | 1.The result field only allows a single result                                        |
		| 69 | [[sourcePath]]              | ""            | ""          | C:\copyfile71.txt | [[a]                  | ""       | [[destPath]]                 | C:\ZIP79            | integrationtester | I73573r0     | True     | [[a]]*]]               | ""               | ""      | AN           | True             | Failed to authenticate with user [ [[a] ] for resource [ C:\copyfile71.txt ]                                             | 1.Failed to authenticate with user [ [[a] ] for resource [ C:\copyfile71.txt ]        |
		| 70 | [[sourcePath]]              | ""            | ""          | C:\copyfile72.txt | ""                    | ""       | [[destPath]]                 | C:\ZIP80            | integrationtester | I73573r0     | True     | [[var@]]               | ""               | ""      | AN           | True             | Result - Variable name [[var@]] contains invalid character(s)                                                            | 1.Result - Variable name [[var@]] contains invalid character(s)                       |
		| 71 | [[sourcePath]]              | ""            | ""          | C:\copyfile73.txt | [[var]]00]]           | ""       | [[destPath]]                 | C:\ZIP81            | integrationtester | I73573r0     | True     | [[var]]00]]            | ""               | ""      | AN           | True             | Failed to authenticate with user [ [[var]]00]] ] for resource [ C:\copyfile73.txt ]                                      | 1.Result - Invalid expression: opening and closing brackets don't match               |
		| 72 | [[sourcePath]]              | ""            | ""          | C:\copyfile74.txt | ""                    | ""       | [[destPath]]                 | C:\ZIP82            | integrationtester | I73573r0     | True     | [[var@]]               | ""               | ""      | AN           | True             | Result - Variable name [[1var]] contains invalid character(s)                                                            | 1.Result - Variable name [[1var]] contains invalid character(s)                       |
		| 73 | [[sourcePath]]              | ""            | ""          | C:\copyfile75.txt | ""                    | ""       | [[destPath]]                 | C:\ZIP83            | integrationtester | I73573r0     | True     | [[var[[a]]]]           | ""               | ""      | AN           | True             | Result - Invalid Region [[var[[a]]]]                                                                                     | 1.Result - Invalid Region [[var[[a]]]]                                                |
		| 74 | [[sourcePath]]              | ""            | ""          | C:\copyfile76.txt | ""                    | ""       | [[destPath]]                 | C:\ZIP84            | integrationtester | I73573r0     | True     | [[var.a]]              | ""               | ""      | AN           | True             | Result - Variable name [[var.a]]contains invalid character(s)                                                            | 1.Result - Variable name [[var.a]] contains invalid character(s)                      |
		| 75 | [[sourcePath]]              | ""            | ""          | C:\copyfile77.txt | ""                    | ""       | [[destPath]]                 | C:\ZIP85            | integrationtester | I73573r0     | True     | [[@var]]               | ""               | ""      | AN           | True             | Result - Variable name [[@var]] contains invalid character(s)                                                            | 1.Result - Variable name [[@var]] contains invalid character(s)                       |
		| 76 | [[sourcePath]]              | ""            | ""          | C:\copyfile78.txt | ""                    | ""       | [[destPath]]                 | C:\ZIP86            | integrationtester | I73573r0     | True     | [[var 1]]              | ""               | ""      | AN           | True             | Result - Variable name [[var 1]] contains invalid character(s)                                                           | 1.Result - Variable name [[var 1]] contains invalid character(s)                      |
		| 77 | [[sourcePath]]              | ""            | ""          | C:\copyfile79.txt | ""                    | ""       | [[destPath]]                 | C:\ZIP87            | integrationtester | I73573r0     | True     | [[rec(1).[[rec().1]]]] | ""               | ""      | AN           | True             | Result - Invalid Region [[rec(1).[[rec().1]]]]                                                                           | 1.Result - Invalid Region [[rec(1).[[rec().1]]]]                                      |
		| 78 | [[sourcePath]]              | ""            | ""          | C:\copyfile80.txt | ""                    | ""       | [[destPath]]                 | C:\ZIP88            | integrationtester | I73573r0     | True     | [[rec(@).a]]           | ""               | ""      | AN           | True             | Result - Recordset index [[@]] contains invalid character(s)                                                             | 1.Result - Recordset index [[@]] contains invalid character(s)                        |
		| 79 | [[sourcePath]]              | ""            | ""          | C:\copyfile81.txt | ""                    | ""       | [[destPath]]                 | C:\ZIP89            | integrationtester | I73573r0     | True     | [[rec"()".a]]          | ""               | ""      | AN           | True             | Result - Recordset name [[rec"()"]] contains invalid character(s)                                                        | 1.Result - Recordset name [[rec"()"]] contains invalid character(s)                   |
		| 80 | [[sourcePath]]              | ""            | ""          | C:\copyfile82.txt | ""                    | ""       | [[destPath]]                 | C:\ZIP90            | integrationtester | I73573r0     | True     | [[rec([[[[b]]]]).a]]   | ""               | ""      | AN           | True             | Result - Invalid Region [[rec([[[[b]]]]).a]]                                                                             | 1.Result - Invalid Region [[rec([[[[b]]]]).a]]                                        |
	  	  										