using System.Reflection;
using System.Runtime.CompilerServices;
#pragma warning disable CC0021 // Use nameof
[assembly: AssemblyCompany(@"Warewolf")]
[assembly: AssemblyProduct(@"Warewolf")]
#pragma warning restore CC0021 // Use nameof
[assembly: AssemblyCopyright(@"Copyright Warewolf 2019")]
[assembly: AssemblyVersion(@"2.2.0.107")]
[assembly: AssemblyInformationalVersion(@"05/31/2019 14:31:17 4e64fc5d7f5ab9aafaaec6c9249107ffe41a52d0 develop")]
[assembly: InternalsVisibleTo("Dev2.Activities.Designers.Tests")]
[assembly: InternalsVisibleTo("Dev2.Activities.Specs")]
[assembly: InternalsVisibleTo("Dev2.Activities.Tests")]
[assembly: InternalsVisibleTo("Dev2.Common.Tests")]
[assembly: InternalsVisibleTo("Dev2.Core.Tests")]
[assembly: InternalsVisibleTo("Dev2.CustomControls.Tests")]
[assembly: InternalsVisibleTo("Dev2.Data.Tests")]
[assembly: InternalsVisibleTo("Dev2.Infrastructure.Tests")]
[assembly: InternalsVisibleTo("Dev2.Integration.Tests")]
[assembly: InternalsVisibleTo("Dev2.Runtime.Tests")]
[assembly: InternalsVisibleTo("Dev2.Studio.Core.Tests")]
[assembly: InternalsVisibleTo("Dev2.TaskScheduler.Wrappers")]
[assembly: InternalsVisibleTo("Dev2.Utils.Tests")]
[assembly: InternalsVisibleTo("Warewolf.Storage.Tests")]
[assembly: InternalsVisibleTo("Warewolf.Studio.ViewModels.Tests")]
[assembly: InternalsVisibleTo("Warewolf.Tools.Specs")]
[assembly: InternalsVisibleTo("Warewolf.UIBindingTests.ComDll")]
[assembly: InternalsVisibleTo("Warewolf.UIBindingTests.PluginSource")]
[assembly: InternalsVisibleTo(@"Dev2.Activities.Designers.Tests")]
[assembly: InternalsVisibleTo(@"Dev2.Activities.Specs")]
[assembly: InternalsVisibleTo(@"Dev2.Activities.Tests")]
[assembly: InternalsVisibleTo(@"Dev2.Core.Tests")]
[assembly: InternalsVisibleTo(@"Dev2.Data.Tests")]
[assembly: InternalsVisibleTo(@"Dev2.Infrastructure.Tests")]
[assembly: InternalsVisibleTo(@"Dev2.Integration.Tests")]
[assembly: InternalsVisibleTo(@"Dev2.Runtime.Tests")]
[assembly: InternalsVisibleTo(@"Dev2.Studio.Core.Tests")]
[assembly: InternalsVisibleTo(@"Dev2.TaskScheduler.Wrappers")]
[assembly: InternalsVisibleTo(@"Warewolf.Studio.ViewModels.Tests")]
[assembly: InternalsVisibleTo(@"Warewolf.Tools.Specs")]
[assembly: InternalsVisibleTo(@"Warewolf.UIBindingTests.ComDll")]
[assembly: InternalsVisibleTo(@"Warewolf.UIBindingTests.PluginSource")]
