@fileFeature
Feature: Move
	In order to be able to Move a File or Folder 
	as a Warewolf user
	I want a tool that will Move File(s) or Folder(s) from a given location to another location
	
Scenario Outline: Move file at location
	Given I have a source path "<source>" with value "<sourceLocation>" 
	And source credentials as "<username>" and "<password>"
	And I have a destination path "<destination>" with value "<destinationLocation>"
    And destination credentials as "<destUsername>" and "<destPassword>"
	And overwrite is "<selected>"
	And use private public key for source is "<sourcePrivateKeyFile>"
	And use private public key for destination is "<destinationPrivateKeyFile>"
	And result as "<resultVar>"
    When the Move file tool is executed
	Then the result variable "<resultVar>" will be "<result>"
	And the execution has "<errorOccured>" error
	And the debug inputs as
         | Source Path                 | Username   | Password |Source Private Key File | Destination Path                      | Destination Username | Destination Password |Destination Private Key File | Overwrite  |
         | <source> = <sourceLocation> | <username> | String   |<sourcePrivateKeyFile>  | <destination> = <destinationLocation> | <destUsername>       | String               |<destinationPrivateKeyFile>  | <selected> |       
	And the debug output as
		|                        |
		| <resultVar> = <result> |
	Examples: 
	   | No | Name             | source         | sourceLocation                                            | username          | password | destination  | destinationLocation                                        | destUsername      | destPassword | selected | resultVar  | result  | errorOccured | sourcePrivateKeyFile | destinationPrivateKeyFile |
	   | 1  | Local to Local   | [[sourcePath]] | c:\movefile0.txt                                          | ""                | ""       | [[destPath]] | C:\moved0.txt                                              | ""                | ""           | True     | [[result]] | Success | NO           |                      |                           |
	   | 2  | Local to FTP     | [[sourcePath]] | c:\movefile1.txt                                          | ""                | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/moved0.txt           | ""                | ""           | True     | [[result]] | Success | NO           |                      |                           |
	   | 3  | Local to FTPS    | [[sourcePath]] | c:\movefile2.txt                                          | ""                | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/moved0.txt           | integrationtester | I73573r0     | True     | [[result]] | Success | NO           |                      |                           |
	   | 4  | Local to SFTP    | [[sourcePath]] | c:\movefile3.txt                                          | ""                | ""       | [[destPath]] | sftp://rsaklfsvrgendev/moved0.txt                          | dev2              | Q/ulw&]      | True     | [[result]] | Success | NO           |                      |                           |
	   | 5  | Local to UNC     | [[sourcePath]] | c:\movefile4.txt                                          | ""                | ""       | [[destPath]] | \\\\RSAKLFSVRPDC\FileSystemShareTestingSite\moved0.txt  | ""                | ""           | True     | [[result]] | Success | NO           |                      |                           |
	   | 6  | UNC to Local     | [[sourcePath]] | \\\\RSAKLFSVRPDC\FileSystemShareTestingSite\movefile0.txt | ""                | ""       | [[destPath]] | C:\moved1.txt                                              | ""                | ""           | True     | [[result]] | Success | NO           |                      |                           |
	   | 7  | UNC to FTP       | [[sourcePath]] | \\\\RSAKLFSVRPDC\FileSystemShareTestingSite\movefile1.txt | ""                | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/moved1.txt           | ""                | ""           | True     | [[result]] | Success | NO           |                      |                           |
	   | 8  | UNC to FTPS      | [[sourcePath]] | \\\\RSAKLFSVRPDC\FileSystemShareTestingSite\movefile2.txt | ""                | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/moved1.txt           | integrationtester | I73573r0     | True     | [[result]] | Success | NO           |                      |                           |
	   | 9  | UNC to SFTP      | [[sourcePath]] | \\\\RSAKLFSVRPDC\FileSystemShareTestingSite\movefile3.txt | ""                | ""       | [[destPath]] | sftp://rsaklfsvrgendev/moved1.txt                          | dev2              | Q/ulw&]      | True     | [[result]] | Success | NO           |                      |                           |
	   | 10 | UNC TO UNC       | [[sourcePath]] | \\\\RSAKLFSVRPDC\FileSystemShareTestingSite\movefile4.txt | ""                | ""       | [[destPath]] | \\\\RSAKLFSVRPDC\FileSystemShareTestingSite\moved1.txt  | ""                | ""           | True     | [[result]] | Success | NO           |                      |                           |
	   | 11 | FTP to Local     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/movefile0.txt          | ""                | ""       | [[destPath]] | C:\moved2.txt                                              | ""                | ""           | True     | [[result]] | Success | NO           |                      |                           |
	   | 12 | FTP to UNC       | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/movefile1.txt          | ""                | ""       | [[destPath]] | \\\\RSAKLFSVRPDC\FileSystemShareTestingSite\moved2.txt  | ""                | ""           | True     | [[result]] | Success | NO           |                      |                           |
	   | 13 | FTP to FTPS      | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/movefile2.txt          | ""                | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/moved2.txt           | integrationtester | I73573r0     | True     | [[result]] | Success | NO           |                      |                           |
	   | 14 | FTP to SFTP      | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/movefile3.txt          | ""                | ""       | [[destPath]] | sftp://rsaklfsvrgendev/moved2.txt                          | dev2              | Q/ulw&]      | True     | [[result]] | Success | NO           |                      |                           |
	   | 15 | FTP to FTP       | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/movefile4.txt          | ""                | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/moved2.txt           | ""                | ""           | True     | [[result]] | Success | NO           |                      |                           |
	   | 16 | FTPS to Local    | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/movefile0.txt          | integrationtester | I73573r0 | [[destPath]] | C:\moved3.txt                                              | ""                | ""           | True     | [[result]] | Success | NO           |                      |                           |
	   | 17 | FTPS to UNC      | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/movefile1.txt          | integrationtester | I73573r0 | [[destPath]] | \\\\RSAKLFSVRPDC\FileSystemShareTestingSite\moved3.txt  | ""                | ""           | True     | [[result]] | Success | NO           |                      |                           |
	   | 18 | FTPS to FTPS     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/movefile2.txt          | integrationtester | I73573r0 | [[destPath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/moved3.txt           | integrationtester | I73573r0     | True     | [[result]] | Success | NO           |                      |                           |
	   | 19 | FTPS to SFTP     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/movefile3.txt          | integrationtester | I73573r0 | [[destPath]] | sftp://rsaklfsvrgendev/moved3.txt                          | dev2              | Q/ulw&]      | True     | [[result]] | Success | NO           |                      |                           |
	   | 20 | FTPS to FTP      | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/movefile4.txt          | integrationtester | I73573r0 | [[destPath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/moved3.txt           | ""                | ""           | True     | [[result]] | Success | NO           |                      |                           |
	   | 21 | SFTP to Local    | [[sourcePath]] | sftp://rsaklfsvrgendev/movefile0.txt                      | dev2              | Q/ulw&]  | [[destPath]] | C:\moved4.txt                                              | ""                | ""           | True     | [[result]] | Success | NO           |                      |                           |
	   | 22 | SFTP to UNC      | [[sourcePath]] | sftp://rsaklfsvrgendev/movefile1.txt                      | dev2              | Q/ulw&]  | [[destPath]] | \\\\RSAKLFSVRPDC\FileSystemShareTestingSite\moved4.txt  | ""                | ""           | True     | [[result]] | Success | NO           |                      |                           |
	   | 23 | SFTP to FTP      | [[sourcePath]] | sftp://rsaklfsvrgendev/movefile2.txt                      | dev2              | Q/ulw&]  | [[destPath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/moved4.txt           | ""                | ""           | True     | [[result]] | Success | NO           |                      |                           |
	   | 24 | SFTP to FTPS     | [[sourcePath]] | sftp://rsaklfsvrgendev/movefile3.txt                      | dev2              | Q/ulw&]  | [[destPath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/moved4.txt           | integrationtester | I73573r0     | True     | [[result]] | Success | NO           |                      |                           |
	   | 25 | SFTP to SFTP     | [[sourcePath]] | sftp://rsaklfsvrgendev/movefile4.txt                      | dev2              | Q/ulw&]  | [[destPath]] | sftp://rsaklfsvrgendev/moved4.txt                          | dev2              | Q/ulw&]      | True     | [[result]] | Success | NO           |                      |                           |
	   | 26 | SFTP to Local PK | [[sourcePath]] | sftp://rsaklfsvrgendev/movefile01.txt                     | dev2              | Q/ulw&]  | [[destPath]] | C:\moved41.txt                                             | ""                | ""           | True     | [[result]] | Success | NO           | C:\\Temp\\key.opk    |                           |
	   | 27 | SFTP to UNC  PK  | [[sourcePath]] | sftp://rsaklfsvrgendev/movefile11.txt                     | dev2              | Q/ulw&]  | [[destPath]] | \\\\RSAKLFSVRPDC\FileSystemShareTestingSite\moved41.txt | ""                | ""           | True     | [[result]] | Success | NO           | C:\\Temp\\key.opk    |                           |
	   | 28 | SFTP to FTP  PK  | [[sourcePath]] | sftp://rsaklfsvrgendev/movefile21.txt                     | dev2              | Q/ulw&]  | [[destPath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/moved41.txt          | ""                | ""           | True     | [[result]] | Success | NO           | C:\\Temp\\key.opk    |                           |
	   | 29 | SFTP to FTPS PK  | [[sourcePath]] | sftp://rsaklfsvrgendev/movefile31.txt                     | dev2              | Q/ulw&]  | [[destPath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/moved41.txt          | integrationtester | I73573r0     | True     | [[result]] | Success | NO           | C:\\Temp\\key.opk    |                           |
	   | 30 | SFTP to SFTP PK  | [[sourcePath]] | sftp://rsaklfsvrgendev/movefile41.txt                     | dev2              | Q/ulw&]  | [[destPath]] | sftp://rsaklfsvrgendev/moved41.txt                         | dev2              | Q/ulw&]      | True     | [[result]] | Success | NO           | C:\\Temp\\key.opk    | C:\\Temp\\key.opk         |


Scenario Outline: Move file at location Null
	Given I have a source path "<source>" with value "<sourceLocation>" 
	And source credentials as "<username>" and "<password>"
	And I have a destination path "<destination>" with value "<destinationLocation>"
    And destination credentials as "<destUsername>" and "<destPassword>"
	And overwrite is "<selected>"
	And use private public key for source is "<sourcePrivateKeyFile>"
	And use private public key for destination is "<destinationPrivateKeyFile>"
	And result as "<resultVar>"
    When the Move file tool is executed
	Then the execution has "<errorOccured>" error
	Examples: 
	   | No | Name           | source         | sourceLocation                                               | username | password | destination  | destinationLocation                              | destUsername      | destPassword | selected | resultVar  | result  | errorOccured | sourcePrivateKeyFile | destinationPrivateKeyFile |
	   | 1  | Local to Local | [[sourcePath]] | NULL                                                         | ""       | ""       | [[destPath]] | Null                                             | ""                | ""           | True     | [[result]] | Failure | AN           |                      |                           |
	   | 2  | Local to Local | [[sourcePath]] | C:\moved0.txt                                                | ""       | ""       | [[destPath]] | C:\moved0.txt                                    | ""                | ""           | True     | [[result]] | Failure | AN           |                      |                           |
	   | 3  | UNC to Local   | [[sourcePath]] | \\\\RSAKLFSVRPDC\FileSystemShareTestingSite\movefile0.txt | ""       | ""       | [[destPath]] | cv:\moved1.txt                                   | ""                | ""           | True     | [[result]] | Failure | AN           |                      |                           |
	   | 4  | Local to FTP   | [[sourcePath]] | c:\temp\movefile1.txt                                        | ""       | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/moved0.txt | ""                | ""           | True     | [[result]] | Failure | NO           |                      |                           |
	   | 5  | Local to FTPS  | [[sourcePath]] | v:\movefile2.txt                                             | ""       | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/moved0.txt | integrationtester | I73573r0     | True     | [[result]] | Failure | AN           |                      |                           |
	   | 6  | Local to SFTP  | [[sourcePath]] | " "                                                          | ""       | ""       | [[destPath]] | sftp://rsaklfsvrgendev/moved0.txt                | dev2              | Q/ulw&]      | True     | [[result]] | Failure | AN           |                      |                           |
	 


Scenario Outline: Move file Validation
	Given I have a variable "[[a]]" with a value "<Val1>"
	And I have a variable "[[b]]" with a value "<Val2>"
	And I have a variable "[[rec(1).a]]" with a value "<Val1>"
	And I have a variable "[[rec(2).a]]" with a value "<Val2>"
	And I have a variable "[[index]]" with a value "1"
	And I have a source path "<File or Folder>" with value "<sourceLocation>" 
	And source credentials as "<username>" and "<password>"
	And I have a destination path "<destination>" with value "<destinationLocation>"
    And destination credentials as "<destUsername>" and "<destPassword>"
	And overwrite is "<selected>"
	And use private public key for source is "<sourcePrivateKeyFile>"
	And use private public key for destination is "<destinationPrivateKeyFile>"
	And result as "<resultVar>"
	Then validation is "<ValidationResult>"
	And validation message is "<DesignValidation>"
    When the Move file tool is executed
	Then the result variable "<resultVar>" will be "<result>"
	And the execution has "<errorOccured>" error
	And the debug inputs as
       | Source Path                         | Username   | Password | Destination Path                      | Destination Username | Destination Password | Overwrite  |
       | <File or Folder> = <sourceLocation> | <username> | String   | <destination> = <destinationLocation> | <destUsername>       | String               | <selected> |
	And the debug output as
		|                        |
		| <resultVar> = <result> |
	Examples: 
		| No | File or Folder                 | Val1              | Val2            | sourceLocation         | username              | password | destination                    | destinationLocation  | destUsername | destPassword | selected | resultVar  | result  | errorOccured | ValidationResult | DesignValidation                                                              | OutputError                                                                     | sourcePrivateKeyFile | destinationPrivateKeyFile |
		| 1  | [[sourcePath]]                 |                   |                 | c:\temp\movefile57.txt | ""                    | ""       | [[destPath]]                   | C:\temp\moved057.txt | ""           | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |                      |                           |
		| 2  | [[sourcePath]]                 |                   |                 | c:\temp\movefile58.txt | ""                    | ""       | [[destPath]]                   | C:\temp\moved058.txt | ""           | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |                      |                           |
		| 3  | [[sourcePath]]                 |                   |                 | c:\temp\movefile59.txt | ""                    | ""       | [[destPath]]                   | C:\temp\moved059.txt | ""           | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |                      |                           |
		| 4  | [[sourcePath]]                 |                   |                 | c:\temp\movefile60.txt | ""                    | ""       | [[destPath]]                   | C:\temp\moved060.txt | ""           | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |                      |                           |
		| 5  | [[sourcePath]]                 |                   |                 | c:\temp\movefile61.txt | ""                    | ""       | [[destPath]]                   | C:\temp\moved061.txt | ""           | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |                      |                           |
		| 6  | [[sourcePath]]                 |                   |                 | c:\temp\movefile5.txt  | ""                    | ""       | [[destPath]]                   | C:\temp\moved05.txt  | ""           | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |                      |                           |
		| 7  | [[sourcePath]]                 |                   |                 | c:\temp\movefile6.txt  | ""                    | ""       | [[destPath]]                   | C:\temp\moved06.txt  | ""           | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |                      |                           |
		| 8  | [[sourcePath]]                 |                   |                 | c:\temp\movefile7.txt  | ""                    | ""       | [[destPath]]                   | C:\temp\moved07.txt  | ""           | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |                      |                           |
		| 9  | [[sourcePath]]                 |                   |                 | c:\temp\movefile8.txt  | ""                    | ""       | [[destPath]]                   | C:\temp\moved08.txt  | ""           | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |                      |                           |
		| 10 | [[sourcePath]]                 |                   |                 | c:\temp\movefile9.txt  | ""                    | ""       | [[destPath]]                   | C:\temp\moved09.txt  | ""           | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |                      |                           |
		| 11 | [[sourcePath]]                 |                   |                 | c:\temp\movefile10.txt | ""                    | ""       | [[destPath]]                   | C:\temp\moved010.txt | ""           | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |                      |                           |
		| 12 | [[sourcePath]]                 |                   |                 | c:\temp\movefile11.txt | ""                    | ""       | [[destPath]]                   | C:\temp\moved011.txt | ""           | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |                      |                           |
		| 13 | [[sourcePath]]                 |                   |                 | c:\temp\movefile12.txt | ""                    | ""       | [[destPath]]                   | C:\temp\moved012.txt | ""           | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |                      |                           |
		| 14 | [[sourcePath]]                 |                   |                 | c:\temp\movefile13.txt | ""                    | ""       | [[destPath]]                   | C:\temp\moved013.txt | ""           | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |                      |                           |
		| 15 | [[sourcePath]]                 |                   |                 | c:\temp\movefile14.txt | ""                    | ""       | [[destPath]]                   | C:\temp\moved014.txt | ""           | ""           | True     | [[result]] | Success | NO           | False            | ""                                                                            | ""                                                                              |                      |                           |				
		| 42 | [[a&]]                         |                   |                 |                        | ""                    | ""       | [[destPath]]                   | C:\moved0.txt        | ""           | ""           | True     | [[result]] | ""      | AN           | True             | File or Folder - Variable name [[a&]] contains invalid character(s)           | 1.File or Folder - Variable name [[a&]] contains invalid character(s)           |                      |                           |
		| 43 | [[rec(**).a]]                  |                   |                 |                        | ""                    | ""       | [[destPath]]                   | C:\moved0.txt        | ""           | ""           | True     | [[result]] | ""      | AN           | True             | File or Folder - Recordset index (**) contains invalid character(s)           | 1.File or Folder - Recordset index (**) contains invalid character(s)           |                      |                           |
		| 44 | [[a]                           |                   |                 |                        | ""                    | ""       | [[destPath]]                   | C:\moved0.txt        | ""           | ""           | True     | [[result]] | ""      | AN           | True             | File or Folder - Invalid expression: opening and closing brackets don"t match | 1.File or Folder - Invalid expression: opening and closing brackets don"t match |                      |                           |
		| 45 | [[rec(a]]                      |                   |                 |                        | ""                    | ""       | [[destPath]]                   | C:\moved0.txt        | ""           | ""           | True     | [[result]] | ""      | AN           | True             | File or Folder - Recordset name [[rec(a]] contains invalid character(s)       | 1.File or Folder - Recordset name [[rec(a]] contains invalid character(s)       |                      |                           |
		| 46 | c(*()                          |                   |                 |                        | ""                    | ""       | [[destPath]]                   | C:\moved0.txt        | ""           | ""           | True     | [[result]] | ""      | AN           | True             | Please supply a valid File or Folder                                          | 1.Please supply a valid File or Folder                                          |                      |                           |
		| 47 | [[rec([[inde$x]]).a]]          |                   |                 |                        | ""                    | ""       | [[destPath]]                   | C:\moved0.txt        | ""           | ""           | True     | [[result]] | ""      | AN           | True             | File or Folder - Variable name [[inde$x]]  contains invalid character(s)      | 1.File or Folder - Variable name [[inde$x]]  contains invalid character(s)      |                      |                           |
		| 48 | ghjghj                         |                   |                 |                        | ""                    | ""       | [[destPath]]                   | C:\moved0.txt        | ""           | ""           | True     | [[result]] | ""      | AN           | True             | Please supply a valid File or Folder                                          | 1.Please supply a valid File or Folder                                          |                      |                           |
		| 49 | ""                             |                   |                 |                        | ""                    | ""       | [[destPath]]                   | C:\moved0.txt        | ""           | ""           | True     | [[result]] | ""      | AN           | True             | File or Folder cannot be empty or only white space                            | 1.File or Folder cannot be empty or only white space                            |                      |                           |
		| 50 | [[sourcePath]]                 |                   |                 | c:\copyfile41.txt      | ""                    | ""       | [[a&]]                         | C:\moved0.txt        | ""           | ""           | True     | [[result]] | ""      | AN           | True             | Destination - Variable name [[a&]] contains invalid character(s)              | 1.Destination - Variable name [[a&]] contains invalid character(s)              |                      |                           |
		| 51 | [[sourcePath]]                 |                   |                 | c:\copyfile42.txt      | ""                    | ""       | [[rec(**).a]]                  | C:\moved0.txt        | ""           | ""           | True     | [[result]] | ""      | AN           | True             | Destination - Recordset index (**) contains invalid character(s)              | 1.Destination - Recordset index (**) contains invalid character(s)              |                      |                           |
		| 52 | [[sourcePath]]                 |                   |                 | c:\copyfile43.txt      | ""                    | ""       | [[a]                           | C:\moved0.txt        | ""           | ""           | True     | [[result]] | ""      | AN           | True             | Destination - Invalid expression: opening and closing brackets don"t match    | 1.Destination - Invalid expression: opening and closing brackets don"t match    |                      |                           |
		| 53 | [[sourcePath]]                 |                   |                 | c:\copyfile44.txt      | ""                    | ""       | [[rec(a]]                      | C:\moved0.txt        | ""           | ""           | True     | [[result]] | ""      | AN           | True             | Destination - Recordset name [[rec(a]] contains invalid character(s)          | 1.Destination - Recordset name [[rec(a]] contains invalid character(s)          |                      |                           |
		| 54 | [[sourcePath]]                 |                   |                 | c:\copyfile45.txt      | ""                    | ""       | c(*()                          | C:\moved0.txt        | ""           | ""           | True     | [[result]] | ""      | AN           | True             | Please supply a valid File or Folder                                          | 1.Please supply a valid File or Folder                                          |                      |                           |
		| 55 | [[sourcePath]]                 |                   |                 | c:\copyfile46.txt      | ""                    | ""       | [[rec([[inde$x]]).a]]          | C:\moved0.txt        | ""           | ""           | True     | [[result]] | ""      | AN           | True             | Destination - Variable name [[inde$x]]  contains invalid character(s)         | 1.Destination - Variable name [[inde$x]]  contains invalid character(s)         |                      |                           |
		| 56 | [[sourcePath]]                 |                   |                 | c:\copyfile47.txt      | ""                    | ""       | ghjghj                         | C:\moved0.txt        | ""           | ""           | True     | [[result]] | ""      | AN           | True             | Please supply a valid File or Folder                                          | 1.Please supply a valid File or Folder                                          |                      |                           |
		| 57 | [[sourcePath]]                 |                   |                 | c:\copyfile48.txt      | ""                    | ""       | ""                             | C:\moved0.txt        | ""           | ""           | True     | [[result]] | ""      | AN           | True             | Destination cannot be empty or only white space                               | 1.Destination cannot be empty or only white space                               |                      |                           |
		| 58 | [[sourcePath]]                 |                   |                 | c:\copyfile49.txt      | [[a&]]                | String   | [[destPath]]                   | C:\moved0.txt        | ""           | ""           | True     | [[result]] | ""      | AN           | True             | Username - Variable name [[a&]] contains invalid character(s)                 | 1.Username - Variable name [[a&]] contains invalid character(s)                 |                      |                           |
		| 59 | [[sourcePath]]                 |                   |                 | c:\copyfile50.txt      | [[rec(**).a]]         | String   | [[destPath]]                   | C:\moved0.txt        | ""           | ""           | True     | [[result]] | ""      | AN           | True             | Username - Recordset index (**) contains invalid character(s)                 | 1.Username - Recordset index (**) contains invalid character(s)                 |                      |                           |
		| 60 | [[sourcePath]]                 |                   |                 | c:\copyfile51.txt      | [[a]                  | String   | [[destPath]]                   | C:\moved0.txt        | ""           | ""           | True     | [[result]] | ""      | AN           | True             | Username - Invalid expression: opening and closing brackets don"t match       | 1.Username - Invalid expression: opening and closing brackets don"t match       |                      |                           |
		| 61 | [[sourcePath]]                 |                   |                 | c:\copyfile52.txt      | [[rec(a]]             | String   | [[destPath]]                   | C:\moved0.txt        | ""           | ""           | True     | [[result]] | ""      | AN           | True             | Username - Recordset name [[rec(a]] contains invalid character(s)             | 1.Username - Recordset name [[rec(a]] contains invalid character(s)             |                      |                           |
		| 62 | [[sourcePath]]                 |                   |                 | c:\copyfile53.txt      | [[rec([[inde$x]]).a]] | String   | [[destPath]]                   | C:\moved0.txt        | ""           | ""           | True     | [[result]] | ""      | AN           | True             | Username - Variable name [[inde$x]]  contains invalid character(s)            | 1.Username - Variable name [[inde$x]]  contains invalid character(s)            |                      |                           |
		| 64 | [[sourcePath]]                 |                   |                 | c:\copyfile55.txt      | [[a&]]                | String   | [[destPath]]                   | C:\moved0.txt        | ""           | ""           | True     | [[result]] | ""      | AN           | True             | Username - Variable name [[a&]] contains invalid character(s)                 | 1.Destination Username - Variable name [[a&]] contains invalid character(s)     |                      |                           |
		| 65 | [[sourcePath]]                 |                   |                 | c:\copyfile56.txt      | [[rec(**).a]]         | String   | [[destPath]]                   | C:\moved0.txt        | ""           | ""           | True     | [[result]] | ""      | AN           | True             | Username - Recordset index (**) contains invalid character(s)                 | 1.Destination Username - Recordset index (**) contains invalid character(s)     |                      |                           |
