trigger: none

pool:
  vmImage: 'windows-2022'

jobs:

- job: build
  displayName: 'Analyse'

  steps:
  - task: PowerShell@2
    inputs:
      filePath: '$(Agent.BuildDirectory)\s\Compile.ps1'
      arguments: '-AcceptanceTesting -MSBuildPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe"'
      
  - script: |
      dotnet tool install --global ApiPort
      ApiPort analyze -r HTML --force -f "$(Agent.BuildDirectory)\s\bin\AcceptanceTesting" -t .NET
      
  - task: PublishHtmlReport@1
    displayName: 'Publish HTML Report'
    inputs:
      htmlPath: '$(Agent.BuildDirectory)\s\ApiPortAnalysis.html'
