schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - "*"

pool:
  vmImage: 'windows-2022'

jobs:

- job: build
  displayName: 'Analyse'

  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      source: 'specific'
      project: '$(System.TeamProjectId)'
      pipeline: 10
      runVersion: 'specific'
      runId: 2452
      allowPartiallySucceededBuilds: true
        
  - powershell: |
        New-Item -ItemType Directory "$(Agent.BuildDirectory)\s\bin\ServerTests"
        expand "$(Agent.BuildDirectory)\WebView2\Microsoft.WebView2.FixedVersionRuntime.cab" -F:* "$(Agent.BuildDirectory)\s\bin\ServerTests"
    displayName: 'Expand WebView2 Cab'

  - task: PowerShell@2
    inputs:
      filePath: '$(Agent.BuildDirectory)\s\Compile.ps1'
      arguments: '-ServerTest -MSBuildPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe"'
      
  - script: |
      dotnet tool install --global ApiPort
      ApiPort analyze -r HTML --force -f "$(Agent.BuildDirectory)\s\bin\ServerTests" -t ".NET, Version=6.0"
      
  - task: PublishHtmlReport@1
    displayName: 'Publish HTML Report'
    inputs:
      htmlPath: '$(Agent.BuildDirectory)\s\ApiPortAnalysis.html'
