schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - "*"

pool:
  vmImage: 'windows-2022'

jobs:

- job: build
  displayName: 'Analyse'

  steps:
  - task: PowerShell@2
    inputs:
      filePath: '$(Agent.BuildDirectory)\s\Compile.ps1'
      arguments: '-AcceptanceTesting -MSBuildPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe"'
      
  - script: |
      curl https://objects.githubusercontent.com/github-production-release-asset-2e65be/27931923/46907ba6-3742-4f34-b187-2e9a99d3d3e5?X-Amz-Algorithm=AWS4-HMAC-SHA256^&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20220315%2Fus-east-1%2Fs3%2Faws4_request^&X-Amz-Date=20220315T031227Z^&X-Amz-Expires=300^&X-Amz-Signature=8ee80dc60cbfdfd1e5809d82325a04597eee361cab8e71aaabe1d1f7da72181f^&X-Amz-SignedHeaders=host^&actor_id=0^&key_id=0^&repo_id=27931923^&response-content-disposition=attachment%3B%20filename%3DApiPort.2.8.25.Offline.zip^&response-content-type=application%2Foctet-stream --output ApiPort.2.8.25.Offline.zip
      tar -xf .\ApiPort.2.8.25.Offline.zip
      ".\ApiPort.Offline\netcoreapp3.1\ApiPort.exe" analyze -r HTML --force -f "$(Agent.BuildDirectory)\s\bin\AcceptanceTesting" -t .NET
      'C:\Program Files\ApiPort\ApiPort.exe' analyze -f '$(Agent.BuildDirectory)\s\bin\AcceptanceTesting' -r HTML --force -t .NET
      
  - task: PublishHtmlReport@1
    displayName: 'Publish HTML Report'
    inputs:
      reportDir: '$(Agent.BuildDirectory)\s\ApiPortAnalysis.html'
