# This is a TEMPLATE where:
# [[PROJECTNAME EG: Dev2.Integration.Tests]] and
# [[TESTNAME EG: "Load Test","Server Startup Test" or AnonymousRedisTest]] need to be replaced and
# This file copied over "pipeline.yml"
# For running a test category or categories replace -TestsToRun with -Category or -Categories
# NOTE: Use -Category for a single category and -Categories for multiple categories.
###################################################################################################
# Case 1:
# Example of single project and multiple tests (Project: Dev2.Activities.Tests)
# Script: powershell -NoProfile -NoLogo -ExecutionPolicy Bypass -NoExit -File "$(Agent.BuildDirectory)\TestRun.ps1" -RetryCount 6 -Projects "Dev2.Activities.Tests" -TestsToRun "DsfCommentActivity_GetState_ReturnsStateVariable","CommentGetDebugInputOutputWithText" -PreTestRunScript "StartAsService.ps1 -Cleanup -ResourcesPath ServerTests" -PostTestRunScript ReverseDeployLog.ps1
###################################################################################################
# Case 2:
# Example of Multiple Projects and multiple tests (Projects:  Dev2.Activities.Tests, Dev2.Common.Tests)
# Script: powershell -NoProfile -NoLogo -ExecutionPolicy Bypass -NoExit -File "$(Agent.BuildDirectory)\TestRun.ps1" -RetryCount 6 -Projects "Dev2.Activities.Tests","Dev2.Common.Tests" -TestsToRun "ComputerName_ToString_SetProperty_Expect_SetName","Search_Ctor","DsfCommentActivity_GetState_ReturnsStateVariable","CommentGetDebugInputOutputWithText" -PreTestRunScript "StartAsService.ps1 -Cleanup -ResourcesPath ServerTests" -PostTestRunScript ReverseDeployLog.ps1
###################################################################################################
# Case 3:
# Single project and single test category (Projects: "Dev2.Activities.Tests","Warewolf.Auditing.Tests")
# Script: powershell -NoProfile -NoLogo -ExecutionPolicy Bypass -NoExit -File "$(Agent.BuildDirectory)\TestRun.ps1" -RetryCount 6 -Projects Dev2.Activities.Tests -Category AuditQueryableElasticTests,DsfCommentActivity_UpdateForEachInputs,DsfCommentActivity_UpdateForEachOutputs -PreTestRunScript "StartAsService.ps1 -Cleanup -ResourcesPath ServerTests" -PostTestRunScript ReverseDeployLog.ps1
###################################################################################################
# Case 4:
# Multiple projects and multiple tests categories (Projects: "Dev2.Activities.Tests","Warewolf.Auditing.Tests")
# Script: powershell -NoProfile -NoLogo -ExecutionPolicy Bypass -NoExit -File "$(Agent.BuildDirectory)\TestRun.ps1" -RetryCount 6 -Projects Dev2.Activities.Tests,Warewolf.Auditing.Tests -Categories AuditQueryableElasticTests,DsfCommentActivity_UpdateForEachInputs,DsfCommentActivity_UpdateForEachOutputs -PreTestRunScript "StartAsService.ps1 -Cleanup -ResourcesPath ServerTests" -PostTestRunScript ReverseDeployLog.ps1
trigger:
  batch: true

pool:
  vmImage: 'windows-2022'

stages:
- stage: Compile
  jobs:
  
  - job: build
    displayName: 'Compile'
  
    steps:
    - task: PowerShell@2
      inputs:
        filePath: '$(Agent.BuildDirectory)/s/Compile.ps1'
        arguments: '-ServerTests -StudioProject -MSBuildPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe"'
        displayName: 'Compile'

    - powershell: |
        @"
        <?xml version="1.0" encoding="utf-8"?>
        <subscriptionSettings>
          <add key="CustomerId" value="$env:ChargeBeeCustomerIdValue" />
          <add key="SubscriptionId" value="$env:ChargeBeeSubscriptionIdValue" />
          <add key="Status" value="Active" />
          <add key="PlanId" value="developer" />
          <add key="SubscriptionKey" value="$env:ChargeBeeSubscriptionKeyValue" />
          <add key="SubscriptionSiteName" value="warewolf-test" />
          <add key="StopExecutions" value="false" />
        </subscriptionSettings>
        "@ | Out-File -LiteralPath "$(Agent.BuildDirectory)\s\bin\ServerTests\Warewolf License.secureconfig" -Encoding utf8 -Force
      displayName: 'Programmatically License The Server Under Test'
      env:
        ChargeBeeCustomerIdValue: $(ChargeBeeCustomerId)
        ChargeBeeSubscriptionIdValue: $(ChargeBeeSubscriptionId)
        ChargeBeeSubscriptionKeyValue: $(ChargeBeeSubscriptionKey)
  
    - task: DeleteFiles@1
      inputs:
        SourceFolder: '$(Agent.BuildDirectory)\s\bin\ServerTests'
        Contents: 'TestResults'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Agent.BuildDirectory)\s\bin\ServerTests'
        ArtifactName: 'ServerBinaries'
        publishLocation: 'Container'
        StoreAsTar: false

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Agent.BuildDirectory)\s\bin\StudioProject'
        ArtifactName: 'StudioBinaries'
        publishLocation: 'Container'
        StoreAsTar: false
        
- stage: Test
  jobs:
  
  - job: Database_Workflow_Execution_Specs
    displayName: 'Database Workflow Execution Specs'
  
    steps:
    - checkout: none
    
    - task: Docker@2
      displayName: Run MySQL container
      inputs:
        command: run
        imageName: registry.gitlab.com/warewolf/mysql-connector-testing
        containerName: mysql-connector-testing
        options: '-e MYSQL_ROOT_PASSWORD=admin -p 3306:3306 -d'
    
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'ServerBinaries'
        targetPath: '$(Agent.BuildDirectory)'
  
    - script: |
        IF NOT EXIST C:\Builds\PGDATA mkdir C:\Builds\PGDATA
        git clone https://ashley.lewis%40theunlimited.co.za:%TestDependencyPassword%@gitlab.com/warewolf/postgres-connector-testing.git
        copy /Y "postgres-connector-testing\pg_hba.conf" "%PGDATA%\pg_hba.conf"
        copy /Y "postgres-connector-testing\postgres.conf" "%PGDATA%\postgresql.conf"
        sc config postgresql-x64-14 start= auto
        sc start postgresql-x64-14
        ping -n 10 127.0.0.1 > nul
        type postgres-connector-testing\postgres.backup | "%PGBIN%\psql" --username postgres postgres
        "%PGBIN%\createdb" TestDB
        type postgres-connector-testing\testdb.backup | "%PGBIN%\psql" --username postgres TestDB
        docker exec -i mysql-connector-testing sh -c 'exec mysql -uroot -p"$MYSQL_ROOT_PASSWORD" < "./mysqldump.sql"'
        cd /d "$(Agent.BuildDirectory)"
        powershell -NoProfile -NoLogo -ExecutionPolicy Bypass -NoExit -File "$(Agent.BuildDirectory)\TestRun.ps1" -RetryCount 6 -Projects Dev2.Activities.Specs -Category DatabaseWorkflowExecution -PreTestRunScript "StartAsService.ps1 -Cleanup -DoExit -ResourcesPath ServerTests" -PostTestRunScript ReverseDeployLog.ps1
      displayName: 'Run Tests'
      env:
        TestDependencyPassword: $(VSTestContainerPassword)

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Agent.BuildDirectory)\TestResults\warewolf-server.log'
        ArtifactName: 'Database_Workflow_Execution_Specs_Server_Log_File'
        publishLocation: 'Container'
        StoreAsTar: false
        
    - task: PublishTestResults@2
      inputs:
        testRunner: VSTest
        testResultsFiles: '$(Agent.BuildDirectory)\TestResults\*.trx'
        failTaskOnFailedTests: true
        testRunTitle: 'Database Workflow Execution Specs'
        
    - script: 'if not exist "$(Agent.BuildDirectory)\TestResults\*.trx" exit 1'