trigger:
  batch: true

pool:
  vmImage: 'windows-2022'

stages:
- stage: Compile
  jobs:
  
  - job: build
    displayName: 'Compile'
  
    steps:
    
    - script: |
        sqllocaldb start MSSQLLocalDB$instanceInfo = sqllocaldb info MSSQLLocalDB
        Write-Output "LocalDB Instance Info:`n$instanceInfo"
      displayName: 'Try start local sql server'