trigger:
  batch: true

pool:
  vmImage: 'windows-2022'

stages:
- stage: Compile
  jobs:
  
  - job: build
    displayName: 'Compile'
  
    steps:
    
    - script: |
        sqllocaldb start MSSQLLocalDB
        IF NOT EXIST C:\Builds mkdir C:\Builds
        git clone https://ashley.lewis%40theunlimited.co.za:%TestDependencyPassword%@gitlab.com/warewolf/mssql-connector-testing.git
      displayName: 'Install LocalDB'
      env:
        TestDependencyPassword: $(VSTestContainerPassword)
    
    - powershell: |        
        $serverInstance = "(localdb)\MSSQLLocalDB"
        Invoke-Sqlcmd -ServerInstance $serverInstance -Query "CREATE LOGIN [testuser] WITH PASSWORD = 'test123', CHECK_POLICY = OFF"
        Invoke-Sqlcmd -ServerInstance $serverInstance -Query "EXEC SP_ADDSRVROLEMEMBER 'testuser','SYSADMIN'"
        $backupPath = "$(Agent.BuildDirectory)\s\mssql-connector-testing\dev2testingdb.bak"
        $mdfPath = "C:\Builds\Dev2TestingDB.mdf"
        $ldfPath = "C:\Builds\Dev2TestingDB.ldf"        
        Invoke-Sqlcmd -ServerInstance $serverInstance -Query "RESTORE DATABASE [Dev2TestingDB] FROM DISK='$backupPath' WITH MOVE 'Dev2TestingDB' TO '$mdfPath', MOVE 'Dev2TestingDB_log' TO '$ldfPath'"
        Invoke-Sqlcmd -ServerInstance $serverInstance -Query "USE Dev2TestingDB; EXEC sp_change_users_login 'AUTO_FIX', 'testuser'"
      displayName: 'SQL Server Dependency'