@fileFeature
Feature: Rename
	In order to be able to Rename File or Folder 
	as a Warewolf user
	I want a tool that will rename a File or Floder at a given location


Scenario Outline: Rename file at location
	Given I have a source path '<source>' with value '<sourceLocation>' 
	And source credentials as '<username>' and '<password>'
	And I have a destination path '<destination>' with value '<destinationLocation>'
    And destination credentials as '<destUsername>' and '<destPassword>'
	And overwrite is '<selected>'
	And result as '<resultVar>'
    When the rename file tool is executed
	Then the result variable '<resultVar>' will be '<result>'
	And the execution has "<errorOccured>" error
	And the debug inputs as
         | Source Path                 | Username   | Password | Destination Path                      | Destination Username | Destination Password | Overwrite  |
         | <source> = <sourceLocation> | <username> | String   | <destination> = <destinationLocation> | <destUsername>       | String               | <selected> |
	And the debug output as
		|                        |
		| <resultVar> = <result> |
	Examples: 
	| No | Name           | source         | sourceLocation                                                 | username          | password | destination  | destinationLocation                                         | destUsername      | destPassword | selected | resultVar              | result  | errorOccured |
	| 1  | Local to Local | [[sourcePath]] | c:\renamefile0.txt                                             | ""                | ""       | [[destPath]] | C:\renamed0.txt                                             | ""                | ""           | True     | [[result]]             | Success | NO           |
	| 2  | Local to FTP   | [[sourcePath]] | c:\renamefile1.txt                                             | ""                | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/renamed0.txt          | ""                | ""           | True     | [[result]]             | Success | NO           |
	| 3  | Local to FTPS  | [[sourcePath]] | c:\renamefile2.txt                                             | ""                | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed0.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           |
	| 4  | Local to SFTP  | [[sourcePath]] | c:\renamefile3.txt                                             | ""                | ""       | [[destPath]] | sftp://localhost/renamed0.txt                               | dev2              | Q/ulw&]      | True     | [[result]]             | Success | NO           |
	| 5  | Local to UNC   | [[sourcePath]] | c:\renamefile4.txt                                             | ""                | ""       | [[destPath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\renamed0.txt | ""                | ""           | True     | [[result]]             | Success | NO           |
	| 6  | UNC to Local   | [[sourcePath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\renamefile0.txt | ""                | ""       | [[destPath]] | C:\renamed1.txt                                             | ""                | ""           | True     | [[result]]             | Success | NO           |
	| 7  | UNC to FTP     | [[sourcePath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\renamefile1.txt | ""                | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/renamed1.txt          | ""                | ""           | True     | [[result]]             | Success | NO           |
	| 8  | UNC to FTPS    | [[sourcePath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\renamefile2.txt | ""                | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed1.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           |
	| 9  | UNC to SFTP    | [[sourcePath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\renamefile3.txt | ""                | ""       | [[destPath]] | sftp://localhost/renamed1.txt                               | dev2              | Q/ulw&]      | True     | [[result]]             | Success | NO           |
	| 10 | UNC to UNC     | [[sourcePath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\renamefile4.txt | ""                | ""       | [[destPath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\renamed1.txt | ""                | ""           | True     | [[result]]             | Success | NO           |
	| 11 | FTP to Local   | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/renamefile0.txt          | ""                | ""       | [[destPath]] | C:\renamed2.txt                                             | ""                | ""           | True     | [[result]]             | Success | NO           |
	| 12 | FTP to UNC     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/renamefile1.txt          | ""                | ""       | [[destPath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\renamed2.txt | ""                | ""           | True     | [[result]]             | Success | NO           |
	| 13 | FTP to FTPS    | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/renamefile2.txt          | ""                | ""       | [[destPath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed2.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           |
	| 14 | FTP to SFTP    | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/renamefile3.txt          | ""                | ""       | [[destPath]] | sftp://localhost/renamed2.txt                               | dev2              | Q/ulw&]      | True     | [[result]]             | Success | NO           |
	| 15 | FTP to FTP     | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/renamefile4.txt          | ""                |          | [[destPath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/renamed2.txt          | ""                | ""           | True     | [[result]]             | Success | NO           |
	| 16 | FTPS to Local  | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamefile0.txt          | integrationtester | I73573r0 | [[destPath]] | C:\renamed3.txt                                             | ""                | ""           | True     | [[result]]             | Success | NO           |
	| 17 | FTPS to UNC    | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamefile1.txt          | integrationtester | I73573r0 | [[destPath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\renamed3.txt | ""                | ""           | True     | [[result]]             | Success | NO           |
	| 18 | FTPS to FTPS   | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamefile2.txt          | integrationtester | I73573r0 | [[destPath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed3.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           |
	| 19 | FTPS to SFTP   | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamefile3.txt          | integrationtester | I73573r0 | [[destPath]] | sftp://localhost/renamed3.txt                               | dev2              | Q/ulw&]      | True     | [[result]]             | Success | NO           |
	| 20 | FTPS to FTP    | [[sourcePath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamefile4.txt          | integrationtester | I73573r0 | [[destPath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/renamed3.txt          | ""                | ""           | True     | [[result]]             | Success | NO           |
	| 21 | SFTP to Local  | [[sourcePath]] | sftp://localhost/renamefile0.txt                               | dev2              | Q/ulw&]  | [[destPath]] | C:\renamed4.txt                                             | ""                | ""           | True     | [[result]]             | Success | NO           |
	| 22 | SFTP to UNC    | [[sourcePath]] | sftp://localhost/renamefile1.txt                               | dev2              | Q/ulw&]  | [[destPath]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\renamed4.txt | ""                | ""           | True     | [[result]]             | Success | NO           |
	| 23 | SFTP to FTP    | [[sourcePath]] | sftp://localhost/renamefile2.txt                               | dev2              | Q/ulw&]  | [[destPath]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/renamed4.txt          | ""                | ""           | True     | [[result]]             | Success | NO           |
	| 24 | SFTP to FTPS   | [[sourcePath]] | sftp://localhost/renamefile3.txt                               | dev2              | Q/ulw&]  | [[destPath]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed4.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           |
	| 25 | SFTP to SFTP   | [[sourcePath]] | sftp://localhost/renamefile4.txt                               | dev2              | Q/ulw&]  | [[destPath]] | sftp://localhost/renamed4.txt                               | dev2              | Q/ulw&]      | True     | [[result]]             | Success | NO           |



Scenario Outline: Rename file at location1
	Given I have a source path '<File or Folder>' with value '<sourceLocation>' 
	And source credentials as '<username>' and '<password>'
	And I have a destination path '<destination>' with value '<destinationLocation>'
    And destination credentials as '<destUsername>' and '<destPassword>'
	And overwrite is '<selected>'
	And result as '<resultVar>'
	When validating the tool
	Then validation is '<ValidationResult>'
	And validation message is '<DesignValidation>'
    When the rename file tool is executed
	Then the result variable '<resultVar>' will be '<result>'
	And the execution has "<errorOccured>" error
	And execution error message will be '<DesignValidation>'
	And the debug inputs as
        | Source Path                         | Username   | Password | Destination Path                      | Destination Username | Destination Password | Overwrite  |
        | <File or FOlder> = <sourceLocation> | <username> | String   | <destination> = <destinationLocation> | <destUsername>       | String               | <selected> |
	And the debug output as
		|                        |
		| <resultVar> = <result> |
	Examples: 
		| No | File or Folder                  | sourceLocation      | username              | password | destination                     | destinationLocation                                          | destUsername      | destPassword | selected | resultVar              | result  | errorOccured | ValidationResult | DesignValidation                                                              | OutputError                                                                           |
		| No | [[sourcePath]]                  | c:\renamefile5.txt  | ""                    | ""       | [[destPath]]                    | C:\renamed6.txt                                              | dev2              | Q/ulw&]      | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 4  | [[sourcePath]]                  | c:\renamefile6.txt  | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1001/FORTESTING/renamed7.txt           | ""                | ""           | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 5  | [[sourcePath]]                  | c:\renamefile7.txt  | ""                    | ""       | [[destPath]]                    | C:\renamed6.txt                                              | ""                | ""           | Truee    | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 1  | [[sourcePath]]                  | c:\renamefile8.txt  | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1001/FORTESTING/renamed8.txt           | ""                | ""           | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 2  | [[sourcePath]]                  | c:\renamefile9.txt  | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed9.txt           | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 3  | [[sourcePath]]                  | c:\renamefile10.txt | ""                    | ""       | [[destPath]]                    | C:\renamed6.txt                                              | ""                | ""           | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 6  | [[sourcePath]]                  | c:\renamefile11.txt | ""                    | ""       | [[destPath]]                    | C:\renamed6.txt                                              | ""                | ""           | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 7  | [[sourcePath]]                  | c:\renamefile12.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1001/FORTESTING/renamed10.txt          | ""                | ""           | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 8  | [[sourcePath]]                  | c:\renamefile13.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed11.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 9  | [[sourcePath]]                  | c:\renamefile14.txt | ""                    | ""       | [[destPath]]                    | sftp://localhost/renamed12.txt                               | dev2              | Q/ulw&]      | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 10 | [[sourcePath]]                  | c:\renamefile15.txt | ""                    | ""       | [[destPath]]                    | C:\renamed8.txt                                              | ""                | ""           | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 11 | [[sourcePath]]                  | c:\renamefile16.txt | ""                    | ""       | [[destPath]]                    | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\renamed13.txt | ""                | ""           | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 12 | [[sourcePath]]                  | c:\renamefile17.txt | ""                    | ""       | [[destPath]]                    | C:\renamed9.txt                                              | ""                | ""           | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 13 | [[sourcePath]]                  | c:\renamefile18.txt | ""                    | ""       | [[destPath]]                    | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\renamed14.txt | ""                | ""           | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 14 | [[sourcePath]]                  | c:\renamefile19.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed11.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 15 | [[a]][[b]]                      | c:\renamefile20.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed12.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 16 | [[a]]\[[b]]                     | c:\renamefile21.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed13.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 17 | [[a]][[b]].txt                  | c:\renamefile22.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed14.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 18 | [[a]]:[[b]]                     | c:\renamefile23.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed15.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 19 | C:[[a]][[b]].txt                | c:\renamefile24.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed16.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 20 | [[rec(1).a]][[rec(2).a]]        | c:\renamefile25.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed17.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 21 | [[rec(1).a]]\[[rec(2).a]]       | c:\renamefile26.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed18.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 22 | [[rec(1).a]][[rec(2).a]] .txt   | c:\renamefile27.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed19.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 23 | [[rec(1).a]]:[[rec(2).a]]       | c:\renamefile28.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed20.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 24 | C:[[rec(1).a]][[rec(2).a]] .txt | c:\renamefile29.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed21.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 25 | c:\copyfile0.txt                | c:\renamefile30.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed22.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 26 | [[rec([[index]]).a]]            | c:\renamefile31.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed23.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 27 | c:\copyfile0.txt                | c:\renamefile32.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed24.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 28 | [[sourcePath]]                  | c:\renamefile33.txt | ""                    | ""       | [[a]][[b]]                      | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed25.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 29 | [[sourcePath]]                  | c:\renamefile34.txt | ""                    | ""       | [[a]]\[[b]]                     | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed26.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 30 | [[sourcePath]]                  | c:\renamefile35.txt | ""                    | ""       | [[a]][[b]].txt                  | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed27.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 31 | [[sourcePath]]                  | c:\renamefile36.txt | ""                    | ""       | [[a]]:[[b]]                     | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed28.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 32 | [[sourcePath]]                  | c:\renamefile37.txt | ""                    | ""       | C:[[a]][[b]].txt                | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed29.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 33 | [[sourcePath]]                  | c:\renamefile38.txt | ""                    | ""       | [[rec(1).a]][[rec(2).a]]        | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed30.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 34 | [[sourcePath]]                  | c:\renamefile39.txt | ""                    | ""       | [[rec(1).a]]\[[rec(2).a]]       | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed31.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
		| 35 | [[sourcePath]]                  | c:\renamefile40.txt | ""                    | ""       | [[rec(1).a]][[rec(2).a]] .txt   | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed32.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 36 | [[sourcePath]]                  | c:\renamefile41.txt | ""                    | ""       | [[rec(1).a]]:[[rec(2).a]]       | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed33.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 37 | [[sourcePath]]                  | c:\renamefile42.txt | ""                    | ""       | C:[[rec(1).a]][[rec(2).a]] .txt | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed34.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 38 | [[sourcePath]]                  | c:\renamefile43.txt | ""                    | ""       | c:\copyfile0.txt                | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed35.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 39 | [[sourcePath]]                  | c:\renamefile44.txt | ""                    | ""       | [[rec([[index]]).a]]            | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed36.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 40 | [[sourcePath]]                  | c:\renamefile45.txt | ""                    | ""       | c:\copyfile0.txt                | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed37.txt          | integrationtester | I73573r0     | True     | [[result]]             | Success | NO           | False            | ""                                                                            | ""                                                                                    |
#		| 41 | [[a&]]                          |                     | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed38.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | File or Folder - Variable name [[a&]] contains invalid character(s)           | 1.File or Folder - Variable name [[a&]] contains invalid character(s)                 |
#		| 42 | [[rec(**).a]]                   |                     | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed39.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | File or Folder - Recordset index (**) contains invalid character(s)           | 1.File or Folder - Recordset index (**) contains invalid character(s)                 |
#		| 43 | [[a]                            |                     | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed40.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | File or Folder - Invalid expression: opening and closing brackets don't match | 1.File or Folder - Invalid expression: opening and closing brackets don't match       |
#		| 44 | [[rec(a]]                       |                     | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed41.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | File or Folder - Recordset name [[rec(a]] contains invalid character(s)       | 1.File or Folder - Recordset name [[rec(a]] contains invalid character(s)             |
#		| 45 | c(*()                           |                     | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed42.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Please supply a valid File or Folder                                          | 1.Please supply a valid File or Folder                                                |
#		| 46 | [[rec([[inde$x]]).a]]           |                     | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed43.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | File or Folder - Variable name [[inde$x]]  contains invalid character(s)      | 1.File or Folder - Variable name [[inde$x]]  contains invalid character(s)            |
#		| 47 | ghjghj                          |                     | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed44.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Please supply a valid File or Folder                                          | 1.Please supply a valid File or Folder                                                |
#		| 48 | ""                              |                     | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed45.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | File or Folder cannot be empty or only white space                            | 1.File or Folder cannot be empty or only white space                                  |
#		| 49 | [[sourcePath]]                  | c:\renamefile46.txt | ""                    | ""       | [[a&]]                          | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed46.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Destination - Variable name [[a&]] contains invalid character(s)              | 1.Destination - Variable name [[a&]] contains invalid character(s)                    |
#		| 50 | [[sourcePath]]                  | c:\renamefile47.txt | ""                    | ""       | [[rec(**).a]]                   | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed47.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Destination - Recordset index (**) contains invalid character(s)              | 1.Destination - Recordset index (**) contains invalid character(s)                    |
#		| 51 | [[sourcePath]]                  | c:\renamefile48.txt | ""                    | ""       | [[a]                            | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed48.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Destination - Invalid expression: opening and closing brackets don't match    | 1.Destination - Invalid expression: opening and closing brackets don't match          |
#		| 52 | [[sourcePath]]                  | c:\renamefile49.txt | ""                    | ""       | [[rec(a]]                       | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed49.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Destination - Recordset name [[rec(a]] contains invalid character(s)          | 1.Destination - Recordset name [[rec(a]] contains invalid character(s)                |
#		| 53 | [[sourcePath]]                  | c:\renamefile50.txt | ""                    | ""       | c(*()                           | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed50.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Please supply a valid File or Folder                                          | 1.Please supply a valid File or Folder                                                |
#		| 54 | [[sourcePath]]                  | c:\renamefile51.txt | ""                    | ""       | [[rec([[inde$x]]).a]]           | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed51.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Destination - Variable name [[inde$x]]  contains invalid character(s)         | 1.Destination - Variable name [[inde$x]]  contains invalid character(s)               |
#		| 55 | [[sourcePath]]                  | c:\renamefile52.txt | ""                    | ""       | ghjghj                          | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed52.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Please supply a valid File or Folder                                          | 1.Please supply a valid File or Folder                                                |
#		| 56 | [[sourcePath]]                  | c:\renamefile53.txt | ""                    | ""       | ""                              | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed53.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Destination cannot be empty or only white space                               | 1.Destination cannot be empty or only white space                                     |
#		| 57 | [[sourcePath]]                  | c:\renamefile54.txt | [[a&]]                | String   | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed54.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Username - Variable name [[a&]] contains invalid character(s)                 | 1.Username - Variable name [[a&]] contains invalid character(s)                       |
#		| 58 | [[sourcePath]]                  | c:\renamefile55.txt | [[rec(**).a]]         | String   | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed55.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Username - Recordset index (**) contains invalid character(s)                 | 1.Username - Recordset index (**) contains invalid character(s)                       |
#		| 59 | [[sourcePath]]                  | c:\renamefile56.txt | [[a]                  | String   | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed56.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Username - Invalid expression: opening and closing brackets don't match       | 1.Username - Invalid expression: opening and closing brackets don't match             |
#		| 60 | [[sourcePath]]                  | c:\renamefile57.txt | [[rec(a]]             | String   | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed57.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Username - Recordset name [[rec(a]] contains invalid character(s)             | 1.Username - Recordset name [[rec(a]] contains invalid character(s)                   |
#		| 61 | [[sourcePath]]                  | c:\renamefile58.txt | [[rec([[inde$x]]).a]] | String   | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed58.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Username - Variable name [[inde$x]]  contains invalid character(s)            | 1.Username - Variable name [[inde$x]]  contains invalid character(s)                  |
#		| 62 | [[sourcePath]]                  | c:\renamefile59.txt |                       | String   | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed59.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Username cannot be empty or only white space                                  | 1.Username cannot be empty or only white space                                        |
#		| 63 | [[sourcePath]]                  | c:\renamefile50.txt | [[a&]]                | String   | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed60.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Username - Variable name [[a&]] contains invalid character(s)                 | 1.Destination Username - Variable name [[a&]] contains invalid character(s)           |
#		| 64 | [[sourcePath]]                  | c:\renamefile61.txt | [[rec(**).a]]         | String   | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed61.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Username - Recordset index (**) contains invalid character(s)                 | 1.Destination Username - Recordset index (**) contains invalid character(s)           |
#		| 65 | [[sourcePath]]                  | c:\renamefile62.txt | [[a]                  | String   | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed62.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Username - Invalid expression: opening and closing brackets don't match       | 1.Destination Username - Invalid expression: opening and closing brackets don't match |
#		| 66 | [[sourcePath]]                  | c:\renamefile63.txt | [[rec(a]]             | String   | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed63.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Username - Recordset name [[rec(a]] contains invalid character(s)             | 1.Destination Username - Recordset name [[rec(a]] contains invalid character(s)       |
#		| 67 | [[sourcePath]]                  | c:\renamefile64.txt | [[rec([[inde$x]]).a]] | String   | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed64.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Username - Variable name [[inde$x]]  contains invalid character(s)            | 1.Destination Username - Variable name [[inde$x]]  contains invalid character(s)      |
#		| 68 | [[sourcePath]]                  | c:\renamefile65.txt | ""                    | String   | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed65.txt          | integrationtester | I73573r0     | True     | [[result]]             | ""      | AN           | True             | Username cannot be empty or only white space                                  | 1.Destination Username cannot be empty or only white space                            |
#		| 69 | [[sourcePath]]                  | c:\renamefile66.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed66.txt          | integrationtester | I73573r0     | True     | [[result]][[a]]        | ""      | AN           | True             | The result field only allows a single result                                  | 1.The result field only allows a single result                                        |
#		| 70 | [[sourcePath]]                  | c:\renamefile67.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed67.txt          | integrationtester | I73573r0     | True     | [[a]]*]]               | ""      | AN           | True             | Result - Invalid expression: opening and closing brackets don't match         | 1.Result - Invalid expression: opening and closing brackets don't match               |
#		| 71 | [[sourcePath]]                  | c:\renamefile68.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed68.txt          | integrationtester | I73573r0     | True     | [[var@]]               | ""      | AN           | True             | Result - Variable name [[var@]] contains invalid character(s)                 | 1.Result - Variable name [[var@]] contains invalid character(s)                       |
#		| 72 | [[sourcePath]]                  | c:\renamefile69.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed69.txt          | integrationtester | I73573r0     | True     | [[var]]00]]            | ""      | AN           | True             | Result - Invalid expression: opening and closing brackets don't match         | 1.Result - Invalid expression: opening and closing brackets don't match               |
#		| 73 | [[sourcePath]]                  | c:\renamefile70.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed70.txt          | integrationtester | I73573r0     | True     | [[(1var)]]             | ""      | AN           | True             | Result - Variable name [[1var]] contains invalid character(s)                 | 1.Result - Variable name [[1var]] contains invalid character(s)                       |
#		| 74 | [[sourcePath]]                  | c:\renamefile71.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed71.txt          | integrationtester | I73573r0     | True     | [[var[[a]]]]           | ""      | AN           | True             | Result - Invalid Region [[var[[a]]]]                                          | 1.Result - Invalid Region [[var[[a]]]]                                                |
#		| 75 | [[sourcePath]]                  | c:\renamefile72.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed72.txt          | integrationtester | I73573r0     | True     | [[var.a]]              | ""      | AN           | True             | Result - Variable name [[var.a]]contains invalid character(s)                 | 1.Result - Variable name [[var.a]] contains invalid character(s)                      |
#		| 76 | [[sourcePath]]                  | c:\renamefile73.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed73.txt          | integrationtester | I73573r0     | True     | [[@var]]               | ""      | AN           | True             | Result - Variable name [[@var]] contains invalid character(s)                 | 1.Result - Variable name [[@var]] contains invalid character(s)                       |
#		| 77 | [[sourcePath]]                  | c:\renamefile74.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed74.txt          | integrationtester | I73573r0     | True     | [[var 1]]              | ""      | AN           | True             | Result - Variable name [[var 1]] contains invalid character(s)                | 1.Result - Variable name [[var 1]] contains invalid character(s)                      |
#		| 78 | [[sourcePath]]                  | c:\renamefile75.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed75.txt          | integrationtester | I73573r0     | True     | [[rec(1).[[rec().1]]]] | ""      | AN           | True             | Result - Invalid Region [[rec(1).[[rec().1]]]]                                | 1.Result - Invalid Region [[rec(1).[[rec().1]]]]                                      |
#		| 79 | [[sourcePath]]                  | c:\renamefile76.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed76.txt          | integrationtester | I73573r0     | True     | [[rec(@).a]]           | ""      | AN           | True             | Result - Recordset index [[@]] contains invalid character(s)                  | 1.Result - Recordset index [[@]] contains invalid character(s)                        |
#		| 80 | [[sourcePath]]                  | c:\renamefile77.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed77.txt          | integrationtester | I73573r0     | True     | [[rec"()".a]]          | ""      | AN           | True             | Result - Recordset name [[rec"()"]] contains invalid character(s)             | 1.Result - Recordset name [[rec"()"]] contains invalid character(s)                   |
#		| 81 | [[sourcePath]]                  | c:\renamefile78.txt | ""                    | ""       | [[destPath]]                    | ftp://rsaklfsvrsbspdc:1002/FORTESTING/renamed78.txt          | integrationtester | I73573r0     | True     | [[rec([[[[b]]]]).a]]   | ""      | AN           | True             | Result - Invalid Region [[rec([[[[b]]]]).a]]                                  | 1.Result - Invalid Region [[rec([[[[b]]]]).a]]                                        |
		
			  	  																																																																				 

		
	
		
		
		

















