@fileFeature
Feature: Write File
	In order to be able to Write File
	as a Warewolf user
	I want a tool that writes a file at a given location

Scenario Outline: Write file at location
	Given I have a source path '<source>' with value '<sourceLocation>' 
	And source credentials as '<username>' and '<password>'	
	And Method is '<method>'
	And input contents as '<content>'     
	And result as '<resultVar>'
    When the write file tool is executed
	Then the result variable '<resultVar>' will be '<result>'
	And the execution has "<errorOccured>" error
	And the debug inputs as
         | Output Path                 | Method   | Username   | Password | File Contents |
         | <source> = <sourceLocation> | <method> | <username> | String   | <content>     |
	And the debug output as
		|                        |
		| <resultVar> = <result> |
		Examples: 
		| Name                     | source   | sourceLocation                                                  | method        | content        | username          | password | resultVar              | result  | errorOccured |
		| Local with Overwrite     | [[path]] | c:\filetowrite0.txt                                             | Overwrite     | warewolf rules | ""                | ""       | [[result]]             | Success | NO           |
		| UNC with Overwrite       | [[path]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\filetowrite0.txt | Overwrite     | warewolf rules | ""                | ""       | [[result]]             | Success | NO           |
		| FTP with Overwrite       | [[path]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/filetowrite0.txt          | Overwrite     | warewolf rules | ""                | ""       | [[result]]             | Success | NO           |
		| FTPS with Overwrite      | [[path]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/filetowrite0.txt          | Overwrite     | warewolf rules | integrationtester | I73573r0 | [[result]]             | Success | NO           |
		| SFTP with Overwrite      | [[path]] | sftp://localhost/filetowrite0.txt                               | Overwrite     | warewolf rules | dev2              | Q/ulw&]  | [[result]]             | Success | NO           |
		| Local with Append Top    | [[path]] | c:\filetowrite1.txt                                             | Append Top    | warewolf rules | ""                | ""       | [[result]]             | Success | NO           |
		| UNC with Append Top      | [[path]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\filetowrite1.txt | Append Top    | warewolf rules | ""                | ""       | [[result]]             | Success | NO           |
		| FTP with Append Top      | [[path]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/filetowrite1.txt          | Append Top    | warewolf rules | ""                | ""       | [[result]]             | Success | NO           |
		| FTPS with Append Top     | [[path]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/filetowrite1.txt          | Append Top    | warewolf rules | integrationtester | I73573r0 | [[result]]             | Success | NO           |
		| SFTP with Append Top     | [[path]] | sftp://localhost/filetowrite1.txt                               | Append Top    | warewolf rules | dev2              | Q/ulw&]  | [[result]]             | Success | NO           |
		| Local with Append Bottom | [[path]] | c:\filetowrite2.txt                                             | Append Bottom | warewolf rules | ""                | ""       | [[result]]             | Success | NO           |
		| UNC with Append Bottom   | [[path]] | \\\\RSAKLFSVRSBSPDC\FileSystemShareTestingSite\filetowrite2.txt | Append Bottom | warewolf rules | ""                | ""       | [[result]]             | Success | NO           |
		| FTP with Append Bottom   | [[path]] | ftp://rsaklfsvrsbspdc:1001/FORTESTING/filetowrite2.txt          | Append Bottom | warewolf rules | ""                | ""       | [[result]]             | Success | NO           |
		| FTPS with Append Bottom  | [[path]] | ftp://rsaklfsvrsbspdc:1002/FORTESTING/filetowrite2.txt          | Append Bottom | warewolf rules | integrationtester | I73573r0 | [[result]]             | Success | NO           |
		| SFTP with Append Bottom  | [[path]] | sftp://localhost/filetowrite2.txt                               | Append Bottom | warewolf rules | dev2              | Q/ulw&]  | [[result]]             | Success | NO           |
#Bug12180| Local with Overwrite     | [[path]] | c:\filetowrite0.txt                                             | Overwrite     | warewolf rules | ""                | ""       | [[result]][[a]]        | Failure | NO           |
		#| Local with Overwrite     | [[path]] | c:\filetowrite0.txt                                             | Overwrite     | warewolf rules | ""                | ""       | [[a]]*]]               | Failure | NO           |
		#| Local with Overwrite     | [[path]] | c:\filetowrite0.txt                                             | Overwrite     | warewolf rules | ""                | ""       | [[var@]]               | Failure | NO           |
		#| Local with Overwrite     | [[path]] | c:\filetowrite0.txt                                             | Overwrite     | warewolf rules | ""                | ""       | [[var]]00]]            | Failure | NO           |
		#| Local with Overwrite     | [[path]] | c:\filetowrite0.txt                                             | Overwrite     | warewolf rules | ""                | ""       | [[(1var)]]             | Failure | NO           |
		#| Local with Overwrite     | [[path]] | c:\filetowrite0.txt                                             | Overwrite     | warewolf rules | ""                | ""       | [[var[[a]]]]           | Failure | NO           |
		#| Local with Overwrite     | [[path]] | c:\filetowrite0.txt                                             | Overwrite     | warewolf rules | ""                | ""       | [[var.a]]              | Failure | NO           |
		#| Local with Overwrite     | [[path]] | c:\filetowrite0.txt                                             | Overwrite     | warewolf rules | ""                | ""       | [[@var]]               | Failure | NO           |
		#| Local with Overwrite     | [[path]] | c:\filetowrite0.txt                                             | Overwrite     | warewolf rules | ""                | ""       | [[var 1]]              | Failure | NO           |
		#| Local with Overwrite     | [[path]] | c:\filetowrite0.txt                                             | Overwrite     | warewolf rules | ""                | ""       | [[rec(1).[[rec().1]]]] | Failure | NO           |
		#| Local with Overwrite     | [[path]] | c:\filetowrite0.txt                                             | Overwrite     | warewolf rules | ""                | ""       | [[rec(@).a]]           | Failure | NO           |
		#| Local with Overwrite     | [[path]] | c:\filetowrite0.txt                                             | Overwrite     | warewolf rules | ""                | ""       | [[rec"()".a]]          | Failure | NO           |
		#| Local with Overwrite     | [[path]] | c:\filetowrite0.txt                                             | Overwrite     | warewolf rules | ""                | ""       | [[result]][[a]]        | Failure | NO           |


Scenario: Write file with carriage returns
	Given I have a source path '[[path]]' with value 'c:\filetowrite1.txt' 	
	And source credentials as '' and ''	
	And Method is 'Overwrite'
	And the input contents from a file 'infile1WithCarriageReturn.txt'     
	And result as 'Success'
    When the write file tool is executed	
	Then the output contents from a file 'outfile1WithCarriageReturn.txt'
	And the execution has "NO" error

Scenario: Write file when contents has variables that cannot be evealuated
	Given I have a source path '[[path]]' with value 'c:\filetowrite1.txt' 	
	And source credentials as '' and ''	
	And Method is 'Overwrite'
	And the input contents from a file 'filewithvariables.txt'     
	And result as '[[res]]'
	When the write file tool is executed	
	Then the result variable '[[res]]' will be ''
	And the execution has "AN" error


	
#Scenario Outline: Write file at location1
#    Given I have a variable "[[a]]" with a value '<Val1>'
#	Given I have a variable "[[b]]" with a value '<Val2>'
#	Given I have a variable "[[rec(1).a]]" with a value '<Val1>'
#	Given I have a variable "[[rec(2).a]]" with a value '<Val2>'
#	Given I have a variable "[[index]]" with a value "1"
#	Given I have a source path '<File or Folder>' with value '<sourceLocation>' 
#	And source credentials as '<username>' and '<password>'
#	And Method is '<method>'
#	And input contents as '<content>'   
#	And result as '<resultVar>'
#	When validating the tool
#	Then validation is '<ValidationResult>'
#	And validation message is '<DesignValidation>'
#    When the write file tool is executed	
#	Then the result variable '<resultVar>' will be '<result>'
#	And the execution has "<errorOccured>" error
#	And execution error message will be '<DesignValidation>'
#	And the debug inputs as
#         | Input Path                          | Username   | Password |
#         | <File or Folder> = <sourceLocation> | <username> | String   |
#	And the debug output as
#		|                        |
#		| <resultVar> = <result> |
#	Examples: 
#		| No | Name                 | File or Folder                 | Val1              | Val2            | sourceLocation    | method        | content                | username              | password | resultVar              | result | errorOccured | ValidationResult | DesignValidation                                                                                                                                                                                                          | OutputError                                                                                                                                                                                                                    |
#		| 1  | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | c:\filetoread.txt | Overwrite     | warewolf rules         | ""                    | ""       | [[result]]             | Guid   | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |
#		| 2  | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | c:\filetoread.txt | Overwrite     | warewolf rules         | ""                    | ""       | [[result]]             | Guid   | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |
#		| 3  | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | c:\filetoread.txt | Overwrite     | warewolf rules         | ""                    | ""       | [[result]]             | Guid   | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |
#		| 4  | Local with Overwrite | [[a]].txt                      | c:\file           | toread          | c:\filetoread.txt | Overwrite     | warewolf rules         | ""                    | ""       | [[result]]             | Guid   | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |
#		| 5  | Local with Overwrite | [[a]][[b]].txt                 | c:\fileto         | read            | c:\filetoread.txt | Overwrite     | warewolf rules         | ""                    | ""       | [[result]]             | Guid   | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |
#		| 6  | Local with Overwrite | [[rec([[index]]).a]]           | c:\filetoread.txt | ""              | c:\filetoread.txt | Append Top    | warewolf rules         | ""                    | ""       | [[result]]             | Guid   | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |
#		| 7  | Local with Overwrite | [[a]][[b]]                     | c:\file           | toread.txt      | c:\filetoread.txt | Append Top    | warewolf rules         | ""                    | ""       | [[result]]             | Guid   | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |
#		| 8  | Local with Overwrite | [[a]]\[[b]]                    | c:                | filetoread.txt  | c:\filetoread.txt | Append Top    | warewolf rules         | ""                    | ""       | [[result]]             | Guid   | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |
#		| 9  | Local with Overwrite | [[a]]:[[b]]                    | c                 | \filetoread.txt | c:\filetoread.txt | Append Top    | warewolf rules         | ""                    | ""       | [[result]]             | Guid   | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |
#		| 10 | Local with Overwrite | C:[[a]][[b]].txt               | \fileto           | read            | c:\filetoread.txt | Append Top    | warewolf rules         | ""                    | ""       | [[result]]             | Guid   | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |
#		| 11 | Local with Overwrite | [[rec(1).a]][[rec(2).a]]       | c:\fileto         | read.txt        | c:\filetoread.txt | Append Bottom | warewolf rules         | ""                    | ""       | [[result]]             | Guid   | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |
#		| 12 | Local with Overwrite | [[rec(1).a]]\[[rec(2).a]]      | c:                | filetoread.txt  | c:\filetoread.txt | Append Bottom | warewolf rules         | ""                    | ""       | [[result]]             | Guid   | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |
#		| 13 | Local with Overwrite | [[rec(1).a]][[rec(2).a]].txt   | c:\file           | toread          | c:\filetoread.txt | Append Bottom | warewolf rules         | ""                    | ""       | [[result]]             | Guid   | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |
#		| 14 | Local with Overwrite | [[rec(1).a]]:[[rec(2).a]]      | c                 | \filetoread.txt | c:\filetoread.txt | Append Bottom | warewolf rules         | ""                    | ""       | [[result]]             | Guid   | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |
#		| 15 | Local with Overwrite | C:[[rec(1).a]][[rec(2).a]].txt | fileto            | read            | c:\filetoread.txt | Append Bottom | warewolf rules         | ""                    | ""       | [[result]]             | Guid   | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |
#		| 16 | Local with Overwrite | c:\copyfile0.txt               | ""                | ""              |                   | method        | content                | ""                    | ""       | [[result]]             | Guid   | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |
#		| 17 | Local with Overwrite | [[rec([[index]]).a]]           | c:\filetoread.txt | ""              | c:\filetoread.txt | Overwrite     | warewolf rules         | ""                    | ""       | [[result]]             | Guid   | NO           | False            | ""                                                                                                                                                                                                                        | ""                                                                                                                                                                                                                             |
#		| 18 | Local with Overwrite | [[a&]]                         | ""                | ""              |                   | Overwrite     | warewolf rules         | ""                    | ""       | [[result]]             | ""     | AN           | True             | File Name - Variable name [[a&]] contains invalid character(s)                                                                                                                                                            | 1.File Name - Variable name [[a&]] contains invalid character(s)                                                                                                                                                               |
#		| 19 | Local with Overwrite | [[rec(**).a]]                  | ""                | ""              |                   | Overwrite     | warewolf rules         | ""                    | ""       | [[result]]             | ""     | AN           | True             | File Name - Recordset index (**) contains invalid character(s)                                                                                                                                                            | 1.File Name - Recordset index (**) contains invalid character(s)                                                                                                                                                               |
#		| 20 | Local with Overwrite | c(*()                          | ""                | ""              |                   | Overwrite     | warewolf rules         | ""                    | ""       | [[result]]             | ""     | AN           | True             | Please supply a valid File or Folder                                                                                                                                                                                      | 1.Please supply a valid File or Folder                                                                                                                                                                                         |
#		| 21 | Local with Overwrite | C:\\\\\gvh                     | ""                | ""              |                   | Overwrite     | warewolf rules         | ""                    | ""       | [[result]]             | ""     | AN           | False            | ""                                                                                                                                                                                                                        | 1.File Name not found [ C:\\\\\gvh ]                                                                                                                                                                                           |
#		| 22 | Local with Overwrite | [[rec([[inde$x]]).a]]          | ""                | ""              |                   | Append Top    | warewolf rules         | ""                    | ""       | [[result]]             | ""     | AN           | True             | File Name - Variable name [[index$x]] contains invalid character(s)                                                                                                                                                       | 1.File Name - Variable name [[index$x]] contains invalid character(s)                                                                                                                                                          |
#		| 23 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              |                   | Append Top    | warewolf rules         | ""                    | ""       | [[result]]             | ""     | AN           | False            | ""                                                                                                                                                                                                                        | 1.No Value assigned for [[a]]                                                                                                                                                                                                  |
#		| 24 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | c:\filetoread.txt | Append Top    | warewolf rules         | [[$#]]                | String   | [[result]]             | ""     | AN           | True             | Username - Variable name [[$#]] contains invalid character(s)                                                                                                                                                             | 1.Username - Variable name [[$#]] contains invalid character(s)                                                                                                                                                                |
#		| 25 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | c:\filetoread.txt | Append Top    | warewolf rules         | [[a]]\[[b]]           | String   | [[result]]             | ""     | AN           | False            | ""                                                                                                                                                                                                                        | 1.No Value assigned for [[a]] 2.1.No Value assigned for [[b]]                                                                                                                                                                  |
#		| 26 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | c:\filetoread.txt | Append Top    | warewolf rules         | [[rec([[index]]).a]]  | String   | [[result]]             | ""     | AN           | False            | ""                                                                                                                                                                                                                        | 1.No Value assigned for [[index]]                                                                                                                                                                                              |
#		| 27 | Local with Overwrite | [[sourcePath]].txt             | ""                | ""              | c:\filetoread.txt | Append Bottom | warewolf rules         | [[rec([[index&]]).a]] | String   | [[result]]             | ""     | AN           | True             | Username - Recordset name [[indexx&]] contains invalid character(s)                                                                                                                                                       | Username - Recordset name [[indexx&]] contains invalid character(s)                                                                                                                                                            |
#		| 28 | Local with Overwrite | [[sourcePath]].txt             | ""                | ""              | c:\filetoread.txt | Append Bottom | warewolf rules         | [[a]]*]]              | String   | [[result]]             | ""     | AN           | True             | Username - Invalid expression: opening and closing brackets don't match                                                                                                                                                   | 1.Username - Invalid expression: opening and closing brackets don't match                                                                                                                                                      |
#		| 29 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | c:\filetoread.txt | Append Bottom | warewolf rules         | ""                    | ""       | [[result]][[a]]        | ""     | AN           | True             | The result field only allows a single result                                                                                                                                                                              | 1.The result field only allows a single result                                                                                                                                                                                 |
#		| 30 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | c:\filetoread.txt | Append Bottom | warewolf rules         | ""                    | ""       | [[a]]*]]               | ""     | AN           | True             | Result - Invalid expression: opening and closing brackets don't match                                                                                                                                                     | 1.Result - Invalid expression: opening and closing brackets don't match                                                                                                                                                        |
#		| 31 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | c:\filetoread.txt | Append Bottom | warewolf rules         | ""                    | ""       | [[var@]]               | ""     | AN           | True             | Result - Variable name [[var@]] contains invalid character(s)                                                                                                                                                             | 1.Result - Variable name [[var@]] contains invalid character(s)                                                                                                                                                                |
#		| 32 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | c:\filetoread.txt | method        | content                | ""                    | ""       | [[var]]00]]            | ""     | AN           | True             | Result - Invalid expression: opening and closing brackets don't match                                                                                                                                                     | 1.Result - Invalid expression: opening and closing brackets don't match                                                                                                                                                        |
#		| 33 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | c:\filetoread.txt | Overwrite     | warewolf rules         | ""                    | ""       | [[(1var)]]             | ""     | AN           | True             | Result - Variable name [[var@]] contains invalid character(s)                                                                                                                                                             | 1.Result - Variable name [[var@]] contains invalid character(s)                                                                                                                                                                |
#		| 34 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | c:\filetoread.txt | Overwrite     | warewolf rules         | ""                    | ""       | [[var[[a]]]]           | ""     | AN           | True             | Result - Invalid Region [[var[[a]]]]                                                                                                                                                                                      | 1.Result - Invalid Region [[var[[a]]]]                                                                                                                                                                                         |
#		| 35 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | c:\filetoread.txt | Overwrite     | warewolf rules         | ""                    | ""       | [[var.a]]              | ""     | AN           | True             | Result - Variable name [[var.a]]contains invalid character(s)                                                                                                                                                             | 1.Result - Variable name [[var.a]] contains invalid character(s)                                                                                                                                                               |
#		| 36 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | c:\filetoread.txt | Overwrite     | warewolf rules         | ""                    | ""       | [[@var]]               | ""     | AN           | True             | Result - Variable name [[@var]] contains invalid character(s)                                                                                                                                                             | 1.Result - Variable name [[@var]] contains invalid character(s)                                                                                                                                                                |
#		| 37 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | c:\filetoread.txt | Overwrite     | warewolf rules         | ""                    | ""       | [[var 1]]              | ""     | AN           | True             | Result - Variable name [[var 1]] contains invalid character(s)                                                                                                                                                            | 1.Result - Variable name [[var 1]] contains invalid character(s)                                                                                                                                                               |
#		| 38 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | c:\filetoread.txt | Append Top    | warewolf rules         | ""                    | ""       | [[rec(1).[[rec().1]]]] | ""     | AN           | True             | Result - Invalid Region [[var[[a]]]]                                                                                                                                                                                      | 1.Result - Invalid Region [[var[[a]]]]                                                                                                                                                                                         |
#		| 39 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | c:\filetoread.txt | Append Top    | warewolf rules         | ""                    | ""       | [[rec(@).a]]           | ""     | AN           | True             | Result - Recordset index [[@]] contains invalid character(s)                                                                                                                                                              | 1.Result - Recordset index [[@]] contains invalid character(s)                                                                                                                                                                 |
#		| 40 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | c:\filetoread.txt | Append Top    | warewolf rules         | ""                    | ""       | [[rec"()".a]]          | ""     | AN           | True             | Result - Recordset name [[rec"()"]] contains invalid character(s)                                                                                                                                                         | 1.Result - Recordset name [[rec"()"]] contains invalid character(s)                                                                                                                                                            |
#		| 41 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | c:\filetoread.txt | Append Top    | warewolf rules         | ""                    | ""       | [[rec([[[[b]]]]).a]]   | ""     | AN           | True             | Result - Invalid Region [[rec([[[[b]]]]).a]]                                                                                                                                                                              | 1.Result - Invalid Region [[rec([[[[b]]]]).a]]                                                                                                                                                                                 |
#		| 42 | Local with Overwrite | [[a]                           | ""                | ""              |                   | Append Top    | warewolf rules         | ""                    | ""       | [[result]]             | ""     | AN           | True             | File Name - Invalid expression: opening and closing brackets don't match                                                                                                                                                  | 1.File Name - Invalid expression: opening and closing brackets don't match                                                                                                                                                     |
#		| 43 | Local with Overwrite | [[rec]                         | ""                | ""              |                   | Append Bottom | warewolf rules         | ""                    | ""       | [[result]]             | ""     | AN           | True             | File Name - [[rec]] does not exist in your variable list                                                                                                                                                                  | 1.File Name - [[rec]] does not exist in your variable list                                                                                                                                                                     |
#		| 43 | Local with Overwrite | [[rec]                         | ""                | ""              |                   | Append Bottom | warewolf rules         | ""                    | ""       | [[result]]             | ""     | AN           | True             | File Name - Recordset name [[rec(]] contains invalid character(s)                                                                                                                                                         | 1.File Name - Recordset name [[rec(]] contains invalid character(s)                                                                                                                                                            |
#		| 44 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | c:\filetoread.txt | Append Bottom | warewolf rules         | Test                  | ""       | [[result]]             | ""     | AN           | True             | Password cannot be empty or only white space                                                                                                                                                                              | 1.Password cannot be empty or only white space                                                                                                                                                                                 |
#		| 45 | Local with Overwrite | A                              | ""                | ""              | ""                | Append Bottom | warewolf rules         | Test                  | ""       | [[result]]             | ""     | AN           | True             | Please supply valid File Name                                                                                                                                                                                             | 1.Please supply valid File Name                                                                                                                                                                                                |
#		| 46 | Local with Overwrite | [[var@]]                       | ""                | ""              |                   | Append Bottom | warewolf rules         | [[var@]]              | ""       | [[var@]]               | ""     | AN           | True             | Username - Variable name [[$#]] contains invalid character(s)   Result - Variable name [[var@]] contains invalid character(s)                                                                                             | 1.Username - Variable name [[$#]] contains invalid character(s)  2.Result - Variable name [[var@]] contains invalid character(s)                                                                                               |
#		| 47 | Local with Overwrite | C#$%#$]]                       | ""                | ""              |                   | Append Bottom | warewolf rules         | C#$%#$]]              | ""       | C#$%#$]]               | ""     | AN           | True             | File Name - Invalid expression: opening and closing brackets don't match  Username - Invalid expression: opening and closing brackets don't match   Result - Invalid expression: opening and closing brackets don't match | 1.File Name - Invalid expression: opening and closing brackets don't match 2.Username - Invalid expression: opening and closing brackets don't match   3.Result - Invalid expression: opening and closing brackets don't match |
#		| 44 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | c:\filetoread.txt | Append Bottom | [[rec(]]               | ""                    | ""       | [[result]]             | ""     | AN           | True             | Contents - Recordset name [[indexx&]] contains invalid character(s)                                                                                                                                                       | 1.Contents - Recordset name [[indexx&]] contains invalid character(s)                                                                                                                                                          |
#		| 45 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | c:\filetoread.txt | Append Bottom | [[var$]]               | ""                    | ""       | [[result]]             | ""     | AN           | True             | Contents - Variable name [[var$]]  contains invalid character(s)                                                                                                                                                          | 1.Contents - Variable name [[var$]]  contains invalid character(s)                                                                                                                                                             |
#		| 46 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | c:\filetoread.txt | Append Bottom | [[rec(**).a]] rules    | ""                    | ""       | [[result]]             | ""     | AN           | True             | Contents - Recordset index (**) contains invalid character(s)                                                                                                                                                             | 1.Contents - Recordset index (**) contains invalid character(s)                                                                                                                                                                |
#		| 47 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | c:\filetoread.txt | Append Bottom | [[rec(**).a            | ""                    | ""       | [[result]]             | ""     | AN           | True             | Contents - Invalid expression: Opening and closing brackets dont match                                                                                                                                                    | 1.Contents - Invalid expression: Opening and closing brackets dont match                                                                                                                                                       |
#		| 48 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | c:\filetoread.txt | Append Bottom | [[rec().a]] rules      | ""                    | ""       | [[result]]             | ""     | AN           | False            |                                                                                                                                                                                                                           | 1.Contents - No Value assigned for : [[rec().a]]                                                                                                                                                                               |
#		| 49 | Local with Overwrite | [[sourcePath]]                 | ""                | ""              | c:\filetoread.txt | Append Bottom | [[rec([[a]]).a]] rules | ""                    | ""       | [[result]]             | ""     | AN           | False            |                                                                                                                                                                                                                           | 1.Contents - No Value assigned for : [[a]]                                                                                                                                                                                     |
      





	