# For more information on GitHub Actions, refer to https://github.com/features/actions

on: [push]

jobs:

  Auditing_Unit_Tests:
    runs-on: self-hosted
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Run Tests
      run: "&'.\\Dev\\.run\\Job Shortcuts\\Container\\Auditing Unit Tests.bat';trx2junit .\\Bin\\AcceptanceTesting\\TestResults\\*.trx"
      
    - name: Publish Unit Test Results
      run: |
        echo '##[group]Publish Unit Test Results'
        python.exe D:\actions-runner\_work\_actions\EnricoMi\publish-unit-test-result-action\v1\python\publish_unit_test_results.py
        echo '##[endgroup]'
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_RETRIES: 10
        COMMIT: $GITHUB_SHA
        CHECK_NAME: "Unit Test Results"
        COMMENT_TITLE: "Unit Test Results"
        FAIL_ON: "test failures"
        FILES: ".\\Bin\\AcceptanceTesting\\TestResults\\*.xml"
        REPORT_INDIVIDUAL_RUNS: "false"
        DEDUPLICATE_CLASSES_BY_FILE_NAME: "false"
        HIDE_COMMENTS: "all but latest"
        COMMENT_MODE: "update last"
        COMPARE_TO_EARLIER_COMMIT: "true"
        PULL_REQUEST_BUILD: "merge"
        TEST_CHANGES_LIMIT: "10"
        CHECK_RUN_ANNOTATIONS: "all tests, skipped tests"
        CHECK_RUN_ANNOTATIONS_BRANCH: "develop"
        SECONDS_BETWEEN_GITHUB_READS: "0.25"
        SECONDS_BETWEEN_GITHUB_WRITES: "2.0"

